/**
 * Per-country practical facts for the "Nomad facts at a glance" panel on every city page
 * (scripts/apply_city_facts.cjs). Country-level approximation: precise enough to orient a
 * newcomer, not a substitute for checking locally. Plug letters come from country-meta.cjs;
 * this file adds currency, language, mains voltage, tap-water guidance, tipping norm,
 * ride-hailing app(s) and the emergency number. eSIM (Airalo/Holafly) works almost everywhere
 * so it is shown as a generic line by the apply script rather than stored per country.
 *
 * Values are honest general guidance and can change; treat emergency numbers as a starting
 * point (112 reaches emergency services from any mobile across most of the world).
 * Name variants (UK / United Kingdom, Bosnia / Bosnia and Herzegovina) are both keyed.
 */
const EU = { volt: '230V / 50Hz', water: 'Safe to drink', emg: '112' };
const f = (o) => o;

const FACTS = {
  Albania: { cur: 'Lek (ALL)', lang: 'Albanian', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: 'Round up or 5-10%', ride: 'Bolt', emg: '112' },
  Argentina: { cur: 'Peso ($, ARS)', lang: 'Spanish', volt: '220V / 50Hz', water: 'Safe in cities; bottled elsewhere', tip: '10%, usually cash', ride: 'Uber, Cabify, DiDi', emg: '911' },
  Armenia: { cur: 'Dram (֏, AMD)', lang: 'Armenian, Russian', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10%', ride: 'Yandex Go, GG', emg: '112' },
  Australia: { cur: 'Dollar ($, AUD)', lang: 'English', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Not expected; round up', ride: 'Uber, DiDi', emg: '000' },
  Austria: { cur: 'Euro (€, EUR)', lang: 'German', ...EU, tip: 'Round up or 5-10%', ride: 'Uber, Bolt' },
  Azerbaijan: { cur: 'Manat (₼, AZN)', lang: 'Azerbaijani, Russian', volt: '220V / 50Hz', water: 'Bottled or filtered', tip: 'Round up or 10%', ride: 'Bolt, Yandex Go', emg: '112' },
  Bahrain: { cur: 'Dinar (BD, BHD)', lang: 'Arabic, English', volt: '230V / 50Hz', water: 'Safe (desalinated); many prefer bottled', tip: '10-15%, often added', ride: 'Careem, Uber', emg: '999' },
  Belgium: { cur: 'Euro (€, EUR)', lang: 'Dutch, French', ...EU, tip: 'Round up or 5-10%', ride: 'Uber, Bolt' },
  Bolivia: { cur: 'Boliviano (Bs, BOB)', lang: 'Spanish', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: 'Round up or 10%', ride: 'inDrive, Yango', emg: '911' },
  Bosnia: { cur: 'Mark (KM, BAM)', lang: 'Bosnian', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10%', ride: 'Bolt', emg: '112' },
  'Bosnia and Herzegovina': { cur: 'Mark (KM, BAM)', lang: 'Bosnian', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10%', ride: 'Bolt', emg: '112' },
  Brazil: { cur: 'Real (R$, BRL)', lang: 'Portuguese', volt: '127/220V / 60Hz', water: 'Bottled or filtered', tip: '10%, usually added', ride: 'Uber, 99', emg: '190' },
  Bulgaria: { cur: 'Lev (лв, BGN)', lang: 'Bulgarian', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10%', ride: 'Bolt', emg: '112' },
  Cambodia: { cur: 'Riel (៛, KHR) / USD', lang: 'Khmer', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: 'Not expected; appreciated', ride: 'Grab, PassApp', emg: '117' },
  Canada: { cur: 'Dollar ($, CAD)', lang: 'English, French', volt: '120V / 60Hz', water: 'Safe to drink', tip: 'Expected; 15-20%', ride: 'Uber, Lyft', emg: '911' },
  'Cape Verde': { cur: 'Escudo ($, CVE)', lang: 'Portuguese, Creole', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: 'Round up or 10%', ride: 'Local taxis', emg: '112' },
  Chile: { cur: 'Peso ($, CLP)', lang: 'Spanish', volt: '220V / 50Hz', water: 'Safe in cities; bottled elsewhere', tip: '10%, usually added', ride: 'Uber, DiDi, Cabify', emg: '133' },
  China: { cur: 'Yuan (¥, CNY)', lang: 'Mandarin', volt: '220V / 50Hz', water: 'Bottled or boiled', tip: 'Not customary', ride: 'DiDi', emg: '110' },
  Colombia: { cur: 'Peso ($, COP)', lang: 'Spanish', volt: '110V / 60Hz', water: 'Safe in major cities; bottled elsewhere', tip: '10%, often added', ride: 'Uber, DiDi, Cabify', emg: '123' },
  'Costa Rica': { cur: 'Colon (₡, CRC)', lang: 'Spanish', volt: '120V / 60Hz', water: 'Safe in most areas', tip: '10% often added', ride: 'Uber, DiDi', emg: '911' },
  Nicaragua: { cur: 'Cordoba (C$, NIO)', lang: 'Spanish', volt: '120V / 60Hz', water: 'Bottled recommended', tip: '10%, often added', ride: 'InDrive, local taxis', emg: '118' },
  Cuba: { cur: 'Peso (CUP)', lang: 'Spanish', volt: '110V / 60Hz (some 220V)', water: 'Bottled recommended', tip: '10%, often added', ride: 'Local taxis, colectivos', emg: '106' },
  Croatia: { cur: 'Euro (€, EUR)', lang: 'Croatian', ...EU, tip: 'Round up or 10%', ride: 'Uber, Bolt' },
  Cyprus: { cur: 'Euro (€, EUR)', lang: 'Greek, English', ...EU, tip: 'Round up or 10%', ride: 'Bolt, nEXT' },
  'Czech Republic': { cur: 'Koruna (Kč, CZK)', lang: 'Czech', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10%', ride: 'Uber, Bolt', emg: '112' },
  Denmark: { cur: 'Krone (kr, DKK)', lang: 'Danish', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Not expected; round up', ride: 'Bolt', emg: '112' },
  'Dominican Republic': { cur: 'Peso (RD$, DOP)', lang: 'Spanish', volt: '120V / 60Hz', water: 'Bottled or filtered', tip: '10% often added', ride: 'Uber, inDrive', emg: '911' },
  Ecuador: { cur: 'US Dollar ($, USD)', lang: 'Spanish', volt: '120V / 60Hz', water: 'Bottled or filtered', tip: '10% often added', ride: 'Uber, inDrive, Cabify', emg: '911' },
  Egypt: { cur: 'Pound (E£, EGP)', lang: 'Arabic', volt: '220V / 50Hz', water: 'Bottled or filtered', tip: 'Baksheesh, 10%', ride: 'Uber, Careem', emg: '122' },
  Estonia: { cur: 'Euro (€, EUR)', lang: 'Estonian', ...EU, tip: 'Round up or 10%', ride: 'Bolt, Uber' },
  Ethiopia: { cur: 'Birr (Br, ETB)', lang: 'Amharic', volt: '220V / 50Hz', water: 'Bottled or filtered', tip: '10% appreciated', ride: 'Ride, Feres', emg: '911' },
  Fiji: { cur: 'Dollar ($, FJD)', lang: 'English, Fijian', volt: '240V / 50Hz', water: 'Safe in towns; bottled rurally', tip: 'Not expected', ride: 'Local taxis', emg: '911' },
  Finland: { cur: 'Euro (€, EUR)', lang: 'Finnish', ...EU, tip: 'Not expected; round up', ride: 'Bolt, Uber' },
  France: { cur: 'Euro (€, EUR)', lang: 'French', ...EU, tip: 'Service included; round up', ride: 'Uber, Bolt' },
  Georgia: { cur: 'Lari (₾, GEL)', lang: 'Georgian', volt: '220V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10%', ride: 'Bolt, Yandex Go', emg: '112' },
  Germany: { cur: 'Euro (€, EUR)', lang: 'German', ...EU, tip: 'Round up or 5-10%', ride: 'Uber, Bolt, FreeNow' },
  Ghana: { cur: 'Cedi (₵, GHS)', lang: 'English', volt: '230V / 50Hz', water: 'Bottled or sachet water', tip: '10% appreciated', ride: 'Bolt, Uber', emg: '112' },
  Greece: { cur: 'Euro (€, EUR)', lang: 'Greek', volt: '230V / 50Hz', water: 'Safe on mainland; bottled on islands', tip: 'Round up or 10%', ride: 'Uber, Bolt, FreeNow', emg: '112' },
  Guatemala: { cur: 'Quetzal (Q, GTQ)', lang: 'Spanish', volt: '120V / 60Hz', water: 'Bottled or filtered', tip: '10%', ride: 'Uber, inDrive', emg: '110' },
  Hungary: { cur: 'Forint (Ft, HUF)', lang: 'Hungarian', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10%', ride: 'Bolt', emg: '112' },
  Iceland: { cur: 'Krona (kr, ISK)', lang: 'Icelandic, English', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Not expected', ride: 'Hopp, local taxis', emg: '112' },
  India: { cur: 'Rupee (₹, INR)', lang: 'Hindi, English', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: '10% appreciated', ride: 'Uber, Ola, Rapido', emg: '112' },
  Indonesia: { cur: 'Rupiah (Rp, IDR)', lang: 'Indonesian', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: 'Not expected; round up', ride: 'Gojek, Grab', emg: '112' },
  Iran: { cur: 'Rial (IRR)', lang: 'Persian', volt: '230V / 50Hz', water: 'Safe in many cities; bottled to be safe', tip: 'Round up or 10%', ride: 'Snapp, Tapsi', emg: '110' },
  Ireland: { cur: 'Euro (€, EUR)', lang: 'English', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10%', ride: 'FreeNow, Uber', emg: '112 / 999' },
  Israel: { cur: 'Shekel (₪, ILS)', lang: 'Hebrew, English', volt: '230V / 50Hz', water: 'Safe to drink', tip: '10-12%', ride: 'Gett, Yango', emg: '112' },
  Italy: { cur: 'Euro (€, EUR)', lang: 'Italian', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Coperto charged; round up', ride: 'FreeNow, Uber (limited), Bolt', emg: '112' },
  Japan: { cur: 'Yen (¥, JPY)', lang: 'Japanese', volt: '100V / 50-60Hz', water: 'Safe to drink', tip: 'No tipping', ride: 'GO, Uber', emg: '110' },
  Jordan: { cur: 'Dinar (JD, JOD)', lang: 'Arabic', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: '10%', ride: 'Uber, Careem', emg: '911' },
  Kazakhstan: { cur: 'Tenge (₸, KZT)', lang: 'Kazakh, Russian', volt: '220V / 50Hz', water: 'Bottled or filtered', tip: 'Round up or 10%', ride: 'Yandex Go, inDrive', emg: '112' },
  Kenya: { cur: 'Shilling (KSh, KES)', lang: 'Swahili, English', volt: '240V / 50Hz', water: 'Bottled or filtered', tip: '10% appreciated', ride: 'Uber, Bolt, Little', emg: '999 / 112' },
  Zambia: { cur: 'Kwacha (K, ZMW)', lang: 'English', volt: '230V / 50Hz', water: 'Bottled recommended', tip: '10% often added', ride: 'Ulendo, local taxis', emg: '999 / 112' },
  Kosovo: { cur: 'Euro (€, EUR)', lang: 'Albanian, Serbian', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: 'Round up or 10%', ride: 'Local taxis', emg: '112' },
  Kuwait: { cur: 'Dinar (KD, KWD)', lang: 'Arabic', volt: '240V / 50Hz', water: 'Safe (desalinated); many prefer bottled', tip: '10-15%, often added', ride: 'Careem, Uber', emg: '112' },
  Kyrgyzstan: { cur: 'Som (KGS)', lang: 'Kyrgyz, Russian', volt: '220V / 50Hz', water: 'Bottled or filtered', tip: 'Round up or 10%', ride: 'Yandex Go, inDrive', emg: '112' },
  Laos: { cur: 'Kip (₭, LAK)', lang: 'Lao', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: 'Not expected; appreciated', ride: 'LOCA, Grab', emg: '1191' },
  Latvia: { cur: 'Euro (€, EUR)', lang: 'Latvian', ...EU, tip: 'Round up or 10%', ride: 'Bolt' },
  Lebanon: { cur: 'Pound (LBP) / USD', lang: 'Arabic, French', volt: '220V / 50Hz', water: 'Bottled or filtered', tip: '10%, often added', ride: 'Bolt, Uber', emg: '112' },
  Lithuania: { cur: 'Euro (€, EUR)', lang: 'Lithuanian', ...EU, tip: 'Round up or 10%', ride: 'Bolt' },
  Luxembourg: { cur: 'Euro (€, EUR)', lang: 'Luxembourgish, French', ...EU, tip: 'Round up or 10%', ride: 'Bolt' },
  Malaysia: { cur: 'Ringgit (RM, MYR)', lang: 'Malay, English', volt: '240V / 50Hz', water: 'Boiled or bottled', tip: 'Not expected; round up', ride: 'Grab', emg: '999' },
  Malta: { cur: 'Euro (€, EUR)', lang: 'Maltese, English', volt: '230V / 50Hz', water: 'Safe (desalinated); many prefer bottled', tip: 'Round up or 10%', ride: 'Bolt, eCabs', emg: '112' },
  Mauritius: { cur: 'Rupee (₨, MUR)', lang: 'English, French, Creole', volt: '230V / 50Hz', water: 'Safe in most areas; bottled to be safe', tip: '10% appreciated', ride: 'Yugo, local taxis', emg: '112 / 999' },
  Mexico: { cur: 'Peso ($, MXN)', lang: 'Spanish', volt: '127V / 60Hz', water: 'Bottled or filtered', tip: '10-15%', ride: 'Uber, DiDi', emg: '911' },
  Montenegro: { cur: 'Euro (€, EUR)', lang: 'Montenegrin', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10%', ride: 'Local taxis', emg: '112' },
  Morocco: { cur: 'Dirham (DH, MAD)', lang: 'Arabic, French', volt: '220V / 50Hz', water: 'Bottled or filtered', tip: '10%, small change', ride: 'Careem, inDrive, Heetch', emg: '190 / 112' },
  Mozambique: { cur: 'Metical (MT, MZN)', lang: 'Portuguese', volt: '220V / 50Hz', water: 'Bottled or filtered', tip: '10% appreciated', ride: 'Yango, local taxis', emg: '119' },
  Namibia: { cur: 'Dollar ($, NAD) / Rand', lang: 'English', volt: '220V / 50Hz', water: 'Safe in towns; bottled rurally', tip: '10%', ride: 'LEFA, local taxis', emg: '112' },
  Nepal: { cur: 'Rupee (रू, NPR)', lang: 'Nepali', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: '10% appreciated', ride: 'Pathao, inDrive', emg: '100' },
  Netherlands: { cur: 'Euro (€, EUR)', lang: 'Dutch', ...EU, tip: 'Round up or 5-10%', ride: 'Uber, Bolt' },
  'New Caledonia': { cur: 'CFP franc (₣, XPF)', lang: 'French', volt: '220V / 50Hz', water: 'Safe to drink', tip: 'Not expected', ride: 'Local taxis', emg: '112' },
  'New Zealand': { cur: 'Dollar ($, NZD)', lang: 'English', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Not expected; round up', ride: 'Uber, Ola', emg: '111' },
  Nigeria: { cur: 'Naira (₦, NGN)', lang: 'English', volt: '230V / 50Hz', water: 'Bottled or sachet water', tip: '10% appreciated', ride: 'Bolt, Uber', emg: '112 / 199' },
  'North Macedonia': { cur: 'Denar (ден, MKD)', lang: 'Macedonian', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10%', ride: 'Local taxis, Bolt', emg: '112' },
  Norway: { cur: 'Krone (kr, NOK)', lang: 'Norwegian', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Not expected; round up', ride: 'Bolt, Uber', emg: '112' },
  Oman: { cur: 'Rial (RO, OMR)', lang: 'Arabic', volt: '240V / 50Hz', water: 'Safe (desalinated); many prefer bottled', tip: '10%', ride: 'Careem, Otaxi', emg: '9999' },
  Palestine: { cur: 'Shekel (₪, ILS)', lang: 'Arabic', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: '10%', ride: 'Local taxis', emg: '100' },
  Panama: { cur: 'Balboa / USD ($)', lang: 'Spanish', volt: '120V / 60Hz', water: 'Safe in most areas', tip: '10%', ride: 'Uber, inDrive', emg: '911' },
  Paraguay: { cur: 'Guarani (₲, PYG)', lang: 'Spanish, Guarani', volt: '220V / 50Hz', water: 'Bottled or filtered', tip: '10%', ride: 'Bolt, MUV', emg: '911' },
  Peru: { cur: 'Sol (S/, PEN)', lang: 'Spanish', volt: '220V / 60Hz', water: 'Bottled or filtered', tip: '10% often added', ride: 'Uber, DiDi, Cabify', emg: '105 / 911' },
  Philippines: { cur: 'Peso (₱, PHP)', lang: 'Filipino, English', volt: '220V / 60Hz', water: 'Bottled or filtered', tip: '10% often added', ride: 'Grab', emg: '911' },
  Poland: { cur: 'Zloty (zł, PLN)', lang: 'Polish', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10%', ride: 'Uber, Bolt, FreeNow', emg: '112' },
  Portugal: { cur: 'Euro (€, EUR)', lang: 'Portuguese', ...EU, tip: 'Round up or 5-10%', ride: 'Uber, Bolt' },
  'Puerto Rico': { cur: 'US Dollar ($, USD)', lang: 'Spanish, English', volt: '120V / 60Hz', water: 'Safe to drink', tip: 'Expected; 15-20%', ride: 'Uber', emg: '911' },
  Qatar: { cur: 'Riyal (QR, QAR)', lang: 'Arabic, English', volt: '240V / 50Hz', water: 'Safe (desalinated); many prefer bottled', tip: '10-15%, often added', ride: 'Uber, Careem', emg: '999' },
  Romania: { cur: 'Leu (lei, RON)', lang: 'Romanian', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10%', ride: 'Uber, Bolt', emg: '112' },
  Rwanda: { cur: 'Franc (FRw, RWF)', lang: 'Kinyarwanda, English, French', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: '10% appreciated', ride: 'Move, YegoMoto', emg: '112' },
  'Saudi Arabia': { cur: 'Riyal (SR, SAR)', lang: 'Arabic', volt: '230V / 60Hz', water: 'Safe (desalinated); many prefer bottled', tip: '10-15%', ride: 'Uber, Careem', emg: '911' },
  Senegal: { cur: 'CFA franc (XOF)', lang: 'French', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: '10%', ride: 'Yango, Heetch', emg: '17' },
  Serbia: { cur: 'Dinar (дин, RSD)', lang: 'Serbian', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10%', ride: 'CarGo, Yandex Go', emg: '112' },
  Singapore: { cur: 'Dollar ($, SGD)', lang: 'English', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Not expected; service charged', ride: 'Grab, Gojek', emg: '999' },
  Slovakia: { cur: 'Euro (€, EUR)', lang: 'Slovak', ...EU, tip: 'Round up or 10%', ride: 'Bolt, Uber' },
  Slovenia: { cur: 'Euro (€, EUR)', lang: 'Slovenian', ...EU, tip: 'Round up or 10%', ride: 'Local taxis' },
  'South Africa': { cur: 'Rand (R, ZAR)', lang: 'English', volt: '230V / 50Hz', water: 'Safe in cities; bottled rurally', tip: '10-15%', ride: 'Uber, Bolt', emg: '112 / 10111' },
  'South Korea': { cur: 'Won (₩, KRW)', lang: 'Korean', volt: '220V / 60Hz', water: 'Safe; locals often bottle', tip: 'No tipping', ride: 'Kakao T', emg: '112 / 119' },
  Spain: { cur: 'Euro (€, EUR)', lang: 'Spanish', ...EU, tip: 'Round up or 5-10%', ride: 'Uber, Cabify, Bolt' },
  'Sri Lanka': { cur: 'Rupee (Rs, LKR)', lang: 'Sinhala, Tamil, English', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: '10% often added', ride: 'PickMe, Uber', emg: '119' },
  Sweden: { cur: 'Krona (kr, SEK)', lang: 'Swedish', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Not expected; round up', ride: 'Uber, Bolt', emg: '112' },
  Switzerland: { cur: 'Franc (CHF)', lang: 'German, French, Italian', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up; service included', ride: 'Uber, Bolt', emg: '112' },
  Taiwan: { cur: 'Dollar (NT$, TWD)', lang: 'Mandarin', volt: '110V / 60Hz', water: 'Treated; locals boil or bottle', tip: 'Not customary', ride: 'Uber, LINE Taxi', emg: '110 / 119' },
  Tanzania: { cur: 'Shilling (TSh, TZS)', lang: 'Swahili, English', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: '10% appreciated', ride: 'Uber, Bolt', emg: '112' },
  Thailand: { cur: 'Baht (฿, THB)', lang: 'Thai', volt: '220V / 50Hz', water: 'Bottled or filtered', tip: 'Not expected; round up', ride: 'Grab, Bolt', emg: '191' },
  Tunisia: { cur: 'Dinar (DT, TND)', lang: 'Arabic, French', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: '10%', ride: 'Bolt, inDrive', emg: '197 / 112' },
  Turkey: { cur: 'Lira (₺, TRY)', lang: 'Turkish', volt: '230V / 50Hz', water: 'Bottled or filtered', tip: '5-10%', ride: 'BiTaksi, Uber (taxi)', emg: '112' },
  UAE: { cur: 'Dirham (AED)', lang: 'Arabic, English', volt: '230V / 50Hz', water: 'Safe (desalinated); many prefer bottled', tip: '10-15%, often added', ride: 'Uber, Careem', emg: '999 / 112' },
  UK: { cur: 'Pound (£, GBP)', lang: 'English', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10-12.5%', ride: 'Uber, Bolt', emg: '999 / 112' },
  Uganda: { cur: 'Shilling (USh, UGX)', lang: 'English, Swahili', volt: '240V / 50Hz', water: 'Bottled or filtered', tip: '10% appreciated', ride: 'Uber, Bolt, SafeBoda', emg: '112 / 999' },
  'United Kingdom': { cur: 'Pound (£, GBP)', lang: 'English', volt: '230V / 50Hz', water: 'Safe to drink', tip: 'Round up or 10-12.5%', ride: 'Uber, Bolt', emg: '999 / 112' },
  'United States': { cur: 'US Dollar ($, USD)', lang: 'English', volt: '120V / 60Hz', water: 'Safe to drink', tip: 'Expected; 15-20%', ride: 'Uber, Lyft', emg: '911' },
  Uruguay: { cur: 'Peso ($U, UYU)', lang: 'Spanish', volt: '230V / 50Hz', water: 'Safe to drink', tip: '10% often added', ride: 'Uber, Cabify', emg: '911' },
  Uzbekistan: { cur: "Som (so'm, UZS)", lang: 'Uzbek, Russian', volt: '220V / 50Hz', water: 'Bottled or filtered', tip: 'Round up or 10%', ride: 'Yandex Go, MyTaxi', emg: '112' },
  Vietnam: { cur: 'Dong (₫, VND)', lang: 'Vietnamese', volt: '220V / 50Hz', water: 'Bottled or filtered', tip: 'Not expected; appreciated', ride: 'Grab, Be', emg: '113 / 115' },
};

module.exports = FACTS;
