#!/usr/bin/env python3
"""Add comprehensive category descriptions for all cities."""
import json
import os

DATA_FILE = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

# Comprehensive descriptions for each city's categories
DESCRIPTIONS = {
    "lisbon": {
        "climate": "Lisbon enjoys a Mediterranean climate with over 300 sunny days per year. Winters are mild (10-15°C) and rarely require more than a light jacket, while summers are warm but tempered by Atlantic breezes. Spring and fall offer ideal conditions for outdoor work sessions on rooftop terraces. The reliable weather makes it easy to plan outdoor activities and maintain a consistent routine year-round.",
        "cost": "Lisbon has become pricier in recent years but remains affordable compared to Western European capitals. A comfortable nomad lifestyle costs €1,500-2,500/month including rent. Central apartments range €800-1,200/month, coworking is €150-250/month, and dining out averages €10-15 for lunch. The nearby coast and countryside offer even better value.",
        "wifi": "Portugal boasts excellent internet infrastructure with average speeds of 100+ Mbps. Most cafés offer free, reliable WiFi, and coworking spaces typically provide 200+ Mbps fiber connections. Mobile data is affordable with plans like NOS or Vodafone offering unlimited 4G/5G for €15-20/month. Power outages are extremely rare.",
        "nightlife": "Lisbon's nightlife is legendary, centered around Bairro Alto's narrow streets packed with bars, and the riverside clubs of Cais do Sodré. The night starts late (11pm+) and runs until dawn. From fado houses in Alfama to techno clubs like Lux Frágil, there's something for every taste. The city truly comes alive after dark.",
        "nature": "Despite being a capital city, Lisbon offers remarkable access to nature. The Atlantic beaches of Cascais and Costa da Caparica are 30 minutes away. Sintra's mystical forests and palaces are perfect for weekend hikes. The Arrábida Natural Park offers dramatic coastal cliffs. Even within the city, miradouros (viewpoints) and parks provide green escapes.",
        "safety": "Lisbon is one of Europe's safest capitals. Violent crime is rare, and most neighborhoods are safe to walk at night. Petty theft can occur in touristy areas like Baixa and on trams, so keep valuables secure. The police are helpful, and the overall atmosphere is relaxed and welcoming to foreigners.",
        "food": "Portuguese cuisine is a highlight of living in Lisbon. Fresh seafood is exceptional—try grilled sardines, bacalhau (cod), or seafood rice. Pastéis de nata (custard tarts) are a must. The city has exploded with international options too, from Brazilian to Mozambican to modern fusion. Markets like Time Out Market showcase the best of local food.",
        "community": "Lisbon has one of Europe's strongest digital nomad communities. Regular meetups, Facebook groups (like Digital Nomads Lisbon), and coworking events make it easy to connect. The city attracts a diverse mix of entrepreneurs, developers, and creatives. Many nomads extend their stays indefinitely, creating a stable community rather than a transient one.",
        "english": "English is widely spoken in Lisbon, especially among younger Portuguese and in tourist/business areas. You can easily navigate daily life, open bank accounts, and handle bureaucracy in English. However, learning basic Portuguese is appreciated and enriches your experience. Most official documents are available in English.",
        "visa": "EU citizens can live and work freely. Non-EU nomads can stay 90 days visa-free, then apply for the D7 passive income visa or the new Digital Nomad Visa (requires €3,040/month income). Portugal is actively courting remote workers with favorable tax regimes (NHR) and streamlined visa processes.",
        "culture": "Lisbon is steeped in history, from Moorish influences in Alfama to Manueline architecture at Belém Tower. The city celebrates its maritime past while embracing contemporary art at LX Factory and MAAT museum. Fado music echoes through traditional taverns, and festivals like Santos Populares bring neighborhoods to life. The Portuguese value of 'saudade'—a nostalgic longing—permeates the culture.",
        "cleanliness": "Lisbon is generally clean by European standards, though the historic hills can accumulate some litter. The city has improved significantly with regular street cleaning and waste collection. Graffiti is common but often artistic. Public spaces and beaches are well-maintained, and tap water is safe to drink throughout the city.",
        "airquality": "Lisbon enjoys good air quality thanks to Atlantic winds and limited heavy industry. The AQI typically ranges 20-50 (good to moderate). Summer can bring slightly higher pollution levels, but nothing concerning. The abundance of miradouros and outdoor spaces speaks to how pleasant it is to be outside year-round."
    },
    "barcelona": {
        "climate": "Barcelona enjoys a classic Mediterranean climate with hot summers (25-30°C) and mild winters (10-15°C). Rain is infrequent, mostly in spring and fall. The sea breeze keeps summers bearable, and you can enjoy beach days from May to October. Winters are short and rarely require heavy clothing—perfect for year-round outdoor living.",
        "cost": "Barcelona has become expensive, especially in central areas. Budget €2,000-3,000/month for a comfortable nomad lifestyle. Rent in desirable neighborhoods (Eixample, Gràcia) runs €1,000-1,500/month. However, daily expenses like groceries, transport, and eating out remain reasonable. The nearby coast and smaller cities offer better value.",
        "wifi": "Spain has excellent internet infrastructure. Barcelona cafés and coworking spaces typically offer 50-200 Mbps connections. Home fiber from Movistar or Vodafone delivers 300+ Mbps for €30-40/month. Mobile data is affordable, and 5G coverage is expanding rapidly. Finding a good connection is never a problem.",
        "nightlife": "Barcelona's nightlife is legendary and runs later than almost anywhere in Europe. Clubs don't fill up until 2am and stay open until 6am. From the beach clubs of Barceloneta to the underground scene in Poble Sec, options are endless. The city also excels at rooftop bars, live music venues, and the traditional 'vermut' afternoon drinking culture.",
        "nature": "Barcelona uniquely combines city and nature. Beaches are minutes from downtown, while Montjuïc and Tibidabo hills offer urban hiking. Day trips to Costa Brava's coves, Montserrat's dramatic peaks, or the Pyrenees (2 hours) provide serious outdoor adventures. The mild climate means you can enjoy nature year-round.",
        "safety": "Barcelona is generally safe but has a well-known pickpocketing problem, especially on La Rambla, in the metro, and at beaches. Violent crime is rare. Use common sense with valuables and be aware in crowded areas. Neighborhoods like Gràcia, Eixample, and Poblenou are very safe, even at night.",
        "food": "Catalan cuisine is distinct and delicious—try pa amb tomàquet, escalivada, and fresh seafood at La Boqueria market. Barcelona also has an incredible international food scene, from Japanese to Mexican to Middle Eastern. The city boasts numerous Michelin-starred restaurants and some of the world's best tapas bars. Food is taken seriously here.",
        "community": "Barcelona has a massive international community including many digital nomads and entrepreneurs. Coworking spaces like Aticco and MOB host regular events. Meetup groups cover everything from tech to sports. The beach and outdoor lifestyle make it easy to socialize. Many nomads stay for years, creating stable friendships.",
        "english": "English is widely spoken in Barcelona, especially in business, tech, and tourist areas. Most young Catalans speak good English. However, the local languages are Catalan and Spanish—learning basics earns respect and enriches your experience. Official matters may require Spanish, but English usually works.",
        "visa": "EU citizens have full freedom. Non-EU nationals can stay 90 days visa-free in the Schengen zone. Spain offers a Digital Nomad Visa requiring proof of remote work and income (approx. €2,300/month). The bureaucracy can be slow but is manageable. Many nomads also use Portugal's easier visa and visit Barcelona from there.",
        "culture": "Barcelona is a cultural powerhouse. Gaudí's architectural masterpieces—Sagrada Família, Park Güell, Casa Batlló—define the cityscape. World-class museums (Picasso, MACBA, Fundació Miró) and a thriving contemporary art scene complement the historic Gothic Quarter. Catalan identity is strong, celebrated through festivals like La Mercè and Sant Jordi. The city pulses with creative energy.",
        "cleanliness": "Barcelona is reasonably clean but faces challenges from tourism pressure. The city center can get littered, especially around nightlife areas. Beaches are cleaned daily. The metro is well-maintained. Residential neighborhoods like Gràcia are notably cleaner. Overall, it's comparable to other major European cities.",
        "airquality": "Barcelona's air quality is moderate, typical of a large Mediterranean city. The sea breeze helps, but traffic and cruise ships contribute to pollution. The AQI usually ranges 30-70. The city is investing in green zones and reducing car traffic. Most days are fine for outdoor activities, though summer heat can trap pollution."
    },
    "bangkok": {
        "climate": "Bangkok has a tropical climate—hot and humid year-round. The hot season (March-May) sees temperatures of 35°C+, the rainy season (June-October) brings daily downpours, and the 'cool' season (November-February) is the most pleasant at 25-32°C. Air conditioning is essential, but many nomads adapt to the heat and enjoy the tropical lifestyle.",
        "cost": "Bangkok offers exceptional value for digital nomads. A comfortable lifestyle costs $1,000-1,800/month. Modern condos in areas like Thonglor or Ari rent for $400-800/month. Street food meals cost $1-2, restaurant meals $3-8. Coworking is $100-200/month. This affordability allows a high quality of life on a modest income.",
        "wifi": "Thailand has invested heavily in internet infrastructure. Bangkok cafés typically offer 20-50 Mbps, while coworking spaces and condos provide 100+ Mbps fiber. True, AIS, and DTAC offer cheap unlimited mobile data (around $15/month). The city has abundant options for reliable connectivity, though café WiFi quality varies.",
        "nightlife": "Bangkok's nightlife is legendary and diverse—from rooftop bars with skyline views to underground clubs, backpacker haunts on Khao San Road to sophisticated cocktail lounges in Thonglor. The city never really sleeps. Night markets, late-night street food, and 24-hour establishments mean there's always something happening.",
        "nature": "Bangkok is a concrete jungle, but nature escapes are accessible. Lumpini and Benjakitti parks offer urban green space. Day trips reach beaches (Hua Hin, Pattaya in 2-3 hours) or national parks (Khao Yai, Erawan Falls). The city's canals and river provide a different perspective. Weekend getaways to islands are easy and affordable.",
        "safety": "Bangkok is remarkably safe for a megacity. Violent crime against foreigners is rare. The main concerns are petty scams targeting tourists and traffic accidents. Use common sense, avoid conflict, and be wary of too-good-to-be-true offers. Solo travelers, including women, generally feel safe. The Thai people are welcoming and non-confrontational.",
        "food": "Thai cuisine is one of the world's greatest, and Bangkok is its epicenter. From legendary street food (Chinatown, Yaowarat) to Michelin-starred restaurants, the variety is endless. Pad thai, som tam, green curry, mango sticky rice—all taste better here. The city also excels at Japanese, Chinese, Indian, and international cuisine.",
        "community": "Bangkok has a huge, established digital nomad community. Coworking spaces like Hubba and The Hive host regular events. Facebook groups are active, and meetups happen daily. The low cost of living attracts long-term nomads who've built lasting friendships. It's one of the easiest places in the world to meet other remote workers.",
        "english": "English proficiency varies widely in Bangkok. In tourist areas, malls, and among educated Thais, it's commonly spoken. Street vendors and taxi drivers may speak little English. Google Translate and the Grab app help bridge gaps. Learning basic Thai phrases goes a long way and is appreciated by locals.",
        "visa": "Thailand offers various options for nomads. Tourist visas allow 60 days (extendable). The new 10-year LTR visa targets remote workers with $80k+ income. Many nomads do 'visa runs' to neighboring countries or use the Thailand Elite visa for long-term stays. The system requires some planning but is manageable.",
        "culture": "Thai culture is rich, complex, and deeply Buddhist. Temples (Wat Pho, Wat Arun) are stunning and spiritually significant. The monarchy is revered—never criticize it. Thai people value 'sanuk' (fun), 'mai pen rai' (no worries), and saving face. The city blends ancient traditions with hyper-modern development. Festivals like Songkran and Loy Krathong are unforgettable.",
        "cleanliness": "Bangkok's cleanliness varies by neighborhood. Modern areas like Sukhumvit and Silom are well-maintained. Older areas and markets can be cluttered. Street food hygiene is generally good despite appearances. The BTS/MRT are spotless. Air-conditioned malls provide respite. Don't drink tap water—stick to bottled or filtered.",
        "airquality": "Bangkok's air quality is a significant concern, especially from December to February when pollution peaks. The AQI regularly exceeds 100 (unhealthy for sensitive groups). Traffic, construction, and crop burning contribute. Many nomads use air purifiers at home and masks on bad days. Check the AQI app daily."
    },
    "berlin": {
        "climate": "Berlin has a continental climate with cold winters (often below 0°C with snow) and warm summers (20-30°C). Spring and fall are pleasant but unpredictable. The city gets gray in winter with limited daylight, which affects some people's mood. Summers are glorious with long days and outdoor life. Dress in layers year-round.",
        "cost": "Berlin remains affordable compared to other Western European capitals, though costs are rising. Budget €1,800-2,800/month for a comfortable life. Rent has increased dramatically—expect €800-1,400/month for a central apartment (finding one is the real challenge). Eating out, transport, and entertainment remain reasonable.",
        "wifi": "Germany's internet reputation is mediocre, but Berlin is better than the rest of the country. Cafés offer free WiFi (typically 30-80 Mbps), and coworking spaces have reliable fiber (100+ Mbps). Home internet can be frustratingly slow to set up but works fine once established. Mobile data is expensive compared to other EU countries.",
        "nightlife": "Berlin's nightlife is world-famous. Techno clubs like Berghain and Tresor are pilgrimage sites. The scene is underground, unpretentious, and runs from Friday night to Monday morning. Beyond clubs, there are dive bars, cocktail lounges, beer gardens, and karaoke spots. The city's 'poor but sexy' ethos means nightlife is diverse and affordable.",
        "nature": "Berlin is surprisingly green for a major city. Tiergarten, Tempelhofer Feld (a former airport turned park), and numerous lakes (Wannsee, Müggelsee) offer urban nature. The Brandenburg countryside surrounds the city with forests and lakes perfect for swimming, cycling, and hiking. Summer lake culture is a Berlin highlight.",
        "safety": "Berlin is very safe by global standards. Violent crime is rare, and most neighborhoods are fine at night. The biggest concerns are bike theft (very common) and occasional pickpocketing in tourist areas. Some eastern neighborhoods can feel rough but aren't dangerous. Drug use is visible but not threatening.",
        "food": "Berlin's food scene is international and eclectic rather than traditionally German. Excellent Turkish (Kreuzberg), Vietnamese (especially pho), Middle Eastern, and Asian options abound. The döner kebab here is legendary. Fine dining has improved dramatically, with several Michelin stars. Street food markets and food halls are plentiful.",
        "community": "Berlin has one of Europe's largest nomad and startup communities. Silicon Allee hosts tech meetups weekly. Coworking spaces are social hubs. The city attracts creative entrepreneurs and artists from around the world. Long-term nomads have built strong networks here. English-speaking events are abundant.",
        "english": "English is widely spoken in Berlin, especially among younger people and in international/startup circles. You can live comfortably without German, though learning it helps with bureaucracy and deeper integration. Many expats never learn German—possible but limiting. In eastern neighborhoods, German may be more necessary.",
        "visa": "EU citizens have full rights. Non-EU nationals can use the freelance visa (requires clients and business plan) or the new opportunity card. Germany's bureaucracy is notoriously slow and frustrating. Many nomads work remotely 'under the radar' on tourist visas, though this is technically not permitted. Berlin is more relaxed than other German cities.",
        "culture": "Berlin's culture is defined by its tumultuous history—the wall, division, reunification—and its current status as a creative capital. World-class museums (Museum Island), the street art scene, underground music, and a thriving art market make it a cultural magnet. The city values individuality, counterculture, and creative expression. History is everywhere—sobering and inspiring.",
        "cleanliness": "Berlin is not the cleanest city. Graffiti is everywhere (though often artistic), some neighborhoods are gritty, and you'll see trash in parks after summer weekends. However, public transport is clean, most apartments are well-maintained, and it's nowhere near unpleasant. The grittiness is part of Berlin's charm.",
        "airquality": "Berlin's air quality is generally good, better than most large cities. The AQI typically ranges 20-50. Green spaces and limited heavy industry help. Winter heating can cause temporary spikes. The city is pedestrian and cyclist-friendly, reducing car pollution. You can breathe easy most of the time."
    },
    "tokyo": {
        "climate": "Tokyo has four distinct seasons. Summers (June-August) are hot and humid (30°C+) with a rainy season in June-July. Winters are cold but sunny (5-10°C). Spring brings cherry blossoms (late March-April), and fall offers beautiful foliage. The varied seasons create different experiences throughout the year. Air conditioning is essential in summer.",
        "cost": "Tokyo is expensive but offers value in unexpected ways. Budget ¥250,000-400,000/month ($1,700-2,700). Rent for a small apartment in good areas runs ¥100,000-180,000/month. However, incredible food is cheap (ramen for $6, convenience store meals for $4), transport is efficient, and free cultural experiences abound.",
        "wifi": "Japan has excellent internet. Cafés offer free WiFi, though connections can be weaker than expected. Coworking spaces provide 100+ Mbps. Home fiber (NURO, au) delivers 1-2 Gbps for reasonable rates. Pocket WiFi rentals are popular for flexible connectivity. The bigger challenge is finding laptop-friendly cafés with long working hours.",
        "nightlife": "Tokyo's nightlife is vast and varied. Golden Gai's tiny bars, Shibuya's clubs, Shinjuku's neon-lit streets, Roppongi's international scene—each neighborhood has distinct energy. The city has something for everyone: jazz bars, karaoke boxes, izakayas, clubs open until dawn. It's overwhelming in the best way. Safety even at 4am is remarkable.",
        "nature": "Tokyo itself is a concrete jungle, but nature access is excellent. Parks like Shinjuku Gyoen and Yoyogi provide urban green space. Day trips reach Mt. Takao (hiking), Kamakura (temples and beaches), Hakone (hot springs and Mt. Fuji views), and Nikko (mountains and shrines). The Fuji Five Lakes region is a weekend favorite.",
        "safety": "Tokyo is one of the world's safest major cities. Crime rates are remarkably low, and violent crime against foreigners is extremely rare. You can walk anywhere at night, leave belongings unattended briefly, and generally relax. The main issues are natural disasters (earthquakes, typhoons)—learn basic preparedness.",
        "food": "Japanese cuisine in Tokyo is unparalleled. From Michelin-starred sushi temples to ¥500 ramen joints, quality is consistently high. Convenience store food beats most countries' restaurants. Explore beyond sushi: yakitori, tempura, tonkatsu, kaiseki, depachika (department store food halls). The city has more Michelin stars than any other in the world.",
        "community": "Tokyo's nomad community is smaller than Southeast Asian hubs but growing. Coworking spaces like WeWork and local options host events. Meetup groups cover tech, entrepreneurship, and languages. The expat community is established, though somewhat siloed. Making Japanese friends requires more effort but is rewarding.",
        "english": "English is limited in Tokyo compared to expectations. Signs and menus often have English, but conversational English is rare outside tourist areas. Younger Japanese in international businesses speak well. Translation apps are essential. The language barrier is real but navigable—many nomads thrive without Japanese, though learning basics helps enormously.",
        "visa": "Japan is strict on work visas. Tourist stays (90 days for many nationalities) don't permit remote work technically, though enforcement is minimal. Working holiday visas (under 30/35 from eligible countries) are popular. Long-term options require sponsorship or business formation. Japan has discussed a digital nomad visa but hasn't implemented one yet.",
        "culture": "Japanese culture is fascinatingly complex—ancient traditions coexist with cutting-edge technology. Temples, tea ceremonies, and onsen contrast with anime, robots, and capsule hotels. The city values precision, politeness, and presentation. Cultural experiences are endless: sumo, kabuki, festivals, crafts. Understanding Japanese culture takes years but enriches every aspect of life here.",
        "cleanliness": "Tokyo is exceptionally clean. Streets are spotless despite the lack of public trash cans. Public toilets are immaculate with heated seats and bidets. The metro is pristine. This cleanliness reflects cultural values of respect and orderliness. You'll unconsciously raise your own standards after living here.",
        "airquality": "Tokyo's air quality is good for a megacity of 14 million. The AQI typically ranges 30-60. Spring can bring yellow sand from China, and summer humidity can trap pollution. Generally, outdoor exercise is comfortable year-round. The city has improved dramatically from its polluted past."
    },
    "chiangmai": {
        "climate": "Chiang Mai has three seasons: hot (March-May, 35°C+), rainy (June-October, daily downpours), and cool (November-February, 15-25°C). The cool season is ideal—the hot season can be brutal, and the burning season (February-April) creates serious smoke. Plan your visit around the seasons; many nomads leave during the worst months.",
        "cost": "Chiang Mai is exceptionally affordable. A comfortable nomad lifestyle costs $800-1,500/month. Modern condos rent for $300-600/month. Street food meals cost $1-2, Western food $3-8. Coworking is $50-150/month. This affordability makes it possible to live well on modest income or build savings. The value is unbeatable.",
        "wifi": "Internet infrastructure is solid. Cafés average 20-40 Mbps, coworking spaces offer 50-100+ Mbps, and condos with fiber get 100+ Mbps for cheap. True, AIS, and DTAC provide affordable unlimited mobile data. The digital nomad infrastructure here developed early, so connectivity is rarely an issue.",
        "nightlife": "Chiang Mai's nightlife is more relaxed than Bangkok's. The Night Bazaar area, Nimman Road, and the old city have bars and clubs, but it's not a party destination. Live music venues, chill rooftop bars, and the famous Sunday Walking Street market provide evening entertainment. The vibe is social but not hedonistic.",
        "nature": "Chiang Mai is a nature lover's paradise. Doi Suthep mountain overlooks the city with hiking trails. Doi Inthanon (Thailand's highest peak) is a day trip. Waterfalls, hot springs, elephant sanctuaries, and jungle trekking are easily accessible. The Grand Canyon and Sticky Waterfalls are nomad favorites. Nature is why many people come here.",
        "safety": "Chiang Mai is very safe. Crime against foreigners is rare. The main risks are motorbike accidents (drive carefully, wear a helmet), occasional scams, and the burning season smoke. Thai culture is non-confrontational, and the locals are friendly. Solo female travelers report feeling very comfortable.",
        "food": "Northern Thai cuisine (khao soi, sai oua, nam prik) is distinct and delicious. Chiang Mai's food scene ranges from $1 street food to excellent restaurants. The city also has great vegetarian/vegan options, international cuisine (especially in Nimman), and Western comforts. Food markets like Warorot are endlessly explorable.",
        "community": "Chiang Mai has one of the world's most established digital nomad communities. Punspace, CAMP, and other coworking spaces host regular events. Nomad Coffee Club and numerous Facebook groups facilitate connections. The community is supportive, with experienced nomads helping newcomers. Long-term residents have built genuine friendships and support networks.",
        "english": "English is widely spoken in Chiang Mai's nomad areas—Nimman, the Old City, and tourist spots. Service industry workers and younger Thais generally communicate well. Outside these zones, English drops off quickly. Learning Thai basics enhances your experience and shows respect. Translation apps help with complex situations.",
        "visa": "Thailand's visa situation requires planning. Tourist visas allow 60 days, extendable once. Many nomads do visa runs to neighboring countries or use the Education Visa (learning Thai). The new LTR (Long Term Resident) visa targets wealthy remote workers. Rules change frequently—join nomad groups for current information.",
        "culture": "Chiang Mai was the capital of the Lanna Kingdom, and this heritage remains visible. Over 300 temples dot the city, with Doi Suthep being the most sacred. The old city's moat and gates evoke history. Yi Peng (lantern festival) and Songkran (water festival) are spectacular cultural experiences. The pace is slower and more traditional than Bangkok.",
        "cleanliness": "Chiang Mai is relatively clean by Southeast Asian standards. The old city and tourist areas are well-maintained. Some infrastructure is aging. The biggest cleanliness issue is seasonal—the burning season (February-April) fills the air with smoke and ash, affecting air quality severely. Outside burning season, it's pleasant.",
        "airquality": "Air quality is Chiang Mai's biggest drawback. From February to April, agricultural burning creates hazardous conditions—AQI regularly exceeds 200 (very unhealthy). Many nomads leave during this period. The rest of the year, air quality is good (AQI 20-60). Check AQI apps and plan accordingly."
    },
    "medellin": {
        "climate": "Medellín is the 'City of Eternal Spring'—temperatures hover around 22-28°C year-round at 1,500m elevation. No heating or AC needed. Brief afternoon rain showers are common but rarely disruptive. The consistently perfect weather is a major draw, allowing outdoor living every day of the year.",
        "cost": "Medellín offers excellent value. Budget $1,200-2,000/month for a comfortable lifestyle. Modern apartments in El Poblado or Laureles rent for $500-900/month. Meals cost $3-8, excellent coffee is $1-2, and coworking runs $100-200/month. Colombia's peso fluctuations can make it even cheaper for those earning in dollars.",
        "wifi": "Internet has improved dramatically. Cafés typically offer 20-50 Mbps, coworking spaces provide 100+ Mbps fiber, and residential fiber is widely available. Claro, Movistar, and Tigo offer good mobile data plans. The digital infrastructure supports serious remote work, though occasional outages occur.",
        "nightlife": "Medellín's nightlife is vibrant and social. Parque Lleras in El Poblado is the main scene—bars, clubs, and restaurants packed nightly. Laureles offers a more local vibe. Salsa clubs, reggaeton parties, and rooftop bars cater to different tastes. The city's energy is infectious, and Colombians know how to party.",
        "nature": "The Aburrá Valley setting provides stunning mountain views. Parque Arví (accessible by metro cable) offers hiking and nature. Day trips reach coffee region towns (Jardín, Guatapé with its famous rock), thermal springs, and colonial villages. The surrounding Andes are spectacular. Weekend nature escapes are easy.",
        "safety": "Medellín has transformed dramatically from its Pablo Escobar days. Tourist areas (El Poblado, Laureles, Envigado) are generally safe. Use standard precautions—avoid displaying expensive items, don't walk alone late in unfamiliar areas, use official taxis or apps. Petty crime exists but violent crime against tourists is rare. The improvement is remarkable.",
        "food": "Colombian cuisine centers on hearty dishes like bandeja paisa, arepas, and sancocho. Medellín's food scene has exploded with international options—especially in El Poblado and Provenza. Excellent coffee is everywhere (this is Colombia!). Fresh tropical fruits are abundant. The restaurant scene is sophisticated and reasonably priced.",
        "community": "Medellín has a large and active digital nomad community. Selina, Atomhouse, and various coworking spaces host events. The city attracts entrepreneurs and creatives from around the world. Meetups happen frequently, and making connections is easy. The community is welcoming and internationally diverse.",
        "english": "English is increasingly common in tourist and nomad areas but not as widespread as in Europe or Asia. Service workers in El Poblado speak some English. Learning Spanish dramatically improves your experience and is essential outside tourist zones. Colombians appreciate any effort to speak Spanish.",
        "visa": "Colombia is very friendly to nomads. Most nationalities get 90 days on arrival, extendable to 180 days. The Digital Nomad Visa (2022) allows 2 years for those earning $684+/month. No proof of onward travel is strictly enforced. Long-term stays are relatively easy to arrange.",
        "culture": "Medellín's culture is warm, social, and resilient. Paisas (locals) are known for their friendliness and entrepreneurial spirit. The city's transformation from cartel capital to innovation hub is a point of pride. Art, music, and festivals are integral. The Botero Plaza and street art of Comuna 13 showcase creativity. Family and community are central values.",
        "cleanliness": "Medellín is clean by Latin American standards. The metro (Colombia's only) is spotless and a point of civic pride. Tourist neighborhoods are well-maintained. Some areas show urban grit, but overall it's pleasant. The temperate climate and civic investment have improved the cityscape dramatically.",
        "airquality": "Air quality is a concern in Medellín's valley. The AQI often reaches 60-100 (moderate to unhealthy for sensitive groups). Traffic and topography trap pollution, especially in certain seasons. Some days require limiting outdoor exercise. It's not as bad as some Asian cities but worth monitoring."
    },
    "bali": {
        "climate": "Bali has a tropical climate with wet (November-March) and dry (April-October) seasons. Temperatures are consistently warm (26-30°C) year-round. Humidity is high. The dry season is ideal; the wet season brings daily downpours but also lush greenery and fewer tourists. Ubud is cooler and wetter than the beaches.",
        "cost": "Bali offers a range of budgets. Modest nomad living: $1,000-1,500/month. Comfortable villa lifestyle: $2,000-3,000/month. Luxury options push higher. Scooter rental is $50-80/month, meals range $3-15, coworking $100-250/month. Accommodation varies wildly—a rice field villa in Ubud differs from a Canggu apartment.",
        "wifi": "Internet has improved but remains Bali's Achilles heel. Coworking spaces (Dojo, Hubud, Outpost) provide reliable 50-100 Mbps. Café WiFi is hit-or-miss. Home fiber is available in developed areas but can be unreliable. Many nomads carry backup mobile hotspots. Starlink is gaining popularity for villa stays.",
        "nightlife": "Bali's nightlife varies by area. Seminyak and Canggu have beach clubs, bars, and some clubbing. Kuta is more chaotic and party-focused. Ubud is quiet after dark. Full moon parties and beach events are legendary. The scene is more about sunset drinks and social gatherings than clubbing.",
        "nature": "Bali is extraordinarily beautiful. Rice terraces (Tegallalang), volcanic mountains (Mt. Batur, Mt. Agung), waterfalls, beaches, and coral reefs offer endless exploration. Surfing, diving, yoga retreats, and hiking are all exceptional. The island's natural beauty is a primary draw for nomads seeking work-life balance.",
        "safety": "Bali is safe for tourists. Violent crime is rare. Main concerns are motorbike accidents (a serious risk—drive carefully), petty theft, and occasional scams. The Balinese are gentle and welcoming. Natural disasters (earthquakes, volcanic activity) are worth monitoring. Solo travelers feel comfortable.",
        "food": "Balinese cuisine features dishes like babi guling (suckling pig), nasi goreng, and satay. The international food scene—especially in Canggu and Seminyak—is excellent with vegan cafés, organic restaurants, and global cuisines. Warungs (local eateries) offer delicious meals for $2-4. Healthy eating is easy here.",
        "community": "Bali has one of the world's largest digital nomad communities, centered in Canggu and Ubud. Coworking spaces are social hubs with daily events. The scene attracts entrepreneurs, creatives, wellness practitioners, and influencers. Making connections is effortless. The community is diverse but can feel transient.",
        "english": "English is widely spoken in tourist areas. Balinese working in hospitality, tourism, and nomad services communicate well. Learning basic Indonesian shows respect and helps outside tourist zones. Communication is rarely a barrier in nomad life.",
        "visa": "Indonesia's visa situation requires attention. Visa on Arrival (30 days, extendable to 60) works for short stays. The B211A social visa allows 6 months with extensions. Indonesia launched a Digital Nomad Visa (2024) for remote workers. Many nomads do visa runs to Singapore. Rules change—check current requirements.",
        "culture": "Balinese Hindu culture is unique and pervasive. Temples, daily offerings, ceremonies, and traditional arts are integral to daily life. The island's spirituality attracts yoga practitioners and seekers. Ubud is the cultural heart with dance performances and art galleries. Respect local customs—dress modestly at temples.",
        "cleanliness": "Bali faces environmental challenges. Plastic waste and water pollution are problems, especially on beaches. Tourist areas are maintained, but outside them, trash can accumulate. Water isn't safe to drink. Many eco-conscious initiatives are improving sustainability. Choose accommodations and businesses with good environmental practices.",
        "airquality": "Air quality is generally good, though burning season (dry season agricultural burning) can cause haze. Traffic emissions concentrate in busy areas like Canggu and Seminyak. The ocean breezes help. Ubud has cleaner air. Overall, not a major concern but occasionally noticeable."
    }
}

def main():
    # Load existing data if it exists
    if os.path.exists(DATA_FILE):
        with open(DATA_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
    else:
        data = {}

    # Add/update descriptions
    for city_id, descriptions in DESCRIPTIONS.items():
        data[city_id] = descriptions
        print(f"Added descriptions for {city_id}")

    # Save data
    os.makedirs(os.path.dirname(DATA_FILE), exist_ok=True)
    with open(DATA_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nSaved {len(data)} cities to {DATA_FILE}")

if __name__ == "__main__":
    main()
