#!/usr/bin/env python3
"""Batch 2: Add comprehensive category descriptions for 10 more cities."""
import json
import os

DATA_FILE = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

DESCRIPTIONS = {
    "budapest": {
        "climate": "Budapest has a continental climate with hot summers (25-35°C) and cold winters (-2 to 5°C). Spring and fall are ideal—mild temperatures, fewer tourists, and beautiful colors. Winters can be gray and cold, but the thermal baths make it bearable. Summer brings outdoor festivals and ruin bar terraces. Pack layers year-round.",
        "cost": "Budapest remains one of Europe's best values. Budget €1,200-1,800/month for comfortable living. Rent in central districts runs €500-900/month. A meal at a local restaurant costs €5-10, craft beer €2-3, and monthly transport passes €30. The favorable exchange rate makes it even better for those earning Western currencies.",
        "wifi": "Hungary has excellent internet infrastructure. Cafés typically offer 30-80 Mbps free WiFi. Coworking spaces provide 100+ Mbps fiber connections. Home internet is fast and affordable (€15-25/month for 100+ Mbps). Mobile data from Telekom, Vodafone, or Yettel is cheap with good 4G/5G coverage throughout the city.",
        "nightlife": "Budapest's nightlife is legendary, centered on the famous ruin bars of the Jewish Quarter. Szimpla Kert started the trend, but dozens now fill the area. Beyond ruin bars, there's a thriving club scene, rooftop bars, wine bars, and thermal bath parties (Sparties). The night starts late and runs until dawn.",
        "nature": "The Danube River divides Buda's hills from Pest's plains, creating diverse landscapes. Margaret Island offers urban green space, while Buda Hills provide hiking trails with city views. Lake Balaton (1.5 hours) is a summer favorite. The Danube Bend towns of Szentendre and Visegrád make perfect day trips.",
        "safety": "Budapest is very safe by any standard. Violent crime is rare, and most areas are fine at night. Watch for pickpockets in tourist zones and on public transport. Taxi scams exist—use Bolt instead. Some may experience minor scams at tourist restaurants. Overall, it's one of Europe's safer capitals.",
        "food": "Hungarian cuisine is hearty and flavorful—goulash, chicken paprikash, lángos, and chimney cake are musts. The city has evolved beyond traditional fare with excellent fine dining (several Michelin stars), international options, and a booming brunch culture. The Great Market Hall showcases local ingredients. Wine from Hungarian regions is excellent and affordable.",
        "community": "Budapest has a strong digital nomad community, especially in Districts V, VI, and VII. Coworking spaces like Kaptar, Loffice, and Impact Hub host events. Regular meetups happen through Facebook groups and Meetup.com. The mix of affordability and quality attracts long-term nomads who form lasting connections.",
        "english": "English is widely spoken among younger Hungarians and in tourist/business areas. You can navigate daily life easily in English. However, Hungarian is notoriously difficult, so learning beyond basics is a commitment few make. Service workers in popular areas communicate well enough.",
        "visa": "EU citizens have full freedom. Non-EU nationals get 90 days in the Schengen zone. Hungary doesn't have a specific digital nomad visa, but the White Card (temporary residence) is possible for those with proof of income. Many nomads use Hungary as a base while traveling the Schengen area.",
        "culture": "Budapest's culture reflects its Habsburg and Ottoman past. Stunning architecture—Parliament, Buda Castle, thermal baths—tells the story. The city has a vibrant arts scene with opera, classical music, and contemporary galleries. Ruin bars represent a unique cultural innovation. Café culture dates back centuries. The thermal bath tradition is central to local life.",
        "cleanliness": "Budapest is reasonably clean, though aging infrastructure shows in some areas. The city center is well-maintained. Public transport is clean. Some residential areas have graffiti and wear. The Danube embankment and parks are pleasant. Overall comparable to other Central European capitals.",
        "airquality": "Air quality is moderate, typical of a Central European city. Winter heating can cause spikes. The AQI usually ranges 30-70. Summer is generally better. The hills of Buda have cleaner air than central Pest. Not a major concern for most, but sensitive individuals should monitor conditions."
    },
    "prague": {
        "climate": "Prague has a continental climate with warm summers (20-30°C) and cold, snowy winters (-3 to 3°C). Spring (April-May) and early fall (September) offer the best weather with mild temperatures and fewer tourists. Winters are atmospheric but cold—bring warm clothing. Summer can get crowded but the long evenings are magical.",
        "cost": "Prague is pricier than Budapest but still affordable by Western standards. Budget €1,500-2,200/month. Central apartments cost €700-1,100/month. Czech crowns provide some buffer from euro inflation. Meals run €6-12, beer is famously cheap (€1.50-3), and transport is affordable.",
        "wifi": "Czech internet infrastructure is excellent. Cafés offer reliable free WiFi (30-80 Mbps typically). Coworking spaces have fiber (100+ Mbps). Home internet is fast and reasonably priced. Mobile networks (O2, T-Mobile, Vodafone) provide good coverage and affordable data plans.",
        "nightlife": "Prague has diverse nightlife, from historic beer halls to modern cocktail bars and clubs. The Old Town can be touristy (and notorious for stag parties), but neighborhoods like Žižkov and Vinohrady offer authentic local experiences. Cross Club is legendary for underground electronic music. Czech beer culture is unparalleled—this is where Pilsner was invented.",
        "nature": "Prague itself is beautiful with the Vltava River, Petřín Hill, and numerous parks. Day trips reach stunning destinations: Bohemian Switzerland National Park, Karlštejn Castle, Kutná Hora, and the Bohemian countryside. Hiking and cycling routes are well-marked. The Czech landscape is underrated and easily accessible.",
        "safety": "Prague is very safe. Violent crime is rare. The main concerns are tourist-targeted scams (overcharging, taxi tricks) and pickpockets in crowded areas like Charles Bridge and Old Town Square. Outside tourist zones, you'll find a relaxed, safe city. Night safety is generally good.",
        "food": "Traditional Czech cuisine features svíčková (beef in cream sauce), trdelník (though that's actually more tourist than traditional), and of course roast pork with dumplings. The food scene has diversified significantly with excellent restaurants spanning global cuisines. Farm-to-table and modern Czech interpretations are trending. Beer pairing is an art here.",
        "community": "Prague has an established expat and nomad community, though somewhat smaller than Budapest or Berlin. Coworking spaces like Impact Hub, Locus, and K10 host events. The startup scene is growing. English-speaking meetups are regular. The community is welcoming but you need to seek it out.",
        "english": "English is widely spoken in Prague, especially among younger Czechs and in business/tourist areas. You can live comfortably without Czech. However, outside central Prague and with older generations, English is less common. Learning Czech is extremely difficult but appreciated.",
        "visa": "EU citizens can live and work freely. Non-EU nationals have 90-day Schengen access. The Czech Republic offers a Zivno (trade license) visa that some nomads use for longer stays, though it requires setting up a business entity. No specific digital nomad visa exists yet.",
        "culture": "Prague's culture is deeply rooted in history—the castle, Charles Bridge, and Old Town are UNESCO-listed. Kafka, Dvořák, and Art Nouveau architecture define its intellectual heritage. The city values beer (seriously), classical music, and a certain understated sophistication. Contemporary arts thrive alongside tradition. Christmas markets are enchanting.",
        "cleanliness": "Prague is clean and well-maintained, especially in tourist areas. Public transport is spotless. Some outlying neighborhoods show more wear. The city takes pride in its appearance given the tourist economy. Tap water is safe to drink. Generally one of the cleaner Central European cities.",
        "airquality": "Air quality is decent, with occasional winter inversions causing higher pollution. The AQI typically ranges 25-60. The city center and riverside areas have good air. Not a significant concern for most people, though sensitive individuals should check forecasts during winter."
    },
    "mexicocity": {
        "climate": "Mexico City's high altitude (2,240m) creates spring-like weather year-round: 15-25°C most days. Rainy season (June-October) brings afternoon downpours but mornings are usually clear. Winters are dry and mild. The eternal spring climate is a major draw—you'll rarely need AC or heating. Bring layers for cool evenings.",
        "cost": "Mexico City offers incredible value. Budget $1,200-2,000/month for a great lifestyle. Apartments in Roma, Condesa, or Juárez run $600-1,000/month. Street food tacos cost $0.50-1, restaurant meals $5-15. The peso's fluctuations can make it even cheaper. Quality of life vastly exceeds the cost.",
        "wifi": "Internet infrastructure is solid and improving. Cafés typically offer 20-50 Mbps. Coworking spaces (Selina, WeWork, local options) have 100+ Mbps fiber. Home internet from Telmex, Izzi, or Totalplay is reliable in popular neighborhoods. Telcel and other carriers offer affordable mobile data.",
        "nightlife": "Mexico City's nightlife is vibrant and varied. Condesa and Roma have cocktail bars and clubs, Coyoacán offers laid-back cantinas, and there's everything from mezcalerías to rooftop bars to underground techno. The city starts late—dinner at 10pm, clubs after midnight. Live music venues showcase incredible Mexican talent.",
        "nature": "Despite being a megacity, nature access exists. Chapultepec is one of the world's largest urban parks. Day trips reach pyramids at Teotihuacán, the forests of Desierto de los Leones, mountain towns like Valle de Bravo, and Nevado de Toluca volcano. The surrounding mountains offer hiking and fresh air escapes.",
        "safety": "Safety requires awareness but isn't as dire as headlines suggest. Roma, Condesa, Polanco, and Juárez are safe neighborhoods. Use Uber/DiDi instead of street taxis. Avoid displaying expensive items. Petty crime exists; violent crime against tourists is rare. Learn which areas to avoid. Most nomads feel comfortable once they understand the city.",
        "food": "Mexican cuisine in its birthplace is transcendent. Street tacos, market food, regional specialties—every meal is an adventure. The city has world-class fine dining (Pujol, Quintonil) alongside perfect $1 tacos. Al pastor, barbacoa, carnitas, mole—each neighborhood has specialties. This is a food lover's paradise.",
        "community": "Mexico City's nomad community has exploded. Coworking spaces in Roma and Condesa are social hubs. Facebook groups are active. Regular meetups, language exchanges, and events make connection easy. The mix of Mexican entrepreneurs and international nomads creates dynamic energy. Many people extend their stays indefinitely.",
        "english": "English is common in tourist areas and among educated Mexicans, but Spanish dominates daily life. Service workers in nomad neighborhoods manage basic English. Learning Spanish significantly enriches your experience and is essential outside touristy zones. Mexicans warmly appreciate any Spanish effort.",
        "visa": "Mexico is extremely nomad-friendly. Most nationalities get 180 days on arrival (visa-free), easily extended. The Temporary Resident Visa offers 1-4 year stays for those with income proof (~$1,500/month). Bureaucracy exists but is manageable. The ease of staying legally is a major draw.",
        "culture": "Mexican culture is rich, colorful, and proud. Ancient civilizations (Aztec ruins at Templo Mayor), colonial heritage, and modern creativity coexist. Frida Kahlo, Diego Rivera, and the muralist movement left lasting marks. Día de los Muertos, lucha libre, and mezcal culture are uniquely Mexican. The people are warm and the culture is endlessly fascinating.",
        "cleanliness": "Cleanliness varies by neighborhood. Wealthy areas like Polanco are immaculate. Roma and Condesa are generally clean. Markets and older areas can be cluttered. Air quality affects perceived cleanliness. The city maintains major thoroughfares and tourist areas well. Tap water isn't drinkable—use purified.",
        "airquality": "Air quality is Mexico City's biggest challenge. The valley traps pollution, especially in dry season. AQI often exceeds 100 (unhealthy). Good days exist, particularly after rain. Many nomads use air purifiers at home. Check the AQI app daily and limit outdoor exercise when levels spike."
    },
    "taipei": {
        "climate": "Taipei has a humid subtropical climate. Summers (June-September) are hot and humid (30-35°C) with typhoon season. Winters (December-February) are cool and damp (12-18°C). Spring and fall are pleasant. The humidity takes adjustment. Air conditioning is essential in summer; a dehumidifier helps year-round.",
        "cost": "Taipei is moderately priced. Budget $1,500-2,500/month. Modern apartments in good areas run $600-1,000/month. Local food is cheap ($3-6 per meal), transport is affordable, and healthcare is excellent and inexpensive. Higher than Southeast Asia but lower than Tokyo or Singapore.",
        "wifi": "Taiwan has excellent internet infrastructure. Cafés offer free WiFi (typically 30-100 Mbps). Coworking spaces have fiber connections (100+ Mbps). Home internet is fast and reliable. Chunghwa Telecom and others provide mobile data at reasonable rates. Convenience stores have free WiFi too.",
        "nightlife": "Taipei's nightlife centers on districts like Xinyi (upscale clubs), Da'an (lounges), and the famous night markets that run late. The city has excellent bars—from craft cocktail spots to dive bars. Live music venues and KTV (karaoke) are popular. The scene is diverse but not as wild as Bangkok or Berlin.",
        "nature": "Taipei is surprisingly green. Mountains surround the city with excellent hiking—Elephant Mountain, Yangmingshan National Park, and numerous trails are easily accessible. Hot springs are a highlight (Beitou). Day trips reach dramatic coastline (Jiufen, Northeast Coast), Taroko Gorge, and Sun Moon Lake.",
        "safety": "Taiwan is exceptionally safe. Crime rates are among the lowest in the world. Walking alone at night anywhere is fine. Natural disasters (typhoons, earthquakes) are the main concern—buildings are well-designed for earthquakes. The sense of personal security is remarkable and liberating.",
        "food": "Taiwanese food is phenomenal. Night markets offer endless variety—xiao long bao, beef noodle soup, bubble tea (invented here), stinky tofu, and hundreds more dishes. Japanese influence shows in quality and presentation. Vegetarian options are plentiful. Convenience store food is surprisingly good. Din Tai Fung started here.",
        "community": "Taipei's nomad community is established but smaller than Southeast Asian hubs. Coworking spaces like Futureward and CIT host events. The expat community is welcoming. Meetups happen regularly. Taiwan's tech scene creates interesting networking opportunities. Many nomads discover Taipei later in their journey and wish they'd come sooner.",
        "english": "English proficiency is moderate. Younger Taiwanese and those in business speak well. Street-level English is limited. Signs often have English, and translation apps help. Learning basic Mandarin is useful. The language barrier is manageable but present.",
        "visa": "Many nationalities get 90-day visa-free entry. Taiwan's Gold Card visa for skilled professionals is excellent—3 years with open work rights for those qualifying in specific fields. The Employment Gold Card is popular among nomads in tech. Visa runs to nearby countries are easy.",
        "culture": "Taiwanese culture blends Chinese heritage, Japanese influence, and indigenous traditions. Temples are everywhere and active. The night market is a cultural institution. Traditional arts coexist with cutting-edge technology. Taiwanese people are famously friendly and helpful. The democracy is vibrant. LGBTQ+ rights are the most progressive in Asia.",
        "cleanliness": "Taipei is remarkably clean. The MRT is spotless with strict no-eating rules. Streets are well-maintained. Public facilities are hygienic. Recycling is serious. The overall cleanliness reflects civic pride and effective governance. Tap water isn't typically drunk, but it's safe.",
        "airquality": "Air quality is generally good, though occasional pollution drifts from mainland China. The AQI usually ranges 30-70. Mountain proximity and sea breezes help. Summer can see higher humidity affecting air feel. Overall, not a significant concern for daily life."
    },
    "singapore": {
        "climate": "Singapore has a tropical climate—hot and humid year-round (27-32°C). Brief intense rain showers can happen anytime but rarely last long. There's no real seasonality. Air conditioning is everywhere and essential. You'll adapt to moving between AC interiors and humid outdoors. The consistency is either monotonous or reliably pleasant depending on your perspective.",
        "cost": "Singapore is expensive—one of Asia's costliest cities. Budget $3,000-5,000/month for comfortable living. Rent is the killer: a room costs $1,000-1,500, a studio $2,000+. However, hawker center meals cost $3-5, and transport is efficient if not cheap. It's possible to live more affordably with careful choices.",
        "wifi": "Singapore has world-class internet infrastructure. Free public WiFi (Wireless@SG) is widespread. Cafés and coworking spaces offer fast, reliable connections. Home fiber delivers 1+ Gbps for reasonable rates. Mobile networks provide excellent 4G/5G. Connectivity is never an issue.",
        "nightlife": "Singapore's nightlife is sophisticated and expensive. Clarke Quay offers mainstream bars and clubs. Ann Siang Hill and Keong Saik have speakeasies and cocktail bars. Marina Bay Sands rooftop is iconic. The scene is polished rather than gritty. Alcohol is heavily taxed, so expect to pay $15-20+ for cocktails.",
        "nature": "Despite its urban density, Singapore is a garden city. Gardens by the Bay, Botanic Gardens (UNESCO-listed), MacRitchie Reservoir, and Southern Ridges provide green escapes. Pulau Ubin island feels like old Singapore. The zoo and bird park are world-class. Nature is surprisingly accessible and beautifully maintained.",
        "safety": "Singapore is one of the world's safest cities. Crime is almost non-existent. You can walk anywhere at any hour without concern. Strict laws create this security—don't break them. The only real concerns are heat-related and traffic (which is also well-regulated). Personal safety is essentially guaranteed.",
        "food": "Singapore is a food paradise—hawker centers serve Chinese, Malay, Indian, and Peranakan dishes for $3-5. Michelin-starred hawker stalls exist. The diversity reflects the multicultural society. From laksa to Hainanese chicken rice to roti prata, every meal is an exploration. Fine dining is world-class too.",
        "community": "Singapore has a large expat community but a smaller nomad scene—the cost filters many out. Coworking spaces like WeWork, JustCo, and local options exist. The tech and startup ecosystem is sophisticated. Networking happens in professional contexts. The community is established and career-focused.",
        "english": "English is an official language and the business lingua franca. Signs, government services, and daily life operate in English. Singlish (local English) adds flavor but is comprehensible. This is one of Asia's easiest places for English speakers. Mandarin, Malay, and Tamil are also spoken.",
        "visa": "Singapore is strict on visas. Most nationalities get 30-90 days visa-free for tourism. Working remotely in Singapore technically requires an EntrePass or Employment Pass. The Tech.Pass targets tech professionals. Many nomads use Singapore for short stints or as a regional base for visa runs.",
        "culture": "Singapore's culture reflects its Chinese, Malay, Indian, and colonial British influences. Ethnic neighborhoods (Chinatown, Little India, Kampong Glam) maintain distinct identities. The society values efficiency, rules, and meritocracy. Cultural festivals from multiple traditions are celebrated. Museums and arts have grown significantly. It's modern Asia distilled.",
        "cleanliness": "Singapore is legendarily clean—famous for banning chewing gum and heavy littering fines. Streets are spotless. Public facilities are immaculate. This extends everywhere from hawker centers to the MRT. The cleanliness reflects both strict enforcement and civic culture. It's remarkable.",
        "airquality": "Air quality is usually good but occasionally affected by Indonesian haze from forest fires (mainly August-October). During haze periods, AQI can spike severely. Otherwise, expect AQI 20-50. The city monitors and communicates air quality actively. Most of the year, it's fine."
    },
    "amsterdam": {
        "climate": "Amsterdam has a maritime climate—mild but wet. Summers are pleasant (17-25°C) with long days. Winters are cold (0-7°C), gray, and damp. Rain is possible year-round. Spring brings tulips and beautiful light. The weather requires adaptation—invest in good rain gear and embrace indoor coziness (gezelligheid).",
        "cost": "Amsterdam is expensive. Budget €2,500-4,000/month. Rent is the challenge: expect €1,200-2,000/month for a small apartment (if you can find one—housing crisis is real). Daily expenses are high: coffee €3-4, lunch €12-18, dinner €25-40. The quality of life is high but comes at a price.",
        "wifi": "Dutch internet is excellent. Cafés offer free, fast WiFi. Coworking spaces have 100+ Mbps fiber. Home internet is fast and reliable. KPN, Ziggo, and others provide good service. Mobile data is reasonably priced with good coverage. Connectivity is never an issue.",
        "nightlife": "Amsterdam's nightlife is famous—and diverse. The Red Light District is a tourist draw but beyond that are excellent club nights (techno scene is strong), brown cafés (traditional pubs), cocktail bars, and live music venues. The scene is sophisticated and varies by neighborhood. Leidseplein and Rembrandtplein are nightlife hubs.",
        "nature": "The Dutch landscape is flat but charming—canals, windmills, tulip fields in spring. Vondelpark and Amsterdamse Bos offer city green space. The coast is a short train ride (Zandvoort). The countryside is perfect for cycling. National parks like Hoge Veluwe are accessible by train. Nature is different here but peaceful.",
        "safety": "Amsterdam is safe but requires street smarts. Bike theft is rampant—invest in good locks. Pickpocketing occurs in tourist areas. The Red Light District has sketchy elements late at night. Drug tourism creates some issues. Overall, violent crime is rare and most areas are safe.",
        "food": "Traditional Dutch food is limited (bitterballen, stamppot, cheese), but Amsterdam's food scene is excellent due to its international population. Indonesian (rijsttafel), Surinamese, Turkish, and global cuisines thrive. Markets like Albert Cuyp offer street food. Fine dining options are world-class. Cheese and stroopwafels are must-tries.",
        "community": "Amsterdam has a large international community, including many nomads and remote workers. Coworking spaces are plentiful. Meetup groups cover every interest. The startup scene is vibrant. English is so common that it's easy to never learn Dutch. The community is diverse and welcoming.",
        "english": "English proficiency in Amsterdam is near-native for most Dutch people. It's one of the easiest non-English countries to live in as an English speaker. Business, social life, and services all operate smoothly in English. Learning Dutch is optional, though appreciated for deeper integration.",
        "visa": "EU citizens have full rights. Non-EU nationals can use the Dutch-American Friendship Treaty (DAFT) visa, various startup visas, or the highly skilled migrant visa. The Netherlands doesn't have a specific nomad visa. Many non-EU nomads work remotely while on tourist status, though technically not permitted.",
        "culture": "Dutch culture values directness, equality, and gezelligheid (coziness). The city's Golden Age heritage shows in the museums (Rijksmuseum, Van Gogh), canal houses, and trading history. Liberal attitudes toward drugs and sex work are part of the cultural fabric. Design, architecture, and cycling culture define daily life.",
        "cleanliness": "Amsterdam is relatively clean, though the city center shows wear from tourism. Canals can smell in summer. The Dutch generally maintain tidy spaces. Graffiti exists in some areas. Public transport is clean. Overall, it's well-maintained for a major tourist destination.",
        "airquality": "Air quality is generally good. The AQI typically ranges 25-50. The flat landscape and sea proximity help. Traffic contributes to urban pollution, but cycling culture reduces it. Not a significant concern for most people."
    },
    "dubrovnik": {
        "climate": "Dubrovnik has a Mediterranean climate—hot, dry summers (25-30°C) and mild, wet winters (10-15°C). Summer is peak season with crowds. Shoulder seasons (May-June, September-October) offer ideal conditions: warm weather, swimming possible, fewer tourists. Winter is quiet with occasional rain. The climate supports year-round outdoor living.",
        "cost": "Dubrovnik is Croatia's most expensive city due to tourism. Budget €1,800-2,800/month. Rent varies dramatically by season—€800-1,500/month for a decent apartment, more in summer. Daily expenses are moderate by European standards. Eating out costs €10-20, coffee €2-3. The shoulder season offers better value.",
        "wifi": "Croatian internet is solid. Cafés offer free WiFi (20-50 Mbps typically). Coworking options are limited but growing. Home internet reaches 50-100 Mbps in urban areas. A1 and T-Hrvatski provide good mobile data. The infrastructure supports remote work, though options are fewer than in larger cities.",
        "nightlife": "Dubrovnik's nightlife is seasonal and tourist-oriented. Beach clubs like Banje and East West draw summer crowds. The old town has bars but closes relatively early. Culture Klub Revelin hosts electronic music events. Off-season, nightlife is quieter. It's more about sunset drinks than clubbing.",
        "nature": "The Adriatic coast is stunning—crystal-clear water, dramatic cliffs, and pine-covered islands. Lokrum Island is a quick ferry ride for beaches and swimming. Kayaking the city walls at sunset is magical. Mljet National Park is a day trip. The Pelješac Peninsula offers wine and beaches. Nature access is exceptional.",
        "safety": "Dubrovnik is very safe. Crime against tourists is rare. The worst you'll encounter might be overpriced restaurants in tourist zones. Walking at night is fine. The main safety concerns are summer heat, strong sun, and boat/swimming safety. It's a genuinely secure destination.",
        "food": "Dalmatian cuisine features fresh seafood, olive oil, and Mediterranean flavors. Black risotto, grilled fish, and peka (slow-cooked meat/vegetables) are local specialties. Wine from Pelješac is excellent. Restaurants range from tourist traps to excellent family-run konobas. Seek local recommendations to eat well.",
        "community": "Dubrovnik's nomad community is small but growing. The city attracts tourists more than long-term residents. Coworking infrastructure is developing. The expat community is limited compared to Croatian cities like Zagreb or Split. You'll need to be more proactive about building connections. Summer brings more remote workers.",
        "english": "English is widely spoken in Dubrovnik due to the tourism industry. Young Croats speak excellent English. You can navigate daily life easily. Learning Croatian is unnecessary for basic living but appreciated for deeper local connections.",
        "visa": "EU citizens have full freedom. Croatia joined the Schengen zone in 2023, so non-EU visitors have the standard 90-day limit. Croatia offers a Digital Nomad Visa (up to 1 year) for those earning €2,540+/month from non-Croatian sources—one of Europe's best such visas.",
        "culture": "Dubrovnik's culture centers on its medieval old town—a UNESCO World Heritage site. The city walls, marble streets, and baroque architecture are stunning. Game of Thrones filming put it on the map recently. Local traditions include folk music, religious festivals, and seafood celebrations. The culture is proudly Croatian with Adriatic flair.",
        "cleanliness": "The old town is impeccably maintained—crucial for tourism. Beaches are generally clean. The Adriatic water is pristine. Outside the old town, standards are still good. Public spaces are well-kept. It's one of Croatia's cleanest cities.",
        "airquality": "Air quality is excellent—sea breezes, limited industry, and low traffic in the old town. The AQI typically ranges 15-35 (good). The coastal location ensures fresh air. One of the cleaner places you can live in Europe."
    },
    "capetown": {
        "climate": "Cape Town has a Mediterranean climate with warm, dry summers (December-February, 25-30°C) and cool, wet winters (June-August, 10-15°C). The Cape Doctor (summer wind) can be strong. Seasons are reversed from the Northern Hemisphere. The climate is generally pleasant, though winter can be gray and wet.",
        "cost": "Cape Town offers excellent value. Budget $1,500-2,500/month for a comfortable lifestyle. Rent in desirable areas (Sea Point, Green Point, Gardens) runs $600-1,200/month. Meals cost $5-15, excellent wine is cheap, and activities are affordable. The rand exchange rate makes it even better for foreign earners.",
        "wifi": "South African internet has improved significantly. Fiber is available in most urban areas (50-200 Mbps). Load shedding (power outages) is the challenge—invest in a UPS or choose accommodations with backup power. Coworking spaces handle outages well. Mobile data from Vodacom and MTN provides backup connectivity.",
        "nature": "Cape Town's natural setting is unparalleled. Table Mountain dominates the skyline with hiking trails. Beaches from Camps Bay to Boulders (penguins!) are world-class. The Cape Peninsula, wine regions (Stellenbosch, Franschhoek), and whale watching at Hermanus are nearby. Nature is the primary reason people fall in love with Cape Town.",
        "safety": "Safety requires serious attention. Cape Town has high crime rates—certain areas are no-go zones, especially at night. Tourist areas (V&A Waterfront, Atlantic Seaboard) are safer. Use Uber, avoid walking alone after dark, don't display valuables, and research neighborhoods. Most nomads live comfortably but stay aware.",
        "food": "Cape Town's food scene is excellent—African, Cape Malay, Indian, and international influences merge. Wine country restaurants are world-class and affordable. Braai (barbecue) culture is central. Seafood is fresh. Neighborhoods like Woodstock and Bree Street are foodie destinations. The quality-to-price ratio is exceptional.",
        "community": "Cape Town has a growing nomad community. Coworking spaces like Workshop17, &Collective, and Inner City Ideas Cartel host events. The startup scene is Africa's strongest. Expat groups are active. The community is diverse—locals, African tech talent, and international nomads mix. Connections form relatively easily.",
        "english": "English is one of South Africa's official languages and Cape Town's primary business language. You'll have no communication barriers. Afrikaans and Xhosa are also spoken. This is one of the easiest places in Africa for English speakers.",
        "visa": "Most nationalities get 90 days visa-free. South Africa doesn't have a specific digital nomad visa, though there are discussions. Some nomads use business visas or stay within the tourist visa limits. Extending stays requires leaving and re-entering or more complex visa processes.",
        "culture": "Cape Town's culture reflects South Africa's complexity—colonial history, apartheid legacy, African roots, and rainbow nation ideals. Museums (District Six, Robben Island) tell important stories. The arts scene is vibrant. Wine and food culture are sophisticated. The city is liberal by South African standards. Understanding the context enriches the experience.",
        "cleanliness": "Cleanliness varies dramatically by area. Affluent neighborhoods are well-maintained. Less fortunate areas struggle with informal settlements and service delivery. The city center and tourist areas are generally clean. Beaches are well-kept. The inequality is visible and confronting.",
        "airquality": "Air quality is generally good thanks to ocean breezes and minimal heavy industry. The AQI typically ranges 20-50. The biggest environmental concern is water scarcity rather than air quality. Cape Town is pleasant to breathe in."
    },
    "telaviv": {
        "climate": "Tel Aviv has a Mediterranean climate—hot, humid summers (27-32°C) and mild, wet winters (10-18°C). Summer lasts from May to October with beach weather. Winters are short with rainfall. The spring and fall shoulders are ideal. Sea breezes moderate summer heat. The climate supports the famous outdoor lifestyle.",
        "cost": "Tel Aviv is expensive—comparable to Western European capitals. Budget $3,000-4,500/month. Rent is high: $1,500-2,500/month for a decent apartment. Meals cost $15-30, groceries are pricey. The strong shekel and tech economy drive costs up. However, beach access is free and some pleasures are affordable.",
        "wifi": "Israeli tech infrastructure is excellent. Cafés offer fast, free WiFi. Coworking spaces have fiber (100+ Mbps). Home internet is fast and reliable. Mobile networks (Partner, Cellcom, Pelephone) provide excellent coverage and affordable data. Tech city credentials are earned.",
        "nightlife": "Tel Aviv's nightlife is legendary—the city that never sleeps. Clubs open Thursday night and run through Saturday. Rothschild, Florentin, and the port area have diverse scenes. LGBTQ+ nightlife is world-class. Beach parties, rooftop bars, live music—options are endless. The energy is infectious.",
        "nature": "Beyond the beaches (which are excellent), nature requires day trips. The Golan Heights, Dead Sea, Negev Desert, and Mediterranean coast offer dramatic landscapes. Ein Gedi oasis and Masada are must-visits. Within the city, Yarkon Park provides green space. The country is small—nature is always accessible.",
        "safety": "Security situation is complex. Tel Aviv itself is safe—low crime, walkable at night. The broader regional situation requires awareness. Occasional rocket alerts (Iron Dome protects well) can occur. Political tensions exist. Most residents and visitors live normally without daily concerns. The city feels surprisingly relaxed.",
        "food": "Israeli cuisine is exceptional—hummus, falafel, shakshuka, fresh salads, and Middle Eastern flavors shine. The food scene has exploded with innovative restaurants. Markets like Carmel and Sarona showcase local ingredients. Breakfast culture is elaborate. Vegan options are plentiful. Dining is a highlight of Tel Aviv life.",
        "community": "Tel Aviv has a strong tech and startup community—the 'Startup Nation' lives here. Coworking spaces and accelerators are numerous. The nomad community is growing alongside the established expat scene. Networking events are frequent. The mix of tech, creative, and entrepreneurial people creates dynamic energy.",
        "english": "English is widely spoken—Israel has strong ties to English-speaking countries and tech demands it. Business, social life, and services work fine in English. Hebrew is the local language; Arabic is also official. Most Israelis speak functional to excellent English.",
        "visa": "Tourist visas allow 90 days for most nationalities. Israel offers various work visas but nothing specifically for nomads. Some remote workers stay on tourist status; others use volunteer or student visas. The innovation visa targets entrepreneurs. The bureaucracy can be challenging.",
        "culture": "Israeli culture is direct, intense, and vibrant. Jewish heritage dominates but the society is diverse—secular and religious, immigrants from dozens of countries, Arab minority. The work-hard-play-hard ethos is real. History is omnipresent. Bauhaus architecture (White City) defines Tel Aviv's look. The culture is fascinating and complex.",
        "cleanliness": "Tel Aviv is reasonably clean but imperfect—beach areas are maintained, but some neighborhoods show urban grit. Street cats are everywhere. The Mediterranean lifestyle is slightly chaotic. Public spaces are functional rather than pristine. Not the cleanest city, but acceptable.",
        "airquality": "Air quality is generally good, especially by the coast where sea breezes help. The AQI typically ranges 30-60. Summer haze and occasional dust storms can occur. It's not a significant concern for daily life."
    },
    "porto": {
        "climate": "Porto has an Atlantic climate—mild but wetter than Lisbon. Summers are warm (20-28°C) but not hot. Winters are cool (8-14°C) and rainy. The Douro valley inland is warmer. Expect more gray days than southern Portugal, but the dramatic skies and green landscapes are beautiful. Layering is essential year-round.",
        "cost": "Porto remains affordable despite growing popularity. Budget €1,300-2,000/month. Rent in central areas runs €600-1,000/month. Meals cost €8-15, wine is excellent and cheap, and transport is affordable. It's slightly cheaper than Lisbon with a different character. The value is excellent.",
        "wifi": "Portuguese internet infrastructure is excellent. Cafés offer reliable free WiFi (30-80 Mbps typically). Coworking spaces have fiber (100+ Mbps). Home internet is fast and affordable. NOS, MEO, and Vodafone provide good service. Connectivity is never an issue.",
        "nightlife": "Porto's nightlife is vibrant, centered on Galerias de Paris and the Ribeira district. Wine bars, craft beer spots, live music venues, and clubs cater to different tastes. The scene is more intimate than Lisbon—it's easier to become a regular. Thursday nights are lively. The vibe is unpretentious.",
        "nature": "The Douro Valley (UNESCO World Heritage) is Porto's backyard—wine quintas, terraced vineyards, and river cruises. The Atlantic beaches of Foz are within the city. The Costa Nova striped houses and Aveiro lagoon are day trips. The Peneda-Gerês National Park offers mountain hiking. Nature is accessible and varied.",
        "safety": "Porto is very safe—one of Europe's safest cities. Crime is rare, and walking at night is comfortable. Tourist scams are minimal compared to Lisbon. The worst you might encounter is some mild hassle in tourist zones. The relaxed atmosphere reflects genuine security.",
        "food": "Portuguese cuisine shines in Porto. Francesinha (the local meat sandwich) is legendary. Fresh fish, seafood rice, tripas (tripe—the city's traditional dish), and petiscos (Portuguese tapas) are excellent. The Bolhão market showcases ingredients. Port wine from the famous caves is obligatory. Food is a serious pleasure.",
        "community": "Porto's nomad community is smaller but growing fast. Coworking spaces like Porto i/o and Synergy have active communities. The city attracts a slightly different nomad than Lisbon—perhaps more focused, less party-oriented. Making connections requires more initiative but rewards with quality relationships.",
        "english": "English is widely spoken, especially among younger Portuguese and in tourist areas. You can navigate daily life easily. Porto is slightly less English-saturated than Lisbon, but communication is rarely problematic. Learning Portuguese basics is appreciated.",
        "visa": "Same as Lisbon—EU citizens are free, others get 90 days in Schengen. Portugal's D7 visa and Digital Nomad Visa apply equally to Porto. The NHR tax regime attracts many remote workers. Porto's lower cost makes visa income requirements easier to meet.",
        "culture": "Porto's culture is proudly distinct from Lisbon. The city has a working-class heritage and directness that contrasts with the capital's bureaucratic sophistication. Azulejo tiles cover buildings, creating blue-and-white streetscapes. The literary history (Lello bookstore inspired Harry Potter), fado in local tascas, and the port wine tradition define the culture.",
        "cleanliness": "Porto is clean and well-maintained, especially in tourist areas. The historic center shows some age but is charming rather than dirty. River and beach areas are kept clean. Public spaces are functional. It's tidier than many European cities of similar size.",
        "airquality": "Air quality is good—Atlantic winds, limited industry, and moderate traffic keep the air fresh. The AQI typically ranges 20-45. Winter inversions occasionally trap pollution. Overall, it's a healthy place to breathe."
    }
}

def main():
    # Load existing data
    if os.path.exists(DATA_FILE):
        with open(DATA_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
    else:
        data = {}

    # Add new descriptions
    for city_id, descriptions in DESCRIPTIONS.items():
        data[city_id] = descriptions
        print(f"Added descriptions for {city_id}")

    # Save data
    with open(DATA_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
