/**
 * Add timezone offset (UTC hours) to each city in cities-data.js
 */

const fs = require('fs');
const path = require('path');

// Timezone offsets for each city (UTC hours)
// Positive = east of UTC, Negative = west of UTC
const TIMEZONE_OFFSETS = {
  // Europe - Western
  'lisbon': 0,
  'porto': 0,
  'faro': 0,
  'ericeira': 0,
  'barcelona': 1,
  'madrid': 1,
  'berlin': 1,
  'prague': 1,
  'budapest': 1,
  'vienna': 1,
  'amsterdam': 1,
  'brussels': 1,
  'paris': 1,
  'munich': 1,
  'zurich': 1,
  'milan': 1,
  'rome': 1,
  'florence': 1,
  'naples': 1,
  'copenhagen': 1,
  'stockholm': 1,
  'oslo': 1,
  'helsinki': 2,
  'tallinn': 2,
  'riga': 2,
  'vilnius': 2,
  'warsaw': 1,
  'krakow': 1,
  'bucharest': 2,
  'sofia': 2,
  'belgrade': 1,
  'zagreb': 1,
  'ljubljana': 1,
  'athens': 2,
  'istanbul': 3,
  'tbilisi': 4,
  'yerevan': 4,
  'kyiv': 2,
  'malta': 1,
  'dublin': 0,
  'edinburgh': 0,
  'london': 0,
  'manchester': 0,
  'birmingham': 0,
  'reykjavik': 0,
  'nicosia': 2,
  'cyprus': 2,
  'split': 1,
  'dubrovnik': 1,
  'bratislava': 1,
  'gdansk': 1,
  'wroclaw': 1,
  'poznan': 1,
  'brno': 1,
  'malaga': 1,
  'valencia': 1,
  'seville': 1,
  'granada': 1,
  'palma': 1,
  'tarifa': 1,
  'bilbao': 1,
  'gijon': 1,
  'canary': 0,
  'tenerife': 0,
  'lapalma': 0,
  'laspalmas': 0,
  'fuerteventura': 0,
  'lyon': 1,
  'nice': 1,
  'geneva': 1,
  'hamburg': 1,
  'rotterdam': 1,
  'utrecht': 1,
  'antwerp': 1,
  'ghent': 1,
  'cork': 0,
  'thessaloniki': 2,
  'crete': 2,
  'palermo': 1,
  'valletta': 1,
  'clujnapoca': 2,
  'plovdiv': 2,
  'podgorica': 1,
  'tirana': 1,
  'sarajevo': 1,
  'skopje': 1,
  'batumi': 4,
  'antalya': 3,
  'stavanger': 1,

  // Asia
  'chiangmai': 7,
  'bangkok': 7,
  'phuket': 7,
  'kosamui': 7,
  'kohsamui': 7,
  'kohphangan': 7,
  'krabi': 7,
  'pattaya': 7,
  'huahin': 7,
  'bali': 8,
  'ubud': 8,
  'canggu': 8,
  'jakarta': 7,
  'yogyakarta': 7,
  'kualalumpur': 8,
  'penang': 8,
  'langkawi': 8,
  'ipoh': 8,
  'singapore': 8,
  'hochiminhcity': 7,
  'hanoi': 7,
  'danang': 7,
  'hoian': 7,
  'nhatrang': 7,
  'phuquoc': 7,
  'phnompenh': 7,
  'siemreap': 7,
  'vientiane': 7,
  'luangprabang': 7,
  'manila': 8,
  'cebu': 8,
  'boracay': 8,
  'palawan': 8,
  'taipei': 8,
  'kaohsiung': 8,
  'hongkong': 8,
  'macau': 8,
  'seoul': 9,
  'busan': 9,
  'jeju': 9,
  'tokyo': 9,
  'osaka': 9,
  'kyoto': 9,
  'fukuoka': 9,
  'okinawa': 9,
  'sapporo': 9,
  'nagoya': 9,
  'beijing': 8,
  'shanghai': 8,
  'shenzhen': 8,
  'guangzhou': 8,
  'chengdu': 8,
  'xian': 8,
  'mumbai': 5.5,
  'delhi': 5.5,
  'bangalore': 5.5,
  'goa': 5.5,
  'jaipur': 5.5,
  'kolkata': 5.5,
  'chennai': 5.5,
  'hyderabad': 5.5,
  'pune': 5.5,
  'kochi': 5.5,
  'kathmandu': 5.75,
  'pokhara': 5.75,
  'colombo': 5.5,
  'weligama': 5.5,
  'dhaka': 6,
  'almaty': 6,
  'tashkent': 5,
  'bishkek': 6,
  'dushanbe': 5,
  'baku': 4,
  'dubai': 4,
  'abudhabi': 4,
  'doha': 3,
  'muscat': 4,
  'telaviv': 2,
  'jerusalem': 2,
  'amman': 2,
  'beirut': 2,

  // Americas
  'mexicocity': -6,
  'guadalajara': -6,
  'oaxaca': -6,
  'playadelcarmen': -5,
  'tulum': -5,
  'cancun': -5,
  'puertovallarta': -6,
  'sanmigueldeallende': -6,
  'merida': -6,
  'guanajuato': -6,
  'puertoescondido': -6,
  'sayulita': -6,
  'medellin': -5,
  'bogota': -5,
  'cartagena': -5,
  'santamarta': -5,
  'cali': -5,
  'buenosaires': -3,
  'mendoza': -3,
  'cordoba': -3,
  'bariloche': -3,
  'santiago': -3,
  'valparaiso': -3,
  'lima': -5,
  'cusco': -5,
  'arequipa': -5,
  'quito': -5,
  'guayaquil': -5,
  'cuenca': -5,
  'montanita': -5,
  'lapaz': -4,
  'sucre': -4,
  'cochabamba': -4,
  'santacruz': -4,
  'montevideo': -3,
  'asuncion': -4,
  'saopaulo': -3,
  'riodejaneiro': -3,
  'florianopolis': -3,
  'salvador': -3,
  'fortaleza': -3,
  'recife': -3,
  'brasilia': -3,
  'sanjose': -6,
  'sanjosecr': -6,
  'tamarindo': -6,
  'lakeatitlan': -6,
  'antigua': -6,
  'boquete': -5,
  'panama': -5,
  'sanjuan': -4,
  'santodomingo': -4,
  'puntacana': -4,
  'havana': -5,
  'nassau': -5,
  'kingston': -5,
  'newyork': -5,
  'losangeles': -8,
  'sanfrancisco': -8,
  'miami': -5,
  'austin': -6,
  'denver': -7,
  'seattle': -8,
  'chicago': -6,
  'boston': -5,
  'atlanta': -5,
  'portland': -8,
  'sandiego': -8,
  'lasvegas': -8,
  'phoenix': -7,
  'nashville': -6,
  'neworleans': -6,
  'minneapolis': -6,
  'detroit': -5,
  'philadelphia': -5,
  'washingtondc': -5,
  'honolulu': -10,
  'toronto': -5,
  'vancouver': -8,
  'montreal': -5,
  'calgary': -7,
  'ottawa': -5,
  'victoria': -8,

  // Africa
  'accra': 0,
  'dakar': 0,
  'capetown': 2,
  'johannesburg': 2,
  'durban': 2,
  'nairobi': 3,
  'mombasa': 3,
  'accra': 0,
  'lagos': 1,
  'abuja': 1,
  'cairo': 2,
  'marrakech': 1,
  'casablanca': 1,
  'fes': 1,
  'rabat': 1,
  'tangier': 1,
  'essaouira': 1,
  'taghazout': 1,
  'chefchaouen': 1,
  'tunis': 1,
  'algiers': 1,
  'dakar': 0,
  'addisababa': 3,
  'kampala': 3,
  'kigali': 2,
  'zanzibar': 3,
  'daressalaam': 3,
  'mauritius': 4,
  'reunion': 4,

  // Oceania
  'sydney': 10,
  'melbourne': 10,
  'brisbane': 10,
  'byronbay': 10,
  'perth': 8,
  'adelaide': 9.5,
  'goldcoast': 10,
  'cairns': 10,
  'darwin': 9.5,
  'hobart': 10,
  'auckland': 12,
  'wellington': 12,
  'queenstown': 12,
  'christchurch': 12,
  'fiji': 12
};

const citiesFile = path.join(__dirname, '..', 'cities-data.js');
let content = fs.readFileSync(citiesFile, 'utf-8');

// Add timezone to each city entry
let updatedCount = 0;
let missingCities = [];

for (const [cityId, offset] of Object.entries(TIMEZONE_OFFSETS)) {
  // Pattern: find city block with this id that doesn't have timezone yet
  // Match lng: value followed by newline and closing brace (no timezone)
  const pattern = new RegExp(
    `(id:\\s*"${cityId}"[\\s\\S]*?lng:\\s*-?[\\d.]+)(\\s*\\n\\s*\\})`,
    'i'
  );

  if (content.match(pattern)) {
    content = content.replace(pattern, `$1,\n    timezone: ${offset}$2`);
    updatedCount++;
  }
}

// Find cities without timezone and report them
const cityIdPattern = /id:\s*"([^"]+)"/g;
let match;
while ((match = cityIdPattern.exec(content)) !== null) {
  const cityId = match[1];
  if (!TIMEZONE_OFFSETS[cityId]) {
    missingCities.push(cityId);
  }
}

fs.writeFileSync(citiesFile, content, 'utf-8');

console.log(`Updated ${updatedCount} cities with timezone data`);
if (missingCities.length > 0) {
  console.log(`\nWarning: ${missingCities.length} cities missing timezone data:`);
  missingCities.forEach(city => console.log(`  - ${city}`));
}
