#!/usr/bin/env python3
"""
Add 100 new cities to cities-data.js
"""

import json
import re

# 100 new cities with AI-estimated scores
NEW_CITIES = [
    # EUROPE - 25 cities
    {
        "id": "lecce",
        "climateType": "Mediterranean",
        "name": "Lecce",
        "country": "Italy",
        "flag": "🇮🇹",
        "tagline": "The Florence of the South with baroque beauty.",
        "image": "https://images.unsplash.com/photo-1590073242678-70ee3fc28e8e?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 7, "wifi": 6, "nightlife": 6, "nature": 7, "safety": 8, "food": 9, "community": 3, "english": 4, "visa": 7, "culture": 9, "cleanliness": 7, "airquality": 8},
        "costPerMonth": 1400,
        "lat": 40.3516,
        "lng": 18.1718,
        "timezone": 1
    },
    {
        "id": "trieste",
        "climateType": "Humid Subtropical",
        "name": "Trieste",
        "country": "Italy",
        "flag": "🇮🇹",
        "tagline": "Where Italian and Central European culture meet.",
        "image": "https://images.unsplash.com/photo-1586378842517-2d08e0f3e9d0?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 6, "wifi": 7, "nightlife": 5, "nature": 7, "safety": 8, "food": 8, "community": 3, "english": 5, "visa": 7, "culture": 8, "cleanliness": 8, "airquality": 8},
        "costPerMonth": 1500,
        "lat": 45.6495,
        "lng": 13.7768,
        "timezone": 1
    },
    {
        "id": "genoa",
        "climateType": "Mediterranean",
        "name": "Genoa",
        "country": "Italy",
        "flag": "🇮🇹",
        "tagline": "Historic port city with authentic Italian charm.",
        "image": "https://images.unsplash.com/photo-1553901753-215db344677a?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 6, "wifi": 7, "nightlife": 6, "nature": 7, "safety": 7, "food": 9, "community": 3, "english": 4, "visa": 7, "culture": 8, "cleanliness": 6, "airquality": 7},
        "costPerMonth": 1600,
        "lat": 44.4056,
        "lng": 8.9463,
        "timezone": 1
    },
    {
        "id": "sansebastian",
        "climateType": "Oceanic",
        "name": "San Sebastián",
        "country": "Spain",
        "flag": "🇪🇸",
        "tagline": "World-class food scene on the Basque coast.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 4, "wifi": 8, "nightlife": 7, "nature": 9, "safety": 9, "food": 10, "community": 4, "english": 5, "visa": 7, "culture": 8, "cleanliness": 9, "airquality": 9},
        "costPerMonth": 2200,
        "lat": 43.3183,
        "lng": -1.9812,
        "timezone": 1
    },
    {
        "id": "alicante",
        "climateType": "Mediterranean",
        "name": "Alicante",
        "country": "Spain",
        "flag": "🇪🇸",
        "tagline": "Sunny beach city with affordable living.",
        "image": "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&h=500&fit=crop",
        "scores": {"climate": 9, "cost": 6, "wifi": 7, "nightlife": 7, "nature": 7, "safety": 8, "food": 8, "community": 5, "english": 5, "visa": 7, "culture": 6, "cleanliness": 7, "airquality": 8},
        "costPerMonth": 1500,
        "lat": 38.3452,
        "lng": -0.4810,
        "timezone": 1
    },
    {
        "id": "zaragoza",
        "climateType": "Semi-Arid",
        "name": "Zaragoza",
        "country": "Spain",
        "flag": "🇪🇸",
        "tagline": "Underrated Spanish gem between Madrid and Barcelona.",
        "image": "https://images.unsplash.com/photo-1584355998413-0a25a4c8a7b9?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 7, "wifi": 7, "nightlife": 6, "nature": 5, "safety": 8, "food": 8, "community": 3, "english": 4, "visa": 7, "culture": 7, "cleanliness": 7, "airquality": 7},
        "costPerMonth": 1300,
        "lat": 41.6488,
        "lng": -0.8891,
        "timezone": 1
    },
    {
        "id": "oxford",
        "climateType": "Oceanic",
        "name": "Oxford",
        "country": "United Kingdom",
        "flag": "🇬🇧",
        "tagline": "Historic university city with intellectual charm.",
        "image": "https://images.unsplash.com/photo-1590073242678-70ee3fc28e8e?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 3, "wifi": 9, "nightlife": 6, "nature": 7, "safety": 8, "food": 7, "community": 5, "english": 10, "visa": 5, "culture": 10, "cleanliness": 8, "airquality": 7},
        "costPerMonth": 2500,
        "lat": 51.7520,
        "lng": -1.2577,
        "timezone": 0
    },
    {
        "id": "cambridge",
        "climateType": "Oceanic",
        "name": "Cambridge",
        "country": "United Kingdom",
        "flag": "🇬🇧",
        "tagline": "Punting, pubs, and world-class education.",
        "image": "https://images.unsplash.com/photo-1578922992690-9a4d43e6f45d?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 3, "wifi": 9, "nightlife": 5, "nature": 6, "safety": 8, "food": 7, "community": 5, "english": 10, "visa": 5, "culture": 9, "cleanliness": 8, "airquality": 7},
        "costPerMonth": 2400,
        "lat": 52.2053,
        "lng": 0.1218,
        "timezone": 0
    },
    {
        "id": "york",
        "climateType": "Oceanic",
        "name": "York",
        "country": "United Kingdom",
        "flag": "🇬🇧",
        "tagline": "Medieval walls and Viking history.",
        "image": "https://images.unsplash.com/photo-1595777216528-071e0127ccbf?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 4, "wifi": 8, "nightlife": 6, "nature": 6, "safety": 8, "food": 7, "community": 3, "english": 10, "visa": 5, "culture": 9, "cleanliness": 8, "airquality": 7},
        "costPerMonth": 1800,
        "lat": 53.9591,
        "lng": -1.0815,
        "timezone": 0
    },
    {
        "id": "bath",
        "climateType": "Oceanic",
        "name": "Bath",
        "country": "United Kingdom",
        "flag": "🇬🇧",
        "tagline": "Georgian elegance and Roman baths.",
        "image": "https://images.unsplash.com/photo-1569431059140-8f7bfa24f8a0?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 4, "wifi": 8, "nightlife": 5, "nature": 7, "safety": 9, "food": 7, "community": 3, "english": 10, "visa": 5, "culture": 9, "cleanliness": 9, "airquality": 8},
        "costPerMonth": 2000,
        "lat": 51.3758,
        "lng": -2.3599,
        "timezone": 0
    },
    {
        "id": "trondheim",
        "climateType": "Subarctic",
        "name": "Trondheim",
        "country": "Norway",
        "flag": "🇳🇴",
        "tagline": "Tech hub in Norway's historic heartland.",
        "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=500&fit=crop",
        "scores": {"climate": 3, "cost": 2, "wifi": 9, "nightlife": 5, "nature": 9, "safety": 10, "food": 7, "community": 4, "english": 9, "visa": 6, "culture": 7, "cleanliness": 9, "airquality": 10},
        "costPerMonth": 3000,
        "lat": 63.4305,
        "lng": 10.3951,
        "timezone": 1
    },
    {
        "id": "tromso",
        "climateType": "Subarctic",
        "name": "Tromsø",
        "country": "Norway",
        "flag": "🇳🇴",
        "tagline": "Northern lights and midnight sun.",
        "image": "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&h=500&fit=crop",
        "scores": {"climate": 2, "cost": 2, "wifi": 9, "nightlife": 5, "nature": 10, "safety": 10, "food": 6, "community": 3, "english": 9, "visa": 6, "culture": 6, "cleanliness": 9, "airquality": 10},
        "costPerMonth": 3200,
        "lat": 69.6492,
        "lng": 18.9553,
        "timezone": 1
    },
    {
        "id": "turku",
        "climateType": "Humid Continental",
        "name": "Turku",
        "country": "Finland",
        "flag": "🇫🇮",
        "tagline": "Finland's oldest city with archipelago access.",
        "image": "https://images.unsplash.com/photo-1538332576228-eb5b4c4de6f5?w=800&h=500&fit=crop",
        "scores": {"climate": 3, "cost": 4, "wifi": 9, "nightlife": 5, "nature": 8, "safety": 10, "food": 7, "community": 3, "english": 9, "visa": 7, "culture": 7, "cleanliness": 9, "airquality": 10},
        "costPerMonth": 1800,
        "lat": 60.4518,
        "lng": 22.2666,
        "timezone": 2
    },
    {
        "id": "oulu",
        "climateType": "Subarctic",
        "name": "Oulu",
        "country": "Finland",
        "flag": "🇫🇮",
        "tagline": "Tech city near the Arctic Circle.",
        "image": "https://images.unsplash.com/photo-1569067225637-a4c40a9f5c07?w=800&h=500&fit=crop",
        "scores": {"climate": 2, "cost": 4, "wifi": 9, "nightlife": 4, "nature": 8, "safety": 10, "food": 6, "community": 3, "english": 9, "visa": 7, "culture": 5, "cleanliness": 9, "airquality": 10},
        "costPerMonth": 1700,
        "lat": 65.0121,
        "lng": 25.4651,
        "timezone": 2
    },
    {
        "id": "groningen",
        "climateType": "Oceanic",
        "name": "Groningen",
        "country": "Netherlands",
        "flag": "🇳🇱",
        "tagline": "Youthful energy in the Dutch north.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 5, "wifi": 9, "nightlife": 7, "nature": 6, "safety": 9, "food": 7, "community": 5, "english": 9, "visa": 7, "culture": 7, "cleanliness": 8, "airquality": 7},
        "costPerMonth": 1600,
        "lat": 53.2194,
        "lng": 6.5665,
        "timezone": 1
    },
    {
        "id": "thehague",
        "climateType": "Oceanic",
        "name": "The Hague",
        "country": "Netherlands",
        "flag": "🇳🇱",
        "tagline": "International city of peace and justice.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 4, "wifi": 9, "nightlife": 6, "nature": 7, "safety": 8, "food": 7, "community": 5, "english": 9, "visa": 7, "culture": 8, "cleanliness": 8, "airquality": 7},
        "costPerMonth": 2000,
        "lat": 52.0705,
        "lng": 4.3007,
        "timezone": 1
    },
    {
        "id": "leuven",
        "climateType": "Oceanic",
        "name": "Leuven",
        "country": "Belgium",
        "flag": "🇧🇪",
        "tagline": "Beer, bikes, and brilliant minds.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 5, "wifi": 8, "nightlife": 7, "nature": 5, "safety": 8, "food": 8, "community": 4, "english": 8, "visa": 7, "culture": 7, "cleanliness": 7, "airquality": 7},
        "costPerMonth": 1500,
        "lat": 50.8798,
        "lng": 4.7005,
        "timezone": 1
    },
    {
        "id": "luxembourg",
        "climateType": "Oceanic",
        "name": "Luxembourg City",
        "country": "Luxembourg",
        "flag": "🇱🇺",
        "tagline": "Tiny country, big opportunities.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 2, "wifi": 9, "nightlife": 5, "nature": 7, "safety": 10, "food": 7, "community": 4, "english": 8, "visa": 7, "culture": 7, "cleanliness": 9, "airquality": 8},
        "costPerMonth": 2800,
        "lat": 49.6116,
        "lng": 6.1319,
        "timezone": 1
    },
    {
        "id": "nuremberg",
        "climateType": "Humid Continental",
        "name": "Nuremberg",
        "country": "Germany",
        "flag": "🇩🇪",
        "tagline": "Medieval charm meets modern innovation.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 5, "wifi": 9, "nightlife": 6, "nature": 6, "safety": 8, "food": 8, "community": 4, "english": 7, "visa": 7, "culture": 8, "cleanliness": 8, "airquality": 7},
        "costPerMonth": 1600,
        "lat": 49.4521,
        "lng": 11.0767,
        "timezone": 1
    },
    {
        "id": "stuttgart",
        "climateType": "Humid Continental",
        "name": "Stuttgart",
        "country": "Germany",
        "flag": "🇩🇪",
        "tagline": "Automotive excellence in wine country.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 5, "wifi": 9, "nightlife": 6, "nature": 7, "safety": 8, "food": 7, "community": 4, "english": 7, "visa": 7, "culture": 7, "cleanliness": 8, "airquality": 7},
        "costPerMonth": 1800,
        "lat": 48.7758,
        "lng": 9.1829,
        "timezone": 1
    },
    {
        "id": "dusseldorf",
        "climateType": "Oceanic",
        "name": "Düsseldorf",
        "country": "Germany",
        "flag": "🇩🇪",
        "tagline": "Fashion capital with Japanese flair.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 5, "wifi": 9, "nightlife": 7, "nature": 6, "safety": 8, "food": 8, "community": 5, "english": 7, "visa": 7, "culture": 7, "cleanliness": 8, "airquality": 7},
        "costPerMonth": 1800,
        "lat": 51.2277,
        "lng": 6.7735,
        "timezone": 1
    },
    {
        "id": "freiburg",
        "climateType": "Oceanic",
        "name": "Freiburg",
        "country": "Germany",
        "flag": "🇩🇪",
        "tagline": "Germany's sunniest and greenest city.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 5, "wifi": 8, "nightlife": 5, "nature": 9, "safety": 9, "food": 7, "community": 4, "english": 7, "visa": 7, "culture": 7, "cleanliness": 9, "airquality": 9},
        "costPerMonth": 1700,
        "lat": 47.9990,
        "lng": 7.8421,
        "timezone": 1
    },
    {
        "id": "strasbourg",
        "climateType": "Humid Continental",
        "name": "Strasbourg",
        "country": "France",
        "flag": "🇫🇷",
        "tagline": "French-German fusion at the EU heart.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 5, "wifi": 8, "nightlife": 6, "nature": 6, "safety": 7, "food": 9, "community": 4, "english": 6, "visa": 7, "culture": 8, "cleanliness": 7, "airquality": 7},
        "costPerMonth": 1600,
        "lat": 48.5734,
        "lng": 7.7521,
        "timezone": 1
    },
    {
        "id": "grenoble",
        "climateType": "Humid Continental",
        "name": "Grenoble",
        "country": "France",
        "flag": "🇫🇷",
        "tagline": "Alpine innovation hub at mountain's foot.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 5, "wifi": 8, "nightlife": 5, "nature": 10, "safety": 7, "food": 8, "community": 4, "english": 5, "visa": 7, "culture": 6, "cleanliness": 7, "airquality": 7},
        "costPerMonth": 1500,
        "lat": 45.1885,
        "lng": 5.7245,
        "timezone": 1
    },
    {
        "id": "aixenprovence",
        "climateType": "Mediterranean",
        "name": "Aix-en-Provence",
        "country": "France",
        "flag": "🇫🇷",
        "tagline": "Cézanne's city of fountains and light.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 4, "wifi": 7, "nightlife": 5, "nature": 8, "safety": 8, "food": 9, "community": 4, "english": 5, "visa": 7, "culture": 9, "cleanliness": 8, "airquality": 8},
        "costPerMonth": 2000,
        "lat": 43.5297,
        "lng": 5.4474,
        "timezone": 1
    },

    # ASIA - 30 cities
    {
        "id": "chiangrai",
        "climateType": "Tropical Savanna",
        "name": "Chiang Rai",
        "country": "Thailand",
        "flag": "🇹🇭",
        "tagline": "Northern Thailand's artistic and spiritual center.",
        "image": "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 9, "wifi": 6, "nightlife": 4, "nature": 9, "safety": 8, "food": 8, "community": 4, "english": 4, "visa": 8, "culture": 8, "cleanliness": 7, "airquality": 5},
        "costPerMonth": 800,
        "lat": 19.9105,
        "lng": 99.8406,
        "timezone": 7
    },
    {
        "id": "pattaya",
        "climateType": "Tropical Savanna",
        "name": "Pattaya",
        "country": "Thailand",
        "flag": "🇹🇭",
        "tagline": "Beach resort town close to Bangkok.",
        "image": "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 8, "wifi": 7, "nightlife": 9, "nature": 6, "safety": 6, "food": 8, "community": 6, "english": 6, "visa": 8, "culture": 4, "cleanliness": 5, "airquality": 6},
        "costPerMonth": 1100,
        "lat": 12.9236,
        "lng": 100.8825,
        "timezone": 7
    },
    {
        "id": "khaolak",
        "climateType": "Tropical Monsoon",
        "name": "Khao Lak",
        "country": "Thailand",
        "flag": "🇹🇭",
        "tagline": "Quiet beach paradise near world-class diving.",
        "image": "https://images.unsplash.com/photo-1537956965359-7573183d8f53?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 8, "wifi": 5, "nightlife": 3, "nature": 9, "safety": 8, "food": 7, "community": 3, "english": 4, "visa": 8, "culture": 5, "cleanliness": 7, "airquality": 8},
        "costPerMonth": 900,
        "lat": 8.6377,
        "lng": 98.2468,
        "timezone": 7
    },
    {
        "id": "kanchanaburi",
        "climateType": "Tropical Savanna",
        "name": "Kanchanaburi",
        "country": "Thailand",
        "flag": "🇹🇭",
        "tagline": "Riverside town with WWII history and waterfalls.",
        "image": "https://images.unsplash.com/photo-1506665531195-3566af2b4dfa?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 9, "wifi": 5, "nightlife": 4, "nature": 9, "safety": 8, "food": 7, "community": 2, "english": 3, "visa": 8, "culture": 7, "cleanliness": 6, "airquality": 7},
        "costPerMonth": 700,
        "lat": 14.0227,
        "lng": 99.5328,
        "timezone": 7
    },
    {
        "id": "sanur",
        "climateType": "Tropical Rainforest",
        "name": "Sanur",
        "country": "Indonesia",
        "flag": "🇮🇩",
        "tagline": "Bali's relaxed beachside alternative.",
        "image": "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 8, "wifi": 7, "nightlife": 4, "nature": 7, "safety": 8, "food": 8, "community": 6, "english": 6, "visa": 7, "culture": 7, "cleanliness": 7, "airquality": 7},
        "costPerMonth": 1200,
        "lat": -8.6783,
        "lng": 115.2639,
        "timezone": 8
    },
    {
        "id": "solo",
        "climateType": "Tropical Rainforest",
        "name": "Solo",
        "country": "Indonesia",
        "flag": "🇮🇩",
        "tagline": "Java's cultural heart with royal heritage.",
        "image": "https://images.unsplash.com/photo-1555899434-94d1368aa7af?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 9, "wifi": 6, "nightlife": 4, "nature": 5, "safety": 7, "food": 8, "community": 2, "english": 3, "visa": 7, "culture": 8, "cleanliness": 5, "airquality": 5},
        "costPerMonth": 600,
        "lat": -7.5755,
        "lng": 110.8243,
        "timezone": 7
    },
    {
        "id": "medan",
        "climateType": "Tropical Rainforest",
        "name": "Medan",
        "country": "Indonesia",
        "flag": "🇮🇩",
        "tagline": "Gateway to Lake Toba and Sumatra.",
        "image": "https://images.unsplash.com/photo-1555899434-94d1368aa7af?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 9, "wifi": 6, "nightlife": 5, "nature": 7, "safety": 6, "food": 8, "community": 2, "english": 3, "visa": 7, "culture": 6, "cleanliness": 4, "airquality": 5},
        "costPerMonth": 600,
        "lat": 3.5952,
        "lng": 98.6722,
        "timezone": 7
    },
    {
        "id": "makassar",
        "climateType": "Tropical Monsoon",
        "name": "Makassar",
        "country": "Indonesia",
        "flag": "🇮🇩",
        "tagline": "Eastern Indonesia's vibrant coastal hub.",
        "image": "https://images.unsplash.com/photo-1555899434-94d1368aa7af?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 9, "wifi": 5, "nightlife": 5, "nature": 7, "safety": 6, "food": 8, "community": 2, "english": 3, "visa": 7, "culture": 6, "cleanliness": 4, "airquality": 6},
        "costPerMonth": 550,
        "lat": -5.1477,
        "lng": 119.4327,
        "timezone": 8
    },
    {
        "id": "kuching",
        "climateType": "Tropical Rainforest",
        "name": "Kuching",
        "country": "Malaysia",
        "flag": "🇲🇾",
        "tagline": "Cat city gateway to Borneo's rainforests.",
        "image": "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 8, "wifi": 7, "nightlife": 5, "nature": 9, "safety": 8, "food": 8, "community": 3, "english": 7, "visa": 8, "culture": 7, "cleanliness": 7, "airquality": 6},
        "costPerMonth": 900,
        "lat": 1.5535,
        "lng": 110.3593,
        "timezone": 8
    },
    {
        "id": "johorbahru",
        "climateType": "Tropical Rainforest",
        "name": "Johor Bahru",
        "country": "Malaysia",
        "flag": "🇲🇾",
        "tagline": "Singapore's affordable neighbor.",
        "image": "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 7, "wifi": 7, "nightlife": 5, "nature": 5, "safety": 6, "food": 8, "community": 3, "english": 7, "visa": 8, "culture": 5, "cleanliness": 6, "airquality": 5},
        "costPerMonth": 1000,
        "lat": 1.4927,
        "lng": 103.7414,
        "timezone": 8
    },
    {
        "id": "baguio",
        "climateType": "Subtropical Highland",
        "name": "Baguio",
        "country": "Philippines",
        "flag": "🇵🇭",
        "tagline": "Cool mountain retreat in tropical Philippines.",
        "image": "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 9, "wifi": 6, "nightlife": 5, "nature": 8, "safety": 7, "food": 7, "community": 4, "english": 8, "visa": 7, "culture": 6, "cleanliness": 5, "airquality": 7},
        "costPerMonth": 700,
        "lat": 16.4023,
        "lng": 120.5960,
        "timezone": 8
    },
    {
        "id": "davao",
        "climateType": "Tropical Rainforest",
        "name": "Davao",
        "country": "Philippines",
        "flag": "🇵🇭",
        "tagline": "Clean and safe city in Mindanao.",
        "image": "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 9, "wifi": 6, "nightlife": 5, "nature": 8, "safety": 7, "food": 8, "community": 3, "english": 8, "visa": 7, "culture": 5, "cleanliness": 7, "airquality": 7},
        "costPerMonth": 700,
        "lat": 7.1907,
        "lng": 125.4553,
        "timezone": 8
    },
    {
        "id": "iloilo",
        "climateType": "Tropical Savanna",
        "name": "Iloilo",
        "country": "Philippines",
        "flag": "🇵🇭",
        "tagline": "City of love with growing nomad scene.",
        "image": "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 9, "wifi": 6, "nightlife": 5, "nature": 6, "safety": 7, "food": 8, "community": 3, "english": 8, "visa": 7, "culture": 6, "cleanliness": 6, "airquality": 7},
        "costPerMonth": 650,
        "lat": 10.7202,
        "lng": 122.5621,
        "timezone": 8
    },
    {
        "id": "cantho",
        "climateType": "Tropical Monsoon",
        "name": "Can Tho",
        "country": "Vietnam",
        "flag": "🇻🇳",
        "tagline": "Mekong Delta's largest city with floating markets.",
        "image": "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 9, "wifi": 6, "nightlife": 4, "nature": 7, "safety": 8, "food": 9, "community": 2, "english": 3, "visa": 7, "culture": 7, "cleanliness": 5, "airquality": 6},
        "costPerMonth": 600,
        "lat": 10.0452,
        "lng": 105.7469,
        "timezone": 7
    },
    {
        "id": "hue",
        "climateType": "Tropical Monsoon",
        "name": "Hue",
        "country": "Vietnam",
        "flag": "🇻🇳",
        "tagline": "Imperial capital with UNESCO heritage.",
        "image": "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 9, "wifi": 6, "nightlife": 4, "nature": 7, "safety": 8, "food": 9, "community": 3, "english": 4, "visa": 7, "culture": 9, "cleanliness": 6, "airquality": 6},
        "costPerMonth": 600,
        "lat": 16.4637,
        "lng": 107.5909,
        "timezone": 7
    },
    {
        "id": "ninhbinh",
        "climateType": "Humid Subtropical",
        "name": "Ninh Binh",
        "country": "Vietnam",
        "flag": "🇻🇳",
        "tagline": "Ha Long Bay on land with stunning karsts.",
        "image": "https://images.unsplash.com/photo-1528127269322-539801943592?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 9, "wifi": 5, "nightlife": 2, "nature": 10, "safety": 8, "food": 7, "community": 2, "english": 2, "visa": 7, "culture": 8, "cleanliness": 6, "airquality": 7},
        "costPerMonth": 500,
        "lat": 20.2506,
        "lng": 105.9745,
        "timezone": 7
    },
    {
        "id": "vangvieng",
        "climateType": "Tropical Savanna",
        "name": "Vang Vieng",
        "country": "Laos",
        "flag": "🇱🇦",
        "tagline": "Backpacker paradise turned chill retreat.",
        "image": "https://images.unsplash.com/photo-1558862107-d49ef2a04d72?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 9, "wifi": 4, "nightlife": 5, "nature": 9, "safety": 7, "food": 6, "community": 4, "english": 4, "visa": 7, "culture": 6, "cleanliness": 5, "airquality": 8},
        "costPerMonth": 600,
        "lat": 18.9221,
        "lng": 102.4476,
        "timezone": 7
    },
    {
        "id": "sihanoukville",
        "climateType": "Tropical Monsoon",
        "name": "Sihanoukville",
        "country": "Cambodia",
        "flag": "🇰🇭",
        "tagline": "Beach town with island-hopping access.",
        "image": "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 8, "wifi": 5, "nightlife": 6, "nature": 8, "safety": 5, "food": 6, "community": 3, "english": 5, "visa": 8, "culture": 4, "cleanliness": 4, "airquality": 7},
        "costPerMonth": 800,
        "lat": 10.6093,
        "lng": 103.5296,
        "timezone": 7
    },
    {
        "id": "battambang",
        "climateType": "Tropical Savanna",
        "name": "Battambang",
        "country": "Cambodia",
        "flag": "🇰🇭",
        "tagline": "Cambodia's artistic soul with French charm.",
        "image": "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 9, "wifi": 5, "nightlife": 3, "nature": 6, "safety": 7, "food": 7, "community": 2, "english": 4, "visa": 8, "culture": 7, "cleanliness": 5, "airquality": 7},
        "costPerMonth": 550,
        "lat": 13.0957,
        "lng": 103.2022,
        "timezone": 7
    },
    {
        "id": "nagoya",
        "climateType": "Humid Subtropical",
        "name": "Nagoya",
        "country": "Japan",
        "flag": "🇯🇵",
        "tagline": "Japan's industrial heart with samurai history.",
        "image": "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 4, "wifi": 9, "nightlife": 6, "nature": 6, "safety": 10, "food": 9, "community": 4, "english": 4, "visa": 6, "culture": 8, "cleanliness": 9, "airquality": 7},
        "costPerMonth": 2000,
        "lat": 35.1815,
        "lng": 136.9066,
        "timezone": 9
    },
    {
        "id": "hiroshima",
        "climateType": "Humid Subtropical",
        "name": "Hiroshima",
        "country": "Japan",
        "flag": "🇯🇵",
        "tagline": "City of peace with powerful history.",
        "image": "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 5, "wifi": 9, "nightlife": 5, "nature": 7, "safety": 10, "food": 9, "community": 3, "english": 4, "visa": 6, "culture": 9, "cleanliness": 9, "airquality": 8},
        "costPerMonth": 1800,
        "lat": 34.3853,
        "lng": 132.4553,
        "timezone": 9
    },
    {
        "id": "kanazawa",
        "climateType": "Humid Subtropical",
        "name": "Kanazawa",
        "country": "Japan",
        "flag": "🇯🇵",
        "tagline": "Preserved Edo-era culture and gardens.",
        "image": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 5, "wifi": 8, "nightlife": 4, "nature": 7, "safety": 10, "food": 9, "community": 2, "english": 3, "visa": 6, "culture": 9, "cleanliness": 9, "airquality": 8},
        "costPerMonth": 1700,
        "lat": 36.5944,
        "lng": 136.6256,
        "timezone": 9
    },
    {
        "id": "kaohsiung",
        "climateType": "Tropical Monsoon",
        "name": "Kaohsiung",
        "country": "Taiwan",
        "flag": "🇹🇼",
        "tagline": "Taiwan's sunny southern harbor city.",
        "image": "https://images.unsplash.com/photo-1470004914212-05527e49370b?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 6, "wifi": 8, "nightlife": 6, "nature": 7, "safety": 9, "food": 9, "community": 4, "english": 5, "visa": 8, "culture": 7, "cleanliness": 8, "airquality": 6},
        "costPerMonth": 1200,
        "lat": 22.6273,
        "lng": 120.3014,
        "timezone": 8
    },
    {
        "id": "tainan",
        "climateType": "Tropical Monsoon",
        "name": "Tainan",
        "country": "Taiwan",
        "flag": "🇹🇼",
        "tagline": "Taiwan's oldest city with temple culture.",
        "image": "https://images.unsplash.com/photo-1470004914212-05527e49370b?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 7, "wifi": 8, "nightlife": 5, "nature": 6, "safety": 9, "food": 10, "community": 3, "english": 4, "visa": 8, "culture": 9, "cleanliness": 7, "airquality": 6},
        "costPerMonth": 1000,
        "lat": 22.9998,
        "lng": 120.2269,
        "timezone": 8
    },
    {
        "id": "gwangju",
        "climateType": "Humid Subtropical",
        "name": "Gwangju",
        "country": "South Korea",
        "flag": "🇰🇷",
        "tagline": "Korea's art capital with democratic spirit.",
        "image": "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 6, "wifi": 9, "nightlife": 6, "nature": 6, "safety": 9, "food": 8, "community": 2, "english": 4, "visa": 6, "culture": 8, "cleanliness": 8, "airquality": 6},
        "costPerMonth": 1300,
        "lat": 35.1595,
        "lng": 126.8526,
        "timezone": 9
    },
    {
        "id": "daegu",
        "climateType": "Humid Subtropical",
        "name": "Daegu",
        "country": "South Korea",
        "flag": "🇰🇷",
        "tagline": "Korea's fashion hub surrounded by mountains.",
        "image": "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 6, "wifi": 9, "nightlife": 6, "nature": 7, "safety": 9, "food": 8, "community": 2, "english": 4, "visa": 6, "culture": 6, "cleanliness": 8, "airquality": 5},
        "costPerMonth": 1200,
        "lat": 35.8714,
        "lng": 128.6014,
        "timezone": 9
    },
    {
        "id": "jaipur",
        "climateType": "Semi-Arid",
        "name": "Jaipur",
        "country": "India",
        "flag": "🇮🇳",
        "tagline": "The Pink City with royal heritage.",
        "image": "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 9, "wifi": 6, "nightlife": 4, "nature": 5, "safety": 6, "food": 8, "community": 4, "english": 6, "visa": 7, "culture": 10, "cleanliness": 4, "airquality": 4},
        "costPerMonth": 600,
        "lat": 26.9124,
        "lng": 75.7873,
        "timezone": 5.5
    },
    {
        "id": "kochi",
        "climateType": "Tropical Monsoon",
        "name": "Kochi",
        "country": "India",
        "flag": "🇮🇳",
        "tagline": "Kerala's cosmopolitan port city.",
        "image": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 8, "wifi": 6, "nightlife": 5, "nature": 8, "safety": 7, "food": 9, "community": 4, "english": 7, "visa": 7, "culture": 8, "cleanliness": 6, "airquality": 6},
        "costPerMonth": 700,
        "lat": 9.9312,
        "lng": 76.2673,
        "timezone": 5.5
    },
    {
        "id": "udaipur",
        "climateType": "Semi-Arid",
        "name": "Udaipur",
        "country": "India",
        "flag": "🇮🇳",
        "tagline": "City of Lakes with romantic charm.",
        "image": "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 9, "wifi": 5, "nightlife": 4, "nature": 7, "safety": 7, "food": 7, "community": 4, "english": 5, "visa": 7, "culture": 9, "cleanliness": 5, "airquality": 5},
        "costPerMonth": 550,
        "lat": 24.5854,
        "lng": 73.7125,
        "timezone": 5.5
    },

    # AMERICAS - 25 cities
    {
        "id": "sanfrancisco",
        "climateType": "Mediterranean",
        "name": "San Francisco",
        "country": "United States",
        "flag": "🇺🇸",
        "tagline": "Tech capital with iconic fog and hills.",
        "image": "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 1, "wifi": 10, "nightlife": 8, "nature": 8, "safety": 5, "food": 9, "community": 9, "english": 10, "visa": 5, "culture": 9, "cleanliness": 5, "airquality": 6},
        "costPerMonth": 4500,
        "lat": 37.7749,
        "lng": -122.4194,
        "timezone": -8
    },
    {
        "id": "sandiego",
        "climateType": "Mediterranean",
        "name": "San Diego",
        "country": "United States",
        "flag": "🇺🇸",
        "tagline": "Perfect weather and beach vibes year-round.",
        "image": "https://images.unsplash.com/photo-1538097304804-2a1b932466a9?w=800&h=500&fit=crop",
        "scores": {"climate": 9, "cost": 3, "wifi": 9, "nightlife": 7, "nature": 9, "safety": 7, "food": 8, "community": 6, "english": 10, "visa": 5, "culture": 7, "cleanliness": 8, "airquality": 8},
        "costPerMonth": 3200,
        "lat": 32.7157,
        "lng": -117.1611,
        "timezone": -8
    },
    {
        "id": "losangeles",
        "climateType": "Mediterranean",
        "name": "Los Angeles",
        "country": "United States",
        "flag": "🇺🇸",
        "tagline": "Entertainment capital with endless sunshine.",
        "image": "https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?w=800&h=500&fit=crop",
        "scores": {"climate": 9, "cost": 2, "wifi": 9, "nightlife": 9, "nature": 8, "safety": 5, "food": 9, "community": 8, "english": 10, "visa": 5, "culture": 9, "cleanliness": 5, "airquality": 4},
        "costPerMonth": 3500,
        "lat": 34.0522,
        "lng": -118.2437,
        "timezone": -8
    },
    {
        "id": "newyork",
        "climateType": "Humid Subtropical",
        "name": "New York",
        "country": "United States",
        "flag": "🇺🇸",
        "tagline": "The city that never sleeps.",
        "image": "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 1, "wifi": 9, "nightlife": 10, "nature": 5, "safety": 6, "food": 10, "community": 9, "english": 10, "visa": 5, "culture": 10, "cleanliness": 4, "airquality": 5},
        "costPerMonth": 4500,
        "lat": 40.7128,
        "lng": -74.0060,
        "timezone": -5
    },
    {
        "id": "chicago",
        "climateType": "Humid Continental",
        "name": "Chicago",
        "country": "United States",
        "flag": "🇺🇸",
        "tagline": "Windy city with world-class architecture.",
        "image": "https://images.unsplash.com/photo-1494522855154-9297ac14b55f?w=800&h=500&fit=crop",
        "scores": {"climate": 4, "cost": 3, "wifi": 9, "nightlife": 8, "nature": 6, "safety": 5, "food": 9, "community": 7, "english": 10, "visa": 5, "culture": 9, "cleanliness": 6, "airquality": 6},
        "costPerMonth": 2800,
        "lat": 41.8781,
        "lng": -87.6298,
        "timezone": -6
    },
    {
        "id": "boston",
        "climateType": "Humid Continental",
        "name": "Boston",
        "country": "United States",
        "flag": "🇺🇸",
        "tagline": "Historic charm meets innovation.",
        "image": "https://images.unsplash.com/photo-1501979376754-2ff867a4f659?w=800&h=500&fit=crop",
        "scores": {"climate": 4, "cost": 2, "wifi": 9, "nightlife": 7, "nature": 6, "safety": 6, "food": 8, "community": 7, "english": 10, "visa": 5, "culture": 9, "cleanliness": 7, "airquality": 7},
        "costPerMonth": 3200,
        "lat": 42.3601,
        "lng": -71.0589,
        "timezone": -5
    },
    {
        "id": "nashville",
        "climateType": "Humid Subtropical",
        "name": "Nashville",
        "country": "United States",
        "flag": "🇺🇸",
        "tagline": "Music City with southern hospitality.",
        "image": "https://images.unsplash.com/photo-1545419913-775e3e3d62ce?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 4, "wifi": 8, "nightlife": 9, "nature": 6, "safety": 6, "food": 8, "community": 6, "english": 10, "visa": 5, "culture": 8, "cleanliness": 6, "airquality": 7},
        "costPerMonth": 2200,
        "lat": 36.1627,
        "lng": -86.7816,
        "timezone": -6
    },
    {
        "id": "calgary",
        "climateType": "Humid Continental",
        "name": "Calgary",
        "country": "Canada",
        "flag": "🇨🇦",
        "tagline": "Gateway to the Canadian Rockies.",
        "image": "https://images.unsplash.com/photo-1476304884326-cd2c88572c5f?w=800&h=500&fit=crop",
        "scores": {"climate": 3, "cost": 4, "wifi": 9, "nightlife": 6, "nature": 10, "safety": 9, "food": 7, "community": 5, "english": 10, "visa": 6, "culture": 6, "cleanliness": 9, "airquality": 8},
        "costPerMonth": 2200,
        "lat": 51.0447,
        "lng": -114.0719,
        "timezone": -7
    },
    {
        "id": "victoria",
        "climateType": "Oceanic",
        "name": "Victoria",
        "country": "Canada",
        "flag": "🇨🇦",
        "tagline": "Garden city with British charm.",
        "image": "https://images.unsplash.com/photo-1559511260-66a654ae982a?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 3, "wifi": 9, "nightlife": 5, "nature": 9, "safety": 9, "food": 7, "community": 4, "english": 10, "visa": 6, "culture": 7, "cleanliness": 9, "airquality": 9},
        "costPerMonth": 2400,
        "lat": 48.4284,
        "lng": -123.3656,
        "timezone": -8
    },
    {
        "id": "ottawa",
        "climateType": "Humid Continental",
        "name": "Ottawa",
        "country": "Canada",
        "flag": "🇨🇦",
        "tagline": "Canada's bilingual capital city.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 3, "cost": 4, "wifi": 9, "nightlife": 5, "nature": 7, "safety": 9, "food": 7, "community": 4, "english": 9, "visa": 6, "culture": 8, "cleanliness": 9, "airquality": 8},
        "costPerMonth": 2000,
        "lat": 45.4215,
        "lng": -75.6972,
        "timezone": -5
    },
    {
        "id": "puertorico",
        "climateType": "Tropical Rainforest",
        "name": "San Juan",
        "country": "Puerto Rico",
        "flag": "🇵🇷",
        "tagline": "Caribbean vibes with US convenience.",
        "image": "https://images.unsplash.com/photo-1579687196544-08ae57ab5966?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 4, "wifi": 7, "nightlife": 8, "nature": 8, "safety": 5, "food": 8, "community": 5, "english": 8, "visa": 10, "culture": 8, "cleanliness": 5, "airquality": 8},
        "costPerMonth": 2200,
        "lat": 18.4655,
        "lng": -66.1057,
        "timezone": -4
    },
    {
        "id": "cancun",
        "climateType": "Tropical Savanna",
        "name": "Cancún",
        "country": "Mexico",
        "flag": "🇲🇽",
        "tagline": "Caribbean beaches with Mexican culture.",
        "image": "https://images.unsplash.com/photo-1510097467424-192d713fd8b2?w=800&h=500&fit=crop",
        "scores": {"climate": 9, "cost": 6, "wifi": 7, "nightlife": 9, "nature": 8, "safety": 6, "food": 8, "community": 6, "english": 6, "visa": 9, "culture": 6, "cleanliness": 7, "airquality": 8},
        "costPerMonth": 1500,
        "lat": 21.1619,
        "lng": -86.8515,
        "timezone": -5
    },
    {
        "id": "queretaro",
        "climateType": "Semi-Arid",
        "name": "Querétaro",
        "country": "Mexico",
        "flag": "🇲🇽",
        "tagline": "Colonial charm with modern amenities.",
        "image": "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 7, "wifi": 7, "nightlife": 6, "nature": 6, "safety": 7, "food": 8, "community": 4, "english": 4, "visa": 9, "culture": 8, "cleanliness": 7, "airquality": 7},
        "costPerMonth": 1100,
        "lat": 20.5888,
        "lng": -100.3899,
        "timezone": -6
    },
    {
        "id": "mazatlan",
        "climateType": "Tropical Savanna",
        "name": "Mazatlán",
        "country": "Mexico",
        "flag": "🇲🇽",
        "tagline": "Beach town with authentic Mexican life.",
        "image": "https://images.unsplash.com/photo-1510097467424-192d713fd8b2?w=800&h=500&fit=crop",
        "scores": {"climate": 9, "cost": 7, "wifi": 6, "nightlife": 7, "nature": 8, "safety": 6, "food": 8, "community": 4, "english": 4, "visa": 9, "culture": 7, "cleanliness": 6, "airquality": 8},
        "costPerMonth": 1000,
        "lat": 23.2494,
        "lng": -106.4111,
        "timezone": -7
    },
    {
        "id": "leon",
        "climateType": "Semi-Arid",
        "name": "León",
        "country": "Mexico",
        "flag": "🇲🇽",
        "tagline": "Leather capital with growing tech scene.",
        "image": "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 8, "wifi": 7, "nightlife": 5, "nature": 5, "safety": 6, "food": 7, "community": 2, "english": 3, "visa": 9, "culture": 6, "cleanliness": 6, "airquality": 6},
        "costPerMonth": 900,
        "lat": 21.1250,
        "lng": -101.6860,
        "timezone": -6
    },
    {
        "id": "manizales",
        "climateType": "Subtropical Highland",
        "name": "Manizales",
        "country": "Colombia",
        "flag": "🇨🇴",
        "tagline": "Coffee region city with eternal spring.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 8, "wifi": 6, "nightlife": 5, "nature": 9, "safety": 7, "food": 7, "community": 3, "english": 3, "visa": 7, "culture": 6, "cleanliness": 6, "airquality": 8},
        "costPerMonth": 900,
        "lat": 5.0689,
        "lng": -75.5174,
        "timezone": -5
    },
    {
        "id": "pereira",
        "climateType": "Subtropical Highland",
        "name": "Pereira",
        "country": "Colombia",
        "flag": "🇨🇴",
        "tagline": "Heart of Colombia's coffee triangle.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 8, "wifi": 6, "nightlife": 5, "nature": 8, "safety": 6, "food": 7, "community": 2, "english": 3, "visa": 7, "culture": 5, "cleanliness": 6, "airquality": 8},
        "costPerMonth": 850,
        "lat": 4.8087,
        "lng": -75.6906,
        "timezone": -5
    },
    {
        "id": "barranquilla",
        "climateType": "Tropical Savanna",
        "name": "Barranquilla",
        "country": "Colombia",
        "flag": "🇨🇴",
        "tagline": "Caribbean port city with carnival spirit.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 9, "cost": 8, "wifi": 6, "nightlife": 7, "nature": 5, "safety": 5, "food": 8, "community": 2, "english": 3, "visa": 7, "culture": 7, "cleanliness": 5, "airquality": 6},
        "costPerMonth": 900,
        "lat": 10.9685,
        "lng": -74.7813,
        "timezone": -5
    },
    {
        "id": "guayaquil",
        "climateType": "Tropical Savanna",
        "name": "Guayaquil",
        "country": "Ecuador",
        "flag": "🇪🇨",
        "tagline": "Ecuador's vibrant port city.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 8, "wifi": 6, "nightlife": 6, "nature": 6, "safety": 5, "food": 7, "community": 2, "english": 3, "visa": 8, "culture": 6, "cleanliness": 5, "airquality": 6},
        "costPerMonth": 900,
        "lat": -2.1894,
        "lng": -79.8891,
        "timezone": -5
    },
    {
        "id": "trujillo",
        "climateType": "Arid",
        "name": "Trujillo",
        "country": "Peru",
        "flag": "🇵🇪",
        "tagline": "City of eternal spring with ancient ruins.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 8, "wifi": 5, "nightlife": 5, "nature": 7, "safety": 5, "food": 8, "community": 2, "english": 2, "visa": 8, "culture": 8, "cleanliness": 5, "airquality": 7},
        "costPerMonth": 750,
        "lat": -8.1116,
        "lng": -79.0287,
        "timezone": -5
    },
    {
        "id": "cochabamba",
        "climateType": "Subtropical Highland",
        "name": "Cochabamba",
        "country": "Bolivia",
        "flag": "🇧🇴",
        "tagline": "City of eternal spring in the Andes.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 9, "wifi": 4, "nightlife": 5, "nature": 7, "safety": 5, "food": 6, "community": 2, "english": 2, "visa": 8, "culture": 6, "cleanliness": 4, "airquality": 5},
        "costPerMonth": 600,
        "lat": -17.3895,
        "lng": -66.1568,
        "timezone": -4
    },
    {
        "id": "rosario",
        "climateType": "Humid Subtropical",
        "name": "Rosario",
        "country": "Argentina",
        "flag": "🇦🇷",
        "tagline": "Birthplace of the Argentine flag and Messi.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 8, "wifi": 6, "nightlife": 7, "nature": 5, "safety": 5, "food": 8, "community": 2, "english": 3, "visa": 8, "culture": 7, "cleanliness": 6, "airquality": 7},
        "costPerMonth": 900,
        "lat": -32.9442,
        "lng": -60.6505,
        "timezone": -3
    },
    {
        "id": "mardelplata",
        "climateType": "Oceanic",
        "name": "Mar del Plata",
        "country": "Argentina",
        "flag": "🇦🇷",
        "tagline": "Argentina's summer beach capital.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 8, "wifi": 6, "nightlife": 7, "nature": 8, "safety": 6, "food": 8, "community": 2, "english": 3, "visa": 8, "culture": 6, "cleanliness": 6, "airquality": 9},
        "costPerMonth": 850,
        "lat": -38.0055,
        "lng": -57.5426,
        "timezone": -3
    },
    {
        "id": "recife",
        "climateType": "Tropical Monsoon",
        "name": "Recife",
        "country": "Brazil",
        "flag": "🇧🇷",
        "tagline": "Venice of Brazil with vibrant culture.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 9, "cost": 7, "wifi": 6, "nightlife": 8, "nature": 8, "safety": 4, "food": 8, "community": 3, "english": 3, "visa": 8, "culture": 8, "cleanliness": 5, "airquality": 7},
        "costPerMonth": 1000,
        "lat": -8.0476,
        "lng": -34.8770,
        "timezone": -3
    },

    # AFRICA & MIDDLE EAST - 15 cities
    {
        "id": "luxor",
        "climateType": "Arid",
        "name": "Luxor",
        "country": "Egypt",
        "flag": "🇪🇬",
        "tagline": "World's greatest open-air museum.",
        "image": "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 9, "wifi": 4, "nightlife": 3, "nature": 7, "safety": 6, "food": 7, "community": 2, "english": 5, "visa": 7, "culture": 10, "cleanliness": 4, "airquality": 6},
        "costPerMonth": 500,
        "lat": 25.6872,
        "lng": 32.6396,
        "timezone": 2
    },
    {
        "id": "alexandria",
        "climateType": "Mediterranean",
        "name": "Alexandria",
        "country": "Egypt",
        "flag": "🇪🇬",
        "tagline": "Egypt's Mediterranean pearl.",
        "image": "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 9, "wifi": 5, "nightlife": 5, "nature": 6, "safety": 6, "food": 8, "community": 2, "english": 5, "visa": 7, "culture": 9, "cleanliness": 4, "airquality": 6},
        "costPerMonth": 550,
        "lat": 31.2001,
        "lng": 29.9187,
        "timezone": 2
    },
    {
        "id": "capeverde",
        "climateType": "Arid",
        "name": "Praia",
        "country": "Cape Verde",
        "flag": "🇨🇻",
        "tagline": "Atlantic islands with year-round sun.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 7, "wifi": 5, "nightlife": 5, "nature": 8, "safety": 7, "food": 6, "community": 2, "english": 4, "visa": 6, "culture": 6, "cleanliness": 6, "airquality": 9},
        "costPerMonth": 1000,
        "lat": 14.9315,
        "lng": -23.5087,
        "timezone": -1
    },
    {
        "id": "windhoek",
        "climateType": "Semi-Arid",
        "name": "Windhoek",
        "country": "Namibia",
        "flag": "🇳🇦",
        "tagline": "Clean capital gateway to desert wonders.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 6, "wifi": 5, "nightlife": 4, "nature": 9, "safety": 6, "food": 6, "community": 2, "english": 7, "visa": 6, "culture": 5, "cleanliness": 8, "airquality": 9},
        "costPerMonth": 1100,
        "lat": -22.5609,
        "lng": 17.0658,
        "timezone": 2
    },
    {
        "id": "kampala",
        "climateType": "Tropical Savanna",
        "name": "Kampala",
        "country": "Uganda",
        "flag": "🇺🇬",
        "tagline": "Pearl of Africa's vibrant capital.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 8, "wifi": 5, "nightlife": 6, "nature": 8, "safety": 5, "food": 6, "community": 3, "english": 7, "visa": 6, "culture": 6, "cleanliness": 4, "airquality": 6},
        "costPerMonth": 800,
        "lat": 0.3476,
        "lng": 32.5825,
        "timezone": 3
    },
    {
        "id": "maputo",
        "climateType": "Tropical Savanna",
        "name": "Maputo",
        "country": "Mozambique",
        "flag": "🇲🇿",
        "tagline": "Portuguese-African fusion on the coast.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 7, "wifi": 4, "nightlife": 6, "nature": 7, "safety": 4, "food": 7, "community": 2, "english": 4, "visa": 6, "culture": 6, "cleanliness": 4, "airquality": 7},
        "costPerMonth": 1000,
        "lat": -25.9692,
        "lng": 32.5732,
        "timezone": 2
    },
    {
        "id": "arusha",
        "climateType": "Subtropical Highland",
        "name": "Arusha",
        "country": "Tanzania",
        "flag": "🇹🇿",
        "tagline": "Safari capital at Kilimanjaro's foot.",
        "image": "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 7, "wifi": 4, "nightlife": 4, "nature": 10, "safety": 6, "food": 6, "community": 3, "english": 6, "visa": 6, "culture": 6, "cleanliness": 5, "airquality": 8},
        "costPerMonth": 900,
        "lat": -3.3869,
        "lng": 36.6830,
        "timezone": 3
    },
    {
        "id": "addisababa",
        "climateType": "Subtropical Highland",
        "name": "Addis Ababa",
        "country": "Ethiopia",
        "flag": "🇪🇹",
        "tagline": "Africa's diplomatic capital at altitude.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 8, "wifi": 4, "nightlife": 5, "nature": 6, "safety": 5, "food": 7, "community": 3, "english": 5, "visa": 6, "culture": 8, "cleanliness": 4, "airquality": 6},
        "costPerMonth": 800,
        "lat": 8.9806,
        "lng": 38.7578,
        "timezone": 3
    },
    {
        "id": "salalah",
        "climateType": "Arid",
        "name": "Salalah",
        "country": "Oman",
        "flag": "🇴🇲",
        "tagline": "Oman's tropical escape with monsoon magic.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 5, "wifi": 6, "nightlife": 2, "nature": 8, "safety": 9, "food": 6, "community": 2, "english": 6, "visa": 5, "culture": 7, "cleanliness": 8, "airquality": 9},
        "costPerMonth": 1400,
        "lat": 17.0151,
        "lng": 54.0924,
        "timezone": 4
    },
    {
        "id": "bahrain",
        "climateType": "Arid",
        "name": "Manama",
        "country": "Bahrain",
        "flag": "🇧🇭",
        "tagline": "Gulf island with liberal vibes.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 4, "wifi": 8, "nightlife": 7, "nature": 4, "safety": 8, "food": 8, "community": 4, "english": 8, "visa": 6, "culture": 6, "cleanliness": 8, "airquality": 6},
        "costPerMonth": 2000,
        "lat": 26.2285,
        "lng": 50.5860,
        "timezone": 3
    },
    {
        "id": "riyadh",
        "climateType": "Arid",
        "name": "Riyadh",
        "country": "Saudi Arabia",
        "flag": "🇸🇦",
        "tagline": "Rapidly modernizing desert capital.",
        "image": "https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 4, "wifi": 8, "nightlife": 3, "nature": 4, "safety": 8, "food": 7, "community": 3, "english": 6, "visa": 4, "culture": 7, "cleanliness": 8, "airquality": 5},
        "costPerMonth": 2200,
        "lat": 24.7136,
        "lng": 46.6753,
        "timezone": 3
    },
    {
        "id": "jeddah",
        "climateType": "Arid",
        "name": "Jeddah",
        "country": "Saudi Arabia",
        "flag": "🇸🇦",
        "tagline": "Red Sea gateway with historic core.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 5, "wifi": 7, "nightlife": 3, "nature": 6, "safety": 8, "food": 7, "community": 3, "english": 6, "visa": 4, "culture": 7, "cleanliness": 7, "airquality": 6},
        "costPerMonth": 2000,
        "lat": 21.4858,
        "lng": 39.1925,
        "timezone": 3
    },
    {
        "id": "kuwait",
        "climateType": "Arid",
        "name": "Kuwait City",
        "country": "Kuwait",
        "flag": "🇰🇼",
        "tagline": "Oil-rich city-state on the Gulf.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 4, "cost": 3, "wifi": 8, "nightlife": 3, "nature": 3, "safety": 8, "food": 7, "community": 3, "english": 7, "visa": 4, "culture": 5, "cleanliness": 7, "airquality": 5},
        "costPerMonth": 2500,
        "lat": 29.3759,
        "lng": 47.9774,
        "timezone": 3
    },
    {
        "id": "ramallah",
        "climateType": "Mediterranean",
        "name": "Ramallah",
        "country": "Palestine",
        "flag": "🇵🇸",
        "tagline": "Cultural hub of the West Bank.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 6, "wifi": 6, "nightlife": 5, "nature": 6, "safety": 4, "food": 8, "community": 3, "english": 6, "visa": 3, "culture": 8, "cleanliness": 6, "airquality": 7},
        "costPerMonth": 1200,
        "lat": 31.9038,
        "lng": 35.2034,
        "timezone": 2
    },
    {
        "id": "yazd",
        "climateType": "Arid",
        "name": "Yazd",
        "country": "Iran",
        "flag": "🇮🇷",
        "tagline": "Ancient desert city of wind towers.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 9, "wifi": 4, "nightlife": 2, "nature": 7, "safety": 8, "food": 8, "community": 2, "english": 3, "visa": 4, "culture": 10, "cleanliness": 6, "airquality": 7},
        "costPerMonth": 500,
        "lat": 31.8974,
        "lng": 54.3569,
        "timezone": 3.5
    },

    # OCEANIA - 5 cities
    {
        "id": "darwin",
        "climateType": "Tropical Savanna",
        "name": "Darwin",
        "country": "Australia",
        "flag": "🇦🇺",
        "tagline": "Australia's tropical frontier town.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 7, "cost": 4, "wifi": 8, "nightlife": 5, "nature": 9, "safety": 7, "food": 7, "community": 3, "english": 10, "visa": 5, "culture": 5, "cleanliness": 7, "airquality": 8},
        "costPerMonth": 2200,
        "lat": -12.4634,
        "lng": 130.8456,
        "timezone": 9.5
    },
    {
        "id": "canberra",
        "climateType": "Oceanic",
        "name": "Canberra",
        "country": "Australia",
        "flag": "🇦🇺",
        "tagline": "Australia's planned capital city.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 6, "cost": 4, "wifi": 9, "nightlife": 4, "nature": 8, "safety": 9, "food": 7, "community": 3, "english": 10, "visa": 5, "culture": 8, "cleanliness": 9, "airquality": 8},
        "costPerMonth": 2000,
        "lat": -35.2809,
        "lng": 149.1300,
        "timezone": 10
    },
    {
        "id": "wellington",
        "climateType": "Oceanic",
        "name": "Wellington",
        "country": "New Zealand",
        "flag": "🇳🇿",
        "tagline": "Coolest little capital in the world.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 5, "cost": 4, "wifi": 9, "nightlife": 7, "nature": 8, "safety": 9, "food": 8, "community": 4, "english": 10, "visa": 6, "culture": 8, "cleanliness": 9, "airquality": 10},
        "costPerMonth": 2200,
        "lat": -41.2866,
        "lng": 174.7756,
        "timezone": 12
    },
    {
        "id": "suva",
        "climateType": "Tropical Rainforest",
        "name": "Suva",
        "country": "Fiji",
        "flag": "🇫🇯",
        "tagline": "South Pacific capital with island charm.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 6, "wifi": 5, "nightlife": 4, "nature": 9, "safety": 6, "food": 6, "community": 2, "english": 8, "visa": 7, "culture": 6, "cleanliness": 5, "airquality": 9},
        "costPerMonth": 1400,
        "lat": -18.1416,
        "lng": 178.4419,
        "timezone": 12
    },
    {
        "id": "noumea",
        "climateType": "Tropical Savanna",
        "name": "Nouméa",
        "country": "New Caledonia",
        "flag": "🇳🇨",
        "tagline": "French Pacific paradise.",
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
        "scores": {"climate": 8, "cost": 3, "wifi": 6, "nightlife": 4, "nature": 9, "safety": 7, "food": 7, "community": 2, "english": 4, "visa": 6, "culture": 6, "cleanliness": 7, "airquality": 9},
        "costPerMonth": 2500,
        "lat": -22.2758,
        "lng": 166.4580,
        "timezone": 11
    }
]

def main():
    # Read the existing file
    with open('cities-data.js', 'r', encoding='utf-8') as f:
        content = f.read()

    # Find where to insert (before the closing ];)
    insert_marker = "];"
    insert_pos = content.rfind(insert_marker)

    if insert_pos == -1:
        print("Could not find insertion point")
        return

    # Build the new cities string
    new_cities_str = ""
    for city in NEW_CITIES:
        scores = city['scores']
        new_cities_str += f'''  {{
    id: "{city['id']}",
    climateType: "{city['climateType']}",
    name: "{city['name']}",
    country: "{city['country']}",
    flag: "{city['flag']}",
    tagline: "{city['tagline']}",
    image: "{city['image']}",
    scores: {{
      climate: {scores['climate']},
      cost: {scores['cost']},
      wifi: {scores['wifi']},
      nightlife: {scores['nightlife']},
      nature: {scores['nature']},
      safety: {scores['safety']},
      food: {scores['food']},
      community: {scores['community']},
      english: {scores['english']},
      visa: {scores['visa']},
      culture: {scores['culture']},
      cleanliness: {scores['cleanliness']},
      airquality: {scores['airquality']}}},
    costPerMonth: {city['costPerMonth']},
    lat: {city['lat']},
    lng: {city['lng']},
    timezone: {city['timezone']}
  }},
'''

    # Insert the new cities
    new_content = content[:insert_pos] + new_cities_str + content[insert_pos:]

    # Update the comment at the top
    new_content = new_content.replace(
        "This file contains data for 323 popular digital nomad destinations.",
        f"This file contains data for {322 + len(NEW_CITIES)} popular digital nomad destinations."
    )

    # Write back
    with open('cities-data.js', 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"Added {len(NEW_CITIES)} new cities!")

if __name__ == "__main__":
    main()
