require(require('path').join(__dirname,'_safe_write.cjs'));
/**
 * Build-time only (node_modules/lucide-static is gitignored, never shipped).
 * Generates the two committed icon assets from authentic Lucide line icons (ISC):
 *   - assets/icons.svg        : one cached SVG sprite of <symbol> entries
 *   - scripts/lib/icons.cjs   : the source-of-truth used by every generator/sweep
 *                               (inner markup map, CATEGORY_ICON, WEATHER_ICON, icon()/inlineIcon()).
 * Re-run after adding an icon name below. Idempotent.
 */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const LUCIDE = path.join(ROOT, 'node_modules', 'lucide-static', 'icons');

// Every symbol the site needs, grouped by purpose (comment only).
const NAMES = [
  // categories (13)
  'sun', 'wallet', 'wifi', 'moon', 'trees', 'shield', 'utensils', 'users',
  'messages-square', 'stamp', 'drama', 'sparkles', 'wind',
  // weather
  'cloud-sun', 'cloud', 'cloud-fog', 'cloud-drizzle', 'cloud-rain', 'cloud-snow',
  'cloud-lightning', 'thermometer',
  // ui marks
  'check', 'x', 'thumbs-up', 'thumbs-down', 'star', 'badge-check',
  // homepage rank tiles
  'gem', 'coins', 'flower-2', 'users-round',
  // homepage tools grid
  'map', 'clock', 'target', 'scale', 'globe', 'trophy',
  // blog footer
  'compass', 'coffee',
];

// Pull the inner markup (paths/circles/...) out of a Lucide file, dropping the
// license comment and the outer <svg> wrapper. Collapse to a single line.
function innerOf(name) {
  const raw = fs.readFileSync(path.join(LUCIDE, name + '.svg'), 'utf8');
  const body = raw
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s+/g, ' ')
    .trim();
  return body;
}

const inner = {};
for (const n of NAMES) inner[n] = innerOf(n);

// 1. assets/icons.svg sprite. Stroke attrs live on each <symbol> so external
//    <use> resolves currentColor at the host; .nh-icon in CSS is the sizing hook.
const symbolAttrs =
  'viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" ' +
  'stroke-linecap="round" stroke-linejoin="round"';
const symbols = NAMES.map((n) => `  <symbol id="${n}" ${symbolAttrs}>${inner[n]}</symbol>`).join('\n');
const sprite =
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">\n` +
  `<!-- Line icons from Lucide (ISC). Built by scripts/build_icons.cjs. Do not edit by hand. -->\n` +
  symbols +
  `\n</svg>\n`;
fs.writeFileSync(path.join(ROOT, 'assets', 'icons.svg'), sprite);
console.log('assets/icons.svg written (' + NAMES.length + ' symbols)');

// 2. scripts/lib/icons.cjs source-of-truth.
const CATEGORY_ICON = {
  climate: 'sun', cost: 'wallet', wifi: 'wifi', nightlife: 'moon', nature: 'trees',
  safety: 'shield', food: 'utensils', community: 'users', english: 'messages-square',
  visa: 'stamp', culture: 'drama', cleanliness: 'sparkles', airquality: 'wind',
};
// Open-Meteo WMO weather_code -> icon name.
const WEATHER_ICON = {
  0: 'sun', 1: 'cloud-sun', 2: 'cloud-sun', 3: 'cloud',
  45: 'cloud-fog', 48: 'cloud-fog',
  51: 'cloud-drizzle', 53: 'cloud-drizzle', 55: 'cloud-drizzle',
  61: 'cloud-drizzle', 63: 'cloud-rain', 65: 'cloud-rain',
  71: 'cloud-snow', 73: 'cloud-snow', 75: 'cloud-snow',
  80: 'cloud-drizzle', 81: 'cloud-rain', 82: 'cloud-lightning',
  95: 'cloud-lightning', 96: 'cloud-lightning', 99: 'cloud-lightning',
};

const lib =
`/**
 * Source of truth for the site's line-icon system. Generated by scripts/build_icons.cjs
 * from Lucide (ISC). Symbols live in the cached sprite /assets/icons.svg; helpers below emit
 * either a <use> reference (default, light) or fully inline SVG (for contexts that cannot rely
 * on the external sprite). Used by every generator/sweep so all icons stay identical.
 */
'use strict';

// Inner markup per symbol (for inlineIcon()).
const ICON_INNER = ${JSON.stringify(inner, null, 2)};

const CATEGORY_ICON = ${JSON.stringify(CATEGORY_ICON, null, 2)};
const WEATHER_ICON = ${JSON.stringify(WEATHER_ICON, null, 2)};

const SYMBOL_ATTRS = 'viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';

// Reference the cached sprite (preferred).
function icon(name, extraClass) {
  const cls = 'nh-icon nh-icon-' + name + (extraClass ? ' ' + extraClass : '');
  return '<svg class="' + cls + '" aria-hidden="true"><use href="/assets/icons.svg#' + name + '"></use></svg>';
}

// Self-contained inline SVG (no sprite dependency).
function inlineIcon(name, extraClass) {
  const cls = 'nh-icon nh-icon-' + name + (extraClass ? ' ' + extraClass : '');
  return '<svg class="' + cls + '" ' + SYMBOL_ATTRS + ' aria-hidden="true">' + (ICON_INNER[name] || '') + '</svg>';
}

module.exports = { ICON_INNER, CATEGORY_ICON, WEATHER_ICON, icon, inlineIcon, SYMBOL_ATTRS };
`;
fs.mkdirSync(path.join(ROOT, 'scripts', 'lib'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'scripts', 'lib', 'icons.cjs'), lib);
console.log('scripts/lib/icons.cjs written');

// 3. Runtime helper in cities-data.js (globals for pages that render icons in JS,
//    e.g. compare.html categories). Idempotent: replace the marked block, or append.
{
  const p = path.join(ROOT, 'cities-data.js');
  let s = fs.readFileSync(p, 'utf8');
  const START = '// >>> nh-icons runtime (generated by scripts/build_icons.cjs)';
  const END = '// <<< nh-icons runtime';
  const block =
    START + '\n' +
    'var NH_CATEGORY_ICON = ' + JSON.stringify(CATEGORY_ICON) + ';\n' +
    'var NH_WEATHER_ICON = ' + JSON.stringify(WEATHER_ICON) + ';\n' +
    'function icon(name, extraClass){\n' +
    "  var cls = 'nh-icon nh-icon-' + name + (extraClass ? ' ' + extraClass : '');\n" +
    "  return '<svg class=\"' + cls + '\" aria-hidden=\"true\"><use href=\"/assets/icons.svg#' + name + '\"></use></svg>';\n" +
    '}\n' +
    END;
  const re = new RegExp(START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + END);
  if (re.test(s)) {
    s = s.replace(re, block);
  } else {
    s = s.replace(/\s*$/, '') + '\n\n' + block + '\n';
  }
  fs.writeFileSync(p, s);
  console.log('cities-data.js: nh-icons runtime helper injected');
}
