#!/usr/bin/env python3
"""
Generate neighborhood data for ALL cities in NomadCompass.
Creates 4-5 compelling neighborhoods per city with realistic coordinates and descriptions.
"""

import re
import json
import random
import math

# Read cities from cities-export.json (generated by Node.js)
def load_cities():
    with open('../cities-export.json', 'r', encoding='utf-8') as f:
        return json.load(f)

# Neighborhood templates by region/culture
NEIGHBORHOOD_TEMPLATES = {
    "europe_west": {
        "types": [
            {"name": "Old Town", "vibe": "Historic & Charming", "offset": (0.002, 0.002)},
            {"name": "Creative Quarter", "vibe": "Artsy & Trendy", "offset": (-0.015, 0.008)},
            {"name": "Business District", "vibe": "Modern & Professional", "offset": (0.012, -0.008)},
            {"name": "University Area", "vibe": "Young & Lively", "offset": (-0.008, -0.012)},
            {"name": "Residential Suburb", "vibe": "Quiet & Local", "offset": (0.02, 0.015)},
        ],
        "taglines": [
            "Where history whispers from every cobblestone",
            "The beating heart of the city's cultural scene",
            "Where old-world charm meets modern convenience",
            "A local secret that savvy nomads discover",
            "The neighborhood that feels like a village"
        ]
    },
    "europe_east": {
        "types": [
            {"name": "Historic Center", "vibe": "Cultural & Traditional", "offset": (0.003, 0.002)},
            {"name": "Hipster District", "vibe": "Alternative & Creative", "offset": (-0.012, 0.01)},
            {"name": "New Town", "vibe": "Modern & Developing", "offset": (0.015, -0.01)},
            {"name": "Student Quarter", "vibe": "Budget & Social", "offset": (-0.01, -0.008)},
            {"name": "Green District", "vibe": "Residential & Peaceful", "offset": (0.018, 0.012)},
        ],
        "taglines": [
            "Post-Soviet renaissance in full bloom",
            "Where artists and dreamers congregate",
            "The transformation happening before your eyes",
            "Budget-friendly with character to spare",
            "An authentic slice of local life"
        ]
    },
    "asia_southeast": {
        "types": [
            {"name": "Old Quarter", "vibe": "Traditional & Bustling", "offset": (0.005, 0.003)},
            {"name": "Expat Hub", "vibe": "International & Convenient", "offset": (-0.01, 0.012)},
            {"name": "Local District", "vibe": "Authentic & Affordable", "offset": (0.015, -0.008)},
            {"name": "Riverside Area", "vibe": "Scenic & Relaxed", "offset": (-0.008, -0.015)},
            {"name": "New Development", "vibe": "Modern & Growing", "offset": (0.02, 0.01)},
        ],
        "taglines": [
            "Chaos and charm in perfect harmony",
            "Where nomads find their tribe",
            "The real deal at unbeatable prices",
            "Escape the madness without leaving the city",
            "Tomorrow's hotspot, today's opportunity"
        ]
    },
    "asia_east": {
        "types": [
            {"name": "Downtown", "vibe": "Energetic & Central", "offset": (0.003, 0.003)},
            {"name": "Arts District", "vibe": "Creative & Hip", "offset": (-0.012, 0.008)},
            {"name": "Traditional Quarter", "vibe": "Historic & Cultural", "offset": (0.01, -0.012)},
            {"name": "Residential Area", "vibe": "Quiet & Authentic", "offset": (-0.015, -0.01)},
            {"name": "Tech Hub", "vibe": "Modern & Connected", "offset": (0.018, 0.015)},
        ],
        "taglines": [
            "The pulse of the city never stops here",
            "Where tradition evolves into something new",
            "Step back in time without losing WiFi",
            "The neighborhood locals call home",
            "Innovation district with soul"
        ]
    },
    "latin_america": {
        "types": [
            {"name": "Centro Histórico", "vibe": "Colonial & Cultural", "offset": (0.004, 0.003)},
            {"name": "Zona Rosa", "vibe": "Trendy & Social", "offset": (-0.01, 0.01)},
            {"name": "Barrio Local", "vibe": "Authentic & Affordable", "offset": (0.012, -0.008)},
            {"name": "Safe Zone", "vibe": "Secure & Expat-friendly", "offset": (-0.015, -0.012)},
            {"name": "Emerging Area", "vibe": "Up-and-coming & Creative", "offset": (0.015, 0.012)},
        ],
        "taglines": [
            "Colonial grandeur with modern energy",
            "Where the party never really ends",
            "Real life at real prices",
            "Peace of mind in paradise",
            "The next big thing is happening here"
        ]
    },
    "middle_east": {
        "types": [
            {"name": "Old City", "vibe": "Historic & Atmospheric", "offset": (0.003, 0.002)},
            {"name": "Modern District", "vibe": "Contemporary & Upscale", "offset": (-0.012, 0.01)},
            {"name": "Business Bay", "vibe": "Professional & Connected", "offset": (0.015, -0.008)},
            {"name": "Cultural Quarter", "vibe": "Artsy & Authentic", "offset": (-0.008, -0.012)},
            {"name": "Residential Area", "vibe": "Quiet & Family-friendly", "offset": (0.018, 0.015)},
        ],
        "taglines": [
            "Ancient streets with timeless stories",
            "Where luxury meets innovation",
            "The hub of regional commerce",
            "Tradition preserved with pride",
            "Suburban calm in a dynamic city"
        ]
    },
    "africa": {
        "types": [
            {"name": "City Center", "vibe": "Bustling & Commercial", "offset": (0.003, 0.002)},
            {"name": "Creative District", "vibe": "Artsy & Emerging", "offset": (-0.01, 0.012)},
            {"name": "Expat Neighborhood", "vibe": "Safe & Convenient", "offset": (0.012, -0.01)},
            {"name": "Local Quarter", "vibe": "Authentic & Vibrant", "offset": (-0.015, -0.008)},
            {"name": "Waterfront", "vibe": "Scenic & Upscale", "offset": (0.015, 0.015)},
        ],
        "taglines": [
            "Where Africa's energy is most concentrated",
            "The creative renaissance in action",
            "Comfort zone for international visitors",
            "Experience the real rhythm of the city",
            "Where the views match the lifestyle"
        ]
    },
    "oceania": {
        "types": [
            {"name": "CBD", "vibe": "Central & Convenient", "offset": (0.003, 0.002)},
            {"name": "Beach Suburb", "vibe": "Coastal & Relaxed", "offset": (-0.015, 0.02)},
            {"name": "Inner City", "vibe": "Hip & Walkable", "offset": (0.01, -0.008)},
            {"name": "Leafy Suburb", "vibe": "Green & Residential", "offset": (-0.012, -0.015)},
            {"name": "Foodie District", "vibe": "Diverse & Delicious", "offset": (0.018, 0.01)},
        ],
        "taglines": [
            "Everything you need at your doorstep",
            "Salt air and laid-back vibes",
            "Urban cool with community soul",
            "Where locals raise families",
            "A world of flavors in one neighborhood"
        ]
    },
    "north_america": {
        "types": [
            {"name": "Downtown", "vibe": "Urban & Central", "offset": (0.003, 0.002)},
            {"name": "Arts District", "vibe": "Creative & Trendy", "offset": (-0.012, 0.01)},
            {"name": "Midtown", "vibe": "Mixed & Accessible", "offset": (0.01, -0.01)},
            {"name": "Historic Quarter", "vibe": "Charming & Established", "offset": (-0.015, -0.012)},
            {"name": "Uptown", "vibe": "Upscale & Quiet", "offset": (0.02, 0.015)},
        ],
        "taglines": [
            "The city's beating commercial heart",
            "Where culture and creativity collide",
            "The sweet spot for urban living",
            "Character and history on every block",
            "Refined living for discerning nomads"
        ]
    },
    "south_asia": {
        "types": [
            {"name": "Old City", "vibe": "Historic & Intense", "offset": (0.004, 0.003)},
            {"name": "Cantonment Area", "vibe": "Spacious & Organized", "offset": (-0.015, 0.012)},
            {"name": "Tech Park Zone", "vibe": "Modern & Professional", "offset": (0.018, -0.01)},
            {"name": "Market District", "vibe": "Vibrant & Chaotic", "offset": (-0.01, -0.015)},
            {"name": "New Development", "vibe": "Clean & Contemporary", "offset": (0.02, 0.018)},
        ],
        "taglines": [
            "Sensory overload in the best way",
            "Colonial heritage meets modern convenience",
            "Where India's future is being built",
            "Haggle, eat, repeat",
            "Tomorrow's city rising today"
        ]
    },
    "beach_destination": {
        "types": [
            {"name": "Beach Town", "vibe": "Coastal & Social", "offset": (0.005, 0.008)},
            {"name": "Surf Zone", "vibe": "Active & Laid-back", "offset": (-0.012, 0.015)},
            {"name": "Quiet End", "vibe": "Peaceful & Scenic", "offset": (0.015, -0.01)},
            {"name": "Party Strip", "vibe": "Nightlife & Social", "offset": (-0.008, -0.012)},
            {"name": "Local Village", "vibe": "Authentic & Budget", "offset": (0.02, 0.005)},
        ],
        "taglines": [
            "Sandy toes and laptop pros",
            "Catch waves, catch up on work",
            "Where the crowds thin and the views expand",
            "Work hard, party harder",
            "Real island life at real prices"
        ]
    },
    "island": {
        "types": [
            {"name": "Main Town", "vibe": "Central & Connected", "offset": (0.003, 0.002)},
            {"name": "Beach Area", "vibe": "Coastal & Relaxed", "offset": (-0.01, 0.012)},
            {"name": "Hill District", "vibe": "Scenic & Quiet", "offset": (0.012, -0.008)},
            {"name": "Harbor Zone", "vibe": "Maritime & Historic", "offset": (-0.008, -0.01)},
            {"name": "Resort Strip", "vibe": "Upscale & Convenient", "offset": (0.015, 0.01)},
        ],
        "taglines": [
            "Island essentials without island isolation",
            "Wake up to the sound of waves",
            "Cooler temps and better views",
            "Where sailors and nomads mingle",
            "Comfort meets tropical paradise"
        ]
    }
}

# Country to region mapping
COUNTRY_REGIONS = {
    # Europe West
    "Portugal": "europe_west", "Spain": "europe_west", "France": "europe_west",
    "Italy": "europe_west", "Germany": "europe_west", "Netherlands": "europe_west",
    "Belgium": "europe_west", "UK": "europe_west", "United Kingdom": "europe_west",
    "Ireland": "europe_west", "Switzerland": "europe_west", "Austria": "europe_west",
    "Sweden": "europe_west", "Norway": "europe_west", "Denmark": "europe_west",
    "Finland": "europe_west", "Iceland": "europe_west", "Luxembourg": "europe_west",

    # Europe East
    "Poland": "europe_east", "Czech Republic": "europe_east", "Czechia": "europe_east",
    "Hungary": "europe_east", "Romania": "europe_east", "Bulgaria": "europe_east",
    "Croatia": "europe_east", "Slovenia": "europe_east", "Slovakia": "europe_east",
    "Serbia": "europe_east", "Montenegro": "europe_east", "Bosnia": "europe_east",
    "Albania": "europe_east", "North Macedonia": "europe_east", "Kosovo": "europe_east",
    "Estonia": "europe_east", "Latvia": "europe_east", "Lithuania": "europe_east",
    "Ukraine": "europe_east", "Moldova": "europe_east", "Georgia": "europe_east",
    "Armenia": "europe_east", "Azerbaijan": "europe_east", "Greece": "europe_east",
    "Cyprus": "europe_east", "Turkey": "europe_east", "Malta": "europe_east",

    # Southeast Asia
    "Thailand": "asia_southeast", "Vietnam": "asia_southeast", "Indonesia": "asia_southeast",
    "Malaysia": "asia_southeast", "Philippines": "asia_southeast", "Cambodia": "asia_southeast",
    "Laos": "asia_southeast", "Myanmar": "asia_southeast", "Singapore": "asia_southeast",

    # East Asia
    "Japan": "asia_east", "South Korea": "asia_east", "Korea": "asia_east",
    "Taiwan": "asia_east", "Hong Kong": "asia_east", "China": "asia_east",

    # Latin America
    "Mexico": "latin_america", "Colombia": "latin_america", "Brazil": "latin_america",
    "Argentina": "latin_america", "Chile": "latin_america", "Peru": "latin_america",
    "Ecuador": "latin_america", "Bolivia": "latin_america", "Uruguay": "latin_america",
    "Paraguay": "latin_america", "Costa Rica": "latin_america", "Panama": "latin_america",
    "Guatemala": "latin_america", "Cuba": "latin_america", "Dominican Republic": "latin_america",
    "Puerto Rico": "latin_america", "Venezuela": "latin_america", "Honduras": "latin_america",
    "El Salvador": "latin_america", "Nicaragua": "latin_america",

    # Middle East
    "UAE": "middle_east", "United Arab Emirates": "middle_east", "Israel": "middle_east",
    "Jordan": "middle_east", "Lebanon": "middle_east", "Oman": "middle_east",
    "Qatar": "middle_east", "Bahrain": "middle_east", "Kuwait": "middle_east",
    "Saudi Arabia": "middle_east", "Egypt": "middle_east", "Iran": "middle_east",
    "Palestine": "middle_east",

    # Africa
    "Morocco": "africa", "South Africa": "africa", "Kenya": "africa",
    "Tanzania": "africa", "Ghana": "africa", "Nigeria": "africa",
    "Rwanda": "africa", "Ethiopia": "africa", "Senegal": "africa",
    "Tunisia": "africa", "Mauritius": "africa", "Namibia": "africa",
    "Uganda": "africa", "Mozambique": "africa", "Cape Verde": "africa",

    # Oceania
    "Australia": "oceania", "New Zealand": "oceania", "Fiji": "oceania",
    "New Caledonia": "oceania",

    # North America
    "USA": "north_america", "United States": "north_america", "Canada": "north_america",

    # South Asia
    "India": "south_asia", "Sri Lanka": "south_asia", "Nepal": "south_asia",
    "Pakistan": "south_asia", "Bangladesh": "south_asia",
}

# Beach/island destinations (override region)
BEACH_DESTINATIONS = {
    "bali", "canggu", "ubud", "sanur", "uluwatu", "lombok", "nusapenida",
    "phuket", "kohphangan", "kohsamui", "krabi", "khaolak",
    "boracay", "siargao", "palawan", "elnido", "cebu",
    "langkawi", "penang", "phuquoc",
    "zanzibar", "mauritius", "capeverde",
    "tenerife", "fuerteventura", "ibiza", "palma", "mallorca",
    "santorini", "crete", "rhodes", "cyprus", "paphos", "chania",
    "dubrovnik", "split", "zadar", "pula", "kotor",
    "faro", "ericeira", "cascais", "funchal", "pontadelgada",
    "tarifa", "marbella", "malaga", "cadiz",
    "nice", "marseille",
    "goldcoast", "byronbay", "cairns",
    "queenstown", "wellington",
    "tamarindo", "montanita", "mancora",
    "cancun", "tulum", "playadelcarmen", "puertovallarta", "sayulita", "puertoescondido",
    "puntacana", "sanjuan",
    "weligama", "goa",
    "dahab", "huahin",
}

# Common pros by type
PROS_BY_TYPE = {
    "Old": ["Rich history and architecture", "Walkable streets", "Authentic atmosphere", "Great photo opportunities"],
    "Historic": ["Cultural attractions", "Beautiful old buildings", "Charming cafes", "Central location"],
    "Creative": ["Vibrant art scene", "Trendy cafes", "Interesting nightlife", "Like-minded community"],
    "Artsy": ["Gallery hopping", "Unique boutiques", "Creative energy", "Cool coffee shops"],
    "Business": ["Modern amenities", "Fast WiFi everywhere", "Professional environment", "Good transport"],
    "Modern": ["New buildings", "Reliable infrastructure", "Shopping malls", "International chains"],
    "Local": ["Authentic experience", "Lower prices", "Real culture", "Friendly neighbors"],
    "Authentic": ["Great local food", "Budget-friendly", "Language practice", "Less touristy"],
    "Beach": ["Ocean access", "Healthy lifestyle", "Sunset views", "Relaxed atmosphere"],
    "Coastal": ["Swimming nearby", "Fresh seafood", "Beach walks", "Surf options"],
    "Quiet": ["Peaceful environment", "Good for focus", "Less pollution", "Better sleep"],
    "Residential": ["Safe streets", "Parks and green space", "Family-friendly", "Authentic neighborhood life"],
    "Upscale": ["High-end dining", "Safe area", "Quality apartments", "Premium services"],
    "Safe": ["Low crime", "Well-lit streets", "Security presence", "Peace of mind"],
    "Budget": ["Affordable rent", "Cheap eats", "Value for money", "Stretch your runway"],
    "Student": ["Young energy", "Cheap bars", "Cultural events", "Language exchange"],
    "Expat": ["English spoken", "International community", "Familiar comforts", "Easy transition"],
    "Emerging": ["Lower rents", "Pioneer vibes", "Potential upside", "Authentic discovery"],
}

# Common cons by type
CONS_BY_TYPE = {
    "Old": ["Older buildings", "Narrow streets", "Tourist crowds", "Limited parking"],
    "Historic": ["Can be touristy", "Higher prices", "Old infrastructure", "Crowded peak season"],
    "Creative": ["Can be noisy", "Gentrifying fast", "Weekend crowds", "Pricier than before"],
    "Artsy": ["Sometimes pretentious", "Limited groceries", "Nightlife noise", "Inconsistent quality"],
    "Business": ["Quiet on weekends", "Less character", "Higher rents", "Corporate feel"],
    "Modern": ["Less charm", "Can feel sterile", "Chain restaurants", "Less authentic"],
    "Local": ["Less English", "Basic amenities", "Harder to navigate", "Cultural adjustment"],
    "Authentic": ["Language barrier", "Different standards", "Far from expat scene", "Fewer conveniences"],
    "Beach": ["Tourist prices", "Seasonal crowds", "Sand everywhere", "Limited coworking"],
    "Coastal": ["Can be touristy", "Weather dependent", "Limited culture", "Higher season prices"],
    "Quiet": ["Can be boring", "Less nightlife", "Fewer restaurants", "May need transport"],
    "Residential": ["Less exciting", "Fewer cafes", "Requires commute", "Limited nightlife"],
    "Upscale": ["Expensive", "Can feel sterile", "Less authentic", "Tourist prices"],
    "Safe": ["Higher cost", "Can feel isolated", "Less character", "Expat bubble"],
    "Budget": ["Basic conditions", "Less safe at night", "Fewer amenities", "Quality varies"],
    "Student": ["Can be rowdy", "Seasonal population", "Basic housing", "Loud nights"],
    "Expat": ["Bubble effect", "Higher prices", "Less authentic", "Tourist infrastructure"],
    "Emerging": ["Still rough", "Limited options", "Uncertain future", "Infrastructure gaps"],
}

def get_region(city):
    """Determine region based on country and city characteristics"""
    country = city.get("country", "")
    city_id = city.get("id", "").lower()

    # Check if beach destination
    if city_id in BEACH_DESTINATIONS:
        return "beach_destination"

    # Check country mapping
    region = COUNTRY_REGIONS.get(country, "europe_west")  # Default to europe_west

    return region

def get_pros(neighborhood_type):
    """Get relevant pros based on neighborhood type keywords"""
    pros = []
    for keyword, keyword_pros in PROS_BY_TYPE.items():
        if keyword.lower() in neighborhood_type.lower():
            pros.extend(keyword_pros[:2])

    # Ensure we have at least 4 pros
    if len(pros) < 4:
        defaults = ["Good value", "Convenient location", "Friendly atmosphere", "Easy to settle"]
        pros.extend(defaults[:4-len(pros)])

    return pros[:4]

def get_cons(neighborhood_type):
    """Get relevant cons based on neighborhood type keywords"""
    cons = []
    for keyword, keyword_cons in CONS_BY_TYPE.items():
        if keyword.lower() in neighborhood_type.lower():
            cons.extend(keyword_cons[:2])

    # Ensure we have at least 3 cons
    if len(cons) < 3:
        defaults = ["Can be crowded", "Prices rising", "Takes time to explore"]
        cons.extend(defaults[:3-len(cons)])

    return cons[:3]

def generate_description(city_name, neighborhood_name, vibe, tagline):
    """Generate a compelling description for a neighborhood"""
    templates = [
        f"{neighborhood_name} is {city_name}'s {vibe.lower()} heart. {tagline} Whether you're here for a month or a year, this neighborhood delivers exactly what nomads need: reliable infrastructure, good food, and that perfect balance of productivity and pleasure.",
        f"In {neighborhood_name}, {city_name} shows its {vibe.lower()} side. {tagline} You'll find yourself settling into a rhythm quickly here, with cafes that know your order and streets that become familiar friends.",
        f"{tagline} {neighborhood_name} has evolved into one of {city_name}'s most interesting areas for remote workers. The {vibe.lower()} atmosphere creates an environment where work and life blend seamlessly.",
        f"Ask any long-term nomad in {city_name} about {neighborhood_name}, and you'll hear stories. {tagline} It's the kind of place that turns short stays into extended adventures.",
        f"{neighborhood_name} represents the {vibe.lower()} essence of {city_name}. {tagline} From morning coffee to evening exploration, this neighborhood delivers a complete nomad experience.",
    ]
    return random.choice(templates)

def generate_best_for(vibe):
    """Generate 'best for' text based on vibe"""
    vibe_lower = vibe.lower()

    if "creative" in vibe_lower or "artsy" in vibe_lower:
        return "Creatives, designers, and those seeking inspiration in their environment"
    elif "historic" in vibe_lower or "traditional" in vibe_lower:
        return "Culture lovers, photographers, and those who value atmosphere over convenience"
    elif "business" in vibe_lower or "professional" in vibe_lower:
        return "Business travelers, corporate remote workers, and those who need premium amenities"
    elif "local" in vibe_lower or "authentic" in vibe_lower:
        return "Long-term stayers, language learners, and budget-conscious nomads"
    elif "beach" in vibe_lower or "coastal" in vibe_lower:
        return "Beach lovers, surfers, and those who need ocean access for mental health"
    elif "quiet" in vibe_lower or "peaceful" in vibe_lower:
        return "Focused workers, introverts, and those escaping the hustle"
    elif "social" in vibe_lower or "nightlife" in vibe_lower:
        return "Social butterflies, networkers, and those who work hard and play harder"
    elif "budget" in vibe_lower or "affordable" in vibe_lower:
        return "Budget nomads, bootstrapped founders, and those maximizing runway"
    elif "upscale" in vibe_lower or "luxury" in vibe_lower:
        return "Higher earners, executives, and those who prioritize comfort"
    elif "emerging" in vibe_lower or "developing" in vibe_lower:
        return "Pioneers, adventurous nomads, and those who like discovering before others"
    else:
        return "Digital nomads seeking a balanced lifestyle with good infrastructure"

def generate_neighborhoods_for_city(city):
    """Generate neighborhood data for a single city"""
    region = get_region(city)
    templates = NEIGHBORHOOD_TEMPLATES.get(region, NEIGHBORHOOD_TEMPLATES["europe_west"])

    city_lat = city.get("lat", 0)
    city_lng = city.get("lng", 0)
    city_name = city.get("name", "City")

    neighborhoods = []

    # Randomly select 4-5 neighborhood types
    selected_types = random.sample(templates["types"], min(5, len(templates["types"])))
    selected_taglines = templates["taglines"].copy()
    random.shuffle(selected_taglines)

    price_levels = ["$", "$$", "$$$", "$$", "$"]  # Distribution
    random.shuffle(price_levels)

    for i, ntype in enumerate(selected_types):
        lat_offset, lng_offset = ntype["offset"]
        # Add some randomness to offsets
        lat_offset += random.uniform(-0.003, 0.003)
        lng_offset += random.uniform(-0.003, 0.003)

        tagline = selected_taglines[i % len(selected_taglines)]

        neighborhood = {
            "name": ntype["name"],
            "tagline": tagline,
            "description": generate_description(city_name, ntype["name"], ntype["vibe"], tagline),
            "vibe": ntype["vibe"],
            "bestFor": generate_best_for(ntype["vibe"]),
            "pros": get_pros(ntype["vibe"]),
            "cons": get_cons(ntype["vibe"]),
            "lat": round(city_lat + lat_offset, 4),
            "lng": round(city_lng + lng_offset, 4),
            "priceLevel": price_levels[i]
        }
        neighborhoods.append(neighborhood)

    return neighborhoods

def main():
    """Main function to add neighborhoods to all cities"""

    # Load existing generate_city_pages.js
    with open('generate_city_pages.js', 'r', encoding='utf-8') as f:
        content = f.read()

    # Load cities data
    cities = load_cities()
    print(f"Found {len(cities)} cities")

    # Cities that already have neighborhoods
    existing = set()
    for match in re.finditer(r'"(\w+)":\s*\{[^}]*"neighborhoods":', content):
        existing.add(match.group(1))

    print(f"Cities with existing neighborhoods: {len(existing)}")

    # Generate neighborhoods for cities without them
    added_count = 0
    for city in cities:
        city_id = city.get("id", "")

        if city_id in existing:
            continue

        # Check if city exists in CITY_CONTENT
        pattern = rf'("{city_id}":\s*\{{[^}}]*?"score_description":\s*"[^"]*")'

        if not re.search(pattern, content):
            # City doesn't have detailed content, skip
            continue

        # Generate neighborhoods
        neighborhoods = generate_neighborhoods_for_city(city)

        # Add to content
        neighborhoods_json = json.dumps(neighborhoods, indent=6, ensure_ascii=False)
        neighborhoods_json = neighborhoods_json.replace('\n', '\n    ')

        def add_neighborhoods(match):
            return match.group(1) + ',\n    "neighborhoods": ' + neighborhoods_json

        new_content = re.sub(pattern, add_neighborhoods, content, count=1)

        if new_content != content:
            content = new_content
            added_count += 1
            print(f"Added neighborhoods to {city_id}")

    # Write updated content
    with open('generate_city_pages.js', 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"\nDone! Added neighborhoods to {added_count} cities.")
    print(f"Total cities with neighborhoods: {len(existing) + added_count}")

if __name__ == '__main__':
    main()
