#!/usr/bin/env python3
"""Rewrite batch 2: Detailed descriptions for cities A (aarhus-amsterdam)."""

import json
import os

BATCH_CITIES = {
    "aarhus": {
        "climate": "Aarhus experiences a temperate oceanic climate with mild summers (17-22°C) and cold, damp winters (0-4°C). Rain is distributed throughout the year, with autumn being particularly wet. Snow is common in winter but rarely accumulates heavily. The coastal location moderates extremes, though wind can be biting in winter. Summer days are long with light until 10pm, while winter brings early darkness by 4pm. Pack layers and rain gear year-round.",
        "cost": "Denmark is expensive, and Aarhus is no exception, though slightly cheaper than Copenhagen. A comfortable nomad lifestyle costs €2,500-3,500/month. Apartments range €1,000-1,500/month in the city center. Dining out is pricey at €15-25 for a meal, and a beer costs €7-8. However, Danish salaries and quality of life reflect these costs. Supermarket cooking and student-area eating help manage expenses.",
        "wifi": "Denmark has excellent digital infrastructure with average speeds of 100+ Mbps. Public WiFi is widespread and reliable. The city's numerous cafes cater to laptop workers, and coworking spaces offer premium connectivity. Mobile data is fast with good 5G coverage. Denmark consistently ranks among the world's most connected countries. You'll never struggle for reliable internet here.",
        "nightlife": "Aarhus has a vibrant nightlife scene driven by its large student population. The Latin Quarter is packed with bars ranging from cozy beer cellars to cocktail lounges. Clubs along the harbor stay open until 5am on weekends. The scene is more relaxed and less pretentious than Copenhagen. Summer brings outdoor festivals and harbor-side drinking. Danes socialize late—dinner at 8pm, bars at 11pm, clubs at midnight.",
        "nature": "Aarhus offers easy access to Denmark's gentle landscapes. The surrounding forests are perfect for cycling and running. Beaches south of the city are popular in summer, with surprisingly warm water temperatures. Marselisborg Deer Park lets you walk among wild deer. The Mols Bjerge National Park provides rolling hills and coastal views. Denmark's flat terrain makes it ideal for outdoor activities year-round.",
        "safety": "Aarhus is exceptionally safe, reflecting Denmark's overall low crime rates. Violent crime is virtually nonexistent. Bikes are often left unlocked, and you can walk anywhere at any time without concern. The biggest risk might be cycling accidents—always use lights. Danish society is built on trust, and this permeates daily life. Emergency services are excellent and English-speaking.",
        "food": "Danish cuisine has evolved from heavy traditional dishes to New Nordic innovation. Aarhus has several Michelin-starred restaurants showcasing local ingredients. Smørrebrød (open sandwiches) remain a lunch staple. The food market at Aarhus Street Food offers diverse options at reasonable prices. Coffee culture is strong with excellent roasters. Traditional dishes include flæskesteg (roast pork) and frikadeller (meatballs). Quality is high across all price points.",
        "community": "Aarhus has a welcoming international community centered around its universities and tech companies. Startup culture is growing, with regular meetups and events. The city is small enough that you'll keep running into the same people, building genuine connections. Danes can seem reserved initially but warm up over time. International student events and expat groups provide easy entry points. The nomad community is smaller but growing.",
        "english": "English proficiency in Denmark is among the world's highest. Virtually everyone under 50 speaks fluent English, and business is often conducted in English. You can live comfortably without learning Danish, though making the effort earns respect. University courses are taught in English. Official services are available in English. The only challenge might be understanding older Danes in rural areas.",
        "visa": "Denmark is part of the EU and Schengen Area. EU citizens can live and work freely. Non-EU visitors can stay 90 days within Schengen. Denmark offers a residence permit for self-employed individuals and has introduced startup visas. Requirements include proof of income and comprehensive health insurance. Nordic countries have excellent reciprocal agreements. Denmark's high quality of life makes the visa process worth navigating.",
        "culture": "Aarhus is Denmark's cultural capital, home to ARoS art museum with its famous rainbow panorama. The Old Town open-air museum recreates Danish history. Design is central to Danish identity—clean lines and functionality are everywhere. The concept of 'hygge' (cozy contentment) defines social life, especially in winter. Work-life balance is sacred; Danes leave work at 4pm to enjoy family time. The city hosts major festivals including NorthSide and Aarhus Festival.",
        "cleanliness": "Danish cities are immaculately clean, and Aarhus is no exception. Streets are swept regularly, public spaces are well-maintained, and littering is socially unacceptable. Recycling is thorough and expected. Public transportation is spotless. Even student areas maintain high standards. Tap water is excellent. The overall impression is of a society that takes civic responsibility seriously.",
        "airquality": "Aarhus enjoys excellent air quality, with the AQI typically in the 15-35 range. Coastal winds keep the air fresh, and Denmark's commitment to green energy reduces pollution. Cycling culture means fewer cars. Winter heating doesn't significantly impact air quality thanks to clean energy sources. The proximity to sea and forests ensures consistently clean, fresh air throughout the year."
    },
    "abudhabi": {
        "climate": "Abu Dhabi has an arid desert climate with scorching summers (35-48°C) and pleasant winters (15-25°C). Summer is brutal—from June to September, outdoor activity is limited to early morning or evening. Winter (November-March) offers perfect weather for beach days and outdoor exploration. Humidity can be high near the coast. Rain is rare, falling only a few days per year. Air conditioning is essential and ubiquitous.",
        "cost": "Abu Dhabi is expensive but offers various lifestyle tiers. A comfortable nomad lifestyle costs $3,000-5,000/month. Apartments range from $1,500-3,000/month depending on location and amenities. Dining out varies wildly—street food for $5 or fine dining for $100+. Alcohol is taxed heavily. Transportation is cheap with excellent public options. The cost of living is slightly lower than Dubai with a more relaxed pace.",
        "wifi": "The UAE has invested heavily in digital infrastructure, with Abu Dhabi offering excellent connectivity. Average speeds exceed 100 Mbps, with fiber widely available. Free WiFi is common in malls, hotels, and cafes. Note that VoIP services like WhatsApp calling and Skype are restricted—you'll need a VPN for full functionality. 5G coverage is extensive. Coworking spaces provide reliable, fast connections.",
        "nightlife": "Abu Dhabi's nightlife is more subdued than Dubai's but still offers options. Upscale hotel bars and beach clubs are the main venues. The Yas Island area has developed entertainment districts. Alcohol is served only in licensed venues (hotels and clubs). The scene is sophisticated rather than wild. Thursday nights (start of the weekend) are busiest. Dress codes tend toward smart casual or better.",
        "nature": "Despite the desert setting, Abu Dhabi offers diverse natural experiences. The Corniche beach stretches along the city waterfront. The Empty Quarter (Rub' al Khali) offers dramatic dune landscapes for desert adventures. Mangrove National Park provides kayaking through coastal ecosystems. Sir Bani Yas Island has wildlife reserves. The stunning Liwa Oasis lies a few hours south. Nature here is about extremes—sea, sand, and surprising biodiversity.",
        "safety": "Abu Dhabi is one of the world's safest cities. Crime rates are among the lowest globally, and violent crime is virtually nonexistent. The city is heavily monitored, and laws are strictly enforced. Solo travelers, including women, report feeling very safe. The main concern is harsh penalties for behavior that's legal elsewhere—be aware of local laws regarding alcohol, public behavior, and relationships.",
        "food": "Abu Dhabi's food scene reflects its international population. Arabic cuisine—hummus, shawarma, grilled meats—is excellent and affordable. Indian, Pakistani, and Filipino restaurants serve their large communities. High-end dining in hotels rivals anywhere in the world. The Lebanese and Iranian food is particularly noteworthy. Brunch culture is huge, with lavish hotel spreads. During Ramadan, eating in public during daylight hours is prohibited.",
        "community": "Abu Dhabi hosts a large expat community, comprising over 80% of the population. Connections form through workplace, nationality groups, and interest-based clubs. The pace is more family-oriented than Dubai's hustle culture. Professional networking events are common. Digital nomads are less visible than in other hubs, but remote work is increasingly accepted. The transient nature of expat life means friendships can be intense but temporary.",
        "english": "English is the de facto business language in Abu Dhabi, spoken by the vast majority of residents. You can live entirely in English—shopping, banking, healthcare, all function in English. Arabic is the official language, but English dominates daily life. Signage is bilingual. Only in traditional markets might you encounter language barriers. Learning Arabic phrases is appreciated but unnecessary.",
        "visa": "The UAE has become more accessible for remote workers. Tourist visas allow 30-90 day stays depending on nationality. The UAE now offers remote work visas and freelancer permits through various free zones. The golden visa provides 10-year residency for qualifying individuals. Requirements include proof of income and health insurance. Visa processes are generally efficient, though sponsorship requirements apply for employment.",
        "culture": "Abu Dhabi balances modernization with cultural preservation. The Sheikh Zayed Grand Mosque is a masterpiece of Islamic architecture. Louvre Abu Dhabi brings world-class art to the desert. Traditional markets in Al Ain offer glimpses of pre-oil life. Emirati culture values hospitality, family, and respect. Dress modestly in public spaces. Friday is the holy day—mornings are quiet, afternoons social. The pace is slower and more traditional than Dubai.",
        "cleanliness": "Abu Dhabi is immaculately clean with strict littering laws and constant maintenance. Public spaces are pristine, beaches are cleaned daily, and infrastructure is maintained to high standards. The wealth of the emirate is evident in the polished appearance of everything. Air conditioning keeps indoor spaces comfortable and clean. The only dust challenge comes from occasional sandstorms.",
        "airquality": "Abu Dhabi's air quality varies seasonally. Winter enjoys excellent conditions with AQI typically 30-50. Summer can see higher pollution due to dust storms and haze, sometimes pushing AQI above 100. The desert environment means dust is a constant factor. Indoor air quality is excellent thanks to universal air conditioning and filtration. Coastal areas benefit from sea breezes."
    },
    "accra": {
        "climate": "Accra has a tropical savanna climate with two rainy seasons (April-June and September-October). Temperatures are warm year-round (24-32°C), with the hottest period in February-March. Humidity is moderate, kept bearable by sea breezes. The harmattan wind (December-February) brings dry, dusty air from the Sahara. The climate is generally comfortable, especially compared to other West African cities. Rain typically falls in heavy afternoon showers.",
        "cost": "Accra offers a moderate cost of living for West Africa, though it's pricier than many assume. A comfortable nomad lifestyle costs $1,200-2,000/month. Apartments in expat areas like Osu or Cantonments range $600-1,200/month. Local food is cheap ($3-5), while Western-style restaurants charge $15-25. Transportation via Uber or Bolt is affordable. The cost-quality ratio is favorable once you know where to look.",
        "wifi": "Ghana has made significant telecom investments, and Accra benefits from reasonable connectivity. Average speeds are 20-50 Mbps, with fiber available in better areas. WiFi reliability varies—power outages affect consistency. Coworking spaces like Impact Hub offer stable connections. Mobile data through MTN or Vodafone provides good backup. Load shedding (planned power cuts) can disrupt connectivity, so have backup plans.",
        "nightlife": "Accra's nightlife is vibrant and distinctly African. Osu's Oxford Street hosts bars and clubs playing afrobeats, highlife, and hip-hop. Live music venues showcase Ghana's rich musical heritage. Beach bars at Labadi and Kokrobite offer relaxed vibes. The scene starts late—clubs fill after midnight. Ghanaians love to party, and weekends are energetic. The atmosphere is welcoming to foreigners.",
        "nature": "While Accra itself is urban, nature escapes are accessible. The beaches east and west of the city offer swimming and relaxation. Aburi Botanical Gardens in the hills provide cool escapes. Kakum National Park, a few hours away, features canopy walkways through rainforest. The Volta Region offers waterfalls and mountains. Wildlife reserves house elephants and other species. Day trips reveal Ghana's natural diversity.",
        "safety": "Accra is relatively safe for West Africa, though standard precautions apply. Petty theft can occur, especially at night in busy areas. Avoid displaying expensive items and use registered taxis or ride-hailing apps. Violent crime targeting foreigners is rare. Ghanaians are friendly and often helpful to visitors. Police presence is visible. Trust your instincts, stay aware, and you'll likely have a trouble-free experience.",
        "food": "Ghanaian cuisine is flavorful and filling. Jollof rice is the national pride—expect debates about whether Ghana or Nigeria makes it better. Banku with tilapia, fufu with soup, and kelewele (spiced plantains) are staples. Street food is abundant and affordable. The city also has growing international options, particularly Lebanese and Chinese. Local beers like Star and Club are refreshing. Don't miss fresh tropical fruits.",
        "community": "Accra has a growing community of digital nomads, entrepreneurs, and diaspora returnees. The 'Year of Return' campaign brought increased African American interest. Coworking spaces and tech hubs foster connections. The startup ecosystem is developing rapidly. Ghanaians are welcoming and curious about foreigners. Networking happens easily at events, restaurants, and social gatherings. The community feels dynamic and opportunity-rich.",
        "english": "English is Ghana's official language, making it one of Africa's most accessible countries for English speakers. Ghanaian English has its own rhythm and expressions, but communication is straightforward. Business, government, and media operate in English. Local languages like Twi are widely spoken, and picking up phrases builds rapport. English proficiency varies with education level but is generally good in Accra.",
        "visa": "Ghana is accessible for most nationalities. Visa on arrival is available for African Union citizens and some others. Many nationalities need advance visas from embassies or through the online e-visa system. Tourist visas typically allow 30-60 days, extendable locally. Ghana has positioned itself as welcoming to the African diaspora with special visa provisions. The process can be bureaucratic, so allow time.",
        "culture": "Ghanaian culture is warm, vibrant, and community-oriented. Music and dance are central—you'll hear highlife and afrobeats everywhere. Traditional chiefs still hold cultural authority. Funerals are elaborate celebrations of life. Christianity is dominant, with enthusiastic Sunday worship. Respect for elders is paramount. The concept of 'sankofa' (learning from the past) influences the culture. Ghanaians are proud and welcoming hosts.",
        "cleanliness": "Accra's cleanliness is a work in progress. Main roads and tourist areas are regularly cleaned. Some neighborhoods have waste management challenges, with occasional burning of rubbish. The government has implemented clean-up campaigns. Tap water should be filtered or bottled. Higher-end areas maintain better standards. The situation has improved significantly in recent years.",
        "airquality": "Air quality in Accra is moderate, with AQI often in the 50-100 range. Dust from unpaved roads and the harmattan season affects quality. Vehicle emissions and burning contribute to urban pollution. Coastal areas enjoy better air with sea breezes. The situation is manageable but noticeable, especially during harmattan. Air-conditioned spaces provide respite."
    },
    "addisababa": {
        "climate": "Addis Ababa sits at 2,400m altitude, giving it a pleasant subtropical highland climate despite being near the equator. Temperatures are spring-like year-round (10-25°C), rarely hot and never cold. The main rainy season (June-September) brings daily afternoon showers. The dry season offers clear skies and comfortable conditions. Nights can be cool—bring layers. The altitude means UV is intense; wear sunscreen.",
        "cost": "Addis Ababa offers excellent value for digital nomads. A comfortable lifestyle costs $800-1,400/month. Apartments range $300-700/month, with higher-end options available. Local food is incredibly cheap ($2-4 for a meal), while Western restaurants charge $10-20. Transportation by minibus is cents, and Ride is the local Uber alternative. Ethiopia's economic situation means currency can be complex—carry local birr.",
        "wifi": "Ethiopia's internet infrastructure is developing but can be unreliable. Average speeds are 10-30 Mbps when working, but outages occur. The government has historically implemented internet shutdowns during political tensions. Mobile data through Ethio Telecom (the only provider) offers 4G in the city. Coworking spaces like Mela Hub provide more stable connections. Always have offline work available as backup.",
        "nightlife": "Addis has a unique nightlife centered on live music and cultural entertainment. Traditional 'azmari bet' (minstrel houses) feature music, dancing, and shoulder-shaking eskista performances. Jazz clubs honor Ethiopia's rich musical heritage. The Bole area has more modern bars and clubs. Tej (honey wine) and local beers accompany evenings out. The scene is authentic and surprisingly vibrant, running late into the night.",
        "nature": "Ethiopia is called the 'Roof of Africa,' and nature is spectacular. From Addis, the Entoto Mountains offer hiking with city views. Day trips reach the Rift Valley lakes with birdlife. Further afield, the Simien Mountains and Lalibela's rock churches await. The diverse landscapes—from highlands to lowlands—support unique wildlife including the Ethiopian wolf. Nature here is dramatic and largely undiscovered by mass tourism.",
        "safety": "Addis Ababa is relatively safe for an African capital, though awareness is important. Petty theft and pickpocketing occur, especially in crowded areas like Merkato market. Keep valuables secure and avoid walking alone late at night in unfamiliar areas. Political situations can change quickly—monitor news. Most Ethiopians are friendly and helpful. Scams targeting tourists exist but are manageable with common sense.",
        "food": "Ethiopian cuisine is one of Africa's most distinctive. Injera (spongy flatbread) serves as both plate and utensil for stews called wot. Doro wot (chicken) and kitfo (raw beef) are highlights. Vegetarian options are excellent, driven by Orthodox fasting traditions. Coffee originated in Ethiopia, and the ceremony is a must-experience ritual. Tej (honey wine) and tella (local beer) accompany meals. Eating is communal and social.",
        "community": "Addis has a small but engaged international community, including diplomats, NGO workers, and a growing number of digital nomads. The African Union headquarters brings continental professionals. Tech hubs are emerging, connecting local and foreign entrepreneurs. Ethiopians are warm and curious, though the culture can be formal initially. Expat events and coworking spaces facilitate connections. The community feels pioneering.",
        "english": "English is taught in schools and used in business and higher education, but proficiency varies widely. In hotels, restaurants, and tourist areas, English works fine. Taxi drivers and local markets may require Amharic phrases. Learning basics ('selam' for hello, 'amesegenallo' for thank you) goes far. University-educated Ethiopians often speak excellent English. French and Italian are also sometimes useful.",
        "visa": "Ethiopia offers e-visas for most nationalities, allowing 30-90 day stays. The process is straightforward and online. Visa extensions are possible at the immigration office. Ethiopia has introduced a digital nomad category recognizing remote workers. Requirements include proof of income and health insurance. The country is actively courting diaspora and digital workers. Procedures can be slow but are generally navigable.",
        "culture": "Ethiopia has a unique culture, never colonized and preserving ancient traditions. The Ethiopian Orthodox Church dates to the 4th century, with Lalibela's rock churches being UNESCO treasures. The calendar is different (7-8 years 'behind' the Western calendar), and time is counted differently too. Coffee culture originated here—the ceremony is sacred. Respect for elders and tradition runs deep. The Rastafarian connection through Haile Selassie draws many visitors.",
        "cleanliness": "Addis Ababa's cleanliness varies significantly by neighborhood. The Bole area and diplomatic zones are well-maintained. Older areas like Merkato can be challenging. The city has improved waste management but still faces issues. Tap water should definitely be filtered or bottled. New construction is rapidly changing the city's face. Higher-end establishments maintain good standards.",
        "airquality": "Air quality in Addis Ababa is moderate to poor, with AQI often 50-100+. Altitude doesn't prevent pollution from vehicle emissions and construction dust. The rainy season improves air quality temporarily. Some areas are better than others—higher elevations and greener neighborhoods are fresher. The city's rapid growth has outpaced environmental controls. Sensitive individuals should take precautions."
    },
    "adelaide": {
        "climate": "Adelaide has a Mediterranean climate with hot, dry summers (25-35°C) and mild, wet winters (8-16°C). Summer heat can be intense, occasionally exceeding 40°C during heat waves. Winters are cool and rainy but rarely cold. Spring and autumn are ideal, with comfortable temperatures perfect for exploring. The city enjoys abundant sunshine year-round. Coastal breezes moderate summer heat in beach suburbs.",
        "cost": "Adelaide is significantly more affordable than Sydney or Melbourne while maintaining similar quality of life. A comfortable nomad lifestyle costs AUD 3,000-4,500/month ($2,000-3,000). Apartments range AUD 1,400-2,200/month. Dining out is reasonable by Australian standards—$15-25 for a quality meal. Wine is exceptional and affordable given the nearby regions. Transport is cheaper than eastern cities.",
        "wifi": "Australian internet has improved significantly with the NBN rollout. Adelaide typically sees speeds of 50-100+ Mbps. Public WiFi is available in the city center and many cafes. Coworking spaces offer reliable connections. Mobile coverage is excellent in urban areas, though remote regions can be sparse. Overall connectivity is reliable and sufficient for remote work.",
        "nightlife": "Adelaide's nightlife is concentrated in the city center and suburban hubs like Hindley Street and Rundle Street. The scene is more relaxed than Melbourne or Sydney—less pretentious and easier to navigate. Live music venues showcase local talent. The bar scene ranges from laneway cocktail spots to beachside pubs. Adelaide's festival culture brings international acts and extended hours during events. Pubs close earlier than eastern cities.",
        "nature": "Adelaide is surrounded by natural beauty. The Adelaide Hills offer cooler temperatures, wineries, and bushwalking. Beach suburbs like Glenelg and Henley Beach are easily accessible. Kangaroo Island, Australia's Galápagos, is a short ferry ride away. The Flinders Ranges provide dramatic outback landscapes. Wildlife—kangaroos, koalas, echidnas—is common in surrounding areas. Nature is remarkably accessible from the city center.",
        "safety": "Adelaide is very safe by global standards. Violent crime is rare, and you can walk most areas at any time without concern. Some caution is warranted in certain CBD areas late at night. Australian common sense applies—don't leave valuables visible in cars. Beach safety is important—swim between the flags. Emergency services are excellent. The overall atmosphere is relaxed and trusting.",
        "food": "Adelaide's food scene punches above its weight, fueled by proximity to premier wine regions. The Central Market is a foodie institution, operating since 1869. Modern Australian cuisine showcases local produce—Adelaide's restaurants rival Melbourne for quality. The nearby Barossa and McLaren Vale ensure exceptional wine pairings. Asian food is excellent with significant Vietnamese and Chinese communities. Coffee culture is strong.",
        "community": "Adelaide has a growing tech and creative community. The city's smaller size means networking happens naturally—you'll recognize faces quickly. Coworking spaces like co-HAB and Majoran host events and meetups. The startup ecosystem is developing, supported by government initiatives. Adelaideans are friendly and approachable, more so than in larger cities. The nomad community is smaller but welcoming.",
        "english": "Adelaide is native English-speaking, making daily life straightforward. Australian English has its unique slang and accent, but communication is effortless. Multicultural suburbs offer opportunities to hear many languages. Services, signage, and media are all in English. The relaxed Australian communication style—casual, direct, with dry humor—takes little adjustment.",
        "visa": "Australian visa rules are consistent across cities. Many nationalities can obtain ETAs (Electronic Travel Authorities) online for short visits. Working holiday visas allow those under 30-35 to work and travel for 1-2 years. Skilled worker visas require employer sponsorship or points-based qualification. Australia has introduced specific categories for digital professionals. The immigration system is organized but competitive.",
        "culture": "Adelaide is known as the 'City of Churches' and the 'Festival City.' Major events include Adelaide Festival, Adelaide Fringe (the world's second-largest fringe festival), and WOMADelaide. The city has a more conservative, traditional character than Melbourne or Sydney. Wine culture is integral—the surrounding regions produce world-class varietals. Arts and culture punch above the city's weight. The pace of life is noticeably slower and more relaxed.",
        "cleanliness": "Adelaide is very clean by global standards. Streets are well-maintained, parks are tidy, and public facilities are kept in good condition. The city takes pride in its appearance, particularly in the city center and beach suburbs. Tap water is safe and good quality. Recycling is expected. The overall impression is of a well-managed, orderly city.",
        "airquality": "Adelaide enjoys excellent air quality most of the year, with AQI typically 20-40. The Mediterranean climate and sea breezes keep air fresh. Occasional bushfire smoke can affect quality during summer, though less frequently than eastern states. Industrial activity is limited near residential areas. The clean air complements the outdoor lifestyle that Adelaide enables."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

    # Load existing data
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Update cities with detailed descriptions
    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")

    # Save updated data
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
