#!/usr/bin/env python3
"""Rewrite batch 18: Valletta, Marrakech, Cairo, Nairobi, Auckland."""

import json
import os

BATCH_CITIES = {
    "valletta": {
        "climate": "Valletta enjoys a Mediterranean climate with hot, dry summers and mild, wet winters. Summer temperatures reach 28-35°C (82-95°F) with intense sunshine and minimal rain. Winters are mild at 10-16°C (50-61°F) with periodic rainfall. Spring and autumn offer ideal conditions with warm days and pleasant evenings. Sea breezes moderate summer heat. The swimming season extends from May to October.",
        "cost": "Malta has become more expensive but offers decent value for Europe. Monthly costs range from €1,800-2,800 for a comfortable lifestyle. Rent for a one-bedroom apartment averages €900-1,400 in Valletta, cheaper in surrounding towns. Restaurant meals cost €15-25. Pastizzi (local pastries) cost €0.50. Public transport is affordable at €1.50 per ride. Coworking spaces cost €200-350 monthly.",
        "wifi": "Malta has good internet infrastructure with improving speeds. Most cafes and coworking spaces offer 30-80 Mbps connections. The island has several coworking options concentrated around Valletta and Sliema. Residential connections are generally reliable with fiber expanding. Mobile data through GO or Melita provides strong coverage. Some older buildings in Valletta have connectivity challenges due to thick walls.",
        "nightlife": "Valletta's nightlife has transformed from quiet capital to vibrant scene. Strait Street (once the Red Light district) now features bars, jazz clubs, and wine venues. Paceville in nearby St. Julian's is the main party zone with clubs and bars. Roof-top bars in Valletta offer harbor views. The fortified city walls create atmospheric drinking settings. Nights can extend late, particularly on weekends. The scene suits diverse tastes.",
        "nature": "Malta offers Mediterranean beauty despite small size. Valletta's harbor and fortifications provide dramatic seascapes. Swimming spots dot the coastline with Blue Lagoon on Comino being most famous. Rocky beaches and hidden coves reward exploration. Gozo island offers rural landscapes and dramatic cliffs. The Dingli Cliffs provide panoramic views. Diving is exceptional with wrecks and clear water. Nature is compact but accessible.",
        "safety": "Valletta is extremely safe with very low crime rates. The small city is walkable at all hours without concern. Petty theft is rare but possible in tourist areas. No neighborhoods are considered dangerous. The main hazards are uneven limestone streets and summer heat. Malta's island nature creates a secure atmosphere. Solo travelers of all backgrounds feel comfortable. The community is close-knit and welcoming.",
        "food": "Maltese cuisine blends Italian, North African, and British influences. Pastizzi (ricotta or pea-filled pastries) are ubiquitous street food. Rabbit (fenek) is the national dish, prepared various ways. Fresh fish features prominently. Ftira (Maltese bread) accompanies most meals. Traditional restaurants serve hearty portions. International options have expanded significantly. The food scene combines rustic tradition with Mediterranean freshness.",
        "community": "Malta has developed a significant digital nomad community, attracted by English language, EU membership, and Mediterranean lifestyle. iGaming industry brings tech workers. Coworking spaces host networking events. The expat community spans diverse industries and nationalities. The small size means frequent familiar faces. Facebook groups and meetups connect newcomers. The community is welcoming if compact.",
        "english": "English is an official language in Malta, making it exceptionally accessible. All signage, services, and business operate in English. Maltese people are fluent bilingual speakers. The British colonial legacy established English as standard. No language barrier exists for English speakers. Maltese (the local language) adds cultural depth but is unnecessary for daily life.",
        "visa": "Malta is part of the Schengen Area and EU, allowing visa-free stays of up to 90 days within a 180-day period for citizens of many countries. Malta offers a Nomad Residence Permit for remote workers, requiring proof of employment and income. Various residency programs exist including the Global Residence Programme. EU citizens can live and work freely.",
        "culture": "Valletta packs extraordinary history into a small space, entirely UNESCO-listed. Knights of Malta legacy shows in magnificent baroque architecture. St. John's Co-Cathedral contains Caravaggio masterpieces. The fortifications represent military engineering marvels. Religious festivals, particularly the festa season, showcase traditional culture. Mediterranean warmth balances historic gravitas. The city is one of Europe's most concentrated cultural experiences.",
        "cleanliness": "Valletta is very clean with well-maintained streets and monuments. The historic center is kept pristine for its UNESCO status. Beaches and coastal areas are generally tidy. Some construction areas show temporary disorder. The compact size makes maintenance manageable. Public spaces are well-cared-for. Tap water is drinkable but many prefer bottled. The overall environment is pleasant.",
        "airquality": "Valletta has generally good air quality, benefiting from sea breezes and limited industry. Traffic emissions are lower than larger cities. The maritime location keeps air fresh. Some dust occurs during Saharan wind events (Xlokk). Construction can temporarily affect local air quality. The island environment generally provides clean conditions. Most visitors notice no air quality concerns."
    },
    "marrakech": {
        "climate": "Marrakech has a hot semi-arid climate with scorching summers and mild winters. Summer temperatures reach 35-45°C (95-113°F), making midday activities challenging. Winters are pleasant at 10-20°C (50-68°F) with occasional rain. Spring (March-May) and autumn (September-November) offer ideal conditions. The Atlas Mountains are visible on clear days. Air conditioning is essential in summer.",
        "cost": "Marrakech offers excellent value for tourists and nomads. Monthly costs range from $1,000-1,800 USD for a comfortable lifestyle. Rent for a one-bedroom apartment or riad averages $400-800 in the medina or Gueliz. Street food costs $1-3, while restaurant meals run $5-15. Hammams cost $10-20. Coworking spaces cost $80-200 monthly. Bargaining is expected in souks.",
        "wifi": "Internet in Marrakech has improved significantly, though it can be inconsistent in the old medina. Most cafes and coworking spaces offer 15-50 Mbps connections. Gueliz (new town) has better infrastructure. Coworking spaces like Coworking Marrakech provide reliable connections. Riad WiFi varies widely—verify before booking. Mobile data through Maroc Telecom or Orange provides backup. Power cuts occasionally affect service.",
        "nightlife": "Marrakech's nightlife centers around the new town and riads. Rooftop bars overlooking the medina offer sunset drinks. Gueliz district has modern bars and clubs. Live music venues feature traditional Gnawa music. The famous Comptoir Darna combines dinner and belly dancing. Nightclubs cater to tourists and affluent locals. The scene mixes traditional entertainment with international club culture. Alcohol is available but less visible than elsewhere.",
        "nature": "Marrakech serves as a gateway to Morocco's diverse landscapes. The Atlas Mountains are 90 minutes away for hiking and Berber villages. The Ourika Valley offers waterfalls and mountain escapes. The Sahara Desert is reachable for overnight trips. Essaouira's beaches are 3 hours west. Within the city, Majorelle Garden provides lush oasis escape. Palm groves (Palmeraie) extend beyond the city walls.",
        "safety": "Marrakech requires awareness but is generally safe. The medina can feel overwhelming with touts and persistent sellers. Pickpocketing occurs in crowded souks. Scams targeting tourists are common—be firm but polite. Women may experience more harassment than elsewhere. Avoid deserted areas at night. Most visitors have positive experiences with street smarts. The police presence is visible. Tourist areas are well-patrolled.",
        "food": "Moroccan cuisine is legendary, and Marrakech showcases it beautifully. Tagine (slow-cooked stews) come in countless varieties. Couscous Friday is traditional. Pastilla (sweet-savory pie) is a specialty. Djemaa el-Fna's food stalls offer authentic street food nightly. Fresh-squeezed orange juice costs cents. Tanjia (pot-cooked meat) is a local Marrakech dish. Fine dining riads offer refined versions of classics.",
        "community": "Marrakech has a developing digital nomad community, smaller than European hubs but growing. Coworking spaces cater to remote workers. The city attracts creatives, artists, and entrepreneurs. The expat community includes long-term residents and seasonal visitors. Cultural exchange opportunities abound. Language exchange happens naturally. The community is smaller but passionate about the unique environment.",
        "english": "English proficiency in Marrakech is moderate but improving. Tourism workers typically speak English or French. French is more widely spoken as a second language. Local neighborhoods require Arabic or French. Signs are often in Arabic, French, and sometimes English. Learning basic Arabic or French significantly helps daily interactions. The tourism industry operates with functional English.",
        "visa": "Morocco offers visa-free entry for citizens of many countries, typically allowing stays of 90 days. Extensions are possible but involve bureaucratic processes. There's no specific digital nomad visa. Remote workers enter as tourists. Work permits require employer sponsorship. Some nomads do visa runs to nearby countries for longer stays. The process is straightforward for tourism purposes.",
        "culture": "Marrakech embodies Morocco's cultural richness. The medina's narrow alleys reveal centuries of history. Djemaa el-Fna square transforms nightly into a carnival of storytellers, musicians, and food stalls. Islamic architecture reaches artistic heights in mosques and riads. Berber influence shows in crafts and carpets. The souks preserve traditional trades. French colonial legacy adds another layer. The sensory intensity is unmatched.",
        "cleanliness": "Marrakech's cleanliness varies significantly. Tourist areas and upscale riads are well-maintained. The medina's narrow streets can be cluttered. Waste management in older areas is challenging. Modern Gueliz is cleaner and more organized. Markets are busy but typical for such environments. Tap water is not recommended for drinking. The contrast between tourist and local areas is notable.",
        "airquality": "Marrakech has moderate air quality with seasonal variation. Traffic and dust are the main pollutants. Summer heat can intensify haze. The medina's narrow streets trap exhaust fumes. Modern areas have better air flow. Saharan dust occasionally affects conditions. The air can feel heavy in summer. Most visitors adapt without problems, though sensitive individuals should monitor conditions."
    },
    "cairo": {
        "climate": "Cairo has a hot desert climate with scorching summers and mild winters. Summer temperatures reach 35-42°C (95-108°F) with intense sun. Winters are pleasant at 10-20°C (50-68°F), occasionally cooler at night. Spring brings occasional khamaseen dust storms. Rainfall is extremely rare. The Nile moderates temperatures slightly. Spring and autumn offer the most comfortable conditions.",
        "cost": "Cairo offers exceptional value for digital nomads. Monthly costs range from $800-1,500 USD for a comfortable lifestyle. Rent for a one-bedroom apartment averages $200-500 in decent neighborhoods like Maadi or Zamalek. Street food costs $0.50-2, while restaurant meals run $3-10. Transportation is very cheap. Coworking spaces cost $50-150 monthly. The pound's devaluation has increased value for foreign earners.",
        "wifi": "Internet in Cairo has improved but remains inconsistent. Most cafes and coworking spaces offer 10-40 Mbps connections. Newer districts like New Cairo have better infrastructure. Coworking spaces like District and GrEEK Campus provide reliable connections. Residential internet can be frustrating with outages. Mobile data through Vodafone or Orange provides crucial backup. Patience with connectivity is required.",
        "nightlife": "Cairo's nightlife mixes traditional entertainment with modern venues. Zamalek island has upscale bars and lounges. Downtown Cairo offers gritty authenticity. Nile-side venues provide dinner cruises with live music. Traditional ahwa (cafes) serve shisha until late. Egyptian pop music and belly dancing entertainment persist. Western-style clubs exist in select areas. Alcohol is available but culturally sensitive.",
        "nature": "Cairo is primarily urban, but nature escapes exist. The Nile provides a green corridor through the city. Al-Azhar Park offers refuge from chaos. Day trips to Fayoum Oasis feature lakes, waterfalls, and desert landscapes. The desert begins at the city's edge with pyramid views. Red Sea beaches at Ain Sokhna are 2 hours away. Dahab in Sinai draws nomads for diving and chill vibes.",
        "safety": "Cairo requires cultural awareness and street smarts. Tourist areas are generally safe with visible security. Petty theft and scams targeting tourists occur. Taxis require agreeing fares upfront or using apps. Women experience more street harassment than in many countries. Avoid political gatherings. Most neighborhoods are safe during the day. The chaos is overwhelming but rarely dangerous. Common sense prevails.",
        "food": "Egyptian cuisine offers hearty, affordable eating. Koshari (carb-loaded comfort food) is beloved street food. Falafel (here called ta'meya) originated in Egypt. Ful medames (fava beans) fuel millions of breakfasts. Fresh bread accompanies every meal. Grilled meats and kofta are staples. Fiteer (Egyptian pizza) satisfies late-night cravings. Fine dining showcases both local and international cuisines. The food is delicious and incredibly cheap.",
        "community": "Cairo has a small but dedicated digital nomad community. Coworking spaces host events connecting remote workers. The expat scene includes teachers, NGO workers, and journalists. Arabic language students form their own community. The chaos filters for those who genuinely embrace it. Facebook groups connect foreign residents. The community is smaller than Southeast Asian hubs but passionate.",
        "english": "English proficiency in Cairo varies widely. Tourism and business sectors handle English. Educated Egyptians often speak excellent English. Local neighborhoods require Arabic or patience with gestures. University areas have more English speakers. Signs combine Arabic and sometimes English. Learning Arabic basics dramatically improves daily life and shows respect. The language barrier can be significant outside tourism zones.",
        "visa": "Egypt offers visa on arrival for citizens of many countries ($25 for 30 days). E-visas are available for some nationalities. Extensions are possible through Mugamma (central bureaucracy). There's no specific digital nomad visa. Remote workers typically use tourist status with renewals. Work permits require employer sponsorship. Multiple-entry visas are available. The bureaucracy can be challenging but manageable.",
        "culture": "Cairo is the heart of the Arab world, blending ancient history with dynamic modern life. The Pyramids and Egyptian Museum connect visitors to 5,000 years of civilization. Islamic Cairo preserves medieval architecture and Al-Azhar University. Coptic Cairo showcases Christian heritage. The contemporary art and music scenes thrive despite challenges. Nile-side promenades reveal daily Egyptian life. The cultural density is overwhelming and rewarding.",
        "cleanliness": "Cairo faces significant cleanliness challenges. Streets can be dusty and littered. Traffic congestion creates perpetual chaos. Some neighborhoods are better maintained than others. Maadi and Zamalek are cleaner residential areas. Historical sites are reasonably maintained. Waste management is an ongoing challenge. Tap water is not safe for drinking. The environment requires adjusting expectations from other destinations.",
        "airquality": "Cairo has severe air quality problems, ranking among the world's most polluted cities. Traffic emissions, industrial activity, and dust combine to create persistent smog. Air quality alerts are common. The desert environment adds particulate matter. Winter inversions can trap pollution. Sensitive individuals should monitor conditions and consider masks. Indoor spaces with filtration provide relief. The situation is serious for long-term health."
    },
    "nairobi": {
        "climate": "Nairobi has a subtropical highland climate, moderated by its altitude (1,795m). Temperatures range from 12-26°C (54-79°F) year-round, with cool mornings and warm afternoons. Two rainy seasons occur: long rains (March-May) and short rains (October-December). June-September is the cool, dry season. The climate is comfortable year-round, one of Africa's most pleasant capitals. Light layers are useful for temperature swings.",
        "cost": "Nairobi offers moderate costs for East Africa, with significant range between lifestyles. Monthly costs range from $1,200-2,500 USD for a comfortable lifestyle. Rent for a one-bedroom apartment averages $400-800 in areas like Westlands or Kilimani. Restaurant meals cost $5-15. Street food is cheap at $1-3. Safari trips are additional significant expenses. Coworking spaces cost $100-250 monthly.",
        "wifi": "Kenya has surprisingly good internet infrastructure, leading East Africa in connectivity. Most cafes and coworking spaces offer 20-50 Mbps connections. Nairobi has numerous coworking options including iHub and Nairobi Garage. Mobile data through Safaricom provides excellent coverage and speeds. 4G is widely available. Fiber connections exist in business districts. The tech hub reputation reflects genuine infrastructure quality.",
        "nightlife": "Nairobi's nightlife is vibrant and varied. Westlands neighborhood is the main party zone with clubs and bars. Live music venues showcase Kenyan and African artists. Rooftop bars offer city views. The Alchemist (food court and venue) represents trendy nightlife. Traditional nyama choma (barbecue) joints provide social eating until late. Security concerns mean many drive between venues. The scene is energetic and diverse.",
        "nature": "Nairobi offers unique nature experiences unmatched by other capitals. Nairobi National Park provides safari within sight of skyscrapers—lions, rhinos, and giraffes just 7km from downtown. The Giraffe Centre and David Sheldrick Elephant Orphanage offer animal encounters. Day trips reach the Rift Valley lakes and viewpoints. The Ngong Hills provide hiking with city panoramas. Safari circuits to the Masai Mara and beyond start from here.",
        "safety": "Nairobi requires security awareness that's second nature to locals. Petty crime and mugging can occur, particularly at night. Avoid walking alone after dark in most areas. Use rideshare apps rather than street taxis. Upscale neighborhoods like Karen and Lavington are safer. Mall and hotel security is tight following past incidents. The city has improved but vigilance remains important. Most expats adapt to reasonable precautions.",
        "food": "Kenyan cuisine is hearty and flavorful. Nyama choma (grilled meat) is the national obsession, best enjoyed socially. Ugali (cornmeal staple) accompanies most dishes. Sukuma wiki (collard greens) and mukimo (mashed potatoes and greens) are staples. Ethiopian restaurants reflect the diverse population. International options span every cuisine. The food scene has grown significantly with trendy restaurants and food markets.",
        "community": "Nairobi has a thriving tech and startup community that welcomes digital nomads. iHub pioneered African tech entrepreneurship. Coworking spaces host regular networking events. The expat community includes NGO workers, diplomats, and business professionals. Kenya's M-Pesa (mobile money) reflects local innovation. The community is dynamic and internationally minded. Networking opportunities abound in the 'Silicon Savannah.'",
        "english": "English is an official language in Kenya and widely spoken in Nairobi. All business, education, and services operate in English. Kenyans are typically fluent and articulate English speakers. Swahili is the other official language and adds cultural depth. Signs and media are in English. No language barrier exists for English speakers, making Nairobi highly accessible for remote workers.",
        "visa": "Kenya offers e-visas for most nationalities ($51 for single-entry, 90 days). Visa on arrival is available for some countries. Extensions are possible through immigration. There's no specific digital nomad visa. Remote workers typically use tourist visas. Work permits require employer sponsorship. The East African Tourist Visa allows travel to Uganda and Rwanda. The e-visa process is straightforward online.",
        "culture": "Nairobi is a cultural melting pot representing Kenya's 40+ ethnic groups. Art galleries and craft markets showcase African creativity. Music scene spans traditional rhythms to Afrobeats and Genge (local hip-hop). The literary scene produced Nobel laureate Wangari Maathai. Safari culture and conservation awareness run deep. The energy and ambition of this East African hub are palpable. Contradictions of wealth and poverty coexist visibly.",
        "cleanliness": "Nairobi's cleanliness has improved but challenges remain. Upscale neighborhoods maintain good standards. Downtown and local areas can be less tidy. Traffic congestion creates dust and exhaust. Some infrastructure strain shows in older areas. Shopping malls and hotels are clean. Tap water should be filtered or bottled. The city is working on improvements. Standards vary significantly by area.",
        "airquality": "Nairobi has moderate air quality, affected by traffic, industry, and dust. The high altitude and urban sprawl disperse some pollution. Traffic jams concentrate exhaust in certain areas. Dry seasons bring more dust. Industrial zones have worse air. The leafy suburbs generally have better conditions. Air quality is better than some African cities but worse than highland peers. Most visitors adapt without problems."
    },
    "auckland": {
        "climate": "Auckland has a subtropical oceanic climate with mild temperatures year-round. Summers (December-February) are warm at 20-26°C (68-79°F) with good beach weather. Winters (June-August) are mild at 10-15°C (50-59°F) with more rain. The city is known as the 'City of Sails' for its harbor-friendly conditions. Rainfall is spread throughout the year. Weather can change quickly. Four seasons exist but are moderate.",
        "cost": "Auckland is expensive by global standards. Monthly costs range from NZD 3,500-5,500 for a comfortable lifestyle. Rent for a central one-bedroom apartment averages NZD 2,000-2,800. Dining out costs NZD 20-40 for a meal. Groceries are pricey, especially imported goods. Public transport is reasonable but limited. Coworking spaces cost NZD 300-500 monthly. Housing affordability is a national issue.",
        "wifi": "New Zealand has good internet infrastructure, with Auckland offering reliable connectivity. Cafes and coworking spaces typically provide 30-100 Mbps connections. The city has several coworking options including Generator and BizDojo. Fiber connections are common in apartments. Mobile data coverage is excellent with strong 4G. Some rural areas around Auckland have weaker signals. Overall connectivity supports remote work well.",
        "nightlife": "Auckland's nightlife centers around Britomart, Ponsonby, and the Viaduct Harbour. Wine bars and craft breweries reflect sophisticated tastes. The cocktail scene has improved significantly. Live music venues host local and touring acts. K'Road (Karangahape Road) offers alternative vibes and LGBTQ+ venues. The scene is friendly but winds down earlier than major global cities. Weekends are busiest. The waterfront areas are particularly pleasant.",
        "nature": "Auckland is blessed with extraordinary natural access. The city spans two harbors with numerous beaches. Rangitoto Island offers volcanic hiking with city views. The Waitakere Ranges provide rainforest walks west of the city. Great Barrier Island is accessible for rugged escapes. Black sand beaches like Piha attract surfers. Coromandel Peninsula is a few hours for stunning coastline. Nature is integral to Auckland living.",
        "safety": "Auckland is very safe, consistently ranking among the world's safest cities. Violent crime is rare. Walking at night is comfortable in most areas. Property crime exists but is opportunistic rather than targeting individuals. The main hazards are road safety and outdoor adventures. New Zealand's culture of trust creates a secure atmosphere. Solo travelers of all backgrounds feel comfortable. The environment is welcoming.",
        "food": "Auckland's food scene reflects New Zealand's agricultural bounty and Pacific location. Fresh seafood, including green-lipped mussels and fish, features prominently. Asian cuisines are excellent, reflecting the multicultural population. Coffee culture rivals Australia's best. Farmers markets offer local produce. Pacific Rim fusion defines contemporary dining. Ponsonby and Britomart have the trendiest restaurants. The quality is high if prices match.",
        "community": "Auckland has a growing digital nomad community, though smaller than Australian hubs. The city attracts remote workers seeking quality of life over urban intensity. Coworking spaces host events connecting professionals. The startup ecosystem is developing. The expat community includes professionals from various industries. Integration is smooth with friendly locals. The community is smaller but welcoming.",
        "english": "English is the primary language in Auckland, making it fully accessible. Maori is a co-official language with increasing visibility. All services and daily life operate in English. Kiwi English includes unique expressions but is easily understood. The multicultural population means various accents are heard. No language barrier exists whatsoever for English speakers.",
        "visa": "New Zealand offers visa-free entry for citizens of many countries, allowing stays up to 90 days. Working Holiday Visas are available for citizens of participating countries aged 18-30 (or 35 for some). There's no specific digital nomad visa. Remote workers typically visit as tourists. Work visas require employer sponsorship. The points-based Skilled Migrant Category offers a pathway for longer stays.",
        "culture": "Auckland blends Maori heritage with Pacific and international influences. Maori culture is increasingly celebrated in public life and arts. The maritime tradition shapes identity and activities. Rugby is practically religion. The arts scene includes the Auckland Art Gallery and vibrant street art. Sustainability and environmental consciousness are strong values. The atmosphere is relaxed and outdoors-focused. Work-life balance is prioritized.",
        "cleanliness": "Auckland is very clean, reflecting New Zealand standards. Streets and public spaces are well-maintained. Beaches are kept pristine. Parks and walking trails are managed carefully. Public restrooms are clean and accessible. Recycling and environmental responsibility are practiced. The harbor and waterfront are kept in excellent condition. The overall environment is notably pleasant.",
        "airquality": "Auckland has excellent air quality, consistently among the world's best. The maritime location provides fresh sea breezes. Limited industrial activity and good environmental policies maintain clean conditions. Air Quality Index readings are typically excellent. The green spaces and moderate traffic keep pollution low. The air feels remarkably fresh, particularly near the coast. Breathing quality is a notable attraction."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")

    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
