#!/usr/bin/env python3
"""Rewrite batch 5: Cities B (bali-berlin)."""

import json
import os

BATCH_CITIES = {
    "bali": {
        "climate": "Bali has a tropical climate with two seasons: dry (April-October) and wet (November-March). Temperatures are consistent year-round (27-30°C) with high humidity. The dry season offers the best conditions with lower humidity and minimal rain. Wet season brings daily afternoon showers but also fewer tourists and lush landscapes. The southern beaches are drier than the mountain areas around Ubud. Pack light, breathable clothing year-round.",
        "cost": "Bali offers excellent value, though costs vary dramatically by area. A comfortable nomad lifestyle costs $1,200-2,000/month. Villas range $400-1,000/month depending on location and amenities. Local food is cheap ($2-4), while Western restaurants charge $8-15. Scooter rental is $50-70/month. Canggu and Seminyak are pricier; Ubud and less developed areas offer better value. The digital nomad infrastructure adds convenience at moderate cost.",
        "wifi": "Bali has invested heavily in internet for its nomad economy. Speeds of 30-80 Mbps are common in coworking spaces and developed areas. WiFi reliability has improved dramatically but can still be inconsistent in some accommodations. Coworking spaces like Dojo and Outpost provide reliable connections. Mobile data through Telkomsel offers good backup. Power outages occur occasionally—have battery backup for important work.",
        "nightlife": "Bali's nightlife varies by area. Seminyak and Kuta offer beach clubs and pumping nightlife until dawn. Canggu has a hipper, more laid-back scene with rooftop bars. Ubud is quieter—chill bars and early nights suit the wellness crowd. Full moon parties and beach club events create calendar highlights. The scene caters to all preferences, from yoga retreats to all-night raves.",
        "nature": "Bali's natural beauty is legendary. Rice terraces in Tegalalang and Jatiluwih create iconic landscapes. Volcanic peaks like Mount Batur offer sunrise treks. Waterfalls are scattered throughout—Sekumpul is particularly stunning. Beaches range from surfer havens to calm snorkeling spots. The underwater world offers diving and snorkeling. Despite tourism pressure, nature remains Bali's core attraction.",
        "safety": "Bali is generally safe with low violent crime. The main concerns are traffic (scooters are risky for inexperienced riders), petty theft (don't leave valuables unattended), and scams targeting tourists. Rip currents affect some beaches—heed warning flags. Drug laws are extremely strict with severe penalties. The Balinese are warm and helpful. Standard travel awareness ensures a safe experience.",
        "food": "Balinese food is flavorful and affordable. Nasi goreng (fried rice), mie goreng (fried noodles), and satay are staples. Babi guling (suckling pig) is a local specialty. The island has embraced health food—smoothie bowls, organic cafes, and vegetarian options abound. International cuisine is excellent, from Italian to Japanese. The food scene has evolved to serve every dietary preference at every price point.",
        "community": "Bali has one of the world's largest digital nomad communities, particularly in Canggu. Coworking spaces double as social hubs. Meetups, workshops, and networking events happen constantly. The community includes entrepreneurs, freelancers, remote workers, and creators. Connections form easily but can feel transient—many stay only weeks or months. The shared lifestyle creates instant common ground.",
        "english": "English is widely spoken in tourist areas, making Bali accessible. Most Balinese working in tourism speak functional English. Signs, menus, and services cater to English speakers. Outside tourist zones, Bahasa Indonesia becomes necessary. Learning basic Indonesian phrases enhances interactions and shows respect. The language barrier is minimal for daily life and business.",
        "visa": "Indonesia offers visa on arrival (30 days) or e-visa options. The B211A social visa allows 60-180 days and is popular with nomads. Extensions and visa runs are common practices. Indonesia has discussed digital nomad visas but implementation varies. The process involves some bureaucracy but is manageable. Working officially requires separate permits—many operate in gray areas.",
        "culture": "Balinese Hindu culture permeates daily life with offerings, temple ceremonies, and festivals throughout the year. The artistic tradition spans dance, music, woodcarving, and painting. Despite massive tourism, cultural practices remain authentic in daily life. Respect local customs—dress modestly for temples, don't step on offerings. The Balinese concept of Tri Hita Karana (harmony with God, people, and nature) guides the culture.",
        "cleanliness": "Bali faces environmental challenges from rapid development. Tourist areas are generally maintained. Plastic pollution affects beaches and waterways despite cleanup efforts. Waste management infrastructure struggles with the volume. Tap water is not safe—drink bottled or filtered. Some areas are beautifully maintained; others show wear. The situation is improving but requires visitor awareness.",
        "airquality": "Air quality in Bali is generally good, with AQI typically 30-60. Burning practices (rice fields, trash) can temporarily elevate levels. Traffic in busy areas creates localized pollution. Ubud's elevation and greenery offer fresher air. Sea breezes keep coastal areas fresh. The natural environment generally provides good air quality, though localized issues exist."
    },
    "bangkok": {
        "climate": "Bangkok is hot year-round with temperatures of 28-35°C. The hot season (March-May) is intense, with temperatures exceeding 40°C. Monsoon season (June-October) brings heavy but brief daily rains and slight temperature relief. The cool season (November-February) is most pleasant, with temperatures dropping to 25-30°C and lower humidity. Air conditioning is essential. The heat is the city's biggest lifestyle challenge.",
        "cost": "Bangkok offers incredible value for a major world city. A comfortable lifestyle costs $1,200-2,000/month. Modern apartments range $400-900/month, with luxury options available. Street food costs $1-3, and quality restaurant meals are $5-15. The BTS/MRT system is affordable. Western goods are pricier, but local alternatives offer value. The cost-quality ratio is exceptional.",
        "wifi": "Thailand has excellent internet infrastructure. Bangkok offers speeds of 50-200 Mbps commonly. WiFi is ubiquitous in cafes, malls, and coworking spaces. Coworking options are abundant, from budget to premium. Mobile data is cheap and reliable with AIS, DTAC, or TrueMove. The city is fully equipped for remote work with reliable, fast connectivity.",
        "nightlife": "Bangkok's nightlife is legendary and endless. From rooftop bars with skyline views to underground clubs, from backpacker Khao San Road to sophisticated Thonglor, every preference is served. RCA district hosts megaclubs. Sukhumvit has trendy cocktail bars. The infamous Patpong and Nana areas remain. The scene runs from dusk to dawn. Whatever you're seeking, Bangkok delivers.",
        "nature": "Bangkok is thoroughly urban with limited natural escapes. Lumphini and Chatuchak parks provide green space. Day trips reach beaches (Hua Hin, Pattaya), waterfalls, and national parks. Khao Yai National Park offers jungle trekking. The floating markets combine nature and culture. For real nature immersion, head to Thailand's islands or northern mountains—Bangkok is the hub, not the destination.",
        "safety": "Bangkok is relatively safe for a major city. Violent crime against tourists is rare. Scams exist—be wary of tuk-tuk drivers with 'special deals' and gem shop recommendations. Pickpocketing can occur in tourist areas. Traffic is genuinely dangerous—cross carefully and consider insurance for scooters. The Thai people are welcoming and helpful. Standard urban awareness ensures safety.",
        "food": "Thai cuisine is among the world's best, and Bangkok is its epicenter. Street food is incredible—pad thai, som tam, boat noodles, mango sticky rice. Michelin-starred restaurants offer refined Thai and international cuisine. The variety is endless—food courts, night markets, fine dining. Spice levels challenge the uninitiated—start mild. Eating is central to Thai life and happens constantly.",
        "community": "Bangkok has a massive and established nomad community. Coworking spaces host meetups and events constantly. The community includes tech workers, entrepreneurs, creatives, and teachers. Different neighborhoods attract different crowds—Thonglor for upscale professionals, Ari for creatives, On Nut for budget nomads. Connections form easily through work spaces and social events. The scene is mature and organized.",
        "english": "English is widely spoken in tourist and business areas. Younger Thais often have good English. Hotels, malls, and restaurants in popular areas function in English. Outside these zones, Thai helps significantly. The alphabet is different—learning to read basic signs takes time. Translation apps bridge gaps. The language barrier is manageable but present.",
        "visa": "Thailand offers visa-free entry (30-60 days depending on nationality) or visa on arrival. Extensions are possible at immigration offices. The elite visa provides long-term options for those with funds. Thailand has launched a Digital Nomad Visa (LTR visa) requiring significant income ($80k+/year) or assets. Visa runs remain common practice. The system is evolving to welcome remote workers.",
        "culture": "Thai culture blends Buddhist spirituality with modern dynamism. Temples dot the cityscape—Wat Pho, Wat Arun, Wat Phra Kaew are highlights. The Royal Family commands deep respect. Thai people are warm, smiling, and conflict-averse—'saving face' is crucial. The monarchy, religion, and nation form a revered trinity. The juxtaposition of ancient tradition and cutting-edge modernity defines Bangkok.",
        "cleanliness": "Bangkok is chaotic but functional. Main roads and tourist areas are maintained. Side streets can be rough, with sidewalks in variable condition. Street food hygiene is generally good—eat where locals eat. Tap water should be avoided—bottled or filtered is standard. Air-conditioned spaces are well-maintained. The city functions despite apparent chaos.",
        "airquality": "Air quality in Bangkok is a genuine concern, with AQI often 50-150 and sometimes worse. Traffic emissions, construction, and seasonal agricultural burning contribute. January-April can see severe pollution. Masks are advisable during bad periods. Air purifiers in accommodations help. The government addresses the issue but progress is slow. Sensitive individuals should monitor conditions."
    },
    "barcelona": {
        "climate": "Barcelona enjoys a Mediterranean climate with warm summers (25-30°C) and mild winters (10-15°C). The sea moderates temperatures, though summer humidity can feel intense. Rain is most common in autumn, sometimes in dramatic storms. Spring and autumn are ideal, with comfortable temperatures and lower tourist crowds. Over 300 sunny days per year support the outdoor lifestyle. Winters are short and mild.",
        "cost": "Barcelona has become increasingly expensive, though value remains compared to northern European capitals. A comfortable lifestyle costs €2,200-3,200/month. Apartments range €900-1,500/month in central areas—the housing market is tight and competitive. Restaurant meals cost €12-20, with lunch menus offering value. The tourism pressure drives prices up. Budget-conscious nomads look to outer neighborhoods.",
        "wifi": "Spain has solid internet infrastructure. Barcelona offers speeds of 50-100 Mbps typically. WiFi is available in most cafes, though working from them is less culturally common than in some cities. Coworking spaces are plentiful, from global chains to local options. Mobile data is reliable. The city supports remote work infrastructure, though not at Amsterdam levels.",
        "nightlife": "Barcelona's nightlife is legendary. The scene starts late—dinner at 10pm, bars at midnight, clubs at 2am, beach sunrise after. El Raval and El Born have alternative bars. Poble Sec is the new hot spot. Beachfront clubs span the waterfront. The Gothic Quarter offers intimate venues. The energy runs year-round, peaking in summer. Few cities match Barcelona's nocturnal vitality.",
        "nature": "Barcelona combines urban and natural access. The beaches stretch along the city's eastern edge. Tibidabo mountain offers views and forest walks. Montjuïc provides parks and gardens. Day trips reach Costa Brava beaches, Montserrat monastery, and Pyrenees mountains. The surrounding region offers wine country and medieval villages. Nature is accessible without leaving city limits.",
        "safety": "Barcelona is generally safe but has notorious pickpocketing, especially on Las Ramblas, the metro, and at tourist attractions. Violent crime is rare. Scams targeting tourists exist—be wary of distractions. Keep valuables secure and don't leave bags unattended. Beach theft is common—don't bring valuables. With awareness of petty theft, Barcelona is comfortable and safe.",
        "food": "Catalan cuisine offers excellent eating. Pa amb tomàquet (bread with tomato) accompanies everything. Seafood is exceptional—fideuà, suquet, calcots. The Boqueria market showcases ingredients. Tapas culture is slightly different here—pintxos and vermut. The dining scene has expanded with innovative restaurants. Food markets and traditional bodegas provide authentic experiences. Quality is high across all price points.",
        "community": "Barcelona has a significant international and nomad community, though less concentrated than Lisbon's. The tech and startup scene provides professional networking. Coworking spaces host events. The creative industries bring artists and designers. Neighborhoods develop distinct characters—Gràcia attracts a certain crowd, Poblenou another. Connections require some effort but communities exist for most interests.",
        "english": "English is widely spoken in Barcelona, particularly in tourism and business. Most young Catalans and Spaniards have some English. Menus and signs often include English. Learning Spanish and/or Catalan enriches the experience and earns respect. The language politics between Spanish and Catalan is complex—Catalan independence sentiment is strong. English suffices for daily life.",
        "visa": "Spain is part of the EU and Schengen. EU citizens have freedom of movement. Non-EU visitors stay 90 days within Schengen. Spain offers a digital nomad visa (Ley de Startups) with €2,200/month income requirement. Non-lucrative visas serve those with passive income. The bureaucracy requires patience. NIE (foreigner identification number) is needed for many transactions.",
        "culture": "Barcelona's culture blends Catalan identity with Spanish and Mediterranean influences. Gaudí's architecture—Sagrada Familia, Park Güell—defines the cityscape. Catalan identity is distinct, with its own language, traditions, and independence movement. The city balances historical preservation with modern creativity. Festivals like La Mercè and Sant Jordi showcase local traditions. Art, architecture, and design permeate daily life.",
        "cleanliness": "Barcelona maintains reasonable standards, though tourist pressure creates challenges. Beaches are cleaned daily. The Gothic Quarter can feel gritty. Main thoroughfares and tourist areas are maintained. Some neighborhoods show more wear. Tap water is safe but many prefer bottled. The city makes visible efforts but faces the challenges of 30 million annual visitors.",
        "airquality": "Air quality in Barcelona is moderate, with AQI typically 30-60. Traffic emissions and port activities contribute. Sea breezes help disperse pollution. Low emission zones have been implemented. The climate generally favors air quality dispersion. Summer heat can elevate ozone levels. The situation is typical for Mediterranean coastal cities—acceptable but not pristine."
    },
    "belgrade": {
        "climate": "Belgrade has a humid continental climate with hot summers (26-32°C) and cold winters (-2 to 5°C). Summer can be intensely hot, with temperatures occasionally exceeding 40°C. Winter brings cold, gray days with occasional snow. Spring and autumn are pleasant with moderate temperatures. The confluence of rivers creates humidity. The climate has character—each season is distinct.",
        "cost": "Belgrade offers exceptional value for a European capital. A comfortable lifestyle costs €1,000-1,600/month. Apartments range €350-700/month in central areas. Restaurant meals cost €6-12, with traditional kafanas even cheaper. Nightlife is affordable by any standard. The value attracts digital nomads looking to stretch budgets in Europe. Costs are rising but remain very competitive.",
        "wifi": "Serbia has invested in internet infrastructure. Belgrade offers speeds of 50-100 Mbps commonly. WiFi is available in cafes and restaurants. Coworking spaces provide reliable connections. Mobile data through mt:s, Telenor, or A1 is affordable and reliable. The city supports remote work adequately, though the nomad infrastructure is less developed than Western hubs.",
        "nightlife": "Belgrade's nightlife is legendary, arguably the best in the Balkans. The 'splavovi' (floating river clubs) are unique—massive venues on barges along the Danube and Sava. Skadarlija is the bohemian quarter for kafana dining and music. The scene runs from sophisticated cocktail bars to turbofolk clubs. Energy peaks after midnight and runs until dawn. Few cities party like Belgrade.",
        "nature": "Belgrade sits at the confluence of the Danube and Sava rivers, providing waterfront access. Ada Ciganlija, an island turned peninsula, offers summer beaches and recreation. Kalemegdan fortress and park provide urban green space. Day trips reach Novi Sad, Fruška Gora National Park, and Tara Mountain. Serbian nature is underrated—the countryside offers forests, mountains, and rural charm.",
        "safety": "Belgrade is very safe for a European capital. Violent crime is rare, and the city feels secure at all hours. Petty theft is possible but uncommon. Football match days require some awareness. The political situation is stable for visitors. Serbians are hospitable and helpful to foreigners. Standard urban awareness is sufficient. The atmosphere is relaxed and welcoming.",
        "food": "Serbian cuisine is hearty and meat-heavy. Ćevapi (grilled minced meat), pljeskavica (meat patty), and raznjici (skewers) dominate menus. Kafanas serve traditional dishes with live music. Kajmak (creamy cheese) accompanies everything. Breakfast includes burek (filled pastry) from pekara bakeries. The food is simple, generous, and deeply satisfying. Vegetarian options are limited but improving.",
        "community": "Belgrade's nomad community is growing but less established than Western hubs. Coworking spaces like Nova Iskra and Impact Hub host events. The tech scene is developing. Long-term expats mix with newer nomads. Serbians are social and welcoming once initial reserve fades. Connections form through nightlife, cafes, and shared interests. The community is emerging and intimate.",
        "english": "English is widely spoken among younger Serbians and in tourism/business contexts. Most restaurants, hotels, and services function in English. Outside central areas and with older generations, Serbian helps. Learning basic Serbian phrases earns appreciation—Serbians are proud of their language. Cyrillic and Latin alphabets coexist. Daily life in English is manageable.",
        "visa": "Serbia offers visa-free entry for many nationalities (90 days within 180). The process is straightforward. Serbia is not in the EU or Schengen, providing a separate visa clock. Digital nomad visas don't exist but aren't needed for most stays. Longer residency requires work permits or other arrangements. The relaxed immigration approach makes Belgrade accessible.",
        "culture": "Serbian culture blends Slavic, Ottoman, and Austro-Hungarian influences. Orthodox Christianity shapes traditions and holidays. Music—from turbofolk to brass bands—is central to social life. Hospitality is a serious cultural value. The history is complex—Yugoslavia, the wars of the 1990s, and current EU aspirations all shape identity. Cafes (kafanas) are living rooms. The culture is warm, social, and resilient.",
        "cleanliness": "Belgrade's cleanliness is variable. Central areas and new developments are maintained. Some neighborhoods show wear from years of economic challenges. Infrastructure is improving but uneven. Tap water is safe but mineral content varies. The city is functional rather than pristine. Standards are rising with economic development.",
        "airquality": "Air quality in Belgrade can be challenging, with AQI often 50-100+. Winter heating with coal and wood significantly impacts quality. Traffic emissions add to the problem. Summer is generally better. The river confluence provides some natural ventilation. Air quality is a recognized issue that the city is slowly addressing. Sensitive individuals should monitor conditions."
    },
    "berlin": {
        "climate": "Berlin has a continental climate with warm summers (20-28°C) and cold winters (-2 to 5°C). Summers are pleasant with long daylight hours—sunsets after 9pm. Winters are gray, cold, and can be depressing with darkness by 4pm. Spring and autumn are variable but can be beautiful. Rain is possible year-round. The climate requires seasonal adjustment and appropriate clothing.",
        "cost": "Berlin was Europe's affordable cool capital, but those days are ending. A comfortable lifestyle now costs €2,200-3,200/month. Apartments are extremely competitive, ranging €1,000-1,800/month—waiting lists and bidding wars are common. Restaurant meals cost €12-20. The legendary cheap rents are largely historical. Still cheaper than London or Paris, but rising fast.",
        "wifi": "German internet has a reputation for being behind other developed countries, but Berlin is well-served. Speeds of 50-100+ Mbps are available. Cafes often have WiFi but laptop culture is less embraced than in some cities. Coworking spaces are abundant. Mobile data works well with providers like Telekom, O2, or Vodafone. Connectivity supports remote work adequately.",
        "nightlife": "Berlin's nightlife is world-famous, particularly the techno scene. Berghain is the legendary temple of electronic music. Clubs operate continuously from Friday evening to Monday morning. The scene is underground, diverse, and serious about music. Beyond techno, there are bars for every subculture across the city's neighborhoods. The liberal, experimental attitude defines the experience. Few cities match Berlin's nocturnal intensity.",
        "nature": "Berlin is one of Europe's greenest capitals. Tiergarten is a massive central park. Lakes like Wannsee and Müggelsee offer summer swimming. The Brandenburg countryside is accessible by S-Bahn. Urban gardens and parks dot every neighborhood. The flat terrain is perfect for cycling. Tempelhof, the former airport turned park, is a unique urban space. Nature is integrated into city life.",
        "safety": "Berlin is very safe for a major city. Violent crime is rare. Petty theft can occur in tourist areas and on public transport. Some neighborhoods have rougher reputations, but danger is minimal. The city is progressive and tolerant—LGBTQ+ travelers feel welcome. Drug use is visible but not threatening. Standard urban awareness is sufficient. Walking at night is comfortable almost everywhere.",
        "food": "Berlin's food scene has evolved dramatically. Turkish döner is iconic and ubiquitous. International cuisines from every corner of the world are represented, reflecting the diverse population. The new German cuisine movement has brought innovation. Food markets like Markthalle Neun showcase quality. Vietnamese food is particularly excellent. Street food culture thrives. Quality varies but excellent options exist at every price point.",
        "community": "Berlin has a massive international community and thriving nomad scene. The startup ecosystem is significant. Coworking spaces and meetups are abundant. Different neighborhoods attract different crowds—Kreuzberg for alternatives, Mitte for professionals, Neukölln for creatives. The community is welcoming but Berlin's 'cool' factor can create cliques. Connections form through work spaces, nightlife, and shared interests.",
        "english": "English is widely spoken in Berlin, more so than in other German cities. The international population means English is often the common language. Restaurants, shops, and services function in English. Some Berliners prefer it to German. Integrating deeply into local life benefits from German, but daily life works fine in English. Official bureaucracy often requires German.",
        "visa": "Germany is part of the EU and Schengen. EU citizens have freedom of movement. Non-EU visitors stay 90 days within Schengen. Germany offers a freelance visa (Freiberufler) that has been popular with nomads, though requirements have tightened. The bureaucracy (Ausländerbehörde) is notoriously challenging. Patience and documentation are essential. Job seeker and artist visas provide other options.",
        "culture": "Berlin's culture is defined by history, creativity, and reinvention. The Wall's legacy still shapes the city—East and West retain distinct characters. The arts scene is world-class—museums, galleries, music, and performance. The creative, alternative spirit attracts artists and misfits. History is everywhere—memorials, museums, and preserved sites. The culture values authenticity, anti-commercialism, and individual expression.",
        "cleanliness": "Berlin is functional rather than pristine. Streets are maintained but graffiti is ubiquitous—some consider it art, others mess. Public transport is clean. Parks are well-kept. The alternative culture embraces a certain grittiness. Tap water is excellent. The city works despite appearances that might seem chaotic. Cleanliness standards are relaxed compared to other German cities.",
        "airquality": "Air quality in Berlin is generally good, with AQI typically 25-50. Traffic emissions affect busy areas. The many parks and lakes contribute freshness. Industrial pollution is minimal in the city center. Germany's environmental regulations help. Winter heating has some impact. Overall, Berlin's air quality is among the better European capitals."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
