#!/usr/bin/env python3
"""Rewrite batch 10: Major cities P-S (porto, phuket, rome, seoul, singapore)."""

import json
import os

BATCH_CITIES = {
    "porto": {
        "climate": "Porto has an oceanic climate with mild, rainy winters (8-14°C) and warm summers (18-26°C). Rain is frequent from October to May—the city is greener than Lisbon. Summer offers pleasant beach weather with cooler temperatures than the Algarve. Atlantic winds keep humidity moderate. The climate supports outdoor life most of the year, though an umbrella is essential.",
        "cost": "Porto has become pricier but remains excellent value for Western Europe. A comfortable lifestyle costs €1,400-2,200/month. Apartments range €600-1,100/month—cheaper than Lisbon now. Restaurant meals cost €10-18, with lunch menus offering value. Port wine is affordable at the source. The cost-quality ratio is very favorable.",
        "wifi": "Portuguese internet infrastructure is excellent. Porto offers speeds of 100+ Mbps commonly, with fiber widely available. Cafes offer WiFi, and coworking spaces like Porto i/o provide reliable connections. Mobile data is affordable and fast. Portugal's digital infrastructure supports remote work exceptionally well.",
        "nightlife": "Porto's nightlife is vibrant and intimate. The Ribeira waterfront and Galerias de Paris street host the main scenes. Bars fill narrow streets until late. Live music venues showcase Portuguese and international acts. The vibe is more relaxed than Lisbon—conversations over port wine rather than megaclubs. Summer nights on the Douro are magical.",
        "nature": "Porto's nature is defined by the Douro River, Atlantic beaches, and surrounding wine country. The Foz district has urban beaches. Day trips reach the dramatic Douro Valley wine region. The coast extends north to unspoiled beaches. Peneda-Gerês National Park is a few hours away. Nature combines coast, river, and countryside.",
        "safety": "Porto is very safe—one of Europe's safest cities. Violent crime is virtually nonexistent. Petty theft is rare even in tourist areas. The city has a trusting atmosphere. Walking at night is comfortable everywhere. Portuguese hospitality makes visitors feel welcome and secure.",
        "food": "Porto's food scene rivals Lisbon. The francesinha—a meat sandwich smothered in cheese and sauce—is iconic. Tripas à moda do Porto (tripe stew) divides opinions. Fresh seafood and bacalhau are excellent. The Bolhão market (recently renovated) showcases ingredients. Wine from the Douro is world-class. Quality is high across all price points.",
        "community": "Porto's nomad community has grown rapidly, particularly in recent years. Coworking spaces host events and meetups. The community is smaller and more intimate than Lisbon's. Connections form easily in this manageable-sized city. Portuguese and internationals mix more naturally here. The creative and tech scenes are developing.",
        "english": "English is widely spoken in Porto, especially among younger people and in business/tourism. Daily life functions in English. Portuguese effort is appreciated and earns warmth. Outside tourist zones, Portuguese becomes more useful. The accessibility is high for English speakers.",
        "visa": "Portugal's visa rules apply—EU and Schengen membership. EU citizens have freedom of movement. Non-EU visitors stay 90 days within Schengen. Portugal's D7 visa for passive income holders and the new Digital Nomad Visa offer long-term options. The NHR tax regime (while changing) has attracted many. Processes are manageable if slow.",
        "culture": "Porto's culture is defined by its UNESCO historic center, port wine heritage, and independent spirit. The Livraria Lello is one of the world's most beautiful bookstores. Azulejo tiles cover buildings throughout. The Ribeira riverfront is a UNESCO site. Porto is prouder and grittier than Lisbon—'Porto works while Lisbon parties' is the saying. The culture values authenticity.",
        "cleanliness": "Porto is well-maintained, with the historic center receiving significant preservation investment. The Ribeira is cleaned regularly. Public transport is clean. Streets can be steep and uneven but are generally tidy. Tap water is safe and good. Standards are appropriate for a historic European city.",
        "airquality": "Air quality in Porto is generally good, with AQI typically 20-45. Atlantic winds keep air fresh. Lack of heavy industry helps. Traffic affects central areas minimally. The river and coastal position ensure natural ventilation. The air is clean and pleasant year-round."
    },
    "phuket": {
        "climate": "Phuket has a tropical monsoon climate. The dry season (November-April) offers ideal beach weather with low humidity. The monsoon (May-October) brings daily rain, though often brief afternoon showers. Temperatures are consistent year-round (27-33°C). The west coast has bigger waves in monsoon; east coast is calmer. The climate is beach-friendly most of the year.",
        "cost": "Phuket offers varied costs depending on lifestyle. A comfortable nomad life costs $1,200-2,200/month. Apartments range $400-1,000/month depending on location and amenities. Beach locations command premiums. Local food is cheap ($2-5); tourist restaurants charge more. The island offers both budget and luxury options.",
        "wifi": "Thailand's internet infrastructure is good. Phuket offers speeds of 30-80 Mbps. Coworking spaces like Garage Society provide reliable connections. Beach areas have improved connectivity. Mobile data through AIS, DTAC, or TrueMove is affordable and reliable. The island supports remote work adequately.",
        "nightlife": "Phuket's nightlife is famous—Patong Beach has the most intense scene with Bangla Road's bars and clubs. Other areas like Rawai and Kata are more relaxed. Beach clubs offer sunset sessions. The scene spans from wild party strips to sophisticated lounges. Whatever your preference, Phuket delivers.",
        "nature": "Phuket's nature centers on beaches and the Andaman Sea. Snorkeling and diving access coral reefs and marine life. Phi Phi Islands and Phang Nga Bay are day-trip highlights. The interior has jungle and waterfalls. Big Buddha overlooks the island. The combination of beach and island-hopping opportunities is excellent.",
        "safety": "Phuket is generally safe. Scooter accidents are the main danger—traffic is challenging and helmets are essential. Beach conditions require attention—rip currents during monsoon. Petty crime is possible but uncommon. Tourist scams exist but are manageable. Thai hospitality creates a welcoming atmosphere.",
        "food": "Thai cuisine in Phuket includes southern specialties—more spice, more seafood. The night markets serve excellent local food cheaply. Fresh seafood at beach restaurants is a highlight. International options cater to tourists. From street food to fine dining, quality is available. The food scene is diverse and accessible.",
        "community": "Phuket's nomad community has grown, centered in areas like Rawai and Chalong away from the party zones. Coworking spaces host events. The community includes long-term residents and seasonal visitors. Connections form through work spaces and social activities. The scene is established but more dispersed than Chiang Mai.",
        "english": "English is widely spoken in tourist areas. Hotels, restaurants, and services function in English. Outside tourist zones, Thai becomes more useful. The tourism industry ensures English accessibility. Basic Thai improves interactions but isn't essential.",
        "visa": "Thailand's visa rules apply. Visa-free entry (30-60 days) or visa on arrival. The Thailand LTR visa offers long-term options with significant income requirements. Extensions and visa runs are common practices. The system is manageable for medium-term stays.",
        "culture": "Phuket blends Thai Buddhism with tourism modernity. Temples dot the landscape—Big Buddha is iconic. The Old Town preserves Sino-Portuguese heritage. Vegetarian Festival is a dramatic annual event. Thai culture coexists with tourism—the balance varies by area. The island has more depth than the beaches suggest.",
        "cleanliness": "Phuket's cleanliness varies by area. Tourist beaches are cleaned. Patong can feel crowded and worn. Quieter areas are better maintained. The sea is generally clean for swimming. Tap water should be avoided. Standards are reasonable for a heavily touristed destination.",
        "airquality": "Air quality in Phuket is generally good, with AQI typically 25-50. Sea breezes keep air fresh. The island's position avoids mainland pollution. Occasional haze from regional burning can affect quality. Most days the air is clean and pleasant."
    },
    "rome": {
        "climate": "Rome has a Mediterranean climate with hot, dry summers (28-35°C) and mild, wet winters (6-14°C). Summer heat can be intense, with occasional days exceeding 40°C. Spring and autumn are ideal—pleasant temperatures for walking the ancient sites. Winter is cool but rarely cold. Rain falls mainly October-February. The climate favors outdoor living most of the year.",
        "cost": "Rome is moderately expensive for a major capital. A comfortable lifestyle costs €2,000-3,000/month. Apartments range €900-1,500/month in central areas—cheaper outside Centro Storico. Restaurant meals cost €12-25. The tourist economy inflates some prices. Eating and drinking well remains accessible with local knowledge.",
        "wifi": "Italian internet has improved but still lags northern Europe. Rome offers speeds of 30-70 Mbps. WiFi in cafes is common but Italian culture doesn't prioritize laptop work. Coworking spaces provide reliable connections. Mobile data through TIM, Vodafone, or WindTre is adequate. Connectivity is sufficient though not cutting-edge.",
        "nightlife": "Rome's nightlife is about atmosphere—aperitivo in Trastevere, bars in Campo de' Fiori, clubs in Testaccio. The scene is social and late-starting. Dinner extends into evening drinks that become night. Live music and rooftop bars add variety. The atmosphere is romantic and convivial rather than wild.",
        "nature": "Rome itself has surprising green space—Villa Borghese, Villa Doria Pamphili. Day trips reach beaches (Ostia), volcanic lakes (Bracciano), and hilltop towns. The surrounding countryside is gentle and agricultural. Amalfi Coast and Tuscany are accessible for weekends. Nature requires leaving the city but options are excellent.",
        "safety": "Rome is generally safe but pickpocketing is endemic. Tourist sites, metro, and buses require vigilance. Scams targeting tourists exist. Violent crime is rare. Walking at night is comfortable in most central areas. Italian cities feel safer than they sometimes look. Standard awareness prevents most problems.",
        "food": "Roman cuisine is iconic—carbonara, cacio e pepe, amatriciana, carciofi alla romana. The simplicity and quality of ingredients define the style. Trattorias serve classic dishes; modern restaurants innovate. Avoid tourist traps near monuments. Fresh pasta, supplì (rice balls), and Roman pizza al taglio are daily pleasures. The food alone justifies visiting Rome.",
        "community": "Rome's international community includes academics, artists, and religious communities alongside growing nomads. The nomad scene is smaller than northern European hubs. Connections form through coworking spaces and cultural events. Romans can be reserved initially but warm over time. The community is cultured and established.",
        "english": "English is spoken in tourism and business but Italian dominates daily life. Hotels and restaurants in tourist areas manage in English. Outside these zones, Italian becomes necessary. Learning Italian significantly enriches the experience and is expected for longer stays. Young Romans often have good English.",
        "visa": "Italy's visa rules apply—EU and Schengen membership. EU citizens have freedom of movement. Non-EU visitors stay 90 days within Schengen. Italy offers elective residence visas for those with income. Work visas require sponsorship. The bureaucracy is challenging but navigable.",
        "culture": "Rome's culture spans 3,000 years—the Colosseum, Vatican, Renaissance palaces, and modern vitality. Every corner reveals history. The la dolce vita lifestyle values pleasure and aesthetics. Religious traditions coexist with secular modern life. Fashion, food, and art are serious matters. Living in Rome means immersion in Western civilization's foundations.",
        "cleanliness": "Rome's cleanliness is a persistent challenge. Historic areas are maintained but some streets are rough. Graffiti is common. The trash system has well-documented issues. Tourist sites are cleaned. Tap water is safe—Roman fountains provide excellent drinking water. Expectations should be calibrated for Rome's particular chaos.",
        "airquality": "Air quality in Rome is moderate, with AQI typically 35-65. Traffic affects central areas significantly. Summer heat can elevate levels. Restrictions on vehicles help but challenges remain. The situation is manageable but noticeable, particularly for sensitive individuals. Monitor conditions during heat waves."
    },
    "seoul": {
        "climate": "Seoul has a humid continental climate with hot, humid summers (25-33°C) and cold, dry winters (-6 to 4°C). Summer monsoon brings heavy rain. Winter is genuinely cold with occasional snow. Spring (cherry blossoms) and autumn (fall colors) are spectacular and popular. The seasons are dramatic and distinct. Dress for extremes.",
        "cost": "Seoul is expensive but offers value in certain areas. A comfortable lifestyle costs $2,000-3,200/month. Apartments (officetels) range $800-1,600/month. Eating out is reasonable—excellent meals for $8-15. Transport is cheap and excellent. Korean products are affordable. The cost reflects first-world infrastructure and quality.",
        "wifi": "South Korea has the world's best internet infrastructure. Seoul offers speeds of 200+ Mbps commonly, often gigabit. Free public WiFi is everywhere. Cafes compete on connectivity. Mobile data is fast and affordable. This is the global gold standard for digital infrastructure.",
        "nightlife": "Seoul's nightlife is intense and varied. Gangnam has upscale clubs. Hongdae is the youthful, alternative hub. Itaewon offers international diversity. The scene runs very late—Koreans party hard. Karaoke (noraebang) is cultural institution. The energy and variety match any global city.",
        "nature": "Seoul is surrounded by mountains—Bukhansan National Park is within the city limits. The Han River provides waterfront recreation. Day trips reach beautiful temples, beaches, and countryside. Korea's four seasons make outdoor activities varied. Nature is more accessible than Seoul's mega-city status suggests.",
        "safety": "Seoul is extremely safe—one of the world's safest cities. Violent crime is rare. Lost items are often returned. Walking anywhere at any hour is comfortable. The society is orderly and trusting. Emergency services are excellent. Safety is a genuine strength.",
        "food": "Korean cuisine is exceptional—BBQ, bibimbap, kimchi, fried chicken and beer (chimaek). Street food culture is strong. The food delivery infrastructure is unmatched. From humble to haute, quality is consistent. Late-night eating is cultural. The food scene is a major reason to be in Seoul.",
        "community": "Seoul has a growing international community, particularly in tech and creative industries. The nomad scene is developing. Coworking spaces host events. Koreans can seem reserved initially but are warm in social settings. Language barriers exist but many young Koreans speak English. The community is sophisticated and professional.",
        "english": "English is taught universally but spoken ability varies. Younger Koreans often have good English. Tourism areas function in English. Outside these zones, Korean becomes very useful. Translation technology helps bridge gaps. The language barrier is real but manageable.",
        "visa": "South Korea offers visa-free entry (90 days) for most Western nationalities. Work visas require sponsorship. Korea has introduced the Workcation visa for remote workers. D-10 job-seeking visa provides flexibility. The system is organized and efficient.",
        "culture": "Korean culture blends Confucian tradition with technological modernity. K-pop and K-drama have global reach. Traditional palaces coexist with neon-lit streets. The work culture is intense. Respect for elders and hierarchy structures society. The transformation from war-torn to technological powerhouse defines national identity.",
        "cleanliness": "Seoul is very clean by global standards. Streets are maintained, public facilities are spotless, and infrastructure is modern. The metro is immaculate. Tap water is safe though many prefer filtered. The attention to cleanliness is impressive and consistent.",
        "airquality": "Air quality in Seoul is a concern, with AQI often 50-100+. Yellow dust from China, local emissions, and seasonal factors contribute. Some days require masks. Indoor air is filtered in most modern buildings. The government addresses the issue but progress is gradual. Monitor conditions, especially spring."
    },
    "singapore": {
        "climate": "Singapore has a tropical rainforest climate—hot and humid year-round (27-33°C). Rain is possible any day, usually as brief afternoon thunderstorms. There's no distinct dry season, though November-January sees more rain. The humidity is constant and intense. Air conditioning is universal and essential. The weather is consistent if challenging.",
        "cost": "Singapore is extremely expensive—among the world's most costly cities. A comfortable lifestyle costs S$4,500-7,000/month ($3,300-5,100). Rent for apartments ranges S$2,500-4,500/month. Hawker food is cheap ($3-5), but restaurants are pricey. Alcohol and cars are heavily taxed. Budget carefully for Singapore's costs.",
        "wifi": "Singapore's internet is world-class. Speeds of 200+ Mbps are standard. Free public WiFi is widespread. The island is comprehensively connected. Mobile coverage is excellent. Singapore's smart nation initiative ensures cutting-edge digital infrastructure.",
        "nightlife": "Singapore's nightlife is sophisticated and controlled. Marina Bay and Clarke Quay have rooftop bars and clubs. Alcohol is expensive. The scene is upscale rather than gritty. Laws are strict—behavior is regulated. The quality is high; the edge is smoothed. Networking events blend with nightlife.",
        "nature": "Despite the urban density, Singapore has excellent green spaces. Gardens by the Bay is spectacular. The Botanic Gardens (UNESCO site) provide tropical respite. MacRitchie Reservoir offers jungle trails. Pulau Ubin provides kampung (village) atmosphere. Nature is engineered but genuinely accessible.",
        "safety": "Singapore is one of the world's safest cities. Violent crime is virtually nonexistent. The city is famously strict—laws are enforced. You can walk anywhere at any time. Belongings left unattended are safe. The trade-off for freedom is exceptional security.",
        "food": "Singapore's food is exceptional—the hawker center culture is UNESCO-recognized. Chinese, Malay, Indian, and fusion cuisines create incredible diversity. Chicken rice, laksa, chili crab, and satay are staples. The quality is consistent from hawker stalls to fine dining. Food is a national obsession.",
        "community": "Singapore has a massive international community—expats from every country. The business and tech communities are significant. Networking is constant. The transient nature of expat life means relationships require effort. Coworking spaces and professional events provide connections. The community is professional and diverse.",
        "english": "English is an official language and the primary business language. Daily life functions entirely in English. Singlish (Singapore English) has its own expressions that you'll learn. Communication is effortless. The multilingual society means many languages are heard.",
        "visa": "Singapore offers visa-free entry (30-90 days) for most nationalities. Work visas are competitive—the Employment Pass requires a job offer and salary threshold. The new Tech Pass serves technology professionals. Starting a business requires capital. The system is efficient but selective.",
        "culture": "Singapore's culture reflects its multi-ethnic population—Chinese, Malay, Indian, and others coexist. The city-state is modern and efficient—sometimes called 'Asia's Switzerland.' Rules govern much of life. The transformation from third world to first in one generation shapes identity. Material success is valued.",
        "cleanliness": "Singapore is famously clean—perhaps the world's cleanest city. Streets are spotless. Chewing gum is banned. Littering brings heavy fines. The infrastructure is pristine. Tap water is excellent. The cleanliness is remarkable and consistent.",
        "airquality": "Air quality in Singapore is generally good (AQI 20-50). The annual haze from Indonesian fires can create dangerous conditions (100+ AQI). This typically occurs August-October. Outside haze season, air quality is excellent. Indoor air is universally filtered. Monitor conditions during haze season."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
