#!/usr/bin/env python3
"""Rewrite batch 9: Major cities M-P (medellin, mexicocity, newyork, paris, prague)."""

import json
import os

BATCH_CITIES = {
    "medellin": {
        "climate": "Medellín is the 'City of Eternal Spring' with temperatures of 18-28°C year-round. The valley location at 1,500m creates perfect conditions—never too hot, never cold. Brief afternoon showers are common but don't disrupt life. Dry season (December-March, June-August) has clearer days. No AC or heating needed. The consistently pleasant climate is a major draw.",
        "cost": "Medellín offers exceptional value. A comfortable lifestyle costs $1,200-2,000/month. Modern apartments in Poblado or Laureles range $500-1,000/month. Local food is cheap ($3-6), with quality restaurants at $10-20. The cost-quality ratio is excellent. Colombia's affordable living enables extended stays on modest budgets.",
        "wifi": "Colombia has invested in internet infrastructure. Medellín offers speeds of 30-100 Mbps, with fiber available in good areas. Coworking spaces like Selina and Atomhouse provide reliable connections. Cafes commonly offer WiFi. Mobile data through Claro, Movistar, or Tigo is affordable. Connectivity supports remote work well.",
        "nightlife": "Medellín's nightlife is vibrant and varied. Parque Lleras in Poblado is the famous hub—bars, clubs, and outdoor drinking. Provenza has a more sophisticated vibe. La 70 in Laureles offers local character. Reggaeton and Latin music dominate but variety exists. The scene runs late with energy continuing until dawn. The atmosphere is social and inclusive.",
        "nature": "Medellín sits in the Aburrá Valley surrounded by mountains. Paragliding from nearby hills is popular. The coffee region is a day trip away. Guatapé's lake and rock provide iconic landscapes. El Peñol and Santa Fe de Antioquia offer escapes. The metro cable cars provide mountain views. Nature is accessible and dramatic.",
        "safety": "Medellín has transformed from its notorious past. Tourist areas like Poblado and Laureles are generally safe. Petty theft exists—keep awareness, don't flash valuables. Some neighborhoods remain dangerous—know where to avoid. Violent crime against tourists is rare but not unknown. The city has improved dramatically but requires smart precautions.",
        "food": "Colombian food is hearty and satisfying. Bandeja paisa—beans, rice, meat, egg, plantain, avocado—is iconic. Arepas are everywhere. Fresh tropical fruits are exceptional and cheap. The food scene has evolved with modern restaurants and international options. Quality is good across all levels. The value is excellent.",
        "community": "Medellín has a massive digital nomad community, particularly in Poblado and Laureles. Coworking spaces are numerous. Meetups and events happen constantly. The community includes tech workers, entrepreneurs, and remote professionals. Connections form instantly. The scene can feel bubble-like, somewhat separated from local life. But it's established and welcoming.",
        "english": "English is spoken in nomad areas and tourism but limited elsewhere. Younger Colombians often have some English. Learning Spanish significantly improves the experience and is essential for genuine integration. Many nomads take Spanish classes. Outside the bubble, English won't get you far.",
        "visa": "Colombia offers visa-free entry (90 days) for most nationalities, extendable once. The Digital Nomad Visa allows two years for remote workers ($3,000+/month income required). The process is straightforward. Visa runs to neighboring countries are common for longer stays. Colombia actively welcomes remote workers.",
        "culture": "Colombian culture is warm, social, and resilient. Paisas (Medellín locals) are proud of their city's transformation. Music and dancing—salsa, cumbia, reggaeton—are central to social life. Family bonds are strong. The city's troubled history has created a forward-looking optimism. The transformation from violence to innovation is evident everywhere.",
        "cleanliness": "Medellín is reasonably clean for a Latin American city. Poblado and modern areas are well-maintained. Some neighborhoods face challenges. The metro is famously clean and efficient—a source of civic pride. Parks are maintained. The situation is variable but generally acceptable. Standards have improved significantly.",
        "airquality": "Air quality in Medellín is a concern, with AQI often 50-100+. The valley geography traps pollution. Traffic and industry contribute. Seasonal inversions worsen conditions—March/October tend to be worst. Some days require attention. The government addresses the issue but progress is gradual. Monitor conditions and choose accommodation wisely."
    },
    "mexicocity": {
        "climate": "Mexico City has a subtropical highland climate with mild temperatures year-round (12-25°C). The elevation (2,240m) keeps temperatures comfortable despite the latitude. Rainy season (June-October) brings afternoon showers. Dry season is pleasant with clear days. The altitude means strong sun and cool evenings. The climate is generally pleasant with occasional smoggy days.",
        "cost": "Mexico City offers excellent value for a major global city. A comfortable lifestyle costs $1,500-2,500/month. Apartments in Roma or Condesa range $600-1,200/month. Food is varied—street tacos for $1-2, quality restaurants for $15-30. The cost-quality ratio is exceptional. The city provides world-class experiences at accessible prices.",
        "wifi": "Mexican internet infrastructure is adequate in the capital. Speeds of 30-80 Mbps are typical. Cafes commonly offer WiFi, though reliability varies. Coworking spaces provide stable connections. Mobile data through Telcel, Movistar, or AT&T works well. The city supports remote work, though not as robustly as some Asian hubs.",
        "nightlife": "Mexico City's nightlife is world-class. Roma and Condesa have trendy bars and clubs. Historic Centro has cantinas and live music. Polanco offers sophistication. The scene spans from mezcalerías to techno clubs. Mexican hospitality extends to nightlife—strangers become friends. The energy runs late with diverse options for every taste.",
        "nature": "Mexico City is urban but nature is accessible. Chapultepec Park is one of the world's largest urban parks. The floating gardens of Xochimilco provide waterway escapes. Day trips reach Teotihuacán pyramids, mountain hikes, and pueblos mágicos. The surrounding mountains offer forests and volcanoes. Weekend escapes are varied and accessible.",
        "safety": "Mexico City requires awareness but isn't as dangerous as reputation suggests. Stick to known neighborhoods (Roma, Condesa, Polanco, Coyoacán). Petty theft occurs—be smart with valuables. Some areas are genuinely dangerous—know which to avoid. Uber is preferred over taxis at night. With reasonable precautions, most visitors are fine. The city is much safer than many assume.",
        "food": "Mexican cuisine is UNESCO-recognized, and CDMX is its capital. Street tacos are legendary and ubiquitous. Markets like La Merced showcase ingredients. Modern Mexican restaurants earn international acclaim. From casual to fine dining, every meal impresses. The diversity reflects Mexico's regions. Food is integral to daily life—eating well is easy and affordable.",
        "community": "Mexico City has a large and growing nomad community, particularly in Roma and Condesa. Coworking spaces host events. The creative, tech, and entrepreneurial scenes overlap. Connections form through work spaces, cafes, and social events. Mexicans are warm and social. The community is diverse—locals and internationals mix more naturally than in some hubs.",
        "english": "English is spoken in business, tourism, and educated circles. Roma and Condesa function partly in English. However, Spanish significantly improves daily life and is expected for deeper integration. Mexico City is less English-forward than tourist destinations. Learning Spanish is recommended and rewarding.",
        "visa": "Mexico offers visa-free entry (180 days) for most Western nationalities—one of the longest. Extensions are difficult, but visa runs reset the clock. Mexico has introduced a temporary resident visa for remote workers. The relatively open policy makes extended stays straightforward. The bureaucracy can be challenging for residency.",
        "culture": "Mexican culture is rich, ancient, and vibrant. Pre-Hispanic and Spanish colonial heritage blend uniquely. The arts scene is strong—muralism, contemporary art, literature, and music. Diego Rivera and Frida Kahlo's homes are cultural landmarks. Day of the Dead is globally recognized. The culture values family, celebration, and living fully. The energy is palpable.",
        "cleanliness": "Mexico City's cleanliness varies dramatically by neighborhood. Upscale areas like Polanco and Roma are well-maintained. Popular neighborhoods function reasonably well. Some areas face challenges. The metro is crowded but functional. Tap water should be filtered or bottled. Standards are variable—choose location carefully.",
        "airquality": "Air quality in Mexico City can be challenging, with AQI often 50-100+. The valley geography and altitude trap pollution. Traffic is a major contributor. Environmental alerts occasionally restrict activities. Winter tends to be worse. The situation has improved from past decades but remains a consideration. Monitor conditions."
    },
    "newyork": {
        "climate": "New York has a humid subtropical climate with hot, humid summers (25-32°C) and cold, snowy winters (-2 to 8°C). Spring and fall are generally pleasant but brief. Summer humidity can be oppressive. Winter brings snow, cold wind, and gray days. The seasons are distinct and dramatic. Dress for extremes and enjoy seasonal transitions.",
        "cost": "New York is one of the world's most expensive cities. A comfortable lifestyle costs $5,000-8,000/month. Apartments in Manhattan are brutal—studios start at $2,500+/month. Brooklyn and Queens are slightly cheaper. Restaurant meals cost $20-40+. The cost is challenging but reflects unmatched opportunities. Budget requires careful management.",
        "wifi": "American infrastructure serves NYC well. Speeds of 100+ Mbps are available. Cafes and coworking spaces offer connectivity. Mobile coverage is excellent. The city is fully equipped for remote work, though working from cafes is less common than in some cultures. Connectivity is never an issue.",
        "nightlife": "New York's nightlife needs no introduction. Every preference is served across the five boroughs. Manhattan's clubs and bars span styles and budgets. Brooklyn has the coolest scene. Jazz, comedy, live music, dancing—it's all here. The city never sleeps is literal—something is always open. The scale and variety are unmatched.",
        "nature": "Central Park is the famous green escape in Manhattan. The Hudson River waterfront offers walks. Day trips reach beaches, mountains, and the Hudson Valley. Within the city, parks in each borough provide green space. Urban nature is integrated but genuine wilderness requires leaving the city. Weekend escapes are essential for balance.",
        "safety": "New York is much safer than its reputation suggests—among the safest large American cities. Violent crime has dropped dramatically since the 1990s. Petty theft and scams targeting tourists exist. Some neighborhoods have higher crime—research your areas. The subway is generally safe though late-night requires awareness. Standard urban precautions apply.",
        "food": "New York's food scene is world-class and exhaustive. Every cuisine exists at every level. Pizza and bagels are iconic. The diversity reflects global immigration. Fine dining competes with the world's best. Street food, food halls, and restaurants span all budgets. Quality is available everywhere if you know where to look.",
        "community": "New York has massive and varied communities. The tech, finance, creative, and startup scenes are all significant. Networking is constant—the city runs on connections. Coworking spaces and meetups abound. The challenge is New York's scale and pace—relationships require effort. Community exists within industries, neighborhoods, and interest groups.",
        "english": "New York is native English-speaking with distinctive New York attitudes and pace. The multicultural population means hundreds of languages are spoken. Communication is direct and fast. The city functions entirely in English.",
        "visa": "US visa rules apply. ESTA/visa waiver allows 90-day visits for qualifying nationalities. Working legally requires sponsorship or green card. No digital nomad visa exists. Tourist status prohibits work. The US immigration system is complex and strict. Many work remotely on tourist visas in gray areas.",
        "culture": "New York is a global cultural capital. Broadway, world-class museums (MoMA, Met, Guggenheim), independent galleries, music venues—the cultural infrastructure is unmatched. The pace is fast and demanding. Ambition drives the city. Each neighborhood has distinct character. The energy is intense and addictive. This is the city that defines itself as the center of everything.",
        "cleanliness": "New York's cleanliness is famously variable. Some streets are immaculate; others have visible trash. The subway system shows wear. Gentrified neighborhoods are maintained. The city makes ongoing efforts but faces challenges of scale. Tap water is excellent—among America's best. Expectations should be calibrated.",
        "airquality": "Air quality in NYC is moderate, with AQI typically 30-60. Traffic affects street level. Some days see elevated levels from regional conditions. The geography allows air movement. The situation has improved significantly over decades. Most days are acceptable; check conditions if sensitive."
    },
    "paris": {
        "climate": "Paris has a temperate oceanic climate with mild summers (17-25°C) and cool winters (3-8°C). Rain is possible year-round though usually light. Gray skies are common, especially in winter. Spring and early summer are beautiful with long daylight hours. Autumn has atmospheric charm. The climate is moderate—neither extreme heat nor cold—but rarely warm.",
        "cost": "Paris is expensive, though cheaper than London. A comfortable lifestyle costs €2,800-4,200/month. Apartments are hard to find and pricey, ranging €1,400-2,500/month for central locations. Restaurant meals cost €18-35. Wine makes dining reasonable. The challenge is housing; other costs are manageable. Quality justifies expense.",
        "wifi": "French internet infrastructure is solid. Paris offers speeds of 50-100+ Mbps with fiber widely available. Cafe WiFi exists but French culture doesn't prioritize laptop work in cafes. Coworking spaces provide reliable connections. Mobile data through Orange, SFR, or Free is reliable. Connectivity supports remote work adequately.",
        "nightlife": "Paris nightlife is sophisticated and varied. Cocktail bars, wine bars, and live music venues dot every arrondissement. Le Marais has the trendiest scene. Pigalle mixes traditional and modern. The scene starts and ends earlier than southern Europe. Quality over quantity defines the approach. Nightlife is about conversation, wine, and atmosphere.",
        "nature": "Paris is urban but elegantly green. The Tuileries, Luxembourg Gardens, and Bois de Boulogne provide escapes. The Seine's banks are now car-free. Day trips reach Versailles, Fontainebleau, and Champagne. Real countryside is an hour away. The city integrates nature through its park system and tree-lined boulevards.",
        "safety": "Paris is generally safe but requires awareness. Pickpocketing is common at tourist sites, on the metro, and around train stations. Scams targeting tourists exist. Some suburban areas have higher crime. Central Paris is comfortable at night. The city functions with standard urban precautions. Violence against tourists is rare.",
        "food": "French cuisine needs no introduction, and Paris is its pinnacle. From neighborhood bistros to Michelin stars, the food is exceptional. Bakeries produce daily miracles. Markets overflow with quality. Wine pairing is automatic. The culinary tradition is serious and maintained. Eating well is accessible at various price points—you just can't eat badly.",
        "community": "Paris has a significant international community, including a growing nomad presence. The tech startup scene (Station F) provides professional networks. Coworking spaces host events. French social circles take time to enter—the culture is more closed than some. The international community provides easier access. Persistence builds genuine Parisian friendships.",
        "english": "English is increasingly spoken in Paris, especially in business, tourism, and among younger generations. Daily basics work in English. However, French is expected for integration and earns respect. The Parisian attitude toward English has softened but French effort is appreciated. Deeper life requires French.",
        "visa": "France is part of the EU and Schengen. EU citizens have freedom of movement. Non-EU visitors stay 90 days within Schengen. France offers various visas including the passeport talent for skilled workers. No specific digital nomad visa exists. The bureaucracy is challenging. France is accessible but processes are slow.",
        "culture": "Parisian culture is art, architecture, and lifestyle. The Louvre, Musée d'Orsay, and countless galleries anchor the art world. Architecture spans from Gothic to Haussmanian to modern. Fashion, philosophy, and cuisine are serious matters. The café terrasse is a way of life. The culture values aesthetics, pleasure, and intellectual engagement. Paris demands you participate in living well.",
        "cleanliness": "Paris's cleanliness has improved but remains variable. Main boulevards and tourist areas are maintained. Some streets, particularly around train stations, can be rough. Metro is functional but shows wear. Dog waste has decreased but persists. Tap water is safe and good. Standards are acceptable though imperfect.",
        "airquality": "Air quality in Paris is moderate, with AQI typically 30-60. Traffic affects central areas despite efforts. Some days see elevated levels. The city has implemented restrictions on vehicles. River proximity helps. The situation is typical for major European capitals—managed but not pristine."
    },
    "prague": {
        "climate": "Prague has a humid continental climate with warm summers (20-26°C) and cold winters (-2 to 4°C). Winter can be gray and cold, with occasional snow. Summer is pleasant though briefly hot. Spring and autumn are ideal—comfortable temperatures and beautiful light. The seasons are distinct with real winter. Pack accordingly for each season.",
        "cost": "Prague offers good value for Central Europe, though rising. A comfortable lifestyle costs €1,400-2,200/month. Apartments range €600-1,100/month in central areas. Restaurant meals cost €8-15, with traditional pubs cheaper. Beer is famously cheap—excellent pilsner for €2. The value has decreased but remains solid compared to Western Europe.",
        "wifi": "Czech internet infrastructure is good. Prague offers speeds of 50-100 Mbps commonly. WiFi is available in cafes. Coworking spaces provide reliable connections. Mobile data through O2, T-Mobile, or Vodafone is reliable. The city supports remote work well. Connectivity is not a concern.",
        "nightlife": "Prague's nightlife is vibrant and varied. The Old Town has tourist-oriented bars but also gems. Žižkov is the gritty, local alternative. Cross Club is internationally famous for its industrial aesthetic. The beer culture anchors everything—Czech beer is world-class. The scene runs late. The bachelor party reputation obscures genuinely excellent options.",
        "nature": "Prague itself is green with parks and the Vltava River. Petřín Hill provides forest walks with city views. Day trips reach Bohemian Switzerland National Park, Karlštejn Castle, and charming towns like Český Krumlov. The surrounding Bohemian countryside offers hiking and nature. Escapes are easy and scenic.",
        "safety": "Prague is very safe—one of Europe's safest capitals. Violent crime is rare. Pickpocketing can occur in tourist areas and on trams. Taxi scams exist—use apps. The atmosphere is relaxed and comfortable. Walking at night is fine throughout the center. Standard tourist awareness is sufficient.",
        "food": "Czech cuisine is hearty: svíčková (marinated beef), vepřo knedlo zelo (pork, dumplings, cabbage), and trdelník (pastry). The food is traditionally heavy but satisfying. Modern Czech cuisine has evolved with quality restaurants. Beer is the national drink—the best pilsner in the world. Food quality varies—seek out the good spots.",
        "community": "Prague has a significant nomad and expat community. Coworking spaces like Locus and Node5 host events. The community includes remote workers, entrepreneurs, and developers. Czechs can seem reserved but are warm once connected. The international community is welcoming. Connections form through work spaces and social events.",
        "english": "English is widely spoken in Prague, especially among younger Czechs and in tourism/business. Daily life functions in English. Outside tourist zones, Czech helps. Learning basic phrases earns appreciation. The language accessibility makes Prague easy for English speakers.",
        "visa": "Czech Republic is part of the EU and Schengen. EU citizens have freedom of movement. Non-EU visitors stay 90 days within Schengen. Czechia has a Zivno visa for self-employed workers that's been popular with nomads. The process requires some bureaucracy but is established.",
        "culture": "Prague's culture blends Bohemian history with modern creativity. Charles Bridge, Prague Castle, and the astronomical clock define the historic center. The Czech spirit is skeptical, humorous, and beer-loving. Kafka's legacy pervades. The communist era left marks that are fading. The culture values practicality and quiet quality. Prague resists tourist kitsch through genuine character.",
        "cleanliness": "Prague maintains good standards. The historic center is well-preserved and clean. Public transport is functional and reasonably maintained. Parks are tidy. Tap water is excellent. Some areas outside the center show wear. The city makes visible efforts at maintenance. Standards are appropriate for Central Europe.",
        "airquality": "Air quality in Prague is generally good, with AQI typically 25-50. Traffic affects central areas. Winter heating can increase levels temporarily. The river and parks contribute freshness. The situation is among the better European capitals. Seasonal variation exists but most days are acceptable."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
