#!/usr/bin/env python3
"""Rewrite batch 17: Manila, Siem Reap, Ubud, Canggu, Ericeira."""

import json
import os

BATCH_CITIES = {
    "manila": {
        "climate": "Manila has a tropical monsoon climate with hot, humid conditions year-round. Temperatures range from 26-34°C (79-93°F) throughout the year. The dry season (December-May) brings less rain and slightly lower humidity. Wet season (June-November) features heavy monsoon rains and occasional typhoons. The hottest months are April-May before monsoon arrives. Air conditioning is essential.",
        "cost": "Manila offers good value despite being the capital. Monthly costs range from $1,000-2,000 USD for a comfortable lifestyle. Rent for a one-bedroom apartment averages $400-800 in areas like Makati or BGC. Street food costs $1-3, while restaurant meals run $5-15. Mall dining is slightly pricier. Transportation is very affordable. Coworking spaces cost $100-250 monthly. BGC and Makati have higher costs.",
        "wifi": "Philippines has improved internet infrastructure, though it remains variable. Most coworking spaces and cafes in Manila offer 20-50 Mbps connections. BGC and Makati have the best infrastructure. Fiber connections are becoming more common in new buildings. Mobile data through Globe or Smart provides backup. Some areas have inconsistent service. Coworking spaces offer the most reliable work environment.",
        "nightlife": "Manila's nightlife is vibrant and diverse. Makati's Poblacion neighborhood has become a bar and club hotspot. BGC offers upscale lounges and rooftop bars. Quezon City has a more local scene with live music venues. Mall bars are popular for casual drinking. The scene ranges from dive bars to exclusive clubs. Nights extend late, particularly on weekends. The party culture is enthusiastic.",
        "nature": "Manila is primarily urban, but nature escapes are accessible. Tagaytay offers volcano views and cooler climate just 2 hours away. Batangas beaches provide quick diving and snorkeling trips. La Union is popular for surfing weekends. The Rice Terraces of Banaue make longer trips rewarding. Intramuros offers historic walks within the city. Rizal Park provides green space downtown. The nearby islands are the real draws.",
        "safety": "Manila requires more awareness than some Asian capitals but is manageable. Tourist areas like Makati and BGC are relatively safe. Petty theft and pickpocketing occur in crowded areas and public transport. Avoid displaying expensive items. Some areas should be avoided at night. Traffic is a constant challenge. Use ride-hailing apps rather than street taxis. Most visitors experience no problems with basic precautions.",
        "food": "Filipino cuisine is hearty and flavorful, with Spanish, Chinese, and Malay influences. Adobo (braised meat), sinigang (sour soup), and lechon (roast pig) are national favorites. Street food includes isaw (grilled intestines) and balut (fertilized duck egg) for the adventurous. Mall food courts offer diverse options. International cuisine is widely available in Makati and BGC. The foodie scene is evolving with modern Filipino restaurants.",
        "community": "Manila has a growing digital nomad community, though smaller than other Southeast Asian hubs. Coworking spaces in Makati and BGC host networking events. The expat community includes teachers, business professionals, and remote workers. Filipinos are famously friendly and welcoming. English proficiency makes integration easier. Social media groups connect remote workers. The community is warm and inclusive.",
        "english": "English is an official language in the Philippines, making Manila one of Asia's most English-friendly destinations. Most Filipinos speak fluent English, used in business, education, and daily life. Signs, menus, and media are in English. This eliminates language barriers common elsewhere in Asia. Filipino English includes local expressions that are quickly learned. The call center industry reflects the strong English skills.",
        "visa": "Philippines offers visa-free entry for citizens of many countries, typically allowing 30 days extendable to 36 months total. Extensions are processed through immigration offices. The SRRV visa offers long-term residence options. There's no specific digital nomad visa. Remote workers typically use tourist status with extensions. Work visas require employer sponsorship. The extension process is straightforward if bureaucratic.",
        "culture": "Filipino culture blends Asian foundations with centuries of Spanish and American influence. Catholic traditions shape festivals and family life. Hospitality (pakikisama) is central to social interactions. Music and entertainment are passions—karaoke is ubiquitous. Social media engagement is among the world's highest. Malls serve as community centers. The resilience and cheerfulness of Filipinos are notable despite challenges.",
        "cleanliness": "Manila's cleanliness varies dramatically by area. BGC and Makati business districts are well-maintained. Shopping malls are clean and air-conditioned havens. Older areas and public markets can be grimy. Traffic and flooding challenge street cleanliness. Tap water is not safe to drink. Air quality is poor due to traffic. The contrast between affluent and poor areas is stark.",
        "airquality": "Manila has significant air quality problems, primarily from traffic emissions. The dense urban environment traps pollution. Air quality indexes frequently show unhealthy levels. Indoor spaces with air filtration provide relief. Some areas like BGC have slightly better air. Masks are common among locals. The situation is worse during dry months when dust combines with emissions. Sensitive individuals should monitor conditions."
    },
    "siemreap": {
        "climate": "Siem Reap has a tropical monsoon climate with hot conditions year-round. Temperatures range from 25-35°C (77-95°F) throughout the year. Dry season (November-April) is the best for temple visits with sunny skies and lower humidity. Wet season (May-October) brings daily afternoon downpours but greener landscapes and fewer crowds. The hottest months are March-May. Early morning temple visits beat the heat.",
        "cost": "Siem Reap offers exceptional value for travelers and nomads. Monthly costs range from $700-1,400 USD for a comfortable lifestyle. Rent for a one-bedroom apartment averages $250-500, with great options in central areas. Street food costs $1-2, while restaurant meals run $3-8. Angkor pass costs $62 for 3 days. Coworking spaces cost $50-150 monthly. Prices have risen but remain very affordable.",
        "wifi": "Internet in Siem Reap has improved significantly but remains slower than major cities. Most cafes and guesthouses offer 10-30 Mbps connections. Coworking spaces like Angkor Hub provide more reliable speeds. Newer apartments often have fiber connections. Mobile data through Smart or Metfone provides backup. Power outages occasionally affect connectivity. The infrastructure is adequate for most remote work.",
        "nightlife": "Siem Reap's nightlife centers on Pub Street, a pedestrianized strip of bars, clubs, and restaurants. The scene caters primarily to tourists with bucket drinks and party atmosphere. More sophisticated options exist along the river and in side streets. Khmer cuisine restaurants offer evening entertainment. The night market provides shopping and street food. Nights can go late but many early-rising temple visitors keep it moderate.",
        "nature": "Siem Reap is surrounded by extraordinary landscapes. Angkor Archaeological Park covers 400 square kilometers of temples and forest. Tonle Sap Lake, Southeast Asia's largest freshwater lake, offers floating villages and bird watching. Kulen Mountain provides waterfalls and jungle temples. The countryside features rice paddies and traditional villages. Cycling through temple complexes combines nature and culture. The surrounding areas offer diverse exploration.",
        "safety": "Siem Reap is very safe with low crime rates. The tourist areas are well-patrolled and comfortable to walk at night. Petty theft is rare but keep valuables secure. Bag snatching by motorbike is occasionally reported. Landmines exist in remote areas—stay on marked paths at temple sites. Traffic is relatively calm compared to other Asian cities. Most visitors feel very secure throughout their stay.",
        "food": "Cambodian cuisine is distinct from neighbors, featuring fresh herbs and unique flavors. Amok (coconut curry steamed in banana leaves) is the signature dish. Fish from Tonle Sap features prominently. Lok lak (stir-fried beef) and kuy teav (noodle soup) are everyday favorites. The night market offers diverse street food. French colonial influence shows in excellent baguettes and coffee. Restaurants range from tourist-oriented to authentic local.",
        "community": "Siem Reap has a small but dedicated digital nomad community. The town's pace attracts those seeking affordability and cultural immersion over party scenes. Coworking spaces foster connections among remote workers. The NGO and social enterprise scene draws purpose-driven workers. The expat community includes long-term residents and seasonal visitors. The community is welcoming if smaller than major hubs.",
        "english": "English proficiency in Siem Reap is good due to tourism dependence. Hotels, restaurants, and tour guides speak English well. Tuk-tuk drivers have basic English. Local markets may require gestures or translation apps. Signage is typically bilingual. Young Cambodians often have strong English skills. Learning basic Khmer phrases is appreciated and helpful. The tourism focus makes English sufficient for most needs.",
        "visa": "Cambodia offers multiple entry options. Visa on arrival is available for most nationalities ($30 for 30 days). E-visas can be arranged in advance. Extensions are straightforward through travel agencies. Long-term options include business visas renewable indefinitely (with proper documents). There's no specific digital nomad visa but the business visa serves this purpose. The process is simple if not always transparent.",
        "culture": "Siem Reap's culture centers on the Angkor legacy and living Khmer traditions. The temples represent the height of medieval civilization. Buddhism shapes daily life with monk alms rounds each morning. Traditional dance performances preserve ancient art forms. The tragic Khmer Rouge history is remembered at the landmine museum. Cambodians are known for warmth and resilience. Respectful temple dress and behavior matter.",
        "cleanliness": "Siem Reap is reasonably clean for Southeast Asia. The tourist center is well-maintained. Temple grounds are kept tidy. Local neighborhoods vary in cleanliness. Wet season brings flooding and muddy conditions. Tap water is not safe to drink. Markets are busy but reasonable. The town has improved infrastructure significantly from tourism revenue. Air quality is generally good.",
        "airquality": "Siem Reap has generally good air quality, benefiting from lower traffic and surrounding countryside. The main pollutant is dust, particularly during dry season. Agricultural burning occasionally affects air quality. The temple areas offer fresh air away from town. Traffic emissions are lower than larger cities. Most visitors don't experience air quality concerns. The environment is relatively clean."
    },
    "ubud": {
        "climate": "Ubud has a tropical climate moderated by its inland highland location, making it slightly cooler than coastal Bali. Temperatures range from 22-32°C (72-90°F) year-round. Dry season (April-October) brings sunny days ideal for outdoor activities. Wet season (November-March) features daily afternoon showers but lush green landscapes. Humidity is high year-round. Mornings are typically pleasant regardless of season.",
        "cost": "Ubud offers good value with rising prices due to popularity. Monthly costs range from $1,200-2,200 USD for a comfortable lifestyle. Rent for a one-bedroom villa averages $500-1,000, with budget options around $300-400. Local warung meals cost $2-4, while healthy cafe dishes run $8-15. Yoga classes cost $10-15. Coworking spaces cost $100-300 monthly. The wellness premium affects many prices.",
        "wifi": "Internet in Ubud has improved but remains inconsistent in some areas. Most cafes and coworking spaces offer 20-50 Mbps connections. Dedicated coworking spaces like Outpost and Hubud provide reliable speeds. Villa connections vary widely—verify before booking. Mobile data through Telkomsel provides backup. Rural areas and rice paddies have weaker signals. The infrastructure supports remote work but requires choosing locations wisely.",
        "nightlife": "Ubud's nightlife is distinctly low-key, focusing on wellness rather than parties. Evening activities center around yoga studios, sound healing sessions, and ecstatic dance. Some bars and restaurants offer live music. The Laughing Buddha hosts alternative events. Most places close by 11 PM. Those seeking nightlife head to Canggu or Seminyak. The vibe prioritizes early mornings over late nights.",
        "nature": "Ubud is surrounded by extraordinary natural beauty. The Tegallalang rice terraces offer iconic stepped landscapes. The Sacred Monkey Forest provides jungle walks and primate encounters. Campuhan Ridge offers sunrise walks above river valleys. Mount Batur provides sunrise trekking opportunities. Numerous waterfalls dot the surrounding jungle. The river valleys feature rafting and walking trails. Nature is integral to the Ubud experience.",
        "safety": "Ubud is very safe with low crime rates and a peaceful atmosphere. Walking alone at night is comfortable in central areas. Petty theft is rare but don't leave valuables unattended. Motorbike riding is the main hazard—many accidents involve tourists. Watch for aggressive monkeys who grab food and belongings. The spiritual atmosphere creates a respectful environment. Solo travelers of all backgrounds feel secure.",
        "food": "Ubud has become a global hub for healthy and wellness-focused cuisine. Organic cafes serve smoothie bowls, raw foods, and plant-based dishes. Traditional Balinese warungs offer authentic nasi campur and sate. International options span every diet and preference. The healthy food scene includes high-quality ingredients and conscious sourcing. Traditional Balinese cooking classes are popular. The food culture balances wellness with local traditions.",
        "community": "Ubud has one of the world's most established digital nomad communities. The wellness focus attracts remote workers seeking balance. Coworking spaces host regular events and workshops. The community includes entrepreneurs, creators, and spiritual seekers. Facebook groups and regular meetups facilitate connections. Long-term nomads form lasting friendships. The high season brings constant new arrivals while maintaining a core community.",
        "english": "English proficiency in Ubud is excellent due to tourism. All restaurants, shops, and services cater to international visitors. Balinese working in tourism speak good English. Signs and menus are in English. The international community uses English as the default. Learning basic Indonesian is appreciated but unnecessary for daily life. The bubble is thoroughly English-friendly.",
        "visa": "Indonesia offers visa-free entry for citizens of many countries for 30 days, extendable once for another 30 days. Visa on arrival ($35) allows 60 days with extension option. Social-cultural visas through agencies allow 60 days with multiple extensions. The B211A remote worker visa launched for digital nomads. Multiple visa runs to nearby countries are common for longer stays. Regulations change frequently.",
        "culture": "Ubud is the cultural heart of Bali, where traditional arts and spirituality thrive. Daily offerings and temple ceremonies mark Hindu practice. Traditional dance performances occur nightly. Artisan villages specialize in painting, carving, and crafts. The wellness industry has created a parallel spiritual-tourism culture. Balinese hospitality is legendary. The intersection of traditional and modern attracts seekers. Respect for local customs is important.",
        "cleanliness": "Ubud is reasonably clean with regular efforts to maintain tourist areas. The main streets are swept regularly. Rice paddies and natural areas are generally pristine. Some construction and development areas are messier. Plastic waste is a broader Bali issue being addressed. Tap water is not drinkable. Wellness-focused establishments maintain high standards. The natural environment is largely beautiful.",
        "airquality": "Ubud has generally good air quality, benefiting from surrounding rice paddies and forest. Traffic emissions are lower than coastal areas. Burning of agricultural waste occasionally affects quality. The highland location helps keep air fresh. Morning fog can feel heavy but isn't pollution. The environment feels cleaner than developed areas. Most visitors appreciate the fresh, tropical air."
    },
    "canggu": {
        "climate": "Canggu has a tropical climate with consistent warmth year-round. Temperatures range from 25-33°C (77-91°F) throughout the year. Dry season (April-October) brings excellent beach and surf conditions. Wet season (November-March) features afternoon showers but warm temperatures continue. Humidity is high. The coastal location provides sea breezes. Surfing conditions vary by season with different breaks favored.",
        "cost": "Canggu has become increasingly expensive as the hottest digital nomad destination. Monthly costs range from $1,500-3,000 USD for a comfortable lifestyle. Rent for a one-bedroom villa averages $700-1,500, with budget rooms around $400-500. Brunch dishes cost $10-18 at trendy cafes. Local warungs serve meals for $2-4. Coworking spaces cost $150-350 monthly. The gentrification has significantly raised prices.",
        "wifi": "Internet in Canggu is generally good, supporting the massive digital nomad community. Most cafes and coworking spaces offer 30-100 Mbps connections. Coworking spaces like Dojo, Tropical Nomad, and Outpost provide reliable infrastructure. Villa connections vary—some excellent, others frustrating. Mobile data through Telkomsel provides backup. The tech-savvy population has driven infrastructure improvement. Choose workspaces carefully for important calls.",
        "nightlife": "Canggu's nightlife has exploded with the nomad influx. Beach clubs like Finn's and The Lawn host sunset sessions and parties. Old Man's is legendary for casual drinks and live music. Batu Bolong area features bars, clubs, and late-night venues. The scene ranges from chill surfer bars to international DJ events. Wednesday and Saturday nights are biggest. The party atmosphere differs from Ubud's tranquility.",
        "nature": "Canggu offers beach-focused nature with rice paddies inland. The famous black sand beaches provide surfing at multiple breaks. Echo Beach, Batu Bolong, and Berawa cater to different skill levels. Rice terrace walks remain possible in surrounding areas. Tanah Lot temple provides dramatic coastal scenery. The northern coast has quieter beaches. Day trips to waterfalls and mountains are popular. The ocean is the main attraction.",
        "safety": "Canggu is relatively safe but the party scene brings some risks. Motorbike accidents are the biggest danger—many nomads get hurt. Drink spiking occasionally occurs at parties. Petty theft from villas and beaches happens. The party crowds can get rowdy. Traffic is chaotic and requires constant attention. Most visitors have positive experiences with basic precautions. The daytime atmosphere is very relaxed.",
        "food": "Canggu's food scene caters heavily to Western nomad preferences. Smoothie bowls, avocado toast, and healthy brunch dominate cafe menus. Australian-style coffee is exceptional throughout. Traditional Balinese warungs survive in local areas. International options span every cuisine. Prices are higher than elsewhere in Bali. The scene follows Instagram trends closely. Quality is generally high if not traditionally Balinese.",
        "community": "Canggu has the largest digital nomad concentration in Bali, possibly the world. Coworking spaces overflow with remote workers. The community skews younger and more party-oriented than Ubud. Networking is constant and unavoidable. Facebook groups have thousands of active members. Some find the scene overwhelming or superficial. Others thrive on the energy and opportunities. It's nomad culture at maximum intensity.",
        "english": "English is the default language in Canggu, dominating all nomad-oriented establishments. Local Balinese working in tourism speak excellent English. Signs, menus, and social interaction happen in English. The international bubble rarely requires Indonesian. The scene is almost entirely English-speaking. Learning basic Balinese phrases shows respect. The linguistic environment is thoroughly Western-oriented.",
        "visa": "Indonesia offers visa-free entry for citizens of many countries for 30 days, extendable once for another 30 days. Visa on arrival ($35) allows 60 days with extension option. Social-cultural visas through agencies allow 60 days with multiple extensions. The B211A remote worker visa launched for digital nomads. Multiple visa runs are common for longer stays. Bali agents handle all processes.",
        "culture": "Canggu represents Bali's most Westernized area, where surf culture and digital nomadism dominate. Traditional Balinese culture persists in temples and ceremonies but feels overshadowed by expat influence. The scene centers on cafes, coworking, and beach clubs. Some criticize the cultural displacement, others appreciate the infrastructure. Balinese hospitality remains despite changes. The area is distinctly different from traditional Bali.",
        "cleanliness": "Canggu has typical Bali cleanliness challenges amplified by rapid development. Main streets are reasonably maintained. Beaches can have plastic waste issues, though cleanup efforts continue. Construction zones create dust and disorder. Some drainage problems exist in wet season. The developed areas maintain decent standards. Tap water isn't drinkable. The environment is presentable if not pristine.",
        "airquality": "Canggu has generally acceptable air quality, benefiting from sea breezes. Motorbike emissions create some pollution on busy roads. Construction dust affects certain areas. Burning of waste and agriculture occasionally impacts quality. The coastal location helps clear the air. The environment is less pristine than surrounding countryside but acceptable for most visitors. The ocean air is refreshing."
    },
    "ericeira": {
        "climate": "Ericeira has a Mediterranean climate with Atlantic influence. Summers (June-September) bring warm weather around 20-28°C (68-82°F) with cool ocean breezes and minimal rain. Winters are mild at 10-16°C (50-61°F) with more rain and rougher seas. Spring and autumn offer good conditions for surfing and exploring. The ocean stays cool year-round (15-20°C), requiring wetsuits most months. Mornings can be foggy.",
        "cost": "Ericeira has become pricier with its popularity but remains reasonable. Monthly costs range from €1,500-2,500 for a comfortable lifestyle. Rent for a one-bedroom apartment averages €800-1,300, with seasonal variation. Meals at local restaurants cost €8-15. Coffee culture is affordable at €1-2. Coworking spaces cost €150-300 monthly. Prices rise significantly during summer high season. Long-term rentals offer better value.",
        "wifi": "Portugal has excellent internet infrastructure, and Ericeira offers reliable connectivity. Most cafes and coworking spaces provide 50-200 Mbps connections. The town has several coworking options including Ericeira Cowork and Village Underground. Residential connections are generally good with fiber available in many areas. Mobile data through NOS or Vodafone provides strong backup. The nomad community has driven infrastructure investment.",
        "nightlife": "Ericeira's nightlife is surf-town relaxed rather than clubbing-oriented. Beach bars offer sunset drinks with ocean views. The village center has traditional bars and casual restaurants. Live music appears at various venues, especially in summer. The scene is friendly and social but winds down by midnight most nights. Those seeking bigger nights head to Lisbon (35 minutes). The vibe prioritizes early surf sessions.",
        "nature": "Ericeira is defined by its coastline and surf breaks. The town sits within a World Surfing Reserve with consistent waves year-round. Multiple beaches offer different conditions for all skill levels. Coastal walking trails provide dramatic cliff views. Sintra-Cascais Natural Park is nearby for forest hiking. The surrounding countryside has traditional farms and villages. Day trips to Peniche, Nazaré's giant waves, and Sintra palaces are popular.",
        "safety": "Ericeira is exceptionally safe with virtually no crime concerns. The small-town atmosphere and strong community create natural security. Walking alone at night is comfortable anywhere in town. Petty theft is rare. The main hazards are ocean-related—respect wave conditions and currents. The road from Lisbon requires attention. Solo travelers of all backgrounds feel completely comfortable. The relaxed environment is a major draw.",
        "food": "Ericeira offers excellent Portuguese cuisine with an emphasis on fresh seafood. Grilled fish, seafood rice, and cataplana (seafood stew) are standouts. Traditional tascas serve authentic local dishes at good prices. The surf crowd has brought healthy cafes and international options. Markets sell fresh produce and regional products. Wine culture is strong with local varieties. The mix satisfies traditional and modern palates.",
        "community": "Ericeira has developed a thriving digital nomad community alongside its surf culture. Coworking spaces serve as community hubs. The intersection of surf and work attracts remote workers seeking active lifestyles. Facebook groups and regular meetups connect the community. The scene is friendly and welcoming. Long-term nomads form close-knit groups. The town's human scale fosters genuine relationships. Summer brings larger crowds.",
        "english": "English proficiency in Ericeira is excellent, particularly among younger Portuguese and the international community. Tourism and surf culture have established English as common. All restaurants and services handle English easily. The nomad community operates in English by default. Learning Portuguese is appreciated and enhances cultural connection. Signs and menus are typically bilingual. The environment is very English-friendly.",
        "visa": "Portugal is part of the Schengen Area, allowing visa-free stays of up to 90 days within a 180-day period for citizens of many countries. Portugal offers a digital nomad visa requiring proof of remote income (minimum €3,040/month) and health insurance. The D7 visa for passive income holders is another popular option. Portugal has become one of Europe's most nomad-friendly countries with clear pathways to residency.",
        "culture": "Ericeira blends traditional Portuguese fishing village character with international surf culture. The historic center preserves whitewashed buildings and local traditions. Fishing boats still launch from the harbor. Surf has been central since the 1960s and defines contemporary identity. The international community has added cosmopolitan elements while respecting local character. Portuguese hospitality welcomes visitors warmly.",
        "cleanliness": "Ericeira is very clean, reflecting Portuguese standards and community pride. Streets are swept regularly. Beaches are well-maintained with lifeguards during season. The village center is tidy and well-preserved. Public spaces are kept in good condition. Some construction areas show temporary messiness. Tap water is safe to drink. The overall environment is pleasant and well-cared-for.",
        "airquality": "Ericeira has excellent air quality, benefiting from Atlantic breezes and minimal industry. The coastal location ensures fresh, clean air constantly. Traffic is light compared to cities. No pollution sources affect the area. The air feels remarkably fresh, especially along the coastline. The environment is one of the cleanest in Europe. Many visitors note the air quality improvement from urban origins."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")

    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
