#!/usr/bin/env python3
"""Rewrite batch 7: Major cities D-H (dubai, dublin, florence, hanoi, hongkong)."""

import json
import os

BATCH_CITIES = {
    "dubai": {
        "climate": "Dubai has a hot desert climate with scorching summers (35-45°C, June-September) and pleasant winters (18-28°C, November-March). Summer is brutal—outdoor activity is limited to air-conditioned spaces or early morning/evening. Humidity adds to summer discomfort. Winter is ideal with perfect beach weather. Rain is rare—only a few days per year. Air conditioning is essential and ubiquitous.",
        "cost": "Dubai can be expensive or reasonable depending on lifestyle. A comfortable nomad lifestyle costs $2,500-4,000/month. Apartments range $1,200-2,500/month. Dining varies wildly—street food for $5 or fine dining for $100+. Alcohol is expensive. Transportation is cheap via metro. The tax-free environment and varying neighborhoods allow budget flexibility. Luxury is available; modest living is possible.",
        "wifi": "UAE has invested heavily in digital infrastructure. Dubai offers excellent speeds of 100+ Mbps. Free public WiFi covers many areas. Hotels and cafes provide strong connections. Note that VoIP services (WhatsApp calls, FaceTime, Skype) are restricted—VPNs are necessary. 5G coverage is extensive. Coworking spaces provide reliable connectivity. Overall infrastructure is excellent.",
        "nightlife": "Dubai's nightlife centers on licensed venues—hotels and clubs. The scene is glamorous with rooftop bars, beach clubs, and mega-clubs featuring international DJs. Ladies' nights offer free drinks for women. The dress code tends toward upscale. Alcohol is expensive and only served in licensed venues. The scene is vibrant and international but operates within cultural constraints.",
        "nature": "Dubai is a city built in the desert. The beaches are the primary natural attraction—clean, maintained, and warm most of the year. Desert safaris offer dune driving and camel encounters. The Hajar Mountains are accessible for hiking. Marine life includes snorkeling and diving. The Dubai Miracle Garden creates artificial nature. Natural nature requires leaving the city.",
        "safety": "Dubai is one of the world's safest cities. Crime rates are extremely low. The city is heavily monitored with strict law enforcement. You can walk anywhere at any time. The main concerns are strict laws—public behavior, alcohol, and relationships are regulated differently than in Western countries. Follow local rules. Traffic requires attention. Emergency services are excellent.",
        "food": "Dubai's food scene reflects its cosmopolitan population. Arabic food—hummus, shawarma, grilled meats—is excellent. Indian and Pakistani communities ensure outstanding subcontinental options. Filipino, Chinese, and every global cuisine is represented. High-end dining is world-class. Brunch culture is huge. The variety and quality span all price points. Ramadan affects daytime eating availability.",
        "community": "Dubai's population is 90% expatriate, creating a massive international community. Different nationalities cluster in certain areas and industries. The nomad and entrepreneur community is significant. Networking events are constant. Connections form easily among the transient professional population. The community is dynamic but can feel surface-level due to high turnover. Long-term relationships require effort.",
        "english": "English is the de facto language of Dubai, spoken by the vast majority of residents. Business, services, and daily life function in English. Signs are bilingual. Arabic is official but not necessary for most interactions. Only in traditional markets might English be limited. The multicultural environment makes Dubai extremely accessible.",
        "visa": "UAE has become more accessible for remote workers. Tourist visas (30-90 days) are available for most nationalities. Dubai offers a Remote Work Visa (one year) for those earning $3,500+/month. The golden visa provides 10-year residence for qualifying individuals. Free zone freelancer visas allow self-employment. The system has evolved to welcome international workers.",
        "culture": "Dubai blends Emirati tradition with international modernity. The gold souks and historic Al Fahidi district preserve heritage. The modern skyline—Burj Khalifa, Palm Jumeirah—represents ambition. Islam shapes the culture, with Friday prayers and Ramadan being significant. Respect for local customs is expected. The culture is commercial and forward-looking, with less emphasis on history than nearby regions.",
        "cleanliness": "Dubai is immaculately clean. Streets are constantly maintained, beaches are cleaned daily, and infrastructure is pristine. Littering carries heavy fines. The wealth and governance model ensure exceptional standards. Air conditioning keeps indoor spaces fresh. Even construction sites maintain tidiness. The overall impression is of a polished, well-managed city.",
        "airquality": "Air quality in Dubai varies. Winter enjoys good conditions (AQI 30-60). Summer can see elevated levels due to dust storms and haze, sometimes exceeding 100 AQI. The desert environment means dust is constant. Indoor air quality is excellent thanks to universal air conditioning. The coastal position provides some relief. Monitor conditions during summer months."
    },
    "dublin": {
        "climate": "Dublin has a temperate oceanic climate with mild temperatures year-round. Summers are cool (15-20°C), winters are chilly but rarely freezing (3-8°C). Rain is frequent—perhaps 150+ days per year—though often light drizzle rather than heavy storms. Gray skies are common. Summer brings long daylight hours. The climate is notoriously changeable—'four seasons in one day' is real. Always pack layers and rain gear.",
        "cost": "Dublin has become one of Europe's most expensive cities. A comfortable lifestyle costs €2,800-4,000/month. Apartments are extremely scarce and expensive, ranging €1,500-2,500/month for modest options. Restaurant meals cost €20-35. Pints are €6-8. The housing crisis is acute. Tech salaries reflect costs but nomads earning elsewhere face challenges. Budget carefully.",
        "wifi": "Ireland has good internet infrastructure. Dublin offers speeds of 50-100+ Mbps, with fiber widely available. Cafes typically offer WiFi. Coworking spaces provide reliable connections. Mobile coverage is excellent through Vodafone, Three, or Eir. The tech industry presence ensures modern connectivity. Ireland's EU membership means no roaming charges within Europe.",
        "nightlife": "Irish pub culture is the heart of Dublin nightlife. Traditional pubs with live music create authentic experiences—Temple Bar is touristy but atmospheric. The scene extends to craft cocktail bars, live music venues, and clubs. Comedy is strong. The Irish social rhythm centers on the pub as living room. The scene is friendly and inclusive. Nights start earlier than southern Europe.",
        "nature": "Dublin itself is urban but nature is accessible. Phoenix Park is one of Europe's largest city parks. The coast at Howth and Dalkey offers cliff walks. The Wicklow Mountains are an hour south with hiking and scenery. The Wild Atlantic Way begins a few hours away. Ireland's green landscapes are the draw. Day trips reveal the country's natural beauty easily.",
        "safety": "Dublin is generally safe but has seen increases in certain crimes. The city center at night can feel rough in areas—O'Connell Street has issues. Petty theft occurs in tourist areas. Most neighborhoods are safe. Walking at night requires some awareness. The Irish are famously friendly. Standard urban precautions apply. Violence against tourists is rare.",
        "food": "Irish food has evolved beyond its utilitarian reputation. Traditional dishes—Irish stew, full Irish breakfast, soda bread—remain comforting. The seafood is excellent. The restaurant scene has modernized with excellent contemporary Irish cuisine. Ethnic food is increasingly diverse. Food markets showcase quality produce. The food scene has improved dramatically in recent decades.",
        "community": "Dublin has a significant tech and international community, driven by major companies' European headquarters. The nomad community is smaller than some hubs but present. Coworking spaces host events. The tech scene provides professional networking. Irish sociability makes connections easy. The pub serves as community center. The scene is established if expensive.",
        "english": "Dublin is native English-speaking, making daily life straightforward. Irish (Gaelic) exists but is rarely necessary. Irish English has distinct expressions and rhythms—you'll learn them quickly. Communication is effortless. The Irish gift for conversation makes social integration natural.",
        "visa": "Ireland is in the EU but not Schengen—it has separate visa rules. EU citizens have freedom of movement. Non-EU visitors can stay 90 days on tourist stamps. Ireland offers various work permits but no specific digital nomad visa. The tech industry facilitates many work arrangements. The system favors employed positions over freelance.",
        "culture": "Irish culture is defined by storytelling, music, and social connection. The pub is the heart of community life—conversations over pints are how Ireland works. Literary heritage runs from Joyce to Heaney. Traditional music sessions happen organically. The Irish humor is self-deprecating and quick. Despite modernization and tech wealth, traditional culture remains strong. The craic (fun, good times) is the goal.",
        "cleanliness": "Dublin's cleanliness is moderate. City center can feel gritty, particularly around certain areas. Georgian squares and southern suburbs are well-maintained. Public transport is reasonably clean. Parks are good. Tap water is excellent. The city has faced challenges with homelessness visible in the center. Tourist areas are maintained; some residential areas vary.",
        "airquality": "Air quality in Dublin is generally good, with AQI typically 20-50. Atlantic winds keep air fresh. Traffic affects central areas. The maritime climate ensures air circulation. Some winter evenings see elevated levels with heating emissions. Overall, the air quality benefits from Ireland's natural environment and relatively light industry."
    },
    "florence": {
        "climate": "Florence has a humid subtropical climate with hot summers (28-35°C) and cool winters (3-10°C). Summer can be sweltering in the city center with limited breeze. Winter is mild but damp, with occasional cold snaps. Spring and autumn are ideal—comfortable temperatures for walking the historic center. The surrounding Tuscan hills offer cooler escapes in summer. Pack for seasonal variation.",
        "cost": "Florence is expensive for its size, driven by tourism and limited supply. A comfortable lifestyle costs €2,000-3,000/month. Apartments are hard to find and pricey, ranging €900-1,500/month in the center. Restaurant meals cost €15-25 in tourist areas; trattorias offer better value. The Oltrarno neighborhood is slightly cheaper. Tuscan living comes at a premium.",
        "wifi": "Italian internet has improved, and Florence is adequately connected. Average speeds are 30-70 Mbps. WiFi availability in cafes varies—Italian cafe culture prioritizes conversation over laptops. Coworking spaces like Impact Hub provide reliable connections. Mobile data through TIM, Vodafone, or WindTre offers backup. Connectivity is sufficient though not cutting-edge.",
        "nightlife": "Florence's nightlife is refined rather than wild. The Santo Spirito area in Oltrarno hosts aperitivo and late-night bars. Summer brings outdoor drinking and socializing. Wine bars are everywhere. The scene caters to all ages—students ensure some energy. The scale is intimate compared to larger cities. The focus is on conversation and wine more than clubbing.",
        "nature": "Florence sits in the Arno valley surrounded by Tuscan hills. The hills around Fiesole offer walking and views. The Tuscan countryside—Chianti, Val d'Orcia—is magnificent and accessible for day trips. The Apennine mountains are close. Beaches are 1.5 hours away. The nature is cultivated and beautiful—olive groves, vineyards, cypress trees. The landscape is integral to Tuscany's identity.",
        "safety": "Florence is very safe with low violent crime. Pickpocketing is common in tourist areas—the Duomo, train station, and buses require vigilance. Keep bags secure and be aware in crowds. Scams targeting tourists exist. Walking at night is comfortable throughout the center. Italian cities are generally safe. Standard awareness protects against petty theft.",
        "food": "Tuscan cuisine is simple, ingredient-focused, and exceptional. Bistecca alla fiorentina (T-bone steak), ribollita (bread soup), and lampredotto (tripe sandwich) are local specialties. Pasta here is often simpler than southern Italy. The Mercato Centrale showcases ingredients. Chianti and Brunello wines are obligatory. Trattorias offer better value than tourist-strip restaurants. The food is a major reason to be here.",
        "community": "Florence has a significant international community, including art students, academics, and retirees. The nomad community is smaller—the city attracts more traditional expats. Connections form through cultural events, language schools, and neighborhood life. Florentines can be reserved but warm once connected. The compact size makes community intimate. The scene is cultural and artistic.",
        "english": "English is spoken in tourism and with younger Florentines. Hotels and tourist restaurants manage in English. Outside tourist zones, Italian becomes necessary. The city's international student population helps. Learning Italian significantly enriches the experience and earns respect. Daily life is manageable in English but limited.",
        "visa": "Italy is part of the EU and Schengen. EU citizens have freedom of movement. Non-EU visitors stay 90 days within Schengen. Italy offers an elective residence visa for those with income. Work visas require sponsorship. The bureaucracy is notoriously challenging but navigable. Italy doesn't have a specific digital nomad visa.",
        "culture": "Florence is where the Renaissance happened. The concentration of art and architecture is unmatched—the Uffizi, Duomo, Palazzo Pitti, Michelangelo's David. Walking the streets is a museum experience. The artisan traditions continue in Oltrarno workshops. Opera, fashion, and craftsmanship define the cultural scene. The weight of history is omnipresent. Living here means immersion in Western cultural heritage.",
        "cleanliness": "Florence maintains good standards in the historic center. Streets are cleaned, monuments are preserved. Tourism pressure creates challenges. Some areas show wear. Tap water is safe. The city makes significant preservation efforts. The compact center is generally well-maintained. Standards are reasonable for an Italian city.",
        "airquality": "Air quality in Florence can be challenged by the valley location. AQI typically ranges 30-70. Summer heat and traffic create higher levels. Winter inversions can trap pollution. The surrounding hills contain air flow. Spring and autumn are generally better. The situation is typical for northern Italian cities in valleys."
    },
    "hanoi": {
        "climate": "Hanoi has a humid subtropical climate with four seasons. Summers (May-September) are hot and humid (28-35°C) with heavy monsoon rains. Winters (November-February) are surprisingly cold and damp (10-20°C)—pack warm clothes. Spring and autumn are pleasant. The drizzly winter can feel colder than temperatures suggest. Each season has distinct character.",
        "cost": "Hanoi offers exceptional value. A comfortable lifestyle costs $800-1,400/month. Apartments range $300-600/month, with serviced options available. Local food is incredibly cheap ($1-3), with quality restaurant meals at $5-12. The Old Quarter is pricier; outer districts offer better value. Vietnam's low cost of living makes extended stays financially easy.",
        "wifi": "Vietnam has good internet infrastructure. Hanoi offers speeds of 30-80 Mbps commonly. Cafes—especially the many nomad-friendly spots—provide WiFi. Coworking spaces like Toong and UP offer reliable connections. Mobile data through Viettel, Mobifone, or Vinaphone is cheap and reliable. Some sites are blocked, requiring VPN. Connectivity supports remote work well.",
        "nightlife": "Hanoi's nightlife differs from Ho Chi Minh City's party scene. The Old Quarter's 'Bia Hoi corner' features tiny plastic chairs and cheap draft beer—an essential Hanoi experience. Rooftop bars offer sophistication. Live music venues showcase Vietnamese and international acts. The scene is atmospheric and social rather than clubbing-focused. It shuts down earlier than southern Vietnam.",
        "nature": "Hanoi is urban but nature escapes are accessible. West Lake provides waterfront walking and cafes. Day trips reach stunning landscapes—Ha Long Bay (UNESCO site), Ninh Binh (karst mountains), and Sapa (mountain trekking). The Red River provides some green space. Vietnam's natural diversity is a major draw, easily accessed from Hanoi.",
        "safety": "Hanoi is generally safe with low violent crime. Traffic is the main danger—crossing streets requires courage and technique (walk steadily, don't stop). Petty theft is uncommon but keep awareness in tourist areas. Scams are rare. Vietnamese people are friendly and helpful. The atmosphere is chaotic but not threatening. Standard awareness is sufficient.",
        "food": "Vietnamese cuisine is outstanding, and Hanoi is its cultural heart. Pho (noodle soup), bun cha (grilled pork), banh mi (sandwiches), and egg coffee are local specialties. Street food is excellent and incredibly cheap. The food scene has depth—from street vendors to fine dining. Every meal is an adventure. The freshness and flavors make eating the highlight of Hanoi life.",
        "community": "Hanoi has a smaller nomad community than Ho Chi Minh City but it's growing. Coworking spaces serve as hubs. The community tends toward longer-term residents who appreciate the slower pace. Connections form through work spaces and expat venues. Vietnamese friendships take time but are genuine. The scene is intimate and established.",
        "english": "English is spoken in tourist areas and among younger Vietnamese. Hotels, restaurants, and services in tourist zones manage in English. Outside these areas, Vietnamese becomes necessary. The language barrier is real but manageable. Translation apps help. Learning basic Vietnamese phrases improves daily life significantly.",
        "visa": "Vietnam offers e-visas (30 days) for many nationalities and visa on arrival options. Extensions are possible with some bureaucracy. Vietnam doesn't have a specific digital nomad visa. Most nomads work on tourist visas in gray areas. Visa runs are common practice. The system is relatively accessible for medium-term stays.",
        "culture": "Hanoi is Vietnam's cultural and political capital. The Old Quarter's 1,000-year history is visible in the narrow streets. French colonial architecture blends with Vietnamese tradition. Temples and pagodas punctuate the cityscape. Communist history is present—Ho Chi Minh's mausoleum is central. Traditional water puppetry continues. The culture is more reserved than southern Vietnam—dignified and historical.",
        "cleanliness": "Hanoi's cleanliness is variable. The Old Quarter is chaotic with narrow streets and visible infrastructure challenges. Newer areas and tourist zones are better maintained. Street food hygiene is generally good—eat where locals eat. Tap water should be avoided. The situation is typical for developing Southeast Asia—functional rather than pristine.",
        "airquality": "Air quality in Hanoi can be challenging, with AQI often 50-150 and worse during certain periods. Traffic, construction, and coal burning contribute. Winter inversions trap pollution. Some days require masks. The government is addressing the issue but progress is slow. Sensitive individuals should monitor conditions and consider air purifiers."
    },
    "hongkong": {
        "climate": "Hong Kong has a humid subtropical climate with hot, humid summers (28-33°C, June-August) and mild winters (14-20°C, December-February). Summer brings typhoon season and heavy rain. Spring and autumn are pleasant with moderate temperatures. The humidity is intense—air conditioning is universal. Winter can feel cold in unheated buildings. The climate has distinct seasonal character.",
        "cost": "Hong Kong is one of the world's most expensive cities. A comfortable lifestyle costs HK$25,000-40,000/month ($3,200-5,100). Apartments are notoriously small and expensive, ranging HK$15,000-25,000/month for modest options. Restaurant meals cost HK$80-200. The cost of space is the killer. Eating out is relatively affordable; housing is extreme.",
        "wifi": "Hong Kong has excellent internet infrastructure—among the world's best. Speeds of 200+ Mbps are common. Public WiFi is widespread. The city is hyper-connected. Coworking spaces provide premium connectivity. Mobile data is excellent with competitive providers. Internet is unrestricted unlike mainland China. Hong Kong is fully equipped for remote work.",
        "nightlife": "Hong Kong's nightlife is vibrant and varied. Lan Kwai Fong (LKF) is the famous party district. Soho has sophisticated bars. Wan Chai offers everything from dive bars to clubs. Rooftop venues overlook the skyline. The scene runs late, especially on weekends. The mix of international and local creates diversity. Few cities match Hong Kong's concentrated nightlife energy.",
        "nature": "Despite the urban density, Hong Kong offers surprising nature access. Country parks cover 40% of the territory. The Dragon's Back trail is world-class with city views. Beaches on the outlying islands provide escapes. Lantau Island has hiking and the Big Buddha. The contrast between urban intensity and natural beauty is striking and accessible by public transport.",
        "safety": "Hong Kong is extremely safe—one of Asia's safest cities. Violent crime is rare. Petty theft is uncommon. You can walk anywhere at any time. The city is heavily monitored. Political situations may create temporary concerns, but personal safety for visitors remains high. The MTR is safe and efficient. Standard awareness is all that's needed.",
        "food": "Hong Kong's food scene is phenomenal. Cantonese cuisine is the base—dim sum is essential and excellent. International options span every cuisine at every price point. Street food in Mong Kok, roast meat in Kowloon, fine dining in Central. Michelin stars coexist with hole-in-the-wall legends. The food quality and variety rival any city globally. Eating is central to Hong Kong culture.",
        "community": "Hong Kong has a massive and established international community. Finance, trade, and business draw professionals globally. The nomad community exists within this broader expat scene. Coworking spaces host events. Networking opportunities are abundant. The fast pace means relationships can be transactional. Long-term community takes effort amid the bustle.",
        "english": "English is official alongside Chinese (Cantonese). Business and professional life function in English. Signs and services are bilingual. You can live entirely in English. Outside business contexts and with older residents, Cantonese helps. The colonial legacy and international population ensure excellent English access.",
        "visa": "Hong Kong has separate immigration from mainland China. Many nationalities can stay 90-180 days visa-free. Work visas require sponsorship and specific qualifications. Investment visas exist. The city doesn't have a digital nomad visa. The 'one country, two systems' creates distinct rules from China. Entry is generally straightforward for short to medium stays.",
        "culture": "Hong Kong culture blends Chinese tradition with international influences. Cantonese identity is strong. The pace is relentless—efficiency is a cultural value. Temple visits coexist with corporate life. Shopping and eating are cultural activities. The handover from Britain in 1997 and recent political tensions have shaped identity. The culture is distinctive—neither fully Chinese nor Western.",
        "cleanliness": "Hong Kong is very clean by Asian standards. Streets are regularly cleaned despite the density. The MTR is spotless. Buildings and public spaces are well-maintained. Tap water is safe. The city takes cleanliness seriously. Some older areas show wear, but overall standards are high.",
        "airquality": "Air quality in Hong Kong varies, with AQI typically 30-80. Pollution from mainland China, local traffic, and shipping affects quality. Some days see higher levels, requiring attention. The government monitors and reports conditions. Sea breezes help. The situation has improved but remains a consideration. Sensitive individuals should check daily readings."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
