#!/usr/bin/env python3
"""Rewrite batch 6: Major cities B-C (budapest, buenosaires, capetown, chiangmai, copenhagen)."""

import json
import os

BATCH_CITIES = {
    "budapest": {
        "climate": "Budapest has a continental climate with hot summers (25-32°C) and cold winters (-2 to 5°C). Summer brings heat waves occasionally exceeding 35°C. Winter can be gray and cold, with occasional snow. Spring and autumn are pleasant with moderate temperatures—ideal for exploring. The Danube creates some humidity. Each season has distinct character, with summer being most popular.",
        "cost": "Budapest offers exceptional value for a European capital. A comfortable lifestyle costs €1,200-1,800/month. Apartments range €500-900/month in central areas. Restaurant meals cost €8-15, with traditional Hungarian spots even cheaper. Thermal baths are affordable ($15-20). Nightlife is cheap. The value attracts nomads looking for European culture at affordable prices.",
        "wifi": "Hungary has good internet infrastructure. Budapest offers speeds of 50-100 Mbps commonly, with fiber available in many areas. WiFi is standard in cafes and restaurants. Coworking spaces like Loffice and Kaptar provide excellent connectivity. Mobile data through Vodafone, Telekom, or Telenor is reliable. The city fully supports remote work.",
        "nightlife": "Budapest's nightlife is famous, particularly the 'ruin bars' in the Jewish Quarter. Szimpla Kert started the trend—bars in abandoned buildings with eclectic decor. The scene has expanded to clubs, rooftops, and sophisticated cocktail spots. Sparty parties combine thermal baths and clubbing. The Danube embankment comes alive in summer. The scene is diverse, affordable, and runs very late.",
        "nature": "Budapest itself offers green escapes—Margaret Island is a recreational haven in the Danube. The Buda Hills provide hiking and views. Day trips reach the Danube Bend, Lake Balaton, and wine regions like Eger and Tokaj. The caves beneath the city offer unique exploration. Hungary's nature is gentle—rolling hills, lakes, and thermal landscapes rather than dramatic mountains.",
        "safety": "Budapest is very safe by capital city standards. Violent crime is rare, and the atmosphere is relaxed. Pickpocketing can occur in tourist areas and on public transport—standard precautions apply. Scams targeting tourists exist around major attractions. The city is LGBTQ+ friendly in practice. Walking at night is comfortable throughout central areas. Standard urban awareness is sufficient.",
        "food": "Hungarian cuisine is hearty and flavorful. Goulash soup is the classic, but paprikash, töltött káposzta (stuffed cabbage), and lángos (fried dough) are equally iconic. Food markets like Great Market Hall showcase ingredients. The restaurant scene has evolved with excellent modern Hungarian cuisine. Jewish food traditions remain strong. Portions are generous, prices are fair, and quality is high.",
        "community": "Budapest has a significant and growing nomad community. Coworking spaces host regular events and meetups. The city attracts digital nomads, entrepreneurs, and remote workers. The community is diverse—Eastern European accessibility draws varied nationalities. Connections form through work spaces, ruin bar socializing, and organized events. The scene is established but still intimate enough for genuine relationships.",
        "english": "English is widely spoken among younger Hungarians and in tourist/business contexts. Hotels, restaurants, and services function in English. Outside central areas and with older generations, Hungarian becomes necessary—and it's notoriously difficult. Learning basic phrases earns appreciation. University students often speak excellent English. Daily life in English is manageable in central Budapest.",
        "visa": "Hungary is part of the EU and Schengen. EU citizens have freedom of movement. Non-EU visitors stay 90 days within Schengen. Hungary offers a 'White Card' residence permit for digital nomads (requiring proof of remote work and income). The bureaucracy can be slow but processes exist. Hungary's EU membership provides Schengen access from outside the Union.",
        "culture": "Budapest's culture blends Austro-Hungarian grandeur with contemporary creativity. The thermal bath culture is unique—historic bathhouses like Gellért and Széchenyi are architectural treasures and social spaces. Music ranges from classical (the opera house is magnificent) to ruin bar DJ sets. Architecture spans Art Nouveau, baroque, and socialist brutalism. The coffee house tradition continues. The city is romantic, historic, and increasingly modern.",
        "cleanliness": "Budapest maintains good standards for a major city. The historic center is regularly cleaned. Public transport is functional and reasonably clean. Ruin bars embrace grittiness as aesthetic. Parks and tourist areas are well-maintained. Tap water is safe. Some residential areas show wear. The city makes visible efforts, particularly in tourist-facing areas.",
        "airquality": "Air quality in Budapest is moderate, with AQI typically 30-70. Traffic and winter heating affect quality. The Danube valley can trap pollution. Some industrial activity on the outskirts contributes. Summer generally sees better air. Sensitive individuals may notice differences from cleaner cities. The situation is typical for Central European capitals."
    },
    "buenosaires": {
        "climate": "Buenos Aires has a humid subtropical climate with hot summers (25-35°C, December-February) and mild winters (10-17°C, June-August). Humidity can be oppressive in summer. Winter is pleasant though buildings lack central heating, making indoors cold. Spring (September-November) and autumn (March-May) are ideal. Rain is possible year-round. The climate is generally comfortable with distinct seasons.",
        "cost": "Argentina's economic volatility creates unusual value for foreign currency holders. A comfortable lifestyle costs $1,000-1,800/month at blue dollar rates. Apartments range $400-900/month. Restaurant meals cost $5-15, with parrillas offering excellent meat. The official vs. parallel exchange rate creates complexity. For those earning in dollars or euros, Buenos Aires offers exceptional value. Currency situation changes constantly.",
        "wifi": "Argentina's internet is decent, with Buenos Aires offering speeds of 30-80 Mbps. WiFi is common in cafes and restaurants. Fiber has expanded in recent years. Coworking spaces provide reliable connections. Mobile data through Movistar, Claro, or Personal offers backup. Power outages can affect connectivity, particularly in summer during air conditioning demand peaks.",
        "nightlife": "Buenos Aires' nightlife is legendary and starts late—dinner at 10pm, clubs at 2am. Palermo has trendy bars and clubs. San Telmo offers tango venues from tourist shows to authentic milongas. The electronic music scene is strong. Rooftop bars overlook the city. The porteño social rhythm means evenings extend into early morning. Few cities match the nocturnal energy.",
        "nature": "Buenos Aires is flat and urban with limited natural escapes. The Costanera and Reserva Ecológica provide waterfront access. Day trips reach the Tigre Delta, a maze of islands and waterways. Weekends away reach Uruguay's beaches (Colonia is an easy ferry), Atlantic coast towns like Mar del Plata, and the pampas. Patagonia and Iguazu Falls require flights but are spectacular.",
        "safety": "Buenos Aires requires urban awareness. Petty theft and mugging occur, particularly in tourist areas and at night. Keep valuables secure, avoid showing expensive items, and be alert in less-traveled areas. Violent crime is less common but exists. Certain neighborhoods (La Boca outside Caminito, Villa 31) require caution. Most visitors have safe experiences with reasonable precautions.",
        "food": "Argentine cuisine centers on beef—the parrilla (grill) is a religion. Asado (barbecue) is a social institution. Beyond meat, empanadas, milanesas, and Italian-influenced pasta are staples. Pizza in Buenos Aires has its own style. The café culture includes excellent espresso and facturas (pastries). Malbec wine is obligatory. The food is hearty, social, and excellent value.",
        "community": "Buenos Aires has a vibrant expat and nomad community. The weak peso has attracted digital nomads seeking value. Palermo and Recoleta have English-speaking communities. Coworking spaces host events. Tango brings people together, as do language exchanges. Argentines are warm and social once connected. The community is diverse—entrepreneurs, creatives, and remote workers.",
        "english": "English is less widely spoken than in European cities. Tourist areas and upscale establishments manage in English. Young professionals often have functional English. However, Spanish significantly improves daily life and is necessary for genuine integration. Porteño Spanish has distinct accent and slang. Learning Spanish here is affordable and rewarding.",
        "visa": "Argentina offers visa-free entry for most Western nationalities (90 days). Extensions are possible at immigration or via border trips to Uruguay. Argentina has introduced a digital nomad visa (Rentista visa) with income requirements. The bureaucracy can be challenging. Many nomads work around visa requirements through regular exits. The country is generally accessible.",
        "culture": "Argentine culture is passionate—about politics, football, and life. Tango remains central to identity, from tourist shows to authentic milongas. Psychoanalysis has deep roots—Buenos Aires has more psychologists per capita than anywhere. Café culture invites lingering conversations. The European-immigrant heritage creates a distinct Latin American flavor. Peronism and Maradona remain touchstones. The culture is intellectual, emotional, and engaging.",
        "cleanliness": "Buenos Aires' cleanliness varies by neighborhood. Recoleta and Puerto Madero are well-maintained. Some areas face challenges with infrastructure and waste management. Dog waste on sidewalks is a notable issue. Tap water is safe in central areas. Economic challenges have affected civic maintenance. Tourist areas are generally acceptable; residential areas vary.",
        "airquality": "Air quality in Buenos Aires is moderate, with AQI typically 30-70. Traffic emissions are the main source. The flat, humid geography can trap pollution. Some industrial activity affects certain areas. Summer heat can elevate levels. The situation is manageable but noticeable. Sensitive individuals should monitor conditions during temperature inversions."
    },
    "capetown": {
        "climate": "Cape Town has a Mediterranean climate with warm, dry summers (20-28°C, December-February) and cool, wet winters (8-17°C, June-August). The famous 'Cape Doctor' wind blows in summer, keeping things fresh but occasionally intense. Seasons are reversed from the Northern Hemisphere. Spring (September-November) sees wildflowers; autumn has ideal weather. The climate is generally pleasant with distinct seasonal character.",
        "cost": "Cape Town offers excellent value for a world-class destination. A comfortable lifestyle costs $1,200-2,200/month. Apartments range $500-1,200/month depending on area. Restaurant meals cost $8-20, with wine exceptional and affordable. The rand exchange rate favors foreign currencies. Load shedding (power outages) affects calculations—accommodation with backup power may cost more.",
        "wifi": "South African internet infrastructure varies. Cape Town offers speeds of 30-100 Mbps where fiber is available. Load shedding (scheduled power outages) significantly impacts connectivity—accommodations with generators or solar maintain service. Coworking spaces prioritize backup power. Mobile data through Vodacom or MTN provides backup. Internet is good when there's power; planning around outages is essential.",
        "nightlife": "Cape Town's nightlife is diverse. Long Street is the backpacker strip with bars and clubs. The V&A Waterfront has upscale options. Camps Bay offers beach bars with sunset views. The wine regions host evening events. Township jazz creates authentic experiences. The scene varies by neighborhood and caters to all preferences. Summer nights are particularly vibrant.",
        "nature": "Cape Town's natural setting is spectacular. Table Mountain dominates the city—cable car or hike to the top. The Cape Peninsula extends to the Cape of Good Hope with dramatic coastal drives. Beaches range from Atlantic cold (Camps Bay) to Indian Ocean warm (Muizenberg). Wine regions like Stellenbosch and Franschhoek are day trips. Marine life includes penguins, seals, and seasonal whale watching. Nature here is world-class.",
        "safety": "Safety in Cape Town requires serious attention. Crime rates are high, and violent crime occurs. Know which areas are safe and which to avoid. Don't walk alone at night in most areas. Use Uber rather than walking. Stay in safer neighborhoods (City Bowl, Waterfront, Camps Bay). Township visits should be guided. With awareness and precautions, most visitors are fine, but complacency is dangerous.",
        "food": "Cape Town's food scene is world-class. The Cape Malay influence brings distinctive flavors. Seafood is excellent—don't miss fresh fish and chips. The braai (barbecue) culture is sacred. The wine regions offer paired dining experiences. Farmers' markets showcase local produce. Restaurants range from casual to Michelin-worthy. Quality ingredients, creative chefs, and affordable prices create an outstanding food city.",
        "community": "Cape Town has a significant international community, including many digital nomads attracted by value, weather, and nature. Coworking spaces like Workshop 17 host events. The tech and creative scenes are growing. The community is diverse though somewhat segregated by background. Load shedding becomes a shared bonding experience. Connections form through work spaces, outdoor activities, and social events.",
        "english": "English is widely spoken in Cape Town—one of South Africa's 11 official languages. Business, media, and urban life function in English. Afrikaans and Xhosa are also common. Communication is straightforward for English speakers. South African English has distinct expressions and accent. The language situation makes Cape Town highly accessible.",
        "visa": "South Africa offers visa-free entry (90 days) for many Western nationalities. Extensions can be arranged but involve bureaucracy. South Africa doesn't have a specific digital nomad visa. Business and work visas require sponsorship. Many nomads work on tourist visas in gray areas. The country is generally accessible for medium-term stays.",
        "culture": "Cape Town's culture reflects South Africa's complex history and diversity. Post-apartheid transformation continues to shape society. The art scene is vibrant, with galleries and street art. Music spans jazz, kwaito, and international genres. The wine culture has deep roots. Township culture exists alongside suburban life—a visible inequality that's confronting but important. The culture is dynamic, resilient, and creative.",
        "cleanliness": "Cape Town maintains good standards in tourist and affluent areas. The City Bowl and Waterfront are well-maintained. Beaches are cleaned. Some areas face infrastructure challenges. Water scarcity (recent droughts) has affected services. Load shedding creates municipal challenges. Tourist-facing areas maintain high standards; residential areas vary significantly by neighborhood.",
        "airquality": "Air quality in Cape Town is generally good, with AQI typically 20-50. Sea breezes and the Cape Doctor wind keep air fresh. Industrial activity is limited in the city center. Winter can see temperature inversions trapping pollution. Occasional dust from surrounding areas affects quality. Overall, the air quality benefits from the natural setting and coastal position."
    },
    "chiangmai": {
        "climate": "Chiang Mai has three seasons: hot (March-May, 30-40°C), rainy (June-October), and cool (November-February, 15-25°C). The cool season is ideal—comfortable temperatures and clear skies. Hot season is brutal, though mountains provide some relief. Rainy season brings daily showers, usually brief. The burning season (February-April) creates severe smoke issues. Climate significantly impacts quality of life.",
        "cost": "Chiang Mai is legendary for value. A comfortable lifestyle costs $800-1,400/month. Apartments range $200-500/month, with excellent options throughout. Local food costs $1-3, and quality restaurant meals are $5-10. The nomad infrastructure is affordable—coworking is $100-200/month. The cost-quality ratio is exceptional, making extended stays financially easy.",
        "wifi": "Thailand's internet infrastructure is excellent. Chiang Mai offers speeds of 50-100+ Mbps commonly. Coworking spaces like Punspace, CAMP, and Yellow provide reliable connections. Cafes throughout the city cater to laptop workers with good WiFi. Mobile data is cheap and reliable. The city is built for remote work with connectivity rarely being an issue.",
        "nightlife": "Chiang Mai's nightlife is more relaxed than Bangkok's. The Night Bazaar area has bars and entertainment. Nimmanhaemin is the trendy neighborhood with craft cocktails and live music. The Sunday Walking Street is more market than nightlife. Zoe in Yellow and other clubs provide dancing. The scene is sufficient but not intense—many nomads appreciate the balance with daytime productivity.",
        "nature": "Chiang Mai is surrounded by mountains and nature. Doi Suthep temple overlooks the city from its mountain. Waterfalls, hot springs, and national parks are day-trip distance. Elephant sanctuaries (ethical ones) offer encounters. Trekking and motorcycle touring through mountain villages is popular. The surrounding nature is one of Chiang Mai's biggest draws, accessible and varied.",
        "safety": "Chiang Mai is very safe. Violent crime against foreigners is extremely rare. Scooter accidents are the main danger—traffic can be challenging and helmets are essential. Petty theft is uncommon. The Thai people are friendly and helpful. The laid-back atmosphere extends to safety. Standard awareness is sufficient—most nomads feel very comfortable.",
        "food": "Northern Thai cuisine differs from central Thai—less sweet, more earthy. Khao soi (curry noodles) is the signature dish. The food markets are legendary. Western food has proliferated with the nomad scene—good coffee, brunch spots, and international options abound. Street food is incredible and cheap. The combination of authentic Thai and nomad-friendly options creates excellent eating.",
        "community": "Chiang Mai has one of the world's most established digital nomad communities. Coworking spaces are social hubs with regular events. Facebook groups coordinate meetups. The community includes developers, entrepreneurs, marketers, and creatives. Connections form instantly—the shared lifestyle creates instant common ground. The community is supportive but can feel bubble-like, somewhat separated from Thai life.",
        "english": "English is widely spoken in nomad-focused establishments. Coworking spaces, Western restaurants, and tourist areas function in English. Outside this bubble, Thai becomes more necessary. Many Thai people have some English, but communication can require patience. Learning basic Thai improves daily interactions and earns appreciation. The nomad infrastructure makes English-only life possible.",
        "visa": "Thailand offers visa-free entry (30-60 days) or visa on arrival. Extensions are possible at immigration. The Thailand Elite visa provides long-term options for those with funds. Thailand has introduced a Digital Nomad Visa (LTR) with significant income requirements ($80k+/year). Visa runs to neighboring countries remain common practice. The system is manageable for most stays.",
        "culture": "Northern Thai (Lanna) culture is distinct from central Thailand. Temples dot the old city—Wat Phra Singh and Wat Chedi Luang are highlights. The Sunday Walking Street celebrates local crafts. Buddhist traditions shape daily life. The pace is slower than Bangkok. The modern nomad scene exists alongside traditional culture, sometimes in parallel rather than integrated.",
        "cleanliness": "Chiang Mai maintains reasonable standards. The old city and Nimmanhaemin are well-kept. Infrastructure varies in other areas. Street food hygiene is generally good—eat where locals eat. Tap water should be avoided—filtered or bottled is standard. The main cleanliness issue is air quality during burning season, not physical cleanliness.",
        "airquality": "Air quality in Chiang Mai is a significant issue. Most of the year, AQI is 30-60—acceptable. But during burning season (February-April), smoke from agricultural burning creates dangerous levels, often exceeding 200 AQI. Many nomads leave during this period. The rest of the year is fine. This seasonal issue is Chiang Mai's biggest drawback."
    },
    "copenhagen": {
        "climate": "Copenhagen has a temperate oceanic climate with mild summers (17-23°C) and cold, dark winters (0-5°C). Rain is frequent year-round. Summer brings long daylight hours—sunset after 10pm. Winter is challenging with limited daylight (sunrise 8:30am, sunset 3:30pm) and gray skies. Spring and autumn are variable. The climate requires seasonal adaptation and good rain gear.",
        "cost": "Copenhagen is among the world's most expensive cities. A comfortable lifestyle costs €3,500-5,000/month. Apartments are extremely difficult to find, ranging €1,500-2,500/month. Restaurant meals cost €25-40—even casual dining is pricey. Alcohol is expensive. However, quality is exceptional, and cycling saves transport costs. Budget-conscious nomads find Copenhagen challenging.",
        "wifi": "Danish internet infrastructure is excellent. Copenhagen offers speeds of 100+ Mbps commonly, with gigabit available. Public WiFi is widespread. Cafes welcome laptop workers. Coworking spaces provide premium connectivity. Mobile coverage is excellent. The tech-forward Nordic approach ensures connectivity is never a concern. Copenhagen is fully equipped for remote work.",
        "nightlife": "Copenhagen's nightlife is sophisticated and diverse. Meatpacking District has trendy bars and clubs. Nørrebro is alternative and hip. Vesterbro offers classic Copenhagen vibes. The scene starts relatively early by European standards—Danes socialize over dinner and drinks, with clubs busy by midnight. Quality over quantity defines the approach. Summer brings outdoor drinking culture.",
        "nature": "Copenhagen integrates urban and natural spaces. The harbor is swimmable with popular swimming areas. Parks are everywhere—Fælledparken, Frederiksberg Gardens. The surrounding coast offers beaches. Day trips reach Swedish Malmö, Louisiana Museum, and North Zealand's forests and castles. Denmark's flat landscape is accessible and well-organized. Nature is incorporated into daily urban life.",
        "safety": "Copenhagen is extremely safe—among the world's safest cities. Violent crime is rare. Bikes can be left relatively unattended (though theft exists). You can walk anywhere at any time without concern. Danish society values trust and civic responsibility. Emergency services are excellent. The only 'danger' is cycling accidents—follow the rules.",
        "food": "Copenhagen has become a food destination. Noma put it on the map, and New Nordic cuisine has transformed the scene. Smørrebrød (open sandwiches) remain traditional lunch. Food halls like Torvehallerne showcase local quality. Street food has elevated with Reffen and other markets. The prices are high but quality is exceptional. Pastries at bakeries are outstanding.",
        "community": "Copenhagen has a significant international community, particularly in tech and creative industries. Coworking spaces host events. The startup ecosystem is developing. Danes can seem reserved initially but form genuine friendships over time. Expat networks provide English-speaking community. The community is sophisticated and professional. Integration into Danish society requires effort.",
        "english": "English fluency in Denmark is among the world's highest. Business, socializing, and daily life function in English. Signs and services are often bilingual. Learning Danish is appreciated but not necessary for daily life. University courses are taught in English. The high English proficiency can make learning Danish difficult—Danes switch immediately.",
        "visa": "Denmark is part of the EU and Schengen. EU citizens have freedom of movement. Non-EU visitors stay 90 days within Schengen. Denmark offers various work permits but has strict immigration requirements. The digital nomad visa options are limited. High income requirements and complex bureaucracy make long-term stays challenging for non-EU citizens.",
        "culture": "Danish culture is defined by 'hygge'—cozy contentment—and egalitarian values. Design is central to identity—Danish furniture, architecture, and lifestyle are world-renowned. Cycling isn't just transportation but culture. Work-life balance is sacred. The welfare state shapes expectations. The society is trusting and cooperative. The culture values quality of life over ostentation.",
        "cleanliness": "Copenhagen is immaculately clean. Streets are spotless, public spaces are well-maintained, and civic pride is evident. Cycling culture reduces litter from car windows. Danes expect cleanliness and enforce it socially. Public transport is pristine. Tap water is excellent. The overall impression is of meticulous civic care.",
        "airquality": "Air quality in Copenhagen is excellent, with AQI typically 15-35. Cycling culture and clean energy reduce emissions. Coastal winds keep air fresh. Industrial activity is minimal in central areas. Denmark's environmental commitment shows in air quality. The clean air complements the outdoor, cycling-based lifestyle."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
