#!/usr/bin/env python3
"""Rewrite batch 19: Dubrovnik, Riga, Vilnius, Sofia, Bucharest."""

import json
import os

BATCH_CITIES = {
    "dubrovnik": {
        "climate": "Dubrovnik has a Mediterranean climate with hot, dry summers and mild, wet winters. Summer temperatures reach 28-35°C (82-95°F) with strong sunshine and warm Adriatic waters. Winters are mild at 8-14°C (46-57°F) with periodic rain. Spring and autumn offer ideal conditions with warm weather and fewer tourists. The swimming season extends from May to October. The famous 'bura' wind can bring sudden cold snaps.",
        "cost": "Dubrovnik is Croatia's most expensive city, particularly in summer. Monthly costs range from €1,800-3,000+ for a comfortable lifestyle. Rent for a one-bedroom apartment averages €800-1,400 in the old town or nearby, though summer rentals skyrocket. Restaurant meals cost €15-30 in tourist areas, less in local spots. Coworking options are limited. Off-season prices drop significantly, making winter stays more affordable.",
        "wifi": "Croatia has good internet infrastructure, and Dubrovnik offers reliable connectivity. Most cafes and accommodations provide 30-80 Mbps connections. The old town has fewer coworking options than Zagreb. Some old stone buildings have connectivity challenges. Mobile data through A1 or T-Mobile provides strong coverage. The tourist infrastructure ensures decent WiFi availability, though dedicated work spaces are limited.",
        "nightlife": "Dubrovnik's nightlife is scenic rather than wild. Buža bars carved into cliffs outside the city walls offer sunset drinks with sea views. The old town has wine bars and cocktail lounges in historic settings. Revelin club hosts international DJs in a fortress. The scene is more sophisticated than party-focused. Summer nights have more energy. Game of Thrones fans pack themed venues. The atmosphere prioritizes beauty over intensity.",
        "nature": "Dubrovnik offers stunning coastal beauty. The old town walls provide dramatic sea and rooftop views. Lokrum Island is a 15-minute ferry ride for swimming, gardens, and peacocks. Pristine beaches like Banje and Sveti Jakov front crystal-clear water. Kayaking around the walls is popular. Day trips to Mljet National Park and Elafiti Islands reveal unspoiled nature. Montenegro's Bay of Kotor is a stunning day trip.",
        "safety": "Dubrovnik is extremely safe with virtually no violent crime. The compact old town is comfortable at all hours. Petty theft is rare but possible in crowded tourist areas. The main hazards are uneven stone streets, strong sun, and crowded conditions in summer. No neighborhoods are concerning. The tourist police are helpful and visible. Solo travelers feel completely comfortable. The atmosphere is secure and welcoming.",
        "food": "Dalmatian cuisine showcases fresh seafood and Mediterranean simplicity. Grilled fish, black risotto (cuttlefish ink), and peka (meat or octopus slow-cooked under a bell) are highlights. Fresh oysters from nearby Ston are exceptional. Olive oil and local wines accompany most meals. The old town has many tourist traps—seek out local recommendations. The Green Market sells fresh produce. Quality matches the scenic setting when you choose wisely.",
        "community": "Dubrovnik has a small digital nomad community, more visitors than long-term residents. The city is better for short stays than extended living. High costs and limited coworking limit the scene. Some nomads base here for the old town atmosphere and use it as a Croatian exploration base. The community is transient rather than established. Those seeking long-term community often move to Split or Zagreb.",
        "english": "English proficiency in Dubrovnik is excellent due to tourism. Service workers speak fluent English. Signs and menus are bilingual. Daily life operates easily in English. Croatian is appreciated but unnecessary. Younger Croatians often have excellent English skills. The tourism-dependent economy ensures smooth communication. No language barrier exists for English-speaking visitors.",
        "visa": "Croatia is part of the Schengen Area and EU, allowing visa-free stays of up to 90 days within a 180-day period for citizens of many countries. Croatia offers a digital nomad visa allowing stays up to one year, requiring proof of remote income (minimum €2,540/month). EU citizens can stay indefinitely. The visa process is straightforward for qualified applicants.",
        "culture": "Dubrovnik's culture centers on its extraordinary UNESCO-listed old town, preserved medieval walls, and maritime heritage. The city served as the Ragusa Republic for centuries, maintaining independence through diplomacy. Game of Thrones filming brought renewed fame. The summer festival fills the old town with performances. Baroque architecture, monasteries, and museums showcase rich history. The scale is intimate and walkable.",
        "cleanliness": "Dubrovnik is exceptionally clean, particularly within the old town walls. Streets are maintained meticulously for tourism. Beaches are kept tidy. The compact size makes maintenance manageable. Public spaces are well-cared-for. The sea water is crystal clear. Standards are high throughout the tourist areas. Croatia generally prioritizes cleanliness, and Dubrovnik leads the way.",
        "airquality": "Dubrovnik has excellent air quality, benefiting from coastal breezes and limited industry. The Adriatic location ensures fresh sea air. Traffic is restricted in the old town. No pollution sources affect the area. The air quality is among Europe's best. The maritime environment provides consistently clean conditions. Most visitors remark on the fresh, clean air."
    },
    "riga": {
        "climate": "Riga has a humid continental climate with warm summers and cold, dark winters. Summer temperatures reach 20-26°C (68-79°F) with long daylight hours and pleasant conditions. Winters are cold at -5 to 0°C (23-32°F) with snow and short days. Spring and autumn are transitional with variable weather. The city experiences dramatic seasonal changes. Summer from June to August is the most popular time to visit.",
        "cost": "Riga offers excellent value for a European capital. Monthly costs range from €1,200-2,000 for a comfortable lifestyle. Rent for a central one-bedroom apartment averages €500-800. Meals at local restaurants cost €8-15, while street food is cheaper. Beer costs €3-4 at bars. Public transport is affordable. Coworking spaces range from €100-250 monthly. The cost of living is significantly lower than Western Europe.",
        "wifi": "Latvia has excellent internet infrastructure, among Europe's fastest. Riga cafes and coworking spaces typically offer 50-200 Mbps connections. The city has numerous coworking options including TechHub and LIAA. Free WiFi is available in many public spaces. Mobile data through LMT or Tele2 provides strong 4G/5G coverage. Fiber connections are standard in apartments. Connectivity is exceptional for remote work.",
        "nightlife": "Riga's nightlife is vibrant, centered around the old town and Miera iela (Peace Street) in the Moscow district. Art nouveau bars and cellar clubs create atmospheric settings. The electronic music scene is strong with clubs like Piens and One One. Cocktail bars have sophisticated offerings. The scene ranges from student-friendly to upscale. Summer brings open-air events. Nights can extend late, especially on weekends.",
        "nature": "Riga offers nature access within and near the city. The extensive parks include Mežaparks with forest, beaches, and a zoo. Jūrmala beach resort is 25 minutes by train, with wide sandy beaches and pine forests. The Latvian countryside provides rural escapes with forests and lakes. Day trips to Sigulda offer river valleys and castle ruins. The Gulf of Riga moderates climate and provides maritime recreation.",
        "safety": "Riga is very safe with low crime rates. The old town and central areas are comfortable at all hours. Petty theft is rare but possible in tourist areas. Some caution is warranted in the Moscow district late at night. No violent crime concerns affect tourists. The overall atmosphere is secure and welcoming. Solo travelers feel comfortable. Latvian society is orderly and law-abiding.",
        "food": "Latvian cuisine features hearty dishes suited to the northern climate. Grey peas with bacon, black rye bread, and smoked fish are traditional staples. The Central Market (in historic Zeppelin hangars) offers fresh produce and local specialties. Modern Latvian cuisine reimagines traditions. International options have expanded significantly. The coffee and cafe culture is sophisticated. Restaurant quality has improved markedly in recent years.",
        "community": "Riga has a growing digital nomad community, attracted by affordability and connectivity. Coworking spaces host networking events. The tech startup scene is developing. The expat community includes professionals from various industries. Latvians can be initially reserved but are friendly once engaged. Language exchange and social meetups help build connections. The community is smaller than major hubs but welcoming.",
        "english": "English proficiency in Riga is good among younger people and professionals. Service workers in the center typically speak functional English. Older generations often speak Russian more than English. Outside tourist areas, language barriers can exist. The business environment operates increasingly in English. Learning basic Latvian or Russian phrases is appreciated. The younger population is well-educated in English.",
        "visa": "Latvia is part of the Schengen Area and EU, allowing visa-free stays of up to 90 days within a 180-day period for citizens of many countries. Latvia offers a digital nomad visa option through the startup visa program. EU citizens can live and work freely. Work permits require employer sponsorship for non-EU citizens. The immigration system is straightforward.",
        "culture": "Riga's culture blends medieval heritage with art nouveau magnificence—the city has the world's finest concentration of Jugendstil architecture. The old town is UNESCO-listed with Gothic churches and cobblestone streets. Opera and classical music traditions are strong. The Song and Dance Festival (every 5 years) is a massive celebration of Latvian identity. Soviet legacy adds another historical layer. The arts scene is vibrant.",
        "cleanliness": "Riga is clean and well-maintained. The old town and central areas are kept tidy. Parks and public spaces are cared for. Some Soviet-era residential areas show more wear. The art nouveau district is beautifully preserved. Public transport is clean. Standards meet Western European levels. The city takes pride in its appearance and heritage preservation.",
        "airquality": "Riga has good air quality, benefiting from Baltic sea breezes and extensive parks. The industrial base has declined since Soviet times. Traffic emissions are the main pollutant. Air quality indexes typically show healthy levels. Winter inversions can occasionally trap pollution. The green spaces throughout the city contribute to clean air. Most visitors don't notice air quality concerns."
    },
    "vilnius": {
        "climate": "Vilnius has a humid continental climate with warm summers and cold winters. Summer temperatures reach 20-27°C (68-81°F) with long pleasant days. Winters are cold at -5 to -1°C (23-30°F) with snow common from December to March. Spring and autumn offer mild, changing conditions. The city experiences all four seasons distinctly. The old town is particularly beautiful in winter snow.",
        "cost": "Vilnius offers excellent value for a European capital. Monthly costs range from €1,200-2,000 for a comfortable lifestyle. Rent for a central one-bedroom apartment averages €500-800. Meals at local restaurants cost €7-15. Coffee culture is affordable at €2-3. Public transport is cheap. Coworking spaces range from €100-250 monthly. Lithuania is one of Europe's most affordable EU countries.",
        "wifi": "Lithuania has exceptional internet infrastructure, consistently ranking among Europe's fastest. Vilnius cafes and coworking spaces offer 50-200+ Mbps connections. The city has numerous coworking options including Tech Park and Creative Hub. Free WiFi is widely available in public spaces. Mobile data through Telia or Bite provides excellent 4G/5G coverage. Fiber is standard in most buildings. Remote work infrastructure is outstanding.",
        "nightlife": "Vilnius nightlife centers around the old town and Užupis district. The scene ranges from cozy beer pubs to electronic clubs. Opium and Kablys have strong local followings. The alternative scene in Užupis has bohemian character. Cocktail bars have multiplied. Summer brings outdoor terraces and festivals. The scene is friendly and varied. Lithuanian craft beer deserves exploration. Nights can go late on weekends.",
        "nature": "Vilnius offers green escapes within and around the city. Vingis Park provides 162 hectares of forest and trails. The Neris River banks have walking and cycling paths. Trakai castle town, 30 minutes away, sits beautifully on island lakes. The Curonian Spit (4 hours) offers unique sand dune landscapes. Lithuanian countryside features forests, lakes, and rolling hills. Nature is integral to local culture.",
        "safety": "Vilnius is very safe with low crime rates. The old town and central areas are comfortable at all hours. Petty theft is rare. No neighborhoods are considered dangerous. The main hazards are uneven cobblestones and cold winters. Lithuanian society is orderly and peaceful. Solo travelers of all backgrounds feel secure. The overall atmosphere is calm and welcoming.",
        "food": "Lithuanian cuisine features hearty dishes suited to the climate. Cepelinai (potato dumplings) are the national dish. Cold beet soup (šaltibarščiai) is a summer staple. Rye bread and dairy products are fundamental. Traditional restaurants preserve heritage dishes. The contemporary scene has embraced international cuisines and farm-to-table philosophy. Hales Market offers local products. Coffee culture is sophisticated.",
        "community": "Vilnius has a growing digital nomad and tech community. The city has positioned itself as a fintech hub. Coworking spaces host regular networking events. The startup ecosystem attracts international talent. English-speaking integration is smooth. Facebook groups and meetups connect remote workers. The community is welcoming and internationally minded. The tech focus creates natural networking opportunities.",
        "english": "English proficiency in Vilnius is excellent among younger generations. Most service workers speak good English. The tech and business communities operate primarily in English. Older generations may speak Russian. Signs are often bilingual. Learning Lithuanian basics is appreciated but unnecessary. The education system emphasizes English. Communication is smooth throughout the city.",
        "visa": "Lithuania is part of the Schengen Area and EU, allowing visa-free stays of up to 90 days within a 180-day period for citizens of many countries. Lithuania offers a startup visa for entrepreneurs and remote workers. EU citizens can live and work freely. The digital nomad scene is supported with clear immigration pathways. The process is straightforward and digital-friendly.",
        "culture": "Vilnius combines medieval heritage with artistic bohemianism. The baroque old town is UNESCO-listed, with countless churches and narrow streets. Užupis, the 'Republic' declared by artists, has its own constitution and playful spirit. The Jewish heritage, once called the 'Jerusalem of Lithuania,' is commemorated at memorial sites. Contemporary art and music scenes thrive. The city balances historical weight with youthful energy.",
        "cleanliness": "Vilnius is clean and well-maintained. The old town is kept pristine for its UNESCO status. Parks and public spaces are tidy. Some Soviet-era districts show more wear but are improving. Public transport is clean. The city takes pride in its appearance. Standards meet Western European levels. The compact size makes maintenance manageable.",
        "airquality": "Vilnius has good air quality, benefiting from parks, moderate traffic, and limited industry. The green surroundings contribute to clean conditions. Winter can bring temporary inversions. Traffic is the main pollution source. Air quality indexes typically show healthy levels. The environment is notably fresh compared to many European capitals. Most visitors appreciate the clean air."
    },
    "sofia": {
        "climate": "Sofia has a humid continental climate with warm summers and cold winters. Summer temperatures reach 25-32°C (77-90°F) with occasional heat waves. Winters are cold at -2 to 5°C (28-41°F) with snow common. Spring and autumn offer pleasant conditions with mild temperatures. The surrounding mountains moderate some extremes. The climate has four distinct seasons. Summer thunderstorms are common.",
        "cost": "Sofia is one of Europe's most affordable capitals. Monthly costs range from €1,000-1,800 for a comfortable lifestyle. Rent for a central one-bedroom apartment averages €400-700. Restaurant meals cost €5-12. Coffee and beer are cheap at €1.50-3. Public transport costs €0.80 per ride. Coworking spaces range from €80-200 monthly. The euro isn't used yet (lev), keeping prices low.",
        "wifi": "Bulgaria has invested in internet infrastructure, and Sofia offers reliable connectivity. Most cafes and coworking spaces provide 40-100 Mbps connections. The city has numerous coworking options including Betahaus and Soho. Mobile data through A1 or Vivacom provides good 4G coverage. Fiber is available in many buildings. The tech sector has driven infrastructure improvement. Connectivity supports remote work well.",
        "nightlife": "Sofia's nightlife has exploded in recent years. The Vitosha Boulevard and Rakovski Street areas have bars and clubs. The tech district around Lozenets has trendy spots. Electronic music clubs attract regional talent. Traditional mehanas offer folk entertainment. The scene is varied and increasingly sophisticated. Prices remain low for European nightlife. Summer brings rooftop bars and outdoor events.",
        "nature": "Sofia offers excellent nature access. Vitosha Mountain begins at the city's southern edge, with hiking and skiing within 30 minutes. Boyana Waterfall and trails are easily accessible. The Seven Rila Lakes, a stunning alpine destination, are 2 hours away. Rhodope Mountains offer rural escapes. City parks like Borisova Gradina provide green space. The surrounding mountains set Sofia apart from other capitals.",
        "safety": "Sofia is relatively safe with low violent crime. The center and tourist areas are comfortable. Petty theft occurs in crowded areas and public transport. Stray dogs exist but are generally not aggressive. Some outlying areas are best avoided at night. The infrastructure shows post-communist wear in places. Most visitors experience no problems. Standard urban precautions apply. The overall atmosphere is calm.",
        "food": "Bulgarian cuisine features fresh ingredients and Balkan flavors. Shopska salad (tomatoes, cucumbers, peppers with feta-like sirene) is ubiquitous. Banitsa (filo pastry with cheese) fuels many breakfasts. Grilled meats and fresh vegetables dominate. Rakija (fruit brandy) accompanies meals. Traditional mehanas serve authentic fare. The food scene has expanded with international options. Prices are exceptionally low for the quality.",
        "community": "Sofia has developed a significant digital nomad and tech community. The city positions itself as a European tech hub with low costs. Coworking spaces host events connecting remote workers. The startup ecosystem is growing. International entrepreneurs and remote workers are increasingly common. The community is welcoming and practical. Facebook groups and meetups facilitate connections.",
        "english": "English proficiency in Sofia has improved significantly, good among younger people and professionals. Service workers in central areas often speak English. Older generations may have less English (Russian is more common). Tourist areas handle English well. The tech community operates primarily in English. Learning basic Bulgarian helps but isn't essential. The situation has improved markedly in recent years.",
        "visa": "Bulgaria is in the EU but not yet Schengen (joining soon), with its own 90-day allowance for many nationalities. EU citizens can live and work freely. Bulgaria offers a freelance visa for self-employed individuals. Work permits require employer sponsorship. The country is working toward Schengen integration. Immigration processes are bureaucratic but manageable.",
        "culture": "Sofia blends ancient history with post-communist transformation. Roman ruins sit alongside Ottoman mosques and Soviet-era buildings. The Alexander Nevsky Cathedral is an Orthodox masterpiece. Contemporary art and music scenes are thriving. The mountains influence recreational culture. Bulgarian hospitality emerges once initial reserve passes. The city is transforming rapidly while preserving history.",
        "cleanliness": "Sofia's cleanliness is improving but uneven. The city center and tourist areas are reasonably maintained. Some infrastructure shows Soviet-era wear. Parks and green spaces vary. Public transport is adequate. Construction sites can be messy. The city is improving but hasn't reached Western European standards. Some areas are better than others. The situation is progressing.",
        "airquality": "Sofia has significant air quality issues, particularly in winter. The valley location traps pollution from heating and traffic. Winter inversions create smog that can reach unhealthy levels. Summer air quality is generally better. The government has implemented measures, but progress is slow. Sensitive individuals should monitor conditions during winter. The mountains provide escape. The situation is a genuine concern."
    },
    "bucharest": {
        "climate": "Bucharest has a humid continental climate with hot summers and cold winters. Summer temperatures reach 28-35°C (82-95°F), occasionally higher during heat waves. Winters are cold at -3 to 4°C (27-39°F) with snow and ice. Spring and autumn offer pleasant conditions. The climate has dramatic seasonal swings. Summer can feel oppressive in the concrete city. Layering is essential.",
        "cost": "Bucharest offers excellent value for an EU capital. Monthly costs range from €1,100-1,900 for a comfortable lifestyle. Rent for a central one-bedroom apartment averages €450-750. Restaurant meals cost €6-15. Coffee and beer are affordable at €1.50-3. Public transport is cheap. Coworking spaces range from €80-200 monthly. Romania's currency (leu) provides good value for foreign earners.",
        "wifi": "Romania has exceptional internet infrastructure—among the world's fastest and cheapest. Bucharest cafes and coworking spaces commonly offer 100-500 Mbps connections. The city has numerous coworking options including Impact Hub and TechHub. Mobile data through Vodafone or Orange provides excellent 4G/5G coverage. Fiber is standard in most buildings. The connectivity is genuinely world-class.",
        "nightlife": "Bucharest's nightlife is legendary for energy and diversity. The old town (Lipscani) packs bars and clubs into historic streets. Control and Kristal are famous underground clubs. Rooftop bars offer skyline views. The scene ranges from dive bars to sophisticated lounges. Nights can extend until sunrise. Prices remain low. The energy and variety attract partygoers from across Europe. Summer brings outdoor festivals.",
        "nature": "Bucharest is primarily urban, but nature escapes exist. Herăstrău Park offers 200 hectares of lakeside green space. Carol Park and Cișmigiu Gardens provide central escapes. Day trips to the Carpathian Mountains (2 hours) offer hiking and dramatic scenery. Transylvanian castles combine history with mountain landscapes. The Danube Delta (5 hours) provides unique wildlife. The surroundings compensate for urban density.",
        "safety": "Bucharest is generally safe with low violent crime. The old town and central areas are comfortable day and night. Petty theft occurs in crowded areas and on public transport. Taxi scams have historically been problematic—use apps like Bolt. Some outlying areas are less polished. Stray dogs have reduced significantly. Most visitors experience no problems. Standard urban awareness applies.",
        "food": "Romanian cuisine is hearty and meat-focused. Mămăligă (polenta) accompanies most dishes. Mititei (grilled meat rolls) are beloved street food. Sarmale (stuffed cabbage rolls) is a national favorite. Fresh bread accompanies every meal. Traditional restaurants serve generous portions. The food scene has expanded with international cuisines. Prices are remarkably low. The quality-to-cost ratio is excellent.",
        "community": "Bucharest has a developing digital nomad community, growing with its excellent internet and low costs. Coworking spaces host networking events. The tech sector attracts international talent. The expat community includes business professionals and creatives. Romanians are friendly once engaged. Language exchange and social meetups help build connections. The scene is expanding rapidly.",
        "english": "English proficiency in Bucharest is good among younger generations and professionals. Service workers in central areas typically speak functional English. Older generations often don't. The business and tech communities operate in English. Tourist areas handle English well. Learning basic Romanian helps daily life. The education system emphasizes English. Communication is generally smooth in urban areas.",
        "visa": "Romania is in the EU but not yet Schengen, with its own 90-day allowance for many nationalities. EU citizens can live and work freely. Romania offers a digital nomad visa allowing stays up to one year, requiring proof of remote income. Work permits require employer sponsorship for non-EU citizens. The immigration system is modernizing.",
        "culture": "Bucharest blends Paris-inspired belle époque architecture with communist brutalism and modern development. The Palace of Parliament is the world's heaviest building. The old town preserves 19th-century character. Museums document turbulent history including the 1989 revolution. Contemporary art and music scenes are flourishing. The contrast between elegance and decay defines the aesthetic. The city is transforming rapidly.",
        "cleanliness": "Bucharest's cleanliness varies significantly by area. The center and upscale neighborhoods are reasonably maintained. Some infrastructure shows communist-era wear. Construction is constant, creating temporary disorder. Parks vary in maintenance. Public transport is adequate but dated. The city is improving but slowly. Standards are below Western Europe but progressing. Some areas are much better than others.",
        "airquality": "Bucharest has moderate to poor air quality, affected by traffic and seasonal heating. The flat terrain can trap pollution. Summer dust and vehicle emissions are factors. Winter heating adds particulates. Air quality alerts occur during certain conditions. The situation is better than some Eastern European cities. Most visitors adapt without major concerns. Sensitive individuals should monitor conditions."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")

    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
