#!/usr/bin/env python3
"""Rewrite batch 8: Major cities I-M (istanbul, kualalumpur, london, madrid, melbourne)."""

import json
import os

BATCH_CITIES = {
    "istanbul": {
        "climate": "Istanbul has a borderline Mediterranean/humid subtropical climate. Summers are hot and humid (25-32°C), winters are cool and rainy (5-10°C) with occasional snow. Spring (April-May) and autumn (September-October) are ideal with pleasant temperatures and fewer tourists. The Bosphorus creates microclimates. Rain is common in winter. The city experiences real seasons.",
        "cost": "Turkey's economic situation makes Istanbul exceptional value for foreign currency. A comfortable lifestyle costs $1,000-1,800/month. Apartments range $400-800/month in good neighborhoods. Local food is cheap ($3-8), while Western restaurants charge more. The lira fluctuation means dollar/euro budgets stretch far. Costs have risen but value remains strong.",
        "wifi": "Turkey has developed good internet infrastructure. Istanbul offers speeds of 40-80 Mbps typically. WiFi is common in cafes and restaurants. Some social media access is restricted—VPNs are commonly used. Mobile data through Turkcell, Vodafone, or Türk Telekom is reliable. Coworking spaces provide stable connections. Connectivity supports remote work.",
        "nightlife": "Istanbul's nightlife is legendary and varied. Beyoğlu and Karaköy host bars, clubs, and live music. The Bosphorus clubs offer glamorous experiences. Kadıköy on the Asian side has a cooler, alternative scene. The scene runs late with energy peaking after midnight. Raki and meze fuel the evenings. Few cities match Istanbul's nocturnal variety and energy.",
        "nature": "Istanbul is urban but water defines it. The Bosphorus strait divides Europe and Asia, providing waterfront life. The Princes' Islands offer car-free escapes. Belgrade Forest provides green space. Day trips reach the Black Sea coast. The city itself is green with parks along the water. Nature is woven into the urban fabric through the strait.",
        "safety": "Istanbul is generally safe for a major city. Petty theft can occur in tourist areas and on crowded transport. Political situations may create temporary tensions—monitor news. Solo female travelers receive attention but serious issues are rare. Traffic is aggressive. Most visitors have safe experiences with normal precautions. Turkish hospitality creates a welcoming atmosphere.",
        "food": "Turkish cuisine is exceptional and Istanbul is its showcase. Kebabs, meze, fresh fish from the Bosphorus, street simit (sesame bread), and baklava provide daily pleasures. The breakfast spreads are legendary. Markets and restaurants serve quality at all price points. The food is fresh, flavorful, and affordable. Eating is central to Turkish life and culture.",
        "community": "Istanbul has a growing digital nomad community, particularly in Kadıköy and Cihangir. Coworking spaces host events and meetups. The city attracts entrepreneurs, creatives, and remote workers. Turkish people are warm and social. The international community includes long-term expats and newer arrivals. Connections form through work spaces, cafes, and social events.",
        "english": "English is spoken in tourist areas and by younger Turks. Hotels, restaurants in popular areas, and businesses manage in English. Outside these zones, Turkish becomes necessary. Learning basic Turkish significantly improves daily life and earns appreciation. The language barrier is navigable but present.",
        "visa": "Turkey offers e-visas online for most nationalities ($50 typically), allowing 90 days within 180. The process is quick and straightforward. Turkey has introduced residence permit options for digital nomads and retirees. Extensions and residency permits are possible. The country actively welcomes international visitors and remote workers.",
        "culture": "Istanbul is where civilizations have met for millennia. Byzantine, Ottoman, and modern Turkish layers create unmatched depth. The Hagia Sophia, Blue Mosque, and Grand Bazaar are iconic. The call to prayer echoes across the skyline. Turkish hospitality is genuine—tea and conversation are offered freely. The city bridges Europe and Asia geographically and culturally.",
        "cleanliness": "Istanbul's cleanliness varies by neighborhood. Major tourist areas and new developments are well-maintained. Older areas can be rough. The city makes visible efforts—street cleaning is regular. The Grand Bazaar and historic sites are carefully maintained. Tap water is safe but many drink bottled. Standards are improving but variable.",
        "airquality": "Air quality in Istanbul is moderate to fair, with AQI typically 40-80. Traffic and industrial activity affect quality. Sea breezes help disperse pollution. Winter heating increases levels. The situation has improved with environmental regulations. Sensitive individuals should monitor conditions, particularly in busy areas."
    },
    "kualalumpur": {
        "climate": "Kuala Lumpur has a tropical rainforest climate—hot and humid year-round (27-33°C). Rain is possible any day but often falls in brief afternoon downpours. There's no distinct dry season, though February-March tends to be drier. The equatorial location means consistent weather. Air conditioning is essential. The humidity is the main climate challenge.",
        "cost": "KL offers excellent value for a major Southeast Asian capital. A comfortable lifestyle costs $1,200-2,000/month. Apartments range $400-900/month with good amenities. Local food is cheap ($2-5), with diverse options at every price point. The cost-quality ratio is excellent. Malaysia's affordable living makes extended stays financially easy.",
        "wifi": "Malaysia has invested in internet infrastructure. KL offers speeds of 50-100+ Mbps. WiFi is ubiquitous in malls, cafes, and coworking spaces. Mobile data through Maxis, Celcom, or DiGi is affordable and reliable. The city is well-equipped for remote work. Connectivity is rarely a concern.",
        "nightlife": "KL's nightlife is varied. Changkat Bukit Bintang has the highest concentration of bars and clubs. Bangsar offers sophisticated options. Rooftop bars in KLCC provide skyline views. The scene is diverse—from local mamak stalls to glamorous clubs. Malaysia is Muslim-majority, so alcohol is available but more expensive. The energy varies by neighborhood.",
        "nature": "KL is surrounded by jungle—the Batu Caves blend limestone and temple. FRIM (Forest Research Institute) offers canopy walks. The Genting Highlands provide cool escapes. Day trips reach Cameron Highlands tea plantations or Langkawi beaches. The city itself has KLCC Park beneath the towers. Tropical nature is accessible despite the urban setting.",
        "safety": "KL is generally safe for a Southeast Asian capital. Petty theft like snatch theft exists—be aware of bags and phones. Violent crime is rare. Traffic requires attention. The city is comfortable for solo travelers including women. Standard awareness is sufficient. Malaysian hospitality creates a welcoming environment.",
        "food": "KL's food is a highlight—arguably Southeast Asia's most diverse. Malay, Chinese, Indian, and fusion cuisines are all excellent. Hawker centers and mamak stalls serve incredible food cheaply. The diversity reflects the multicultural population. From laksa to char kway teow to banana leaf rice, every meal offers discovery. Food is central to Malaysian life.",
        "community": "KL has a growing digital nomad community alongside established expats. Coworking spaces host events. The international community includes professionals across industries. Connections form through work spaces, meetups, and social groups. Malaysians are friendly and welcoming. The community is diverse and multicultural.",
        "english": "English is widely spoken in KL—a legacy of British colonization. Business, services, and urban life function in English. Signage is often bilingual or multilingual. Communication is straightforward. Malaysian English has distinct expressions ('lah', 'can or not?'). The language accessibility makes KL easy for English speakers.",
        "visa": "Malaysia offers visa-free entry (90 days) for most nationalities. The DE Rantau visa is specifically for digital nomads, offering one-year stays. Requirements include proof of income ($24k/year) and health insurance. The process is relatively straightforward. Malaysia actively courts remote workers.",
        "culture": "KL is genuinely multicultural—Malay, Chinese, Indian, and other communities coexist. Mosques, temples, and churches stand near each other. Festivals from all traditions are celebrated. The Petronas Towers symbolize modern ambition. Traditional kampung villages contrast with skyscrapers. Islam is the official religion but diversity is the character.",
        "cleanliness": "KL maintains reasonable standards. Modern areas like KLCC and Bukit Bintang are well-maintained. Malls are immaculate. Older areas vary. Hawker centers prioritize food over ambiance. Public transport is clean. Tap water is treated but most drink filtered or bottled. The situation is reasonable for the region.",
        "airquality": "Air quality in KL is usually moderate (AQI 50-80). The annual haze season (August-October) from Indonesian fires can create hazardous conditions exceeding 150+ AQI. This is a serious concern requiring monitoring. Outside haze season, air quality is acceptable. Indoor air in malls and modern buildings is good."
    },
    "london": {
        "climate": "London has a temperate oceanic climate—mild but gray. Summers are pleasant (18-25°C), winters are chilly but rarely freezing (3-8°C). Rain is frequent but usually light drizzle. The reputation for bad weather is exaggerated—there are plenty of nice days. Daylight hours vary dramatically by season. Layer clothing and always have an umbrella accessible.",
        "cost": "London is one of the world's most expensive cities. A comfortable lifestyle costs £3,500-5,500/month. Apartments are extremely expensive, ranging £1,800-3,000+/month for modest options. Restaurant meals cost £15-30. The underground is pricey. The housing market is brutal. Budget carefully and consider outer zones for value.",
        "wifi": "UK internet infrastructure is good. London offers speeds of 50-100+ Mbps with fiber widely available. WiFi is common in cafes though sometimes with time limits. Coworking spaces provide reliable connections. Mobile coverage is excellent. The city supports remote work infrastructure adequately.",
        "nightlife": "London's nightlife is vast and varied. From West End theaters to Soho bars, from Shoreditch clubs to jazz in Camden—every preference is served. The pub culture is foundational—locals are living rooms. World-class music venues host international acts. The scene runs late on weekends. Few cities match London's nightlife diversity and scale.",
        "nature": "London is remarkably green for a major city. Royal parks—Hyde Park, Regent's Park, Richmond Park—provide extensive green space. The Thames Path offers riverside walks. Day trips reach the Cotswolds, Brighton beaches, and countryside easily. Within the city, squares and gardens punctuate neighborhoods. Nature is integrated into urban life.",
        "safety": "London is generally safe for a major city. Petty theft occurs in tourist areas and on public transport. Some areas have higher crime rates—research neighborhoods. Knife crime exists but rarely affects visitors. The city functions with standard urban awareness. Walking at night is comfortable in most central areas. Emergency services are excellent.",
        "food": "London's food scene has transformed. Once mocked for bad food, it now rivals any global city. Every cuisine is represented at every level. Indian food is exceptional. Street food markets showcase diversity. Michelin stars abound. The traditional full English breakfast and Sunday roast remain cultural touchstones. Quality is high; prices match.",
        "community": "London has a massive international community—genuinely global. The nomad scene exists within broader professional networks. Coworking spaces host events. Industry meetups are constant. The challenge is London's scale—community requires finding your niche. Connections can feel transient. The diversity means every interest has its people.",
        "english": "London is native English-speaking, naturally. British English has its own vocabulary and expressions you'll learn. The multicultural population means many languages are heard. Communication is effortless. The city functions entirely in English.",
        "visa": "Post-Brexit UK has separate visa rules from Europe. EU citizens need visas for stays over 6 months. Most Western nationalities can visit for 6 months visa-free. Work visas require sponsorship and points-based qualification. The UK has no digital nomad visa. Immigration requirements are strict. Working legally requires proper arrangements.",
        "culture": "London's culture spans centuries of history and contemporary creativity. World-class museums (free!), West End theatre, music scenes from grime to orchestras—the cultural infrastructure is unmatched. Royalty, Parliament, and tradition coexist with multicultural modernity. Each neighborhood has distinct character. The pace is fast but pockets of calm exist. Culture is everywhere and accessible.",
        "cleanliness": "London maintains good standards with significant effort. The Underground is reasonably clean given volume. Central areas are maintained. Some areas show urban grit. Parks are well-kept. Tap water is excellent. The city faces challenges of scale but functions well. Standards are reasonable for a major world city.",
        "airquality": "Air quality in London is moderate to poor, with AQI typically 40-70. Traffic emissions are the main source—the ULEZ zone helps. Underground air can be poor. Some days see elevated levels. The government addresses the issue with congestion charging and electric buses. The situation is improving but remains a consideration."
    },
    "madrid": {
        "climate": "Madrid has a Mediterranean/continental climate with hot, dry summers (30-40°C) and cool winters (2-10°C). The elevation (650m) creates temperature extremes—scorching summer days but cool nights. Spring and autumn are ideal with comfortable temperatures. Winter can be surprisingly cold. The lack of coast means no moderating effect. Clear, sunny days are common.",
        "cost": "Madrid offers good value for a Western European capital. A comfortable lifestyle costs €1,800-2,800/month. Apartments range €800-1,400/month in central areas—cheaper than Barcelona or Lisbon now. Restaurant meals cost €12-20, with lunch menus offering value. Nightlife is affordable. The cost-quality ratio is favorable.",
        "wifi": "Spanish internet infrastructure is solid. Madrid offers speeds of 50-100+ Mbps. WiFi is available in cafes though Spanish culture favors conversation over laptops. Coworking spaces provide reliable connections. Mobile data is reliable. The city supports remote work adequately.",
        "nightlife": "Madrid's nightlife is legendary. The city truly doesn't sleep—dinner at 10pm, drinks at midnight, clubs at 3am, dawn chocolate con churros. Malasaña and Chueca are nightlife centers. La Latina has traditional bars. The scene is democratic—all ages participate. The energy continues every night of the week. Few cities party like Madrid.",
        "nature": "Madrid is landlocked but nature is accessible. El Retiro park is the green heart. The Sierra de Guadarrama mountains are an hour away for hiking and skiing. Day trips reach historic cities like Toledo and Segovia. The Casa de Campo forest provides urban escapes. The surrounding Castilian landscape is austere but dramatic.",
        "safety": "Madrid is very safe for a major city. Violent crime is rare. Pickpocketing occurs in tourist areas and on metro—keep valuables secure. The atmosphere is relaxed and welcoming. Walking at night is comfortable throughout the center. The Spanish lifestyle fills streets until late, adding natural security. Standard awareness is sufficient.",
        "food": "Spanish cuisine shines in Madrid. Tapas culture is serious—small plates accompany drinks. Bocadillos de calamares (squid sandwiches) are Madrid's street food. Cocido madrileño is the traditional stew. The Mercado de San Miguel showcases quality. Restaurants range from traditional tavernas to modern gastronomy. Eating socially defines Madrid life.",
        "community": "Madrid has a significant international community and growing nomad presence. The city is less saturated than Barcelona or Lisbon. Coworking spaces host events. The creative and startup scenes are developing. Madrileños are warm and social. Connections form through nightlife, language exchanges, and work spaces. The community is welcoming and established.",
        "english": "English is spoken in tourism and business but less than in Barcelona. Young Madrileños often have some English. Learning Spanish significantly improves daily life and is expected for integration. The city is less internationally oriented than coastal Spain. English suffices for basics but Spanish opens the city.",
        "visa": "Spain is part of the EU and Schengen. EU citizens have freedom of movement. Non-EU visitors stay 90 days within Schengen. Spain offers a digital nomad visa (Ley de Startups) with €2,200/month income requirement. Non-lucrative visas serve those with passive income. The bureaucracy requires patience.",
        "culture": "Madrid is Spain's cultural capital. The Prado, Reina Sofía, and Thyssen form the art triangle. Royal palaces and historic plazas define the urban fabric. Flamenco lives in traditional tablaos. Football (Real Madrid) is religion. The culture values living well—long meals, late nights, strong social bonds. The pace is intense but the lifestyle prioritizes pleasure.",
        "cleanliness": "Madrid maintains good standards. The city center is regularly cleaned. Parks are well-maintained. Some areas show urban character. Tap water is safe—Madrid's water from the mountains is excellent. The city functions well with reasonable civic maintenance. Standards are appropriate for a major European capital.",
        "airquality": "Air quality in Madrid is moderate, with AQI typically 30-60. Traffic emissions affect central areas. Summer heat can elevate ozone. The city has implemented restrictions on vehicles. The elevated position provides some air movement. The situation is typical for Mediterranean capitals—manageable but not pristine."
    },
    "melbourne": {
        "climate": "Melbourne is famous for unpredictable weather—'four seasons in one day' is real. Summers are warm (20-30°C) but variable; winters are cool (7-14°C) and damp. Rain is possible anytime. Heat waves occasionally exceed 40°C. The southern location means changeable conditions. Layer clothing and check forecasts. Spring and autumn can be lovely.",
        "cost": "Melbourne is expensive but slightly cheaper than Sydney. A comfortable lifestyle costs AUD 3,500-5,000/month ($2,300-3,300). Apartments range AUD 1,600-2,600/month. Dining out costs $15-30 for quality meals. Coffee culture is strong and affordable. The cost reflects Australian standards but value exists.",
        "wifi": "Australian internet has improved with the NBN. Melbourne offers speeds of 50-100+ Mbps typically. Cafes commonly offer WiFi—the culture welcomes laptop workers. Coworking spaces provide reliable connections. Mobile coverage is excellent in urban areas. The city supports remote work infrastructure well.",
        "nightlife": "Melbourne's nightlife is sophisticated and diverse. Laneway bars define the scene—hidden entrances and craft cocktails. Fitzroy and Collingwood have live music and alternative venues. Chapel Street offers mainstream options. The live music scene is exceptional. The scene starts earlier than Sydney but runs late. Quality and variety are strengths.",
        "nature": "Melbourne provides good nature access. The Royal Botanic Gardens offer urban green space. Beaches like St Kilda are accessible. The Dandenong Ranges provide forest walks an hour away. The Great Ocean Road is a legendary day trip. Phillip Island has penguins. The surrounding Victoria landscapes—from mountains to coast—are varied and accessible.",
        "safety": "Melbourne is very safe by global standards. Violent crime is rare. Some areas have higher property crime. Walking at night is comfortable in most central areas. The atmosphere is relaxed and friendly. Standard urban awareness is sufficient. Australia's generally safe environment extends to Melbourne.",
        "food": "Melbourne's food scene is world-class. The coffee culture sets global standards—flat whites are serious business. Asian food is exceptional, reflecting immigration patterns. Diverse neighborhoods offer every cuisine. Food markets and restaurants showcase quality. The culture takes food seriously—dining is cultural participation. Quality is high across all price points.",
        "community": "Melbourne has a significant international community. The creative, tech, and startup scenes are strong. Coworking spaces and meetups facilitate connections. The city attracts artists, musicians, and entrepreneurs. Melburnians are friendly and social. The community is established and diverse. Connections form through shared interests and neighborhoods.",
        "english": "Melbourne is native English-speaking. Australian English has distinctive slang and expressions ('arvo', 'reckon', etc.). Communication is effortless. The multicultural population means many languages are heard. The city functions entirely in English.",
        "visa": "Australian visa rules are consistent nationwide. ETAs allow short visits for many nationalities. Working holiday visas enable those under 30-35 to work and travel. Skilled worker visas require points-based qualification or sponsorship. Australia has categories for digital professionals. The immigration system is organized but competitive.",
        "culture": "Melbourne positions itself as Australia's cultural capital. Street art, galleries, and independent music define the creative scene. Coffee and food are cultural touchstones. AFL (Australian Rules Football) is religion—Melbourne invented it. The arts scene is strong with festivals throughout the year. The culture is creative, multicultural, and slightly competitive with Sydney.",
        "cleanliness": "Melbourne is very clean by global standards. The CBD laneways are maintained despite their artistic character. Beaches are cleaned. Public transport is reasonably clean. Parks are well-kept. Tap water is excellent. The city maintains high standards. Street art coexists with cleanliness.",
        "airquality": "Air quality in Melbourne is generally good, with AQI typically 20-50. The coastal position helps. Bushfire smoke can create severe conditions during summer fire seasons—this has become more frequent. Some industrial areas have localized issues. Most of the year, air quality is excellent."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
