#!/usr/bin/env python3
"""Rewrite batch 12: Toronto, Tel Aviv, Thessaloniki, Tulum, Valencia."""

import json
import os

BATCH_CITIES = {
    "toronto": {
        "climate": "Toronto has a humid continental climate with warm, humid summers and cold, snowy winters. Summer temperatures range from 20-30°C (68-86°F), making it pleasant for outdoor activities along the waterfront. Winters can be harsh with temperatures often dropping below -10°C (14°F), so pack warm layers. Spring and fall offer mild weather perfect for exploring neighborhoods. The city experiences all four seasons distinctly, which many nomads appreciate for variety.",
        "cost": "Toronto is one of Canada's most expensive cities, with monthly costs typically ranging from $3,000-4,500 CAD for a comfortable lifestyle. Rent for a one-bedroom apartment averages $2,000-2,500 CAD in central areas, though prices have risen significantly. Groceries and dining out are moderately expensive, with meals at casual restaurants around $15-25 CAD. Public transit passes cost around $150 CAD monthly. Coworking spaces range from $300-600 CAD per month.",
        "wifi": "Toronto offers excellent internet infrastructure with widespread fiber optic coverage. Most cafes and coworking spaces provide reliable connections of 50-200 Mbps. The city has numerous coworking options from downtown to trendy neighborhoods like Queen West and Leslieville. Public libraries offer free WiFi throughout the city. Mobile data coverage is strong with multiple carriers offering competitive 5G plans, though Canadian mobile rates are notoriously high.",
        "nightlife": "Toronto's nightlife scene is incredibly diverse, spanning everything from sophisticated cocktail lounges in King West to indie live music venues in Kensington Market. The Entertainment District pulses with clubs and bars on weekends. Queen Street West offers hipster bars and late-night eateries, while Ossington Avenue features trendy cocktail spots. The city has a thriving comedy scene and numerous live music venues showcasing local and international talent throughout the week.",
        "nature": "Despite being a major metropolis, Toronto offers abundant green spaces and natural escapes. The Toronto Islands provide a car-free oasis just a short ferry ride from downtown, with beaches and stunning skyline views. High Park offers 400 acres of trails, gardens, and a small zoo. The Don Valley trails provide forested escapes within city limits. Day trips to Niagara Falls, Bruce Peninsula, and Muskoka cottage country are easily accessible.",
        "safety": "Toronto consistently ranks as one of the safest major cities in North America, with low violent crime rates and a generally welcoming atmosphere. The downtown core and major neighborhoods feel safe to walk around at night. Public transit is safe to use at all hours. Like any large city, petty theft can occur in tourist areas, so keep valuables secure. The city is known for its multiculturalism and tolerance, making diverse visitors feel welcome.",
        "food": "Toronto's food scene rivals any global culinary capital, reflecting its incredible cultural diversity. You'll find authentic cuisine from virtually every country, from Little India's curry houses to Chinatown's dim sum palaces. St. Lawrence Market offers artisanal vendors and fresh produce. The city is famous for its brunch culture, diverse food courts, and innovative fusion restaurants. Kensington Market features eclectic international eateries in a bohemian setting.",
        "community": "Toronto has a substantial and active digital nomad community, bolstered by its status as Canada's tech hub. Numerous coworking spaces host networking events and workshops. The city attracts entrepreneurs, remote workers, and creatives from around the world. Meetup groups cover everything from tech to outdoor activities. The diverse population means you can find communities representing almost any background or interest.",
        "english": "English is the primary language in Toronto, making it extremely easy for English-speaking nomads. The city's multiculturalism means you'll hear many languages spoken, but all services, signage, and business are conducted in English. Some knowledge of French can be helpful for government services, though it's not necessary. Customer service in all industries is available in fluent English.",
        "visa": "Canadians and visitors from visa-exempt countries can stay in Canada for up to 6 months as tourists. For longer stays, the Working Holiday Visa is available for citizens of over 30 countries aged 18-35. Canada offers a Start-up Visa for entrepreneurs. The eTA (Electronic Travel Authorization) is required for visa-exempt visitors arriving by air. Remote workers typically enter as tourists, though technically working requires a permit.",
        "culture": "Toronto prides itself on being one of the world's most multicultural cities, with over 200 ethnic groups represented. This diversity creates a rich cultural tapestry visible in neighborhoods, festivals, and daily life. The city hosts world-class museums like the ROM and AGO, plus the prestigious Toronto International Film Festival. Arts, theater, and music thrive here. Torontonians are generally friendly but reserved compared to other cities.",
        "cleanliness": "Toronto maintains high standards of cleanliness compared to many major cities. Streets are regularly cleaned, and public spaces are well-maintained. The waterfront areas and parks are kept tidy. Some graffiti exists in certain neighborhoods, considered art rather than vandalism in many cases. Recycling and composting programs are comprehensive. Public restrooms in malls and transit stations are generally clean.",
        "airquality": "Toronto has generally good air quality, though summer smog alerts can occur during heat waves due to emissions and lake effect conditions. The Air Quality Health Index usually remains in the low-risk range. Winter air tends to be cleaner and crisper. The city has implemented various environmental initiatives to reduce emissions. Green spaces and the proximity to Lake Ontario help moderate air quality issues."
    },
    "telaviv": {
        "climate": "Tel Aviv enjoys a Mediterranean climate with hot, humid summers and mild, rainy winters. Summer temperatures reach 28-35°C (82-95°F) with high humidity, making the beach essential for cooling off. Winters are mild at 10-18°C (50-64°F) with occasional rain from November to March. Spring and fall offer ideal weather with warm days and pleasant evenings. The city enjoys over 300 sunny days per year.",
        "cost": "Tel Aviv is one of the world's most expensive cities, rivaling London and New York. Monthly costs range from $3,000-5,000 USD for a comfortable lifestyle. Rent for a central one-bedroom apartment averages $1,800-2,500 USD. Dining out is expensive with casual meals costing $15-25 USD. Groceries are pricey, especially imported goods. However, street food like falafel and hummus remains affordable. Coworking spaces cost $300-500 USD monthly.",
        "wifi": "Israel has excellent internet infrastructure, and Tel Aviv offers widespread high-speed connectivity. Cafes and coworking spaces typically provide 50-150 Mbps connections. The city has a thriving startup scene with numerous modern coworking spaces in areas like Rothschild Boulevard and Sarona. Free WiFi is available in many public spaces. Mobile data is affordable and reliable with strong 4G/5G coverage throughout.",
        "nightlife": "Tel Aviv is legendary for its nightlife, often called the city that never sleeps. The party scene starts late, with clubs opening around midnight and going until sunrise. Rothschild Boulevard and Allenby Street feature trendy bars and clubs. The Florentin neighborhood offers underground venues and alternative scenes. Beach bars provide sunset drinks and music. Thursday and Friday nights are the biggest going-out nights due to Shabbat.",
        "nature": "While Tel Aviv is an urban center, nature is never far away. The city boasts a stunning 14-kilometer Mediterranean beach perfect for swimming, surfing, and sunset watching. Yarkon Park offers 3.5 square kilometers of green space with walking trails and boat rentals. Day trips to the Dead Sea, Negev Desert, and Golan Heights are easily accessible. The nearby Judean Mountains offer hiking within an hour's drive.",
        "safety": "Tel Aviv is generally very safe for visitors and residents, with low crime rates despite geopolitical tensions in the region. Street crime is rare, and walking alone at night is common. The city has visible security presence at malls and public venues. While regional conflicts can occasionally affect the area, the city itself maintains normalcy. LGBTQ+ travelers will find Tel Aviv exceptionally welcoming and safe.",
        "food": "Tel Aviv's food scene is extraordinary, blending Middle Eastern traditions with global influences. Fresh hummus, falafel, and shakshuka are local staples of exceptional quality. The Carmel Market offers vibrant produce and street food. The city has embraced veganism like few others, with plant-based options everywhere. High-end restaurants showcase innovative Israeli cuisine. Breakfast culture is celebrated with elaborate spreads at cafes citywide.",
        "community": "Tel Aviv has a thriving digital nomad and expat community, centered around its famous startup ecosystem. The city attracts tech workers, entrepreneurs, and creatives from around the world. Numerous coworking spaces host regular networking events. The local culture is direct and social, making it easy to connect with both locals and foreigners. Facebook groups and Meetups cater to various interests and nationalities.",
        "english": "English is widely spoken in Tel Aviv, especially among younger generations and in the tech industry. Most restaurant menus, signs, and services are available in English. Hebrew knowledge is helpful for deeper cultural immersion but not necessary for daily life. The international business environment means English is commonly used in professional settings. Service industry workers typically speak good English.",
        "visa": "Israel offers visa-free entry for citizens of many countries, allowing stays of up to 90 days. Tourist visas can sometimes be extended. There's no specific digital nomad visa, so long-term stays require creative visa runs or other arrangements. Work visas are available for those with job offers from Israeli companies. The B-1 work visa is an option for remote workers with foreign employers in some cases.",
        "culture": "Tel Aviv is a cultural melting pot, combining Middle Eastern heritage with cosmopolitan modernity. The city is known for its progressive, liberal attitudes, particularly regarding LGBTQ+ rights, making it a haven in the region. Art galleries, museums, and street art flourish throughout. The Bauhaus architecture in the White City is UNESCO-listed. Religious observance is less prominent here than in Jerusalem, though Shabbat still affects Friday evening activities.",
        "cleanliness": "Tel Aviv is reasonably clean but shows typical urban wear. Beaches are well-maintained with daily cleaning during summer. Streets can be dusty, and some older areas show graffiti. The city invests in public space maintenance. Recycling infrastructure exists but isn't as developed as in some European cities. The Yarkon River area and beachfront are kept particularly tidy. Construction is ongoing in many areas.",
        "airquality": "Tel Aviv has moderate air quality, with occasional poor conditions during heat waves or when dust blows in from the desert. The sea breeze helps clear pollution along the coast. Traffic contributes to emissions, though the city is working on expanding public transit. The Air Quality Index typically remains in acceptable ranges. Summer humidity can make the air feel heavy even when technically clean."
    },
    "thessaloniki": {
        "climate": "Thessaloniki has a transitional Mediterranean climate with hot summers and cool, wet winters. Summer temperatures reach 30-35°C (86-95°F) with manageable humidity. Winters are mild but rainy, with temperatures around 5-12°C (41-54°F) and occasional cold snaps. Spring and autumn are ideal seasons with pleasant temperatures perfect for exploring. The city enjoys good sunshine year-round, though less intense than southern Greece.",
        "cost": "Thessaloniki offers excellent value compared to Western Europe. Monthly costs range from €1,200-1,800 for a comfortable lifestyle. Rent for a central one-bedroom apartment averages €400-600, significantly cheaper than Athens. Meals at local tavernas cost €8-15, while upscale dining remains affordable. Groceries are reasonable, especially at the historic markets. Coffee culture is strong with espresso around €2-3. Coworking spaces cost €100-200 monthly.",
        "wifi": "Internet infrastructure in Thessaloniki has improved significantly, with most cafes and accommodations offering 20-50 Mbps connections. Coworking spaces provide reliable high-speed internet. The city's student population has driven demand for good connectivity. Mobile data is affordable with Greek carriers offering competitive EU roaming packages. Some older buildings may have slower connections, so verify speeds when booking accommodation.",
        "nightlife": "Thessaloniki's nightlife rivals Athens, concentrated in the Ladadika and Valaoritou neighborhoods. The city's large student population creates a vibrant, year-round scene. Bars and clubs feature everything from traditional Greek music to international DJs. The waterfront comes alive with bars offering Thermaikos Gulf views. Greeks eat and go out late, with dinner starting around 10 PM and clubs filling after midnight. Summer brings beach bars along nearby coasts.",
        "nature": "Thessaloniki offers easy access to diverse natural landscapes. The waterfront promenade stretches 5 kilometers along the Thermaikos Gulf, perfect for walking and cycling. Mount Olympus is just 90 minutes away for hiking among the gods. Halkidiki peninsula offers pristine beaches and pine forests within an hour. The city has several urban parks and the old town's hillside provides panoramic views. Day trips to stunning monasteries of Meteora are popular.",
        "safety": "Thessaloniki is very safe by European standards, with low violent crime rates. The city center is walkable at all hours, and locals often stroll late into the night. Pickpocketing can occur in crowded areas like markets and transit, so basic precautions apply. Political protests occasionally occur but are typically peaceful. The strong community feel and family-oriented culture contribute to overall security. Solo travelers generally feel comfortable.",
        "food": "Thessaloniki is considered Greece's culinary capital, with a food scene shaped by its multicultural Ottoman and Sephardic history. Don't miss bougatsa (cream-filled pastry), koulouri (sesame bread rings), and traditional meze at old-town tavernas. The Modiano and Kapani markets overflow with fresh produce, olives, and local specialties. Seafood restaurants line the waterfront. The coffee culture is sacred, with countless cafes serving excellent Greek coffee and freddo espresso.",
        "community": "Thessaloniki has a growing digital nomad scene, though smaller than Athens. The city's universities bring international students and researchers. Several coworking spaces cater to remote workers, with communities forming around places like Stone Soup and OK Thess. The local entrepreneurial scene is developing with startup events and tech meetups. Greeks are warm and social, making integration into local circles possible with effort.",
        "english": "English proficiency is good in Thessaloniki, especially among younger people and those in tourism. University students and professionals often speak excellent English. Restaurant menus in tourist areas are typically in English. However, deeper into local neighborhoods, Greek becomes more necessary. Learning basic Greek phrases is appreciated and helps with daily interactions. Signage is generally bilingual in central areas.",
        "visa": "Greece is part of the Schengen Area, allowing visa-free stays of up to 90 days within a 180-day period for citizens of many countries. Digital nomad visas are available for non-EU citizens, requiring proof of remote income (minimum €3,500/month) and allowing stays up to one year. EU citizens can stay indefinitely. Long-term visas require registration with local authorities after 90 days.",
        "culture": "Thessaloniki's culture reflects its rich Byzantine, Ottoman, and Jewish heritage. The White Tower and Roman ruins coexist with Byzantine churches and modern street art. The city hosts numerous cultural festivals, including the Thessaloniki International Film Festival. Locals take pride in their distinct identity from Athens. The café culture is central to social life, with people spending hours over coffee. Museums showcase the city's layered history.",
        "cleanliness": "Thessaloniki is reasonably clean, though some areas show urban wear and graffiti. The waterfront and tourist areas are well-maintained. Side streets in older neighborhoods can be less tidy. The municipal government has worked to improve cleanliness in recent years. Markets and food areas maintain good hygiene standards. Public restrooms are limited, though cafes are welcoming if you make a purchase.",
        "airquality": "Thessaloniki has moderate air quality, with traffic and industrial activities contributing to pollution. Winter can bring smog, particularly during temperature inversions. The sea breeze helps clear the air, especially along the waterfront. Summer air quality is generally better but can be affected by regional wildfires. The city is working on improving public transit to reduce emissions. Check daily indexes if you have respiratory sensitivities."
    },
    "tulum": {
        "climate": "Tulum enjoys a tropical climate with warm weather year-round. The dry season from November to April brings temperatures of 25-30°C (77-86°F) with low humidity and minimal rain. The rainy season from May to October features afternoon showers, higher humidity, and temperatures reaching 32°C (90°F). Hurricane season peaks August-October, though direct hits are relatively rare. Sea breezes moderate the heat along the coast.",
        "cost": "Tulum has become increasingly expensive, particularly in the trendy beach zone. Monthly costs range from $1,500-3,500 USD depending on lifestyle and location. Beach zone accommodations can cost $100-300+ per night, while pueblo (town) options are more reasonable at $600-1,200 monthly for apartments. Meals range from $3-5 at local taquerias to $20-50 at upscale beach clubs. Cenote visits cost $5-20 each. Coworking spaces charge $150-300 monthly.",
        "wifi": "Internet in Tulum has historically been unreliable, though infrastructure is improving. Beach zone connections can be spotty and slow. The pueblo generally has better connectivity, with coworking spaces like Digital Jungle and Mayan Monkey offering reliable speeds of 30-100 Mbps. Many cafes now cater to remote workers with improved WiFi. Consider having a backup mobile hotspot with Telcel for important calls. Starlink is becoming available in some locations.",
        "nightlife": "Tulum's nightlife is famous for its unique jungle party scene. Beach clubs like Papaya Playa Project host legendary full moon parties. The hotel zone features upscale bars with electronic music and bohemian vibes. The pueblo has a more local scene with mezcal bars and rooftop lounges. Nights start late, with parties often running until sunrise. The scene attracts international DJs and a glamorous crowd, especially during peak season.",
        "nature": "Tulum is blessed with extraordinary natural beauty. The Caribbean coastline features powdery white sand beaches with turquoise waters. The region boasts thousands of cenotes—crystal-clear freshwater sinkholes perfect for swimming and diving. The nearby Sian Ka'an Biosphere Reserve protects coastal wetlands and diverse wildlife. Ancient Mayan ruins sit dramatically on cliffs overlooking the sea. Snorkeling with sea turtles is possible just offshore.",
        "safety": "Tulum is generally safe for tourists, though it's important to stay aware of your surroundings. Petty theft can occur, especially from unattended items on beaches. The main concerns involve scams targeting tourists and occasional reports of drink spiking at parties. Stick to well-lit areas at night and use reputable transportation. The police presence has increased in tourist zones. Most visitors experience no issues with basic precautions.",
        "food": "Tulum's food scene ranges from authentic Mexican street food to high-end wellness cuisine. Taquerias in the pueblo serve delicious al pastor and cochinita pibil for a few dollars. The beach zone features trendy restaurants focusing on fresh seafood and plant-based cuisine. Many places emphasize organic, locally-sourced ingredients. Ceviche and fresh fish are standouts. The wellness culture means plenty of açaí bowls and smoothie spots. Markets offer fresh tropical fruits.",
        "community": "Tulum has attracted a large digital nomad and expat community, creating an international bubble within Mexico. You'll meet remote workers, entrepreneurs, yoga instructors, and crypto enthusiasts. Coworking spaces host networking events and workshops. The community can feel transient, with people constantly arriving and departing. Facebook groups and Meetups help newcomers connect. The wellness and spiritual community is particularly strong.",
        "english": "English is widely spoken in Tulum's tourist areas, where many service workers are bilingual or international expats. In the beach zone and at hotels, English is often the default language. The pueblo maintains more Spanish character, though most businesses catering to tourists speak English. Learning Spanish significantly enhances your experience and is essential for deeper cultural immersion and navigating outside tourist bubbles.",
        "visa": "Mexico offers generous visa-free entry to citizens of many countries, with tourism permits valid for up to 180 days. This is automatically granted upon arrival. Extensions are possible but involve bureaucratic processes. There's no specific digital nomad visa, so most remote workers enter as tourists. Technically, working requires a work permit, but enforcement for remote workers is minimal. Long-term stays often involve visa runs to nearby countries.",
        "culture": "Tulum blends ancient Mayan heritage with modern international influences. The famous cliff-top ruins connect visitors to the region's pre-Columbian past. The contemporary scene is shaped by wellness culture, yoga, and spiritual practices that attract seekers worldwide. This has created a somewhat artificial bubble distinct from traditional Mexican culture. Venturing beyond tourist areas reveals authentic Yucatecan traditions and communities worth exploring.",
        "cleanliness": "Tulum faces environmental challenges due to rapid development outpacing infrastructure. The beach zone is generally well-maintained, though sargassum seaweed can affect beaches seasonally (especially May-August). The pueblo has typical small-town cleanliness. Tap water is not drinkable. The region struggles with waste management and protecting cenotes from contamination. Many eco-conscious businesses are working on sustainability initiatives.",
        "airquality": "Tulum has generally good air quality, benefiting from coastal breezes and limited industrial activity. The main pollutant is dust from unpaved roads, particularly noticeable when cycling. Jungle and beach areas offer fresh air. Mosquitoes can be a significant nuisance, especially near cenotes and at dusk. The humidity can feel heavy but is typical of tropical destinations. No major air quality concerns for most visitors."
    },
    "valencia": {
        "climate": "Valencia enjoys a Mediterranean climate with hot summers and mild winters, boasting over 300 sunny days annually. Summer temperatures reach 28-35°C (82-95°F) with refreshing sea breezes. Winters are mild at 10-17°C (50-63°F) with occasional rain. Spring and autumn offer ideal weather for exploring. The famous Las Fallas festival in March celebrates the arrival of spring. Beach season extends from May through October.",
        "cost": "Valencia offers excellent value for a Spanish city, cheaper than Barcelona or Madrid. Monthly costs range from €1,500-2,500 for a comfortable lifestyle. Rent for a central one-bedroom apartment averages €800-1,200, with better deals in neighborhoods like Ruzafa or Benimaclet. Meals at local restaurants cost €10-20. The famous menu del día lunch specials offer three courses for €12-15. Coworking spaces range from €150-300 monthly.",
        "wifi": "Valencia has excellent internet infrastructure with widespread fiber optic coverage. Most cafes and coworking spaces offer 50-200 Mbps connections. The city has numerous coworking options catering to the growing digital nomad community, including Wayco and The Shed. Libraries and public spaces offer free WiFi. Mobile data is affordable with Spanish carriers offering competitive EU packages. Residential internet averages 100+ Mbps.",
        "nightlife": "Valencia's nightlife centers around the Barrio del Carmen and Ruzafa neighborhoods. El Carmen's medieval streets fill with bars and clubs on weekends, ranging from traditional bodegas to modern cocktail bars. Ruzafa offers a trendier scene with wine bars and late-night venues. The waterfront area has beach clubs and terrace bars. Spanish nightlife starts late, with dinner around 10 PM and clubs filling after 1 AM. Summer brings outdoor events and festivals.",
        "nature": "Valencia combines urban life with excellent natural access. The city boasts wide beaches just minutes from the center, including Malvarrosa and Patacona. The Turia Gardens, a 9-kilometer park converted from a former riverbed, runs through the city offering cycling and jogging paths. The Albufera Natural Park provides wetlands, rice paddies, and lake boat rides just 10 kilometers south. Mountains with hiking trails are within an hour's drive.",
        "safety": "Valencia is one of the safest cities in Spain, with low crime rates and a relaxed atmosphere. The city center is walkable at all hours, and locals enjoy late-night strolls. Pickpocketing occurs in tourist areas and beaches, so keep valuables secure. No areas are considered dangerous for tourists. The strong community feel and family-oriented culture contribute to safety. Solo travelers, including women, generally feel very comfortable.",
        "food": "Valencia is the birthplace of paella, and authentic versions here surpass those found anywhere else in Spain. The traditional Valencian paella features rabbit and chicken, while seafood versions are also spectacular. The Mercado Central is one of Europe's largest and most beautiful food markets. Fresh horchata and fartons are local treats. The city has embraced modern cuisine too, with innovative restaurants and a strong tapas culture.",
        "community": "Valencia has a thriving digital nomad community that has grown significantly in recent years. The city's affordability, climate, and quality of life attract remote workers from across Europe and beyond. Coworking spaces host regular events and meetups. Language exchange gatherings are popular. The expat community is well-established with various social groups. Locals are generally welcoming, though integrating fully requires Spanish language skills.",
        "english": "English proficiency in Valencia is moderate—better among younger generations and in tourist areas. Service industry workers in central locations often speak English. However, outside tourist zones, Spanish is essential. The city is less international than Barcelona, so learning Spanish significantly improves daily life and social opportunities. University areas and coworking spaces have more English speakers.",
        "visa": "Spain is part of the Schengen Area, allowing visa-free stays of up to 90 days within a 180-day period for citizens of many countries. Spain offers a digital nomad visa requiring proof of remote income (minimum €2,160/month) and health insurance, allowing stays up to one year with renewal options. The non-lucrative visa is another option for those with savings. EU citizens can stay indefinitely.",
        "culture": "Valencia blends traditional Spanish culture with a progressive, Mediterranean identity. The spectacular City of Arts and Sciences represents modern ambition, while the old town preserves Gothic and Baroque architecture. Las Fallas festival in March features massive sculptures and 24-hour celebrations. The city takes siesta culture seriously, with many shops closing midday. Locals are proud of their Valencian language and distinct identity from Madrid and Catalonia.",
        "cleanliness": "Valencia is notably clean for a Spanish city, with well-maintained streets and public spaces. The beaches are cleaned daily during summer. The historic center and modern areas are kept tidy. Parks and gardens are beautifully maintained. Public restrooms are available in markets and shopping areas. The city has invested in infrastructure improvements and takes pride in its appearance. Recycling facilities are widely available.",
        "airquality": "Valencia has good air quality, benefiting from sea breezes and relatively low industrial activity. The city has implemented traffic restrictions and expanded cycling infrastructure to reduce emissions. Summer can bring occasional heat-related air quality alerts. The extensive parks and gardens contribute to cleaner air. Most days fall within healthy ranges on the Air Quality Index. The proximity to the sea helps moderate any pollution."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")

    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
