#!/usr/bin/env python3
"""Rewrite batch 16: Cartagena, Santiago, Montevideo, Penang, Da Nang."""

import json
import os

BATCH_CITIES = {
    "cartagena": {
        "climate": "Cartagena has a hot tropical climate with temperatures around 28-34°C (82-93°F) year-round. The dry season (December-April) brings less humidity and is the most pleasant for exploring. The wet season (May-November) features afternoon downpours that cool things down. Sea breezes moderate the heat along the coast. Humidity is consistently high. Air conditioning is essential for comfortable sleep. Hurricane risk is minimal.",
        "cost": "Cartagena is more expensive than other Colombian cities due to tourism. Monthly costs range from $1,400-2,500 USD for a comfortable lifestyle. Rent for a one-bedroom apartment averages $700-1,200 in the walled city or Bocagrande, cheaper in Getsemaní or outer areas. Restaurant meals run $10-25, while street food costs $3-6. Tourist area prices are inflated. Coworking spaces cost $120-250 monthly.",
        "wifi": "Internet in Cartagena is generally reliable but slower than Bogotá. Most cafes and restaurants offer 15-40 Mbps connections. Coworking spaces like Selina and Clockwork provide more consistent speeds. Some historic buildings in the walled city have connectivity challenges. Having a mobile data backup (Claro or Movistar) is recommended. Newer apartments and hotels tend to have better internet infrastructure.",
        "nightlife": "Cartagena's nightlife centers around Getsemaní and the walled city's Plaza de los Coches. Rooftop bars offer colonial city views and sea breezes. Salsa clubs let you practice moves with locals. Beach clubs like Decameron host parties. The scene gets livelier on weekends, with pre-gaming at outdoor bars before heading to clubs. Champeta music (Afro-Caribbean) pulses through street parties. Nights extend until dawn.",
        "nature": "Cartagena offers Caribbean beauty within reach. Rosario Islands provide white sand beaches and snorkeling just an hour by boat. Playa Blanca on Barú Island is the most famous beach escape. Mangrove tours explore coastal ecosystems. Volcán del Totumo lets you bathe in a mud volcano. Day trips to Minca in the Sierra Nevada combine beaches with mountain cool. The old city walls themselves offer sunset strolls along the sea.",
        "safety": "Cartagena is generally safe for tourists but requires awareness. The walled city and Bocagrande are well-patrolled. Petty theft occurs, particularly around beaches and busy areas—keep valuables secure. Avoid empty streets in the walled city late at night. Scams targeting tourists exist. Some areas outside the tourist zones are best avoided. Beach vendors can be persistent. Most visitors experience no problems with basic precautions.",
        "food": "Cartagena's cuisine reflects Afro-Caribbean influences alongside Colombian traditions. Fresh seafood is exceptional—try coconut rice with fried fish or ceviche. Arepa de huevo (egg-filled corn cakes) are beloved street food. Caribbean fruits like níspero and mamoncillo appear at markets. The walled city has upscale restaurants with innovative takes on traditional dishes. Bazurto market offers authentic local eating. Coco loco (coconut cocktail) is the signature drink.",
        "community": "Cartagena has a smaller digital nomad community than Medellín, attracting those preferring beaches over mountains. Coworking spaces host networking events. The expat scene includes retirees, real estate investors, and remote workers. The international atmosphere is concentrated in tourist areas. Spanish is more necessary here than in larger Colombian cities. Some nomads divide time between Cartagena and other Colombian destinations.",
        "english": "English proficiency in Cartagena is moderate, better than average for Colombia due to tourism. Hotels, tourist restaurants, and tour guides speak English. Local neighborhoods and everyday services require Spanish. Younger Colombians may have basic English. Spanish significantly improves your experience and is practically necessary outside tourist bubbles. Language schools offer intensive courses for those staying longer.",
        "visa": "Colombia offers visa-free entry for citizens of many countries, allowing stays of up to 90 days. Extensions are available through Migración Colombia for another 90 days. The digital nomad visa allows stays up to 2 years for remote workers, requiring proof of income and health insurance. Work visas require employer sponsorship. Colombia has become increasingly welcoming to remote workers.",
        "culture": "Cartagena blends Spanish colonial heritage with Afro-Caribbean culture. The UNESCO-listed walled city showcases 16th-century architecture with colorful buildings and flower-draped balconies. Gabriel García Márquez made the city famous in his novels. Music and dance are central—cumbia and champeta rhythms fill the streets. Afro-Colombian influence is visible in food, music, and festivals. The city balances preservation with tourism pressures.",
        "cleanliness": "The walled city and tourist areas are well-maintained with regular street cleaning. Getsemaní has a grittier charm. Beach areas vary—resort beaches are clean while public beaches may have litter. Markets are busy but reasonable. Tap water is not safe to drink. Air quality is generally good with sea breezes. Some areas outside the old city show more urban challenges. The colonial beauty is mostly well-preserved.",
        "airquality": "Cartagena has generally good air quality, benefiting from Caribbean sea breezes. The coastal location prevents pollution buildup. Traffic emissions affect some areas but are less severe than landlocked cities. Heat and humidity can feel heavy but don't indicate poor air quality. The sea air is fresh along the waterfront. No major industrial pollution exists in the tourist areas."
    },
    "santiago": {
        "climate": "Santiago has a Mediterranean climate with hot, dry summers (December-February) reaching 30-35°C (86-95°F) and cool, rainy winters (June-August) around 5-15°C (41-59°F). Spring and autumn offer ideal conditions with mild temperatures. The Andes mountains are visible on clear days but smog often obscures them. Four distinct seasons make weather variable. Summer is peak season with longer days.",
        "cost": "Santiago offers moderate costs for South America, cheaper than Brazil but pricier than Colombia. Monthly costs range from $1,400-2,400 USD for a comfortable lifestyle. Rent for a central one-bedroom apartment averages $600-1,000 in Providencia or Las Condes. Restaurant meals cost $10-20, with set lunches around $5-8. Transportation is efficient and affordable. Coworking spaces cost $150-300 monthly.",
        "wifi": "Chile has excellent internet infrastructure, among the best in South America. Santiago cafes and coworking spaces typically offer 50-150 Mbps connections. The city has numerous coworking options including WeWork and local spaces like If. Residential areas have reliable fiber connections. Mobile data through Entel or Movistar provides strong backup. Overall connectivity is reliable and fast throughout the city.",
        "nightlife": "Santiago's nightlife centers around Bellavista, Lastarria, and Providencia neighborhoods. Bellavista offers everything from dive bars to upscale clubs. Barrio Italia has hipster wine bars and cocktail spots. The electronic music scene is strong with clubs like La Feria. Thursdays through Saturdays are busiest, with parties extending until early morning. Wine bars showcase Chilean vintages. The scene caters to diverse tastes and budgets.",
        "nature": "Santiago sits in a valley surrounded by the Andes, offering exceptional nature access. Skiing at Valle Nevado, Portillo, or La Parva is within 90 minutes. Cerro San Cristóbal provides city views and hiking within the city. The Cajón del Maipo valley offers trekking, rafting, and hot springs. Viña del Mar and Valparaíso beaches are 90 minutes away. Wine country tours visit world-class vineyards in the Maipo Valley.",
        "safety": "Santiago is relatively safe for South America but requires awareness. Wealthy neighborhoods like Providencia and Las Condes are very safe. Petty theft and pickpocketing occur in metro stations and crowded areas. Avoid displaying expensive items. Some neighborhoods like parts of downtown can feel sketchy at night. Social protests occasionally flare up. Most visitors experience no problems with basic precautions. Police presence is visible.",
        "food": "Chilean cuisine features excellent seafood and unique specialties. Try pastel de choclo (corn pie), empanadas, and completos (loaded hot dogs). The seafood at Mercado Central is legendary. Wine pairing with Chilean reds enhances any meal. Modern restaurants in Lastarria and Providencia showcase innovative cuisine. Street food includes sopaipillas and mote con huesillo (wheat berry drink). The foodie scene has grown significantly.",
        "community": "Santiago has a developing digital nomad community, smaller than Buenos Aires but growing. Coworking spaces host events for remote workers. The startup ecosystem attracts entrepreneurs from across Latin America. Language exchange meetups are popular. The expat community includes business professionals and international students. Integration takes effort but Chileans are welcoming. Spanish proficiency helps significantly with social connections.",
        "english": "English proficiency in Santiago is moderate, better in business districts and among younger professionals. Tourist areas handle English reasonably well. Local neighborhoods and everyday services typically require Spanish. The business environment operates increasingly with English. Learning Spanish significantly improves your experience and opens doors to local culture. Many nomads take intensive classes while staying.",
        "visa": "Chile offers visa-free entry for citizens of many countries, typically allowing stays of 90 days. Extensions are possible through immigration offices. There's no specific digital nomad visa, so remote workers enter as tourists. Work visas require employer sponsorship. Chile has a straightforward residency pathway for those with income or investment. The immigration system is more organized than some neighbors.",
        "culture": "Santiago blends European influence with Chilean identity. The city has excellent museums, including the Pre-Columbian Art Museum. Street art scenes thrive in Bellavista and Barrio Brasil. Literature and poetry have strong traditions (Pablo Neruda, Isabel Allende). Wine culture is central to social life. Chileans are known as more reserved than other Latin Americans. Fiestas patrias (September) brings national celebrations.",
        "cleanliness": "Santiago is one of South America's cleanest cities. Providencia and Las Condes maintain high standards. The metro system is modern and well-maintained. Some central areas and parks can be grittier. The city has invested in infrastructure improvements. Air quality is the main environmental concern rather than street cleanliness. Tap water is safe to drink. Recycling programs are developing.",
        "airquality": "Santiago has significant air quality problems due to geography and emissions. The city sits in a valley where pollution gets trapped, particularly in winter. Smog alerts are common from May to August. Summer air quality is generally better. The government implements restrictions during alerts. The Andes are often invisible behind haze. Sensitive individuals should monitor conditions and consider masks during poor air days."
    },
    "montevideo": {
        "climate": "Montevideo has a humid subtropical climate with warm summers and mild winters. Summer temperatures (December-February) reach 25-30°C (77-86°F), perfect for beach days. Winters (June-August) are cool at 7-15°C (45-59°F) with occasional cold snaps. Rain falls throughout the year, slightly more in autumn. Spring and autumn offer pleasant conditions. The Río de la Plata moderates temperature extremes.",
        "cost": "Uruguay is expensive by South American standards, and Montevideo reflects this. Monthly costs range from $1,600-2,800 USD for a comfortable lifestyle. Rent for a central one-bedroom apartment averages $700-1,100 in Pocitos or Ciudad Vieja. Restaurant meals cost $15-30, significantly more than neighboring countries. Groceries are pricey. Public transport is reasonable. Coworking spaces cost $150-300 monthly.",
        "wifi": "Uruguay has excellent internet infrastructure, leading South America in connectivity. Montevideo cafes and coworking spaces typically offer 50-150 Mbps connections. The city has reliable fiber optic throughout most neighborhoods. Coworking spaces like Sinergia and WeWork provide fast, consistent connectivity. Mobile data through Antel, Movistar, or Claro offers strong coverage. Internet quality is rarely a concern.",
        "nightlife": "Montevideo's nightlife is relaxed compared to Buenos Aires, centered around Ciudad Vieja, Pocitos, and Palermo neighborhoods. Bar hopping in Ciudad Vieja features historic pubs and trendy spots. Live music venues showcase local talent and tango. Craft beer has exploded with numerous local breweries. Nights start late (dinner at 10 PM, clubs after midnight) in typical River Plate fashion. The scene is friendly and unpretentious.",
        "nature": "Montevideo offers urban beaches along the Rambla promenade, perfect for walks and sunset views. Pocitos and Carrasco beaches provide sandy escapes within the city. Punta del Este resort town is 2 hours east for more dramatic coastline. Colonia del Sacramento offers historic charm and day trip potential. The countryside (campo) features estancias for rural escapes. Cabo Polonio provides wild, off-grid beach experiences.",
        "safety": "Montevideo is relatively safe by regional standards but has seen increased crime recently. Central areas like Pocitos and Ciudad Vieja are generally safe, though petty theft occurs. Avoid displaying expensive items. Some outlying neighborhoods should be avoided at night. Exercise normal urban precautions. The overall atmosphere is calm and welcoming. Most visitors experience no problems with awareness.",
        "food": "Uruguayan cuisine centers on beef—the parrillas (grills) here rival Argentina's. Chivito (loaded steak sandwich) is a national treasure. Asado (barbecue) is a weekend social institution. Italian influence shows in pasta and pizza. Mercado del Puerto offers atmospheric asado dining. Dulce de leche appears in everything sweet. Wine from Tannat grapes pairs perfectly with meat. The food scene is meat-heavy but delicious.",
        "community": "Montevideo has a small but growing digital nomad community. The city attracts those seeking safety, stability, and quality of life over excitement. Coworking spaces host events connecting remote workers. The expat community includes professionals, retirees, and entrepreneurs. Uruguayans are welcoming but social circles form slowly. Spanish proficiency helps significantly. Some nomads find it quiet but appreciate the relaxed pace.",
        "english": "English proficiency in Montevideo is moderate, good among younger people and professionals. Tourist areas and international businesses handle English. Local neighborhoods and everyday services often require Spanish. The business environment uses more English than daily life. Learning Spanish significantly improves your experience and social opportunities. The international school community provides English connections.",
        "visa": "Uruguay offers visa-free entry for citizens of many countries, typically allowing stays of 90 days. Extensions are possible and relatively straightforward. Uruguay is known for its welcoming immigration policies and path to residency. There's no specific digital nomad visa but tourist status works for most stays. Residency options include income, investment, or company formation routes. The bureaucracy is manageable.",
        "culture": "Uruguayan culture blends River Plate traditions with progressive values. Tango and milonga music echo Argentina. Mate drinking is obsessive—locals carry thermoses everywhere. The country leads Latin America in social progressiveness (legal marijuana, same-sex marriage, secular society). Carnival celebrations rival Rio's. Football passion runs deep. Art and literature flourish. The pace of life is notably relaxed. Sunday asados are sacred.",
        "cleanliness": "Montevideo is clean by South American standards. The Rambla promenade is well-maintained. Pocitos and upscale neighborhoods are tidy. Ciudad Vieja shows some urban wear but is generally clean. Parks and beaches are kept reasonably well. Public transport is clean and functional. Tap water is safe to drink. The city takes pride in livability. Some construction zones can be messy.",
        "airquality": "Montevideo has good air quality, benefiting from coastal breezes and limited industrial activity. The Río de la Plata location keeps air fresh. Traffic emissions are lower than larger South American capitals. Air quality indexes typically show healthy levels. Occasional dust from construction or regional conditions can affect quality briefly. The clean environment is a city highlight."
    },
    "penang": {
        "climate": "Penang has a tropical rainforest climate with consistent heat and humidity year-round. Temperatures range from 27-33°C (81-91°F) daily. Rain falls throughout the year, with heavier periods from September to November and April to May. Sea breezes moderate coastal heat. Air conditioning is essential for comfortable sleep. The climate rarely varies, providing predictable warmth. Afternoon thunderstorms are common.",
        "cost": "Penang offers excellent value, even cheaper than Kuala Lumpur. Monthly costs range from $1,000-1,800 USD for a comfortable lifestyle. Rent for a central one-bedroom apartment averages $400-700 in George Town. Street food meals cost $1-3, making eating out very affordable. Restaurant dining runs $5-15. Coworking spaces cost $80-200 monthly. Transportation is cheap with rides around RM 5-15.",
        "wifi": "Malaysia has excellent internet infrastructure, and Penang offers reliable connectivity. Most cafes and coworking spaces provide 30-100 Mbps connections. George Town has numerous digital nomad-friendly venues. Coworking spaces like Common Ground and local options provide fast, consistent connections. Residential internet is affordable and reliable. Mobile data through Maxis or Digi offers strong 4G coverage throughout the island.",
        "nightlife": "Penang's nightlife is more laid-back than Kuala Lumpur, centered around George Town's Armenian Street, Chulia Street, and Upper Penang Road. Rooftop bars offer heritage building views. Live music venues showcase local bands. The craft beer scene has grown significantly. Beach bars at Batu Ferringhi cater to tourists. Nights wind down earlier than major party destinations. The vibe is relaxed and social rather than club-focused.",
        "nature": "Penang Island combines urban exploration with natural escapes. Penang Hill provides cooler temperatures and panoramic views, accessible by funicular. Penang National Park offers jungle trekking and beaches. Tropical Spice Garden educates about regional flora. The Botanic Gardens provide lush green space. Batu Ferringhi beach is the main swimming area. Teluk Bahang offers water activities. The surrounding waters have diving opportunities.",
        "safety": "Penang is very safe for Southeast Asia, with low crime rates and a welcoming atmosphere. George Town is walkable day and night. Petty theft is rare but possible—keep valuables secure. Traffic is the main hazard, particularly when walking and cycling. No areas are considered dangerous for tourists. The multicultural community is tolerant and friendly. Solo travelers of all backgrounds feel comfortable.",
        "food": "Penang is legendary as one of Asia's greatest food destinations. The hawker culture offers Chinese, Malay, Indian, and Peranakan cuisines at incredible value. Char kway teow, Penang laksa, and nasi kandar are must-tries. Lorong Baru hawker center and Gurney Drive food court are excellent starting points. Heritage flavors distinguish Penang food from other Malaysian cities. Vegetarian options abound in Little India. The food scene alone justifies extended stays.",
        "community": "Penang has a thriving digital nomad community drawn by food, affordability, and quality of life. Coworking spaces and cafes serve as community hubs. Regular meetups and networking events connect remote workers. The expat community is diverse and welcoming. Long-term nomads often return season after season. The pace of life allows for genuine relationship building. George Town's human scale fosters community.",
        "english": "English proficiency in Penang is excellent, a legacy of British colonial rule and multicultural society. Most Penangites speak English well, particularly in George Town. Business, signage, and daily life operate smoothly in English. Menus are typically in English with Chinese and Malay. The international atmosphere means language barriers are rare. Learning basic Malay phrases is appreciated but not necessary.",
        "visa": "Malaysia offers visa-free entry for citizens of many countries, typically allowing stays of 90 days. Extensions are possible through immigration but require leaving and re-entering. The DE Rantau digital nomad visa launched for remote workers, allowing stays up to 12 months with income requirements. Work passes require employer sponsorship. Visa runs to Thailand or Singapore are common for longer stays.",
        "culture": "Penang's culture reflects its Straits Chinese (Peranakan) heritage blended with Malay, Indian, and colonial influences. George Town's UNESCO-listed historic core showcases this multicultural past through architecture, temples, and clan houses. Street art has transformed the city into an open-air gallery. Festival calendar includes Chinese New Year, Thaipusam, and Deepavali. The heritage preservation is exceptional. Food culture is central to identity.",
        "cleanliness": "George Town is reasonably clean with regular street cleaning in tourist areas. The historic center is well-maintained. Some side streets and local neighborhoods are grittier. Markets are bustling but reasonably hygienic. Beaches at Batu Ferringhi are kept tidy. Public restrooms vary in cleanliness—malls are reliable. Tap water is not recommended for drinking. The heritage buildings are carefully preserved.",
        "airquality": "Penang generally has good air quality but is affected by regional haze during certain months. The annual burning season (typically August-October) in Indonesia can bring thick smoke. Sea breezes usually keep air fresh outside haze periods. Air quality indexes are typically healthy most of the year. Check conditions before travel during haze season. The island location helps clear pollution."
    },
    "danang": {
        "climate": "Da Nang has a tropical monsoon climate with distinct dry (February-August) and wet (September-January) seasons. Summer temperatures reach 28-35°C (82-95°F) with high humidity. Winter brings cooler weather around 20-25°C (68-77°F) with frequent rain and occasional flooding. September-October sees typhoon risk. Beach season runs March-September. The climate is more temperate than southern Vietnam.",
        "cost": "Da Nang offers exceptional value, even cheaper than Ho Chi Minh City. Monthly costs range from $800-1,500 USD for a comfortable lifestyle. Rent for a modern one-bedroom apartment averages $300-600 with beach views possible. Street food meals cost $1-2, while restaurant dining runs $3-10. Beach clubs and international restaurants cost more. Coworking spaces cost $50-150 monthly. The value is outstanding.",
        "wifi": "Vietnam has invested heavily in internet infrastructure, and Da Nang offers reliable connectivity. Most cafes and coworking spaces provide 30-100 Mbps connections. The city has embraced digital nomads with numerous workspace options. Beach-area cafes often have workable WiFi. Residential internet is affordable and improving. Mobile data through Viettel or Mobifone provides strong backup. Some beach hotels have slower connections.",
        "nightlife": "Da Nang's nightlife is more relaxed than Saigon or Hanoi. Beach clubs and rooftop bars offer sunset drinks along My Khe Beach. The city center has bars and clubs catering to mixed local and foreign crowds. The scene is friendly and unpretentious. Weekend nights are busier but rarely wild. Hoi An (30 minutes away) offers alternative nightlife in a more atmospheric setting. Expect early nights compared to major cities.",
        "nature": "Da Nang combines stunning beaches with mountain scenery. My Khe Beach stretches for kilometers of white sand swimming. The Marble Mountains offer caves, pagodas, and panoramic views. Ba Na Hills features the famous Golden Bridge and cool mountain climate. Son Tra Peninsula has hiking and wildlife. Nearby Hoi An provides historic charm. Hai Van Pass offers dramatic coastal driving. The natural beauty is accessible and diverse.",
        "safety": "Da Nang is very safe with low crime rates and a relaxed atmosphere. Walking and cycling around the city is comfortable day and night. Petty theft is rare but keep valuables secure. Traffic is the main hazard—motorbike riding requires caution. No areas are considered dangerous. The beach and tourist zones are well-maintained. Scams targeting tourists are minimal compared to larger cities.",
        "food": "Da Nang's cuisine features Central Vietnamese specialties. Mi quang (turmeric noodles) and banh xeo (crispy pancakes) are local musts. Fresh seafood restaurants line the beach. Bun cha ca (fish cake noodle soup) is a breakfast staple. Con market offers food stalls and local atmosphere. Hoi An nearby adds cao lau noodles and white rose dumplings to your options. Street food is safe and incredibly cheap.",
        "community": "Da Nang has an established digital nomad community that has grown significantly. Coworking spaces serve as community hubs with regular events. The beach lifestyle attracts long-term remote workers. Facebook groups connect thousands of nomads. The scene is friendly and welcoming to newcomers. Some nomads bounce between Da Nang and other Vietnamese cities. The growing infrastructure caters specifically to remote workers.",
        "english": "English proficiency in Da Nang is moderate and improving, better in tourist areas and among younger people. Hotels, tourist restaurants, and coworking spaces handle English well. Local neighborhoods require basic Vietnamese or translation apps. The international nomad scene operates in English. Learning Vietnamese basics significantly improves daily interactions. Menus increasingly include English translations.",
        "visa": "Vietnam offers multiple visa options for digital nomads. The e-visa allows 90-day single-entry stays for many nationalities. 30-day visa exemptions exist for some countries. Longer stays typically involve visa runs or business visas through agencies. There's no official digital nomad visa, but 3-month business visas are commonly used. Visa regulations change frequently—verify current requirements before travel.",
        "culture": "Da Nang is a modern Vietnamese city with less historical weight than Hanoi or Hue. The city has invested heavily in development and infrastructure. Beach culture mixes with Vietnamese traditions. Nearby Hoi An and Hue provide historical depth. Buddhism remains influential with impressive pagodas. The Da Nang people are known as warm and welcoming. The city balances modernization with local character.",
        "cleanliness": "Da Nang is remarkably clean for Vietnam, reflecting modern development and city pride. Beaches are maintained regularly. Streets are swept and relatively litter-free. Public spaces are kept tidy. The city has invested in infrastructure and appearance. Markets are busy but cleaner than older cities. Tap water is not drinkable. The overall cleanliness exceeds expectations for Southeast Asia.",
        "airquality": "Da Nang has good air quality, benefiting from coastal location and limited heavy industry. Sea breezes keep the air fresh. Traffic emissions are lower than major Vietnamese cities. Air quality indexes typically show healthy levels. Occasional dust from construction affects some areas. The clean air is a notable advantage over Hanoi or Ho Chi Minh City. Beach and mountain areas offer particularly fresh air."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")

    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
