#!/usr/bin/env python3
"""Rewrite batch 1: Detailed descriptions for cities starting with Z."""

import json
import os

BATCH_CITIES = {
    "zagreb": {
        "climate": "Zagreb experiences a humid continental climate with distinct four seasons. Summers are pleasantly warm (20-27°C) with long sunny days perfect for exploring the city's outdoor cafes and parks. Winters can be cold (-2 to 4°C) with occasional snow, creating a cozy atmosphere in the city's many kavanas (coffee houses). Spring and autumn offer mild temperatures ideal for walking the historic Upper Town. The weather is generally predictable, making it easy to plan your work and leisure schedule.",
        "cost": "Zagreb offers excellent value for a European capital city. A comfortable nomad lifestyle costs €1,200-1,800/month. Central apartments in neighborhoods like Trnje or Trešnjevka range €500-900/month, while coworking spaces charge €100-200/month. A quality lunch costs €8-12, and craft beer is €3-4. The cost of living has increased since Croatia joined the EU, but remains significantly cheaper than Western European capitals.",
        "wifi": "Croatia has invested heavily in digital infrastructure, and Zagreb benefits from reliable high-speed internet. Average speeds range 50-100 Mbps, with fiber connections common in the city center. Most cafes offer free WiFi suitable for video calls, and coworking spaces provide dedicated connections of 200+ Mbps. Mobile data is affordable with providers like A1 and T-Mobile offering unlimited plans for €15-25/month. The 5G network is expanding rapidly.",
        "nightlife": "Zagreb's nightlife centers around the legendary Tkalčićeva Street, a pedestrian strip lined with bars that spill onto the cobblestones until the early hours. The scene is diverse—from craft beer bars in the hip Medika cultural center to electronic clubs at Lake Jarun. Croatians socialize late, with dinner starting at 9pm and clubs filling after midnight. The summer terrace culture is especially vibrant, and festivals like INmusic draw international crowds.",
        "nature": "Despite being a landlocked capital, Zagreb offers excellent access to nature. Medvednica Mountain rises directly above the city, with hiking trails reachable by tram. The Sljeme peak offers skiing in winter and mountain biking in summer. The Adriatic coast is just 2 hours away for beach weekends. Within the city, Maksimir Park provides 300+ acres of forest and lakes. The nearby Plitvice Lakes, a UNESCO site, make for stunning day trips.",
        "safety": "Zagreb is remarkably safe for a European capital. Violent crime is virtually nonexistent, and you can walk anywhere at night without concern. Petty theft is rare outside of crowded events. The city has a relaxed, trusting atmosphere—locals leave bags unattended at cafe tables. Croatian hospitality means you'll often receive help before you ask for it. The emergency services are reliable, and English is spoken at hospitals and police stations.",
        "food": "Croatian cuisine in Zagreb blends Central European heartiness with Mediterranean influences. Don't miss štrukli (baked cheese pastry), ćevapi (grilled meat), and fresh seafood from the coast. The Dolac farmers market offers the best local produce. The city has evolved beyond traditional fare with excellent international restaurants, specialty coffee roasters, and a growing vegan scene. Food quality is high, portions are generous, and prices remain reasonable.",
        "community": "Zagreb's digital nomad community is growing steadily, centered around coworking spaces like HUB385 and Impact Hub. Regular meetups, Slack groups, and entrepreneur events make networking easy. The city attracts a mix of tech workers, freelancers, and startup founders. Croatians are warm once you break the initial reserve, and many speak excellent English. The creative scene is thriving, with artists, designers, and musicians adding to the community fabric.",
        "english": "English proficiency in Zagreb is high, especially among younger Croatians and professionals. You can handle all daily tasks—shopping, banking, medical appointments—in English. Most restaurant menus have English translations, and government services often provide English-speaking staff. Learning basic Croatian phrases earns significant goodwill, but it's not essential for daily life. German is also widely understood as a second language.",
        "visa": "Croatia joined the Schengen Area in 2023, simplifying travel within Europe. EU citizens can live and work freely. Non-EU visitors can stay 90 days within any 180-day period visa-free. Croatia has introduced a Digital Nomad Visa allowing stays of up to one year for remote workers earning from abroad (minimum €2,540/month income required). The application process is straightforward, and renewals are possible.",
        "culture": "Zagreb beautifully blends Austro-Hungarian elegance with Croatian warmth. The Upper Town's cobblestoned streets and baroque architecture contrast with the edgy street art of the Lower Town. The city punches above its weight culturally—world-class museums like the Museum of Broken Relationships, a thriving theater scene, and music festivals throughout the year. Coffee culture is sacred; expect long conversations over tiny cups. The Croatian concept of 'fjaka'—a pleasant laziness—makes the pace of life refreshingly unhurried.",
        "cleanliness": "Zagreb is well-maintained by Central European standards. The historic center is regularly cleaned, with particular attention to tourist areas around Ban Jelačić Square. Public parks are tidy, and graffiti, while present, is often artistic rather than vandalism. Waste collection is reliable, and recycling is encouraged. Tap water is excellent—Croatians are proud of their water quality. Public transport is clean and well-kept.",
        "airquality": "Zagreb enjoys generally good air quality, with readings typically in the 'good' to 'moderate' range (AQI 30-60). The surrounding hills and green spaces help maintain freshness. Winter can see higher pollution levels due to heating, but it rarely becomes problematic. The city has been investing in electric public transport and cycling infrastructure. Summer air quality is excellent, enhanced by the mountain breezes from Medvednica."
    },
    "zurich": {
        "climate": "Zurich has a humid continental climate influenced by its lakeside and Alpine position. Summers are pleasantly warm (18-25°C) with long daylight hours and frequent thunderstorms that clear the air. Winters are cold (-2 to 4°C) with regular snowfall and often foggy conditions in the lake basin. Spring and fall are transitional but beautiful, with clear days offering stunning views of the distant Alps. The weather is changeable, so layers are essential year-round.",
        "cost": "Zurich is one of the world's most expensive cities—plan your budget accordingly. A nomad lifestyle costs CHF 4,000-6,000/month ($4,400-6,600). Apartments in the city range CHF 2,200-4,000/month, and even a basic lunch costs CHF 25-35. However, Swiss salaries reflect these costs, and quality is exceptional. Coworking spaces charge CHF 400-600/month. The silver lining: public services are outstanding, and you get what you pay for in every transaction.",
        "wifi": "Swiss infrastructure is world-class, and internet is no exception. Speeds of 100+ Mbps are standard, with gigabit fiber widely available. Public WiFi is excellent, including free coverage at train stations and many public spaces. Mobile coverage is flawless even in Alpine areas. Providers like Swisscom and Sunrise offer reliable, if expensive, plans. You'll never worry about connectivity issues in Switzerland.",
        "nightlife": "Zurich's nightlife is sophisticated rather than wild. The Langstrasse district offers a grittier, more diverse scene with bars, clubs, and late-night food. The old town (Niederdorf) has cozy wine bars and beer halls. Techno fans head to clubs like Hive or Zukunft for world-class electronic music. The Swiss approach to nightlife is quality over quantity—fewer venues, but each one impeccable. Summer brings open-air bars along the lake and river.",
        "nature": "Zurich offers extraordinary nature access for a financial capital. Lake Zurich is swimmable in summer with numerous 'Badis' (public swimming areas). The Uetliberg mountain is 20 minutes from downtown, offering hiking and city views. Day trips to the Alps—Jungfrau, Pilatus, Titlis—take just 1-2 hours. In winter, ski resorts are easily accessible. Even within the city, the Limmat River and numerous parks provide green escapes.",
        "safety": "Zurich is exceptionally safe—one of the world's safest cities by any measure. Violent crime is nearly nonexistent, and you can walk anywhere at any hour without concern. Swiss society values order and civic responsibility. Bikes are left unlocked, lost items are turned in, and public spaces are respected. The biggest 'danger' might be jaywalking fines. Emergency services are efficient and multilingual.",
        "food": "Swiss cuisine is hearty Alpine fare—fondue, raclette, rösti, and Zürcher Geschnetzeltes (veal in cream sauce). Beyond tradition, Zurich has an excellent international food scene, reflecting its cosmopolitan population. Quality is uniformly high; even casual restaurants maintain standards. The city has embraced plant-based dining with numerous vegan options. Food halls like Im Viadukt and weekly markets at Bürkliplatz offer great variety. Expect to pay premium prices everywhere.",
        "community": "Zurich hosts a significant international community, with over 30% foreign residents. The finance and tech sectors draw professionals from around the world. Startup ecosystem is growing, with hubs like Trust Square attracting entrepreneurs. However, Swiss culture can be reserved initially—friendships develop slowly but are deep when formed. Networking events, expat groups, and sports clubs are the best ways to connect. English is widely used in business and tech circles.",
        "english": "English is widely spoken in Zurich, particularly in business, tech, and international contexts. Most professionals are fluent, and you can manage daily life entirely in English. However, German (Swiss German specifically) remains the dominant language, and learning it shows commitment to integration. Many official processes are available in English, though some bureaucracy requires German. French and Italian are also official Swiss languages.",
        "visa": "Switzerland isn't part of the EU but participates in Schengen. EU/EFTA citizens can work freely. Non-EU citizens face strict requirements—work permits typically require employer sponsorship and proof that no local candidate was suitable. Self-employment is possible but complex. Swiss L and B permits have specific income and professional requirements. The high bar for immigration reflects the country's competitive job market and quality of life.",
        "culture": "Zurich defies its banking capital stereotype with surprising cultural depth. It was the birthplace of Dadaism at Cabaret Voltaire, and maintains world-class museums like Kunsthaus. Swiss punctuality and precision are real—trains run to the minute, and appointments are sacred. The concept of 'clean, efficient, expensive' pervades everything. Yet there's warmth beneath the reserve, especially in the city's many traditional guild houses and neighborhood festivals. Sunday quiet laws are strictly observed.",
        "cleanliness": "Zurich sets the global standard for urban cleanliness. Streets are spotless, public toilets are immaculate, and graffiti is virtually nonexistent. Swiss civic pride means litter is unthinkable—you'll see locals picking up stray paper. Public transport is pristine. The lake and rivers are clean enough to swim in. This obsessive tidiness reflects the Swiss value of collective responsibility. Even the 'messy' Langstrasse is clean by any other city's standards.",
        "airquality": "Zurich enjoys excellent air quality, with AQI typically in the 20-40 range. The lake, surrounding forests, and strict environmental regulations keep the air fresh. Alpine winds regularly clear any accumulated pollution. Switzerland's investments in public transport and emissions standards pay dividends. In summer, the air is crystal clear with visibility to distant peaks. Some winter days can see fog trapping pollution in the lake basin, but this is temporary."
    },
    "zakopane": {
        "climate": "Zakopane has a classic mountain climate with cool summers and cold, snowy winters. Summer temperatures are pleasant (15-20°C), offering relief from the heat that grips lowland Poland. Winters are cold (-8 to 0°C) with heavy snowfall that transforms the town into a winter wonderland. The ski season runs December through March, while summer and fall offer perfect hiking weather. Weather can change rapidly in the mountains, so always pack layers.",
        "cost": "Zakopane offers exceptional value for a European mountain resort. A comfortable lifestyle costs €800-1,200/month. Apartments range €300-600/month, significantly cheaper than Alpine equivalents. Restaurant meals cost €5-10, and a day ski pass is just €25-30. The low costs make it possible to extend your stay through an entire season. Prices rise during peak winter and summer holidays but remain affordable by Western standards.",
        "wifi": "Poland has invested heavily in internet infrastructure, and Zakopane benefits from reliable connectivity. Average speeds are 40-80 Mbps, sufficient for remote work. Most accommodations offer WiFi, though speeds vary in older buildings. Coworking options are limited—most nomads work from cafes or their apartments. Mobile coverage is excellent throughout town and even in the mountain valleys. The town is developing more digital nomad infrastructure as the community grows.",
        "nightlife": "Zakopane's nightlife centers on Krupówki Street, the main pedestrian promenade. After a day on the slopes, the après-ski scene offers mulled wine, live music, and traditional highlander dancing. Bars and clubs stay open late, especially in winter season. The atmosphere is festive and unpretentious—locals and tourists mix freely. Summer evenings are quieter but pleasant, with outdoor terraces and mountain views. Don't miss trying oscypek (smoked cheese) with cranberry sauce.",
        "nature": "The Tatra Mountains are Zakopane's raison d'être. Poland's highest peaks offer world-class hiking, with trails ranging from gentle valley walks to challenging ridge routes. Morskie Oko, a stunning glacial lake, is a must-visit. Winter brings excellent skiing and snowboarding on Kasprowy Wierch. The Tatra National Park protects pristine wilderness just minutes from town. Wildlife includes chamois, marmots, and even bears in remote areas. Nature here is dramatic and accessible.",
        "safety": "Zakopane is very safe by any standard. Crime is extremely rare, and the town maintains a welcoming, family-friendly atmosphere. The biggest risks are mountain-related—always check weather conditions and stick to marked trails. Polish mountain rescue (TOPR) is professional but better avoided through preparation. Local highlanders (Górale) are proud and hospitable. You can walk anywhere at any time without concern.",
        "food": "Highlander cuisine is hearty, meat-heavy, and perfect after a day in the mountains. Oscypek (smoked sheep's cheese), kwaśnica (sauerkraut soup), and lamb dishes are local specialties. Restaurants along Krupówki range from tourist traps to authentic gems—ask locals for recommendations. Traditional milk bars (bar mleczny) offer incredibly cheap homestyle food. The regional food culture is strong, with recipes passed down through generations. Vegetarian options are limited but improving.",
        "community": "Zakopane has a growing community of outdoor enthusiasts, seasonal workers, and remote workers drawn by the mountains and low costs. The community is smaller and more seasonal than city-based nomad hubs, but tight-knit. Facebook groups and local meetups connect the international residents. Poles are warm and hospitable once you break through initial shyness. The shared love of mountains creates instant common ground.",
        "english": "English is increasingly common, especially among younger Poles and those in tourism. You can manage daily tasks in English in the main tourist areas. Learning basic Polish phrases will enhance your experience significantly—highlanders appreciate the effort. Menu translations are common but not universal. For more complex matters like banking or medical care, having a Polish speaker or translation app helps. Polish is challenging but rewarding to learn.",
        "visa": "Poland is part of the EU and Schengen Area. EU citizens can live and work freely. Non-EU visitors can stay 90 days within any 180-day period visa-free. Longer stays require a visa or residence permit—Poland offers various options including a visa for business purposes. The bureaucracy can be slow but is manageable. Poland's cost of living makes it attractive for nomads looking to stretch their runway.",
        "culture": "Zakopane preserves the distinctive Górale (highlander) culture unlike anywhere else in Poland. Traditional wooden architecture, folk music, and colorful regional costumes remain part of daily life. The highlanders are proud, independent people with their own dialect and traditions. This isn't tourist theater—you'll see genuine cultural practices in daily life. The town balances tradition with tourism, maintaining authenticity while welcoming visitors. Folk festivals throughout the year showcase highland heritage.",
        "cleanliness": "Zakopane maintains good standards for a mountain resort town. The main tourist areas along Krupówki are regularly cleaned. Accommodations range from basic to excellent, so choose carefully. Mountain trails are generally clean, with Poland's strong outdoor culture encouraging 'leave no trace' practices. Tap water is safe and mountain-fresh. Some side streets show wear during busy seasons, but overall cleanliness is good.",
        "airquality": "Mountain air quality in Zakopane is generally excellent, especially above the town in Tatra National Park. However, the valley location can trap wood smoke in winter, occasionally creating smog conditions. This is worst on cold, windless nights when many homes burn coal or wood for heating. In summer and when winds blow, the air is pristine. Check air quality readings on smoggy winter days before intense outdoor activity."
    },
    "zermatt": {
        "climate": "Zermatt sits at 1,620m altitude with a classic high Alpine climate. Summers are cool and pleasant (12-20°C), while winters are cold (-10 to -2°C) with reliable snow. The high altitude means intense sun—always pack sunscreen, even in winter. Weather can change dramatically within hours, and the Matterhorn creates its own microclimate. The ski season extends through early May thanks to glacier skiing. Over 300 sunny days per year make it surprisingly pleasant.",
        "cost": "Zermatt is one of the world's most expensive ski resorts—budget accordingly. Expect to spend CHF 5,000-8,000/month ($5,500-8,800) for accommodation and living costs. Apartments start at CHF 2,500/month in season, with premium properties far higher. A restaurant meal costs CHF 40-70, and a day ski pass is CHF 90+. The upside: quality is exceptional across the board. Off-season (May-June, October-November) offers slightly better rates.",
        "wifi": "Swiss infrastructure extends even to this high Alpine resort. Internet speeds of 100+ Mbps are common in hotels and chalets. Public WiFi is available throughout the village. Mobile coverage is excellent, including on many ski slopes. The combination of Swiss efficiency and tourism investment ensures connectivity isn't an issue. Several coworking-friendly hotels cater to the growing ski-and-work crowd.",
        "nightlife": "Zermatt's après-ski scene is legendary. Hennu Stall at the base of the slopes and the Papperla Pub offer rowdy early evening drinks. The scene transitions to wine bars and upscale lounges as night falls. Vernissage Club provides dancing until late. Unlike some resorts, Zermatt maintains a sophisticated vibe—less rowdy than Austrian alternatives. Summer nightlife is quieter but still present, centered on hotel bars and the village center.",
        "nature": "The Matterhorn dominates everything—one of the world's most recognizable peaks rises directly above the village. The skiing covers 360km of runs across multiple valleys, including runs into Italy. Summer hiking trails offer glacier walks, mountain lakes, and wildflower meadows. The car-free village means pristine air and quiet streets. Wildlife includes ibex, chamois, and marmots. This is nature at its most dramatic and accessible.",
        "safety": "Zermatt is extremely safe—both as a wealthy Swiss resort and as a small mountain village. Crime is virtually nonexistent. The main safety concerns are mountain-related: avalanches, altitude sickness, and sudden weather changes. Respect the mountains, hire guides for challenging terrain, and stay on marked runs. Mountain rescue is professional but expensive—get proper insurance. The village itself is car-free, adding to safety and tranquility.",
        "food": "Alpine cuisine meets Swiss precision in Zermatt's restaurants. Traditional dishes include fondue, raclette, and rösti with various toppings. Several Michelin-starred restaurants offer fine dining experiences. Mountain huts serve hearty fare with spectacular views. The quality is uniformly high, as is the price—expect CHF 30-40 even for simple meals. International cuisine is available but the focus is Alpine. The local Valais wines are excellent and often overlooked.",
        "community": "Zermatt's community is seasonal and resort-focused. Winter brings ski instructors, hospitality workers, and ski-season nomads from around the world. Summer has a different character with hikers and mountaineers. The permanent community is small but tight-knit. The international staff creates easy English-speaking connections. Several tour operators now offer 'ski and work' packages connecting remote workers with accommodation and workspace.",
        "english": "English is widely spoken in Zermatt, as expected in an international resort. Hotel staff, restaurant servers, and ski instructors are typically multilingual. German is the primary local language, with French and Italian also present (given proximity to Valais and Italian border). You can manage everything in English, though a few German phrases show appreciation. Official Swiss multilingualism means services are available in multiple languages.",
        "visa": "Swiss visa rules apply. EU/EFTA citizens can work freely. Non-EU visitors can stay 90 days within Schengen. Working in Zermatt typically requires employer sponsorship—seasonal workers often come through established programs. The high cost of living makes budget travel difficult, but digital nomads with good income can enjoy an extended mountain lifestyle. Self-employment visas are possible but complex.",
        "culture": "Zermatt balances Alpine tradition with international resort culture. The car-free village maintains its historic character, with electric vehicles and horse-drawn carriages the only transport. The Matterhorn features prominently in local identity—it was first climbed (and tragically) from Zermatt in 1865. Swiss precision is evident in everything from punctual trains to perfectly groomed pistes. Despite the luxury, there's genuine mountain culture here, especially among the Valais locals who've lived here for generations.",
        "cleanliness": "Swiss standards of cleanliness apply even at 1,600m altitude. The car-free village stays remarkably clean. Streets are swept, snow is promptly cleared, and public spaces are maintained to exacting standards. The absence of vehicle emissions keeps the air pure. Mountain huts and ski facilities are immaculate. This attention to cleanliness adds to the premium feeling that justifies Zermatt's high prices.",
        "airquality": "The combination of high altitude, car-free streets, and mountain location gives Zermatt some of the purest air you'll breathe anywhere. The AQI typically reads below 20—excellent by any standard. The Alpine air is noticeably crisp and clean. UV radiation is intense due to altitude and snow reflection, so protect your skin and eyes. This pristine air quality is part of what makes mountain living so invigorating."
    },
    "zanzibar": {
        "climate": "Zanzibar has a tropical climate with warm temperatures year-round (25-32°C). The long rains fall March-May, with shorter rains in November. June-October offers ideal beach weather with lower humidity and cooling trade winds. December-February is hot and humid but still popular. The Indian Ocean moderates extremes, keeping temperatures comfortable. Hurricane risk is minimal, making Zanzibar a reliable tropical destination year-round.",
        "cost": "Zanzibar offers good value for an island destination, though costs exceed mainland Tanzania. A comfortable nomad lifestyle costs $1,000-1,800/month. Apartments range $400-800/month, with beachfront properties at the higher end. Restaurant meals cost $8-15 for local food, more for tourist establishments. The island has a two-tier pricing system—tourist prices versus local prices—so living like a local brings significant savings.",
        "wifi": "Internet infrastructure on Zanzibar has improved significantly but remains variable. Stone Town offers the most reliable connectivity with speeds of 10-40 Mbps. Beach areas can be spotty—check before booking. Mobile data is often more reliable than fixed WiFi. Vodacom and Airtel offer reasonable packages, and 4G coverage has expanded. Bring a backup plan (mobile hotspot, multiple SIM cards) for important work calls.",
        "nightlife": "Stone Town has a growing nightlife scene with rooftop bars, beach clubs, and live music venues. The famous Forodhani Gardens night market is a social highlight. Beach areas like Nungwi have late-night beach bars and full moon parties. Zanzibar's Muslim culture means alcohol is available but less prominent than in other tropical destinations. The vibe is relaxed and social rather than clubbing-focused. Mercury's Restaurant (named for Freddie Mercury) is an institution.",
        "nature": "Zanzibar is famous for its pristine beaches with white sand and turquoise water. The coral reefs offer excellent snorkeling and diving. Stone Town's spice plantations invite exploration of cloves, nutmeg, and cinnamon. The Jozani Forest is home to rare red colobus monkeys found nowhere else. Day trips to Prison Island and surrounding atolls add variety. The underwater world here rivals anywhere in the Indian Ocean.",
        "safety": "Zanzibar is generally safe for tourists, with a strong tourism-dependent economy that values visitor security. Petty theft can occur—don't leave valuables on the beach. Stone Town requires street awareness at night, though violent crime is rare. The conservative Muslim culture means modest dress is appreciated, especially in town. Swim only at beaches with lifeguards or known safe spots—some areas have strong currents. Local hospitality is warm and genuine.",
        "food": "Swahili cuisine blends African, Arab, and Indian influences into something unique. Fresh seafood is exceptional—lobster, octopus, and fish straight from the ocean. Zanzibar's spice heritage flavors everything. Street food at Forodhani Gardens is legendary: Zanzibar pizza (filled crepes), urojo (tangy soup), and grilled seafood. High-end restaurants in Stone Town offer sophisticated takes on local cuisine. The fusion of cultures creates genuinely distinctive flavors.",
        "community": "Zanzibar attracts a small but interesting nomad community drawn by beaches and affordability. Stone Town coworking spaces have emerged to serve this growing demographic. The vibe is relaxed and creative—writers, photographers, and online entrepreneurs predominate. Connections happen easily in this compact island environment. The expat scene includes long-term residents in tourism and conservation. Facebook groups and local meetups facilitate community.",
        "english": "English is widely spoken alongside Swahili, particularly in tourism areas. Most business can be conducted in English, and signs are often bilingual. Learning basic Swahili phrases (jambo, asante, pole pole) earns warmth and smiles. Arabic influences are present in Stone Town. The further from tourist areas, the more Swahili helps. Zanzibaris are patient and helpful with language barriers.",
        "visa": "Zanzibar is part of Tanzania, and the same visa rules apply. Most nationalities can get a visa on arrival for $50 (30 days, extendable to 90). The process is straightforward at the airport. For longer stays, Tanzania offers residence permits with various categories. The laid-back immigration approach makes Zanzibar accessible, though work permit requirements apply for formal employment.",
        "culture": "Zanzibar's culture is a fascinating fusion. Stone Town is a UNESCO World Heritage site with Arab, Persian, Indian, and African influences visible in every carved doorway. The island was a slave trade center and later a spice trade hub—this complex history pervades everything. Islam shapes daily rhythms, with calls to prayer five times daily. The Swahili concept of 'pole pole' (slowly, slowly) governs the pace of life. Freddie Mercury's birthplace adds an unexpected cultural footnote.",
        "cleanliness": "Standards vary across the island. Stone Town's UNESCO status ensures some maintenance, though the historic streets show wear. Beach resorts maintain international standards. Some local areas face waste management challenges typical of developing regions. The ocean is clean for swimming, and beach resorts keep their stretches pristine. Tap water should be filtered or bottled. Tourism pressure is driving improved standards.",
        "airquality": "Zanzibar enjoys excellent air quality with Indian Ocean breezes keeping the air fresh and clean. There's no heavy industry, and vehicle traffic is limited, especially outside Stone Town. The tropical vegetation adds freshness. Air quality readings are consistently in the 'good' range. The sea breeze moderates humidity and brings constant freshness. This is island air at its best."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

    # Load existing data
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Update cities with detailed descriptions
    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")

    # Save updated data
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
