#!/usr/bin/env python3
"""Rewrite batch 14: Krakow, Ho Chi Minh City, Stockholm, Reykjavik, Las Palmas."""

import json
import os

BATCH_CITIES = {
    "krakow": {
        "climate": "Krakow has a humid continental climate with warm summers and cold, snowy winters. Summer temperatures range from 18-26°C (64-79°F), ideal for outdoor exploration. Winters are cold at -4 to 3°C (25-37°F) with frequent snow from December to February. Spring and autumn offer pleasant conditions with mild temperatures. The city experiences significant temperature variations between seasons, each offering different charms.",
        "cost": "Krakow offers excellent value, even cheaper than Warsaw. Monthly costs range from €1,000-1,600 for a comfortable lifestyle. Rent for a central one-bedroom apartment averages €500-750, with great deals in Kazimierz and Podgórze neighborhoods. Meals at local restaurants cost €5-10, and traditional Polish dining remains very affordable. Beer costs €2-3 at bars. Coworking spaces range from €80-200 monthly.",
        "wifi": "Poland has excellent internet infrastructure, and Krakow offers reliable connectivity throughout the city. Most cafes and accommodations provide 30-100 Mbps connections. The city has numerous coworking spaces catering to the growing digital nomad scene, including Cluster and Cavatina Hall. Free WiFi is available in shopping centers and the main square. Mobile data is affordable with strong 4G/5G coverage.",
        "nightlife": "Krakow's nightlife centers around the Main Square and Kazimierz district, offering something for everyone. The Rynek Underground features atmospheric cellar bars in medieval vaults. Kazimierz's former Jewish quarter has transformed into a bohemian bar district with eclectic venues. Student presence keeps prices low and energy high. Clubs play everything from techno to Polish folk. Summer brings outdoor beer gardens and extended hours.",
        "nature": "Krakow provides good natural access despite its urban setting. Planty Park encircles the Old Town with green pathways. The Vistula River banks offer cycling and running paths with views of Wawel Castle. Day trips to Tatra Mountains (2 hours) provide dramatic alpine scenery and hiking. Ojców National Park offers limestone cliffs and caves just 30 minutes away. Zakopane serves as a popular mountain escape.",
        "safety": "Krakow is very safe, with low crime rates throughout the city. The historic center is well-patrolled and walkable at all hours. Pickpocketing can occur in crowded tourist areas like the Main Square, so basic precautions apply. Scams targeting tourists are rare but exist around major attractions. The friendly local culture and strong police presence contribute to security. Solo travelers feel comfortable here.",
        "food": "Polish cuisine shines in Krakow's restaurants and milk bars (bar mleczny). Traditional dishes like pierogi, żurek soup, and placki ziemniaczane (potato pancakes) are hearty and affordable. Kazimierz features restaurants serving Jewish-Polish heritage cuisine. Obwarzanek (Krakow's distinctive bread rings) are everywhere. The Stary Kleparz market offers fresh produce and local specialties. Modern Polish cuisine has also emerged in trendy bistros.",
        "community": "Krakow has a thriving digital nomad and expat community, drawn by affordability and quality of life. Coworking spaces host networking events and workshops. The city's young, international population creates a welcoming atmosphere. Language exchanges and social meetups are frequent. The startup ecosystem is developing with support for entrepreneurs. Integration is easier than in some Polish cities thanks to the international character.",
        "english": "English proficiency is good in Krakow, especially among younger generations and in tourist areas. Service workers in the center typically speak functional English. Students and professionals often speak fluent English. Outside tourist zones and with older residents, Polish becomes more necessary. Learning basic Polish phrases is appreciated. University areas have particularly high English fluency.",
        "visa": "Poland is part of the Schengen Area, allowing visa-free stays of up to 90 days within a 180-day period for citizens of many countries. Poland offers a digital nomad visa program requiring proof of remote income and health insurance. Work visas are available for those with Polish employers. EU citizens can stay indefinitely. Long-term residents must register with local authorities after 90 days.",
        "culture": "Krakow served as Poland's royal capital for centuries, and this heritage defines its character. Wawel Castle and the stunning Main Square showcase medieval and Renaissance architecture. The former Jewish quarter of Kazimierz remembers a vibrant community decimated in the Holocaust. Museums document both royal glory and tragic history. University tradition dates back to 1364. Locals take immense pride in Krakow's cultural significance.",
        "cleanliness": "Krakow maintains good cleanliness standards in the historic center and tourist areas. The Main Square and surrounding streets are well-maintained. Some peripheral neighborhoods show more urban wear. Parks and green spaces are generally tidy. Public transport is clean. Winter smog and air quality issues are the main environmental concern rather than cleanliness. Recycling facilities are available throughout.",
        "airquality": "Krakow unfortunately suffers from serious air pollution, particularly in winter. Cold air inversions trap smog from coal heating and regional industry. Winter days can see dangerously high particulate levels—checking air quality indexes is essential. Summer air quality is significantly better. The city has implemented measures including heating bans, but progress is slow. Sensitive individuals should monitor conditions carefully."
    },
    "hochiminhcity": {
        "climate": "Ho Chi Minh City has a tropical climate with two distinct seasons: wet (May-November) and dry (December-April). Temperatures remain consistently hot at 25-35°C (77-95°F) year-round. Humidity is high throughout, though the dry season feels more comfortable. Afternoon thunderstorms are common during the wet season, usually lasting 30-60 minutes. Air conditioning is essential for comfort.",
        "cost": "Ho Chi Minh City offers exceptional value for digital nomads. Monthly costs range from $1,000-1,800 USD for a comfortable lifestyle. Rent for a modern one-bedroom apartment averages $400-700 in central districts, with cheaper options in less central areas. Street food meals cost $1-3, while restaurant dining runs $5-15. Beer is famously cheap at $0.50-1 for local brands. Coworking spaces cost $80-200 monthly.",
        "wifi": "Vietnam has invested heavily in internet infrastructure, and Ho Chi Minh City offers excellent connectivity. Cafes throughout the city provide free WiFi with 20-100 Mbps speeds. Numerous coworking spaces cater to the large digital nomad community, including Dreamplex and Toong. Mobile data is extremely affordable with carriers like Viettel and Mobifone offering generous 4G packages. Most accommodations have reliable connections.",
        "nightlife": "Ho Chi Minh City's nightlife is vibrant and varied, centered around Districts 1, 2, and 3. Bui Vien Street in the backpacker area offers cheap drinks and international crowds. Rooftop bars provide stunning city views and craft cocktails. Districts 2 and Thao Dien have upscale lounges and live music venues. The club scene features both local DJs and international acts. Nights can extend until 3-4 AM.",
        "nature": "Ho Chi Minh City is primarily urban, but nature escapes are accessible. The Mekong Delta is a 1-2 hour drive, offering river cruises and rural landscapes. Cu Chi Tunnels combine history with countryside exploration. Nearby beaches at Vung Tau provide weekend escapes. Can Gio Mangrove Forest offers monkey encounters and biosphere exploration. City parks like Tao Dan provide green respite from urban intensity.",
        "safety": "Ho Chi Minh City is generally safe, though petty crime requires awareness. Bag snatching from motorbikes is the main concern—keep valuables secure and use crossbody bags facing away from traffic. Traffic itself is the biggest hazard; crossing streets requires patience and steady walking. Scams targeting tourists exist in tourist areas. Violent crime against foreigners is rare. The city feels safe at night in most areas.",
        "food": "Vietnamese cuisine reaches peak expression in Ho Chi Minh City's street food scene. Pho, banh mi, com tam (broken rice), and fresh spring rolls are local staples of exceptional quality. Ben Thanh Market offers food stalls and local specialties. The city's Chinese and international influences create diverse options. Street food is safe when choosing busy stalls with high turnover. Fine dining scene is developing rapidly.",
        "community": "Ho Chi Minh City has one of Southeast Asia's largest digital nomad communities. Coworking spaces and cafes serve as community hubs. Facebook groups and regular meetups connect remote workers. The expat scene is well-established with entrepreneurs, teachers, and creatives. Vietnamese people are friendly and welcoming, though deeper friendships require effort. Districts 2 and 7 have particularly active expat communities.",
        "english": "English proficiency varies widely in Ho Chi Minh City. Tourism and business areas have good English speakers. Younger Vietnamese, especially in international companies, often speak well. Local neighborhoods and markets may require translation apps or basic Vietnamese. Service industry English is functional but limited. Learning Vietnamese basics significantly improves daily interactions and shows respect.",
        "visa": "Vietnam offers multiple visa options for digital nomads. The e-visa allows 90-day single-entry stays for many nationalities. 30-day visa exemptions exist for some countries. Longer stays typically involve visa runs or business visas through agencies. There's no official digital nomad visa, but 3-month business visas are commonly used. Visa regulations change frequently—verify current requirements before travel.",
        "culture": "Ho Chi Minh City (still called Saigon by locals) embodies Vietnam's entrepreneurial energy. French colonial architecture mixes with modern towers and Buddhist pagodas. War Remnants Museum and Cu Chi Tunnels preserve complex history. The city is more Westernized than Hanoi, with a fast-paced, business-oriented culture. Lunar New Year (Tet) brings the city to a standstill as residents return to hometowns. Coffee culture is sacred.",
        "cleanliness": "Ho Chi Minh City has typical developing-city cleanliness challenges. Main streets and tourist areas are regularly cleaned. Side streets and markets can be messier. Air quality is a concern due to motorbike emissions. The city struggles with waste management, though recycling initiatives are growing. Public restrooms vary widely in cleanliness—malls and hotels are reliable. Tap water is not drinkable.",
        "airquality": "Ho Chi Minh City's air quality is often poor, primarily due to motorbike emissions. Particulate matter frequently exceeds healthy levels, especially during rush hours and dry season. Masks are commonly worn by locals for both pollution and sun protection. Air quality varies by district and time of day. Indoor spaces with air conditioning provide respite. Sensitive individuals should monitor daily indexes."
    },
    "stockholm": {
        "climate": "Stockholm has a humid continental climate with warm summers and cold, dark winters. Summer temperatures reach 20-25°C (68-77°F) with up to 19 hours of daylight. Winters are cold at -5 to 2°C (23-36°F) with only 6 hours of daylight in December. Spring arrives late but brings dramatic blooming. Autumn features colorful foliage. The archipelago location moderates extremes somewhat. Pack layers for variable conditions.",
        "cost": "Stockholm is one of Europe's most expensive cities. Monthly costs range from SEK 20,000-35,000 (€1,800-3,200) for a comfortable lifestyle. Rent for a central one-bedroom apartment averages SEK 12,000-18,000, and the housing market is notoriously difficult. Restaurant meals cost SEK 150-250. Groceries are pricey. Public transport passes cost SEK 970/month. Coworking spaces range from SEK 2,500-5,000 monthly.",
        "wifi": "Sweden has exceptional internet infrastructure, and Stockholm offers some of Europe's fastest connections. Cafes and coworking spaces typically provide 100-500 Mbps speeds. The city has numerous modern coworking options including Epicenter and SUP46. Free WiFi is available in public spaces and transit stations. Mobile data is affordable with excellent 5G coverage. Fiber connections are standard in apartments.",
        "nightlife": "Stockholm's nightlife is sophisticated and expensive but rewarding. Södermalm neighborhood offers trendy bars and clubs with diverse crowds. Stureplan in Östermalm features exclusive venues and dress codes. The electronic music scene is world-renowned, having birthed Swedish House Mafia and Avicii. Craft beer bars have proliferated. Pre-drinking at home is common due to alcohol prices. Nights peak late but wind down by 3 AM.",
        "nature": "Stockholm is built on 14 islands, making nature integral to city life. The archipelago comprises 30,000 islands accessible by ferry for hiking and swimming. Djurgården island offers parks and museums minutes from the center. Forest trails begin at metro station ends. Swimming spots dot the city's clean waterways. Winter brings cross-country skiing in city parks. The allemansrätten (right to roam) allows wild camping.",
        "safety": "Stockholm is extremely safe, with low crime rates and a transparent society. Walking alone at night is comfortable in virtually all areas. Some outer suburbs have socioeconomic challenges but aren't dangerous for visitors. Pickpocketing is rare but possible on crowded transit. The main practical concern is the cold and darkness in winter. Swedish culture emphasizes order and mutual respect.",
        "food": "Swedish cuisine has evolved from traditional meatballs and herring to world-class innovation. Stockholm boasts numerous Michelin-starred restaurants and pioneering New Nordic cuisine. Classic fika (coffee break with pastries) is essential to Swedish life. Food halls like Östermalms Saluhall offer quality ingredients. Street food includes korv (hot dogs) and falafel. Vegetarian and vegan options are excellent throughout the city.",
        "community": "Stockholm has a substantial tech and startup community, making it welcoming for digital nomads. Coworking spaces facilitate networking among remote workers. The international business environment means English is common in professional circles. However, Swedes can be initially reserved, and integrating socially requires patience. Organized activities and expat groups help build connections. The nomad scene is smaller than in cheaper cities.",
        "english": "English proficiency in Sweden is among the highest in the world. Virtually everyone under 60 speaks excellent English. All services, menus, and daily interactions can be conducted in English. Swedish is rarely necessary for living and working. However, learning Swedish helps with deeper cultural integration and may be required for certain jobs or residence permits.",
        "visa": "Sweden is part of the Schengen Area, allowing visa-free stays of up to 90 days within a 180-day period for citizens of many countries. There's no specific digital nomad visa, and working typically requires a work permit sponsored by a Swedish employer. Self-employed visas require registering a Swedish company. EU citizens can live and work freely. The D-visa is for longer stays with specific purposes.",
        "culture": "Swedish culture values equality, sustainability, and work-life balance. The concept of lagom (just enough) permeates attitudes—not too much, not too little. Design excellence is evident everywhere from furniture to public spaces. Summer is celebrated intensely after dark winters, with Midsummer being a major holiday. Sustainability and environmental consciousness are mainstream values. Personal space and privacy are respected.",
        "cleanliness": "Stockholm is exceptionally clean, reflecting Swedish values of order and environmental responsibility. Streets, parks, and public transport are immaculately maintained. Recycling is comprehensive with stations throughout the city. Public restrooms are clean and often free. Even industrial areas are kept tidy. Graffiti is minimal. The clean air and water contribute to the overall pristine atmosphere.",
        "airquality": "Stockholm has excellent air quality, benefiting from environmental policies and clean energy. The city regularly ranks among Europe's cleanest capitals. Electric vehicles are common, and public transit runs on renewable energy. Winter inversions can occasionally trap pollution, but this is rare. The surrounding water and forests contribute to fresh air. Breathing is noticeably easier than in many European cities."
    },
    "reykjavik": {
        "climate": "Reykjavik has a subpolar oceanic climate, milder than its latitude suggests thanks to the Gulf Stream. Summers are cool at 10-15°C (50-59°F) with 21+ hours of daylight around the solstice. Winters hover around 0°C (32°F) with only 4-5 hours of light in December. Weather changes rapidly—four seasons in one day is common. Wind and rain are frequent. Northern lights appear October-March.",
        "cost": "Iceland is extremely expensive, and Reykjavik reflects this. Monthly costs range from €3,000-5,000+ for a comfortable lifestyle. Rent for a central one-bedroom apartment averages €1,500-2,500, with limited availability. Restaurant meals cost €25-50. Groceries are pricey—expect to pay €15-20 for basic lunch ingredients. Alcohol is particularly expensive. The only bargain is geothermal heating and hot water.",
        "wifi": "Iceland has excellent internet infrastructure with widespread fiber coverage. Reykjavik cafes and accommodations typically offer 50-200 Mbps connections. Coworking spaces like Regus and local options provide reliable connectivity. Free WiFi is available in libraries and some public spaces. Mobile data coverage is good in the city and along main roads, though remote areas may have gaps. 4G is standard throughout.",
        "nightlife": "Reykjavik's nightlife is legendary despite the small population. The \"rúntur\" (pub crawl) tradition fills downtown bars on Friday and Saturday nights. Icelanders start late—bars empty before midnight then pack after 1 AM. The main strip on Laugavegur features eclectic bars and clubs. Live music venues host local bands. The scene is friendly and unpretentious. Summer brings 24-hour daylight drinking sessions.",
        "nature": "Iceland's nature is Reykjavik's biggest draw, with extraordinary landscapes within easy reach. The Golden Circle (Þingvellir, Geysir, Gullfoss) is a classic day trip. The Blue Lagoon and lesser-known hot springs offer geothermal soaking. Glaciers, volcanoes, and waterfalls dot the countryside. The Snæfellsnes Peninsula provides dramatic coastal scenery. Whale watching operates from the harbor. Northern lights dance overhead in winter.",
        "safety": "Reykjavik is exceptionally safe, consistently ranking among the world's safest capitals. Violent crime is virtually nonexistent. Walking alone at any hour is perfectly safe. The main hazards are weather-related—wind, ice, and rapidly changing conditions when exploring. Driving in winter requires caution. Police are rarely visible because they're rarely needed. The small population creates a village-like accountability.",
        "food": "Icelandic cuisine emphasizes fresh seafood and local ingredients. Lamb, arctic char, and langoustine are standouts. Traditional foods like fermented shark and dried fish are adventurous options. The hot dog stands are beloved institutions. Coffee culture is strong with excellent cafes. Fine dining has flourished with New Nordic influence. Restaurants are expensive, but quality is generally high. Grocery cooking saves significant money.",
        "community": "Reykjavik has a small but tight-knit international community. The population is only 130,000, so connecting is easier than in larger cities. The creative and tech sectors attract foreign workers. Coworking spaces and cafes serve as community hubs. Icelanders are friendly once past initial reserve. The expat community is active with various social groups. English-speaking integration is smooth.",
        "english": "English proficiency in Iceland is exceptional—virtually everyone speaks it fluently. Icelandic is one of the hardest languages to learn, so English serves as the default for foreigners. All services and daily life can be conducted in English. Learning Icelandic is appreciated but not expected. Signs and menus are typically bilingual. Integration into local social circles often happens in English.",
        "visa": "Iceland is part of the Schengen Area, allowing visa-free stays of up to 90 days within a 180-day period for citizens of many countries. There's no specific digital nomad visa. Work permits require employer sponsorship for non-EU citizens. EEA citizens can live and work freely. Long-term stays require registering with the National Registry. Remote workers typically visit as tourists.",
        "culture": "Icelandic culture blends Viking heritage with modern progressivism. Literary traditions run deep—the country has more writers per capita than anywhere else. Music scene punches far above its weight (Björk, Sigur Rós, Of Monsters and Men). Belief in elves and hidden people persists in folklore. The small population creates a everyone-knows-everyone atmosphere. Equality and sustainability are core values. Hot spring culture is sacred.",
        "cleanliness": "Reykjavik is exceptionally clean, benefiting from small population and environmental consciousness. Streets and public spaces are well-maintained. Air is remarkably pure due to geothermal energy and minimal industry. Water comes directly from glaciers and is safe to drink from any tap. Hot spring etiquette requires showering thoroughly before entering. Recycling is standard practice.",
        "airquality": "Reykjavik has some of the cleanest air in the world. The combination of Atlantic winds, geothermal energy (no fossil fuel heating), and minimal industry creates pristine conditions. The Air Quality Index consistently shows excellent readings. No industrial pollution exists. The only potential irritant is volcanic activity, which occasionally produces sulfur smells near geothermal areas. Breathing here is remarkably refreshing."
    },
    "laspalmas": {
        "climate": "Las Palmas de Gran Canaria enjoys one of the world's most pleasant climates, with eternal spring conditions year-round. Temperatures range from 18-26°C (64-79°F) throughout the year, rarely varying more than 10 degrees between seasons. Humidity is moderate and comfortable. Rainfall is minimal, concentrated in winter months. The trade winds keep summers cool. It's genuinely possible to swim year-round.",
        "cost": "Las Palmas offers excellent value for Western Europe. Monthly costs range from €1,500-2,500 for a comfortable lifestyle. Rent for a central one-bedroom apartment averages €700-1,000, with better deals in areas like Guanarteme. Meals at local restaurants cost €8-15. Supermarket prices are reasonable with Canarian specialties priced well. Coworking spaces range from €100-250 monthly, with many digital nomad-focused options.",
        "wifi": "Las Palmas has good internet infrastructure, though not as fast as mainland Spain. Most cafes and coworking spaces offer 30-100 Mbps connections. The city has embraced digital nomads with numerous coworking spaces like Restation and The House. Many apartments include fiber connections. Beachside cafes often have workable WiFi. Mobile data through Spanish carriers is affordable with good coverage.",
        "nightlife": "Las Palmas has lively nightlife centered around the Vegueta old town and Santa Catalina area. Bars range from traditional Spanish tapas spots to international lounges. The Triana neighborhood offers stylish options. Beach bars at Las Canteras provide sunset drinks. Club scene is more low-key than mainland cities but active on weekends. Carnival in February brings legendary street parties. Nights extend late in Spanish tradition.",
        "nature": "Las Palmas combines urban life with extraordinary natural access. Las Canteras beach stretches 3 kilometers along the city with excellent swimming and surfing. The island's interior features dramatic volcanic landscapes and Roque Nublo rock formation. Sand dunes of Maspalomas lie 45 minutes south. Hiking trails cross pine forests and calderas. The surrounding Atlantic offers whale watching and water sports. Each neighborhood of Gran Canaria has distinct microclimates.",
        "safety": "Las Palmas is very safe with low crime rates. The tourist areas and beaches feel secure day and night. Petty theft can occur in busy areas, so keep valuables secure. No neighborhoods are considered dangerous. The relaxed island atmosphere contributes to overall security. Spanish police presence is visible but unobtrusive. Solo travelers of all backgrounds feel comfortable exploring.",
        "food": "Canarian cuisine blends Spanish traditions with African and Latin American influences. Papas arrugadas (wrinkled potatoes with mojo sauce) are essential. Fresh seafood features prominently—try vieja or cherne fish. Gofio (toasted grain flour) appears in various dishes. The Vegueta market offers local produce and specialties. Tapas culture thrives with excellent wine bars. The city has embraced international cuisines catering to its diverse population.",
        "community": "Las Palmas has become one of Europe's premier digital nomad destinations, with a large and active community. Coworking spaces host regular events, workshops, and social gatherings. The consistent climate allows year-round outdoor networking. Facebook groups and Slack channels connect thousands of remote workers. The mix of Europeans and others creates an international atmosphere. Long-term nomads often return season after season.",
        "english": "English proficiency is good in tourist and nomad areas of Las Palmas. Coworking spaces and international-oriented businesses communicate in English. Local restaurants and shops may have more limited English. Spanish helps significantly for daily life and deeper integration. The international nomad community means English is commonly heard. Younger Canarians often speak functional English.",
        "visa": "Spain is part of the Schengen Area, allowing visa-free stays of up to 90 days within a 180-day period for citizens of many countries. Spain offers a digital nomad visa requiring proof of remote income (minimum €2,160/month) and health insurance, allowing stays up to one year with renewal options. The non-lucrative visa is another option. EU citizens can stay indefinitely.",
        "culture": "Canarian culture blends Spanish traditions with island identity. The annual Carnival is one of the world's largest, second only to Rio. Local fiestas feature traditional music, folk dancing, and regional cuisine. The historical old town of Vegueta preserves colonial architecture. Island pride (\"Canariedad\") is distinct from mainland Spain. The relaxed pace of life attracts those escaping hectic cities. Art and music scenes thrive.",
        "cleanliness": "Las Palmas maintains good cleanliness standards, though some areas show urban wear. Las Canteras beach is cleaned daily and well-maintained. The historic center and tourist zones are kept tidy. Some side streets can be less pristine. Public spaces and parks are generally well-maintained. Beach facilities are clean with showers and changing areas. Tap water is safe but many prefer bottled.",
        "airquality": "Las Palmas has excellent air quality, benefiting from ocean breezes and limited industrial activity. The trade winds keep the air fresh and clear. Occasional Calima events bring Saharan dust, creating hazy conditions and temporary air quality warnings. These typically last 2-4 days and are more common in winter. Otherwise, the clean Atlantic air is a major health benefit of island living."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")

    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
