#!/usr/bin/env python3
"""Rewrite batch 13: Warsaw, Wellington, Athens, Kyoto, Osaka."""

import json
import os

BATCH_CITIES = {
    "warsaw": {
        "climate": "Warsaw has a humid continental climate with warm summers and cold, snowy winters. Summer temperatures range from 20-28°C (68-82°F), with occasional heat waves reaching 30°C+. Winters are cold at -5 to 3°C (23-37°F), with snow common from December to March. Spring and autumn offer mild, pleasant weather ideal for exploring the rebuilt Old Town. The city experiences all four seasons distinctly, each with its own charm.",
        "cost": "Warsaw offers excellent value for a European capital. Monthly costs range from €1,200-2,000 for a comfortable lifestyle. Rent for a central one-bedroom apartment averages €600-900, with better deals in outer districts. Meals at local restaurants cost €6-12, while upscale dining remains affordable by Western standards. Public transport is efficient and cheap at €30/month. Coworking spaces range from €100-250 monthly.",
        "wifi": "Poland has excellent internet infrastructure, with Warsaw leading in connectivity. Most cafes, restaurants, and accommodations offer reliable 50-200 Mbps connections. The city has numerous modern coworking spaces, including Google Campus Warsaw and WeWork locations. Free WiFi is available in shopping centers and public spaces. Mobile data is affordable with competitive 4G/5G coverage from carriers like Play and Orange.",
        "nightlife": "Warsaw's nightlife has flourished since the city's transformation, centered around the Praga and Powiśle districts. The alternative scene thrives in former industrial spaces and hidden courtyards. Nowy Świat street offers traditional bars and clubs, while Pawilony features quirky open-air drinking spots. The electronic music scene is particularly strong with clubs like Smolna attracting international DJs. Nights often extend until dawn on weekends.",
        "nature": "Despite being a major city, Warsaw offers abundant green spaces. Łazienki Park spans 76 hectares with palaces, gardens, and resident peacocks. The Vistula River banks have been revitalized with beaches, cycling paths, and summer bars. The Warsaw Uprising museum sits amid reflective gardens. Day trips to Kampinos National Park offer forest hiking just 30 minutes away. The Mazovian countryside provides easy escapes from urban life.",
        "safety": "Warsaw is one of Europe's safest capitals, with very low crime rates. The city center is walkable at all hours, and public transport is safe to use late at night. Petty theft is rare but possible in tourist areas. No neighborhoods are considered dangerous for visitors. The strong police presence and community-minded culture contribute to overall security. Solo travelers of all backgrounds generally feel comfortable.",
        "food": "Polish cuisine has evolved beyond pierogi, though Warsaw's versions remain excellent. Traditional restaurants serve hearty dishes like żurek (sour rye soup) and bigos (hunter's stew). The food hall trend has brought diverse options to spots like Hala Koszyki and Hala Gwardii. The city's vegan scene is surprisingly strong. Jewish culinary heritage is preserved in restaurants around the Nożyk Synagogue area. Modern Polish cuisine is experiencing a renaissance.",
        "community": "Warsaw has a growing digital nomad and expat community, centered around the tech and startup ecosystem. Coworking spaces host regular networking events and workshops. The city attracts remote workers seeking affordable European living with good infrastructure. Facebook groups and Meetups cover tech, languages, and social activities. Locals can be initially reserved but are warm once friendships form.",
        "english": "English proficiency in Warsaw is good among younger generations and professionals. Service workers in central areas typically speak functional English. However, outside tourist zones and with older residents, Polish is often necessary. The business environment operates increasingly in English. Learning basic Polish phrases is appreciated and helps with daily interactions. University areas have particularly high English fluency.",
        "visa": "Poland is part of the Schengen Area, allowing visa-free stays of up to 90 days within a 180-day period for citizens of many countries. Poland offers a digital nomad visa program requiring proof of remote income and health insurance. Work visas are available for those with Polish employers. EU citizens can stay indefinitely. Long-term residents must register with local authorities.",
        "culture": "Warsaw's culture reflects its tragic history and remarkable rebirth. The Old Town, completely rebuilt after WWII destruction, represents resilience and dedication to heritage. World-class museums document the Warsaw Uprising and Jewish history. The contemporary art scene thrives in galleries and street art. Classical music concerts in historic venues continue a rich tradition. Poles take pride in their complex history and cultural achievements.",
        "cleanliness": "Warsaw is notably clean for a major Eastern European city. The rebuilt center and public spaces are well-maintained. Parks and green areas are kept tidy. Some older residential areas and Praga district show more urban wear. The city has invested heavily in infrastructure and appearance. Public transport is clean and modern. Graffiti exists but is less prevalent than in many European cities.",
        "airquality": "Warsaw's air quality is moderate, with winter smog being the main concern due to coal heating in surrounding areas. Cold weather temperature inversions can trap pollution. Summer air quality is generally better. The city has implemented measures to reduce emissions, including expanding public transit and green zones. Check daily indexes during winter if you have respiratory sensitivities. Central areas often have better air quality than suburbs."
    },
    "wellington": {
        "climate": "Wellington is famously windy, with a temperate maritime climate that brings changeable weather year-round. Summers (December-February) are mild at 17-23°C (63-73°F) with occasional warm days. Winters (June-August) are cool at 6-12°C (43-54°F) with rain but rarely snow. The wind can make temperatures feel cooler. Four seasons in one day is a local joke that rings true. Pack layers regardless of season.",
        "cost": "Wellington is expensive by global standards but slightly cheaper than Auckland. Monthly costs range from NZD 3,000-4,500 for a comfortable lifestyle. Rent for a central one-bedroom apartment averages NZD 1,800-2,400, though flatshare options bring costs down. Dining out costs NZD 20-40 for a meal. Groceries are pricey, especially imported goods. Public transport is reasonable. Coworking spaces cost NZD 300-500 monthly.",
        "wifi": "New Zealand has good internet infrastructure, with Wellington offering reliable connectivity in most areas. Cafes and coworking spaces typically provide 30-100 Mbps connections. The city has several coworking options including BizDojo and Generator. Free WiFi is available in libraries and some public spaces. Mobile data is more expensive than many countries but coverage is strong. Fiber connections are common in newer apartments.",
        "nightlife": "Wellington punches above its weight in nightlife, with Cuba Street and Courtenay Place as the main hubs. The craft beer scene is exceptional with numerous local breweries and bars. Live music venues host local and touring acts in intimate settings. Late-night eateries serve everything from Malaysian to Mexican. The vibe is friendly and unpretentious. Most action happens Thursday through Saturday, with bars closing around 3 AM.",
        "nature": "Wellington offers remarkable natural access for a capital city. The harbor and surrounding hills provide stunning scenery. The Town Belt wraps around the city with walking trails through native bush. Red Rocks coast features wild seals and dramatic coastline. Day trips to Kapiti Island offer native bird encounters. The nearby Rimutaka ranges provide proper hiking. Cable car rides to Botanic Gardens reveal panoramic views.",
        "safety": "Wellington is extremely safe, consistently ranking among the world's safest cities. Violent crime is rare, and the compact city center feels secure at all hours. Street harassment is uncommon. The main concerns are petty theft and earthquake preparedness (the region is seismically active). Locals are helpful and look out for each other. Solo travelers of all backgrounds feel comfortable here.",
        "food": "Wellington claims to be the coffee capital of New Zealand, with world-class roasters and baristas. The dining scene punches well above the city's size, from food trucks to fine dining. Fresh seafood features prominently, including green-lipped mussels and crayfish. Asian cuisines are well-represented. The night market on Cuba Street offers diverse street food. Farm-to-table philosophy dominates local menus.",
        "community": "Wellington has a tight-knit creative and tech community. The city attracts filmmakers, game developers, and digital creatives drawn by Weta Workshop's presence. Coworking spaces foster connections among remote workers and startups. The small city size means you'll keep running into familiar faces. Meetups and events are welcoming to newcomers. The overall vibe is friendly, quirky, and inclusive.",
        "english": "English is the primary language in Wellington, with Maori as a co-official language. All services, signage, and daily interactions are in English. Kiwi English includes unique slang and a distinctive accent that's easy to understand. Maori words are increasingly used in official contexts and place names. The multicultural population means you'll hear many languages spoken.",
        "visa": "New Zealand offers visa-free entry for citizens of many countries, allowing stays of up to 90 days. Working Holiday Visas are available for citizens of participating countries aged 18-30 (or 35 for some). There's no specific digital nomad visa, so remote workers typically enter as tourists. Work visas require employer sponsorship. The points-based Skilled Migrant Category offers a path for longer stays.",
        "culture": "Wellington is New Zealand's cultural capital, home to Te Papa national museum and the film industry that produced Lord of the Rings. The arts scene is vibrant with galleries, street art, and theater. Maori culture is increasingly visible and celebrated. The compact city fosters a village-like creative community. Coffee culture is taken seriously. Sustainability and environmental consciousness are core values. The vibe is progressive and inclusive.",
        "cleanliness": "Wellington is extremely clean by global standards. Streets are well-maintained, and public spaces are tidy. The harbor and waterfront are kept pristine. Parks and walking trails are well-managed. Public toilets are clean and widely available. The small population and civic pride contribute to cleanliness. Recycling and composting are standard practice. Wind helps keep the air fresh and streets clear.",
        "airquality": "Wellington has excellent air quality, benefiting from strong winds that prevent pollution buildup. The city has minimal industrial emissions and relatively low traffic. Sea breezes keep the air fresh. The Air Quality Index typically shows healthy levels year-round. The main air concern is occasional smoke from controlled burns or rare distant bushfires. Clean, crisp air is one of the city's defining features."
    },
    "athens": {
        "climate": "Athens has a hot Mediterranean climate with long, dry summers and mild, wet winters. Summer temperatures reach 30-38°C (86-100°F), making midday activities challenging. Winters are mild at 8-15°C (46-59°F) with occasional rain. Spring (April-May) and autumn (September-October) offer ideal conditions for exploring ancient sites. The Acropolis is less crowded and cooler in early morning or late afternoon during summer.",
        "cost": "Athens offers good value compared to other European capitals, though costs have risen. Monthly expenses range from €1,500-2,500 for a comfortable lifestyle. Rent for a central one-bedroom apartment averages €600-900, with better deals in neighborhoods like Pangrati or Kypseli. Meals at tavernas cost €10-18. Coffee culture is strong with espresso around €2-3. Coworking spaces range from €150-300 monthly.",
        "wifi": "Internet infrastructure in Athens has improved significantly, with most cafes and accommodations offering 30-100 Mbps connections. Coworking spaces provide reliable high-speed internet. The tourist areas have generally better connectivity. Mobile data is affordable with Greek carriers like Cosmote and Vodafone. Some older buildings in historic areas may have slower connections. Free WiFi is available in many public squares.",
        "nightlife": "Athens nightlife is legendary, with the action centered in neighborhoods like Gazi, Psiri, and Koukaki. Greeks eat dinner late (9-11 PM), and bars fill after midnight. Rooftop bars with Acropolis views create magical settings. The music scene spans everything from traditional rembetiko to international DJs. Summer moves the party outdoors to beach clubs along the Athens Riviera. Nights can easily extend until sunrise.",
        "nature": "Athens is surrounded by mountains and sea, offering easy natural escapes. Mount Lycabettus provides panoramic city views from its summit. The Athens Riviera stretches south with beaches accessible by tram. Day trips to the Temple of Poseidon at Sounion offer dramatic coastal scenery. The mountains of Parnitha offer hiking and cooler temperatures. Islands like Aegina are just an hour by ferry for quick getaways.",
        "safety": "Athens is generally safe, with low violent crime rates typical of Greek cities. Tourist areas like Plaka and Monastiraki are well-patrolled. Pickpocketing occurs on crowded metro lines and around Omonia Square, which can feel sketchy at night. Protests occur occasionally near Syntagma Square but are typically peaceful. Most visitors experience no problems with basic precautions. The friendly local culture adds to the sense of security.",
        "food": "Greek cuisine shines in Athens, from humble souvlaki stands to sophisticated tavernas. Don't miss the Central Market for fresh produce and atmosphere. Classic dishes like moussaka, grilled octopus, and fresh salads with feta are exceptional. The mezze culture encourages sharing multiple small plates. Street food like koulouri (sesame bread) and spanakopita provides cheap, delicious fuel. Wine and ouzo flow freely at reasonable prices.",
        "community": "Athens has a growing digital nomad community, attracted by the affordable living, climate, and culture. Coworking spaces like Romantso and Stone Soup host events and workshops. The expat scene is established with various social groups and language exchanges. Greeks are warm and social, though initial friendships may develop slowly. The café culture provides natural spaces for meeting and working.",
        "english": "English proficiency is moderate in Athens—good among younger people and those in tourism, limited among older generations. Restaurant menus in tourist areas are typically bilingual. Outside central Athens, Greek becomes more necessary. Learning basic Greek phrases is appreciated and improves daily interactions. The business and startup community operates increasingly in English.",
        "visa": "Greece is part of the Schengen Area, allowing visa-free stays of up to 90 days within a 180-day period for citizens of many countries. Greece offers a digital nomad visa requiring proof of remote income (minimum €3,500/month) and health insurance. EU citizens can stay indefinitely. Long-term stays require registration with authorities. Extensions beyond 90 days involve bureaucratic processes.",
        "culture": "Athens is a living museum where ancient history meets vibrant modern life. The Acropolis and Parthenon represent the foundations of Western civilization. Yet the city pulses with contemporary energy through street art, café culture, and nightlife. Orthodox traditions remain important, with religious holidays widely observed. Greeks are passionate about politics, football, and family. The crisis years fostered resilience and creativity that continues today.",
        "cleanliness": "Athens has improved in cleanliness but remains grittier than Northern European cities. Tourist areas and upscale neighborhoods are well-maintained. Some side streets show graffiti and urban wear, particularly around Exarchia. Public spaces vary in maintenance. The metro system is clean and modern. Summer heat can intensify city odors in older areas. Regular strikes occasionally affect garbage collection.",
        "airquality": "Athens experiences moderate to poor air quality, particularly during summer heat waves when smog can blanket the city. Traffic contributes significantly to pollution. The notorious \"nefos\" (cloud) of pollution has improved from past decades but remains an issue. Sea breezes help on many days. Winter air quality is generally better. The government has implemented traffic restrictions in the center to reduce emissions."
    },
    "kyoto": {
        "climate": "Kyoto has a humid subtropical climate with hot, humid summers and cold winters. Summer temperatures reach 33-38°C (91-100°F) with high humidity, making outdoor exploration challenging. Winters drop to 1-9°C (34-48°F), cold but manageable with proper layers. Spring brings famous cherry blossoms (late March-April), while autumn (November) features spectacular fall foliage. These peak seasons draw massive crowds to temples and gardens.",
        "cost": "Kyoto is expensive but manageable with planning. Monthly costs range from ¥250,000-400,000 ($1,800-2,900 USD) for a comfortable lifestyle. Rent for a central one-bedroom apartment averages ¥80,000-120,000, cheaper than Tokyo. Budget meals at local restaurants cost ¥500-1,000, while traditional kaiseki dining is considerably more. Temple entrance fees (¥300-1,000 each) add up quickly. Coworking spaces are limited but cost ¥15,000-30,000 monthly.",
        "wifi": "Japan has excellent internet infrastructure, and Kyoto is well-connected. Many cafes offer free WiFi, though connections can be slower than in Tokyo. Pocket WiFi rentals provide reliable mobile connectivity. The city has fewer dedicated coworking spaces than Tokyo, but options like Impact Hub Kyoto cater to remote workers. Some traditional accommodations may have limited connectivity. Mobile data SIM cards are readily available.",
        "nightlife": "Kyoto's nightlife is sophisticated rather than wild, befitting the cultural capital. Gion and Pontocho districts feature traditional bars and upscale establishments. The Kiyamachi area along the canal offers more casual izakayas and cocktail bars. Traditional geisha entertainment remains available for those who book through proper channels. Live jazz and whisky bars attract evening crowds. Nights typically wind down earlier than Tokyo or Osaka.",
        "nature": "Kyoto is blessed with exceptional natural beauty integrated into its urban fabric. The Arashiyama bamboo grove creates an otherworldly atmosphere. Temple gardens represent centuries of cultivation and design philosophy. The Philosopher's Path offers serene canal-side walking. Surrounding mountains provide hiking trails with panoramic views. Day trips to the nearby Japan Alps or rural Miyama offer countryside escapes. Seasonal changes create ever-shifting beauty.",
        "safety": "Kyoto is extremely safe, reflecting Japan's overall security. Crime against tourists is virtually unheard of. Walking alone at night, even in unfamiliar areas, is perfectly safe. Lost items are commonly returned. The main cautions involve respecting cultural sites and avoiding restricted areas in Gion. Earthquake preparedness is important as the region is seismically active. Solo travelers of all backgrounds feel completely secure.",
        "food": "Kyoto cuisine emphasizes refinement and seasonality. Traditional kaiseki dining represents Japanese culinary art at its highest. Tofu dishes are elevated here, with centuries-old restaurants specializing in the ingredient. Matcha features prominently in sweets and drinks given Uji's nearby tea production. Nishiki Market offers food stalls and local specialties. Yudofu (hot pot tofu) and obanzai (Kyoto home cooking) are regional highlights.",
        "community": "Kyoto has a smaller but dedicated digital nomad community compared to Tokyo. The city attracts those seeking cultural immersion over urban energy. Coworking spaces and cafes facilitate connections among remote workers. The traditional arts community includes international practitioners. Language exchange events help bridge cultures. Integration with locals requires Japanese language skills and patience, as Kyoto culture values reserved behavior.",
        "english": "English proficiency in Kyoto is moderate, better than rural Japan but less than Tokyo. Tourist sites and upscale establishments handle English well. Local restaurants and shops outside tourist zones often have limited English. Translation apps are essential for daily life. Learning Japanese significantly improves your experience and is necessary for cultural immersion. Written English signage helps at major attractions and transit.",
        "visa": "Japan offers visa-free entry for citizens of many countries, allowing stays of up to 90 days. Extensions are possible but difficult. There's no digital nomad visa; remote workers typically enter as tourists. Working requires a proper work visa sponsored by a Japanese employer. The Specified Skilled Worker visa program is expanding. Long-term stays often require visa runs to nearby countries like Korea.",
        "culture": "Kyoto was Japan's imperial capital for over a millennium, and this heritage permeates daily life. The city contains 17 UNESCO World Heritage sites, including iconic temples and shrines. Traditional arts like tea ceremony, flower arranging, and geisha culture are preserved here. The pace of life is slower and more formal than Tokyo. Respect for tradition, attention to detail, and understated aesthetics define Kyoto's character.",
        "cleanliness": "Kyoto is impeccably clean, reflecting Japanese standards. Streets are spotless despite minimal public trash cans. Temple grounds and gardens are meticulously maintained. Public restrooms are clean and often feature high-tech features. Recycling is taken seriously with multiple sorting categories. Traditional wooden townhouses are preserved with care. This cleanliness extends to public behavior and noise levels.",
        "airquality": "Kyoto has generally good air quality, surrounded by mountains that can trap occasional pollution but also provide forested air corridors. The city has limited industrial activity compared to Osaka. Summer humidity can feel heavy but doesn't indicate poor air quality. Cherry blossom and autumn seasons bring ideal conditions. Winter can see some pollution from heating. Overall air quality is healthy for most visitors."
    },
    "osaka": {
        "climate": "Osaka has a humid subtropical climate similar to Kyoto, with hot, humid summers and cool winters. Summer temperatures reach 32-36°C (90-97°F) with oppressive humidity from June to September. Winters are milder than Kyoto at 3-10°C (37-50°F). The rainy season (tsuyu) runs from mid-June to mid-July. Spring and autumn offer pleasant conditions for exploring. Air conditioning is essential in summer.",
        "cost": "Osaka is expensive but cheaper than Tokyo. Monthly costs range from ¥200,000-350,000 ($1,450-2,550 USD) for a comfortable lifestyle. Rent for a central one-bedroom apartment averages ¥70,000-100,000. The famous street food scene allows cheap eating, with takoyaki and okonomiyaki costing ¥500-800. Restaurant meals run ¥800-1,500. Transport is efficient with day passes available. Coworking spaces cost ¥15,000-30,000 monthly.",
        "wifi": "Japan has excellent internet infrastructure, and Osaka is well-connected. Cafes and restaurants commonly offer free WiFi. Coworking spaces like WeWork and local options provide reliable high-speed connections. Pocket WiFi rentals are popular for mobile connectivity. The metro and major public spaces have WiFi access. Mobile data SIM cards for tourists are readily available at airports and electronics stores.",
        "nightlife": "Osaka's nightlife is famously vibrant, centered around Dotonbori and Namba's neon-lit streets. The Shinsekai district offers retro charm and izakayas. America-mura (American Village) caters to younger crowds with clubs and bars. Osaka-style drinking involves bar-hopping between standing bars and small izakayas. The city has a more casual, boisterous atmosphere than Tokyo. Live music venues host local bands. Nights can extend late, especially on weekends.",
        "nature": "Osaka is more urban than Kyoto but offers natural escapes. Osaka Castle Park provides green space in the city center with cherry blossoms in spring. The nearby Mount Rokko offers hiking and panoramic views. Day trips to Nara feature ancient temples and friendly deer. The Osaka Bay waterfront provides seaside atmosphere. Minoo Park, just 30 minutes away, has waterfalls and forested trails. Mount Koya offers temple stays.",
        "safety": "Osaka is very safe by global standards, though slightly grittier than other Japanese cities. Violent crime is rare. The Shinsekai and Tobita areas have seedier reputations but aren't dangerous for tourists. The main concerns are bicycle theft and occasional drunk behavior in entertainment districts. Walking alone at night is generally safe anywhere. Japan's overall culture of respect and order prevails.",
        "food": "Osaka calls itself Japan's kitchen (tenka no daidokoro), and the food scene is legendary. Street food reigns supreme: takoyaki (octopus balls), okonomiyaki (savory pancakes), and kushikatsu (deep-fried skewers) define the cuisine. The Kuromon Market offers fresh seafood and snacks. Ramen shops compete for devoted followings. The city's attitude toward food is more casual and indulgent than Kyoto's refinement. Eating while walking is more accepted here.",
        "community": "Osaka has a growing digital nomad community, though smaller than Tokyo's. The city attracts those who prefer its friendlier, more casual atmosphere. Coworking spaces host networking events for remote workers and entrepreneurs. The expat community is welcoming and connected through various social groups. Osakans are known as Japan's most outgoing people, making connections easier than in reserved Kyoto or formal Tokyo.",
        "english": "English proficiency in Osaka is moderate, similar to other major Japanese cities. Tourist areas handle English reasonably well. Local restaurants and shops may have limited English but will try to help with gestures and translation apps. Written menus often have pictures. Learning basic Japanese significantly improves daily life. The friendly Osaka personality means people will attempt to communicate despite language barriers.",
        "visa": "Japan offers visa-free entry for citizens of many countries, allowing stays of up to 90 days. Extensions are possible but difficult. There's no digital nomad visa; remote workers typically enter as tourists. Work visas require sponsorship from Japanese employers. The Specified Skilled Worker program is expanding opportunities. Long-term stays often involve periodic trips to nearby countries to reset tourist status.",
        "culture": "Osaka's culture is famously different from Tokyo's—more direct, humorous, and unpretentious. The local dialect (Osaka-ben) is known for comedic delivery. The city has produced many of Japan's comedians and entertainers. Merchant culture historically shaped values of practicality over formality. Food culture is central to identity. The Hanshin Tigers baseball team inspires fierce loyalty. Osakans take pride in their distinctive regional character.",
        "cleanliness": "Osaka is very clean by global standards, though slightly less immaculate than Kyoto or Tokyo. Streets are well-maintained with minimal litter despite few public trash cans. Entertainment districts can get messier on weekend nights. Public transportation is clean and efficient. The main tourist areas are kept tidy. Japanese standards of public cleanliness apply throughout, with recycling carefully observed.",
        "airquality": "Osaka has moderate air quality, being Japan's second-largest metropolitan area with significant industrial activity. Summer humidity can make the air feel heavy. The surrounding mountains can trap pollution on still days. Air quality indexes typically remain in acceptable ranges but occasionally reach unhealthy levels during certain conditions. Sea breezes from Osaka Bay help clear the air. Most visitors don't notice issues."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")

    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
