#!/usr/bin/env python3
"""Rewrite batch 11: Major cities S-V (split, sydney, taipei, tbilisi, tokyo, vienna)."""

import json
import os

BATCH_CITIES = {
    "split": {
        "climate": "Split has a Mediterranean climate with hot, dry summers (28-33°C) and mild, rainy winters (8-14°C). Summer is ideal for beach life, though crowded. Spring and autumn offer pleasant temperatures with fewer tourists. Winter is quiet but comfortable for exploration. The Adriatic moderates temperatures. Over 2,600 hours of sunshine annually make it reliably sunny.",
        "cost": "Split offers good value for the Adriatic. A comfortable lifestyle costs €1,300-2,000/month. Apartments range €500-900/month—higher in the old town. Restaurant meals cost €10-18. Summer season brings premium pricing. Off-season offers significantly better value. Croatia's EU membership has increased costs but value remains solid.",
        "wifi": "Croatian internet is reliable. Split offers speeds of 40-80 Mbps. WiFi is available in cafes and restaurants. Coworking spaces provide stable connections. Mobile data through A1, T-Mobile, or Tele2 is affordable. The infrastructure supports remote work adequately.",
        "nightlife": "Split's nightlife is vibrant, especially in summer. The Riva promenade fills with bars. Bačvice beach has nighttime energy. The old town's narrow streets host atmospheric venues. The scene is social and Mediterranean—drinks, conversation, late dinners. Clubs cater to summer crowds. The atmosphere is relaxed and welcoming.",
        "nature": "Split is gateway to Dalmatian nature. The city beach (Bačvice) is steps from the palace. Day trips reach the islands—Hvar, Brač, Vis are spectacular. Krka waterfalls and Plitvice Lakes are accessible. Mosor mountain rises behind the city. The combination of beach, islands, and mountains creates diverse options.",
        "safety": "Split is very safe. Violent crime is virtually nonexistent. Petty theft is rare outside busy tourist periods. Croatian hospitality creates a welcoming atmosphere. Walking at night is comfortable anywhere. The relaxed Mediterranean culture extends to safety. Standard awareness is sufficient.",
        "food": "Dalmatian cuisine showcases fresh seafood, olive oil, and Mediterranean vegetables. Grilled fish, black risotto, and pršut (prosciutto) are highlights. The green market offers fresh ingredients. Konobas (traditional restaurants) serve authentic cuisine. The food is simple, ingredient-focused, and excellent. Quality matches the Adriatic setting.",
        "community": "Split's nomad community has grown significantly. The combination of beach, history, and lifestyle attracts remote workers. Coworking spaces serve the growing scene. The community is smaller but tight-knit compared to larger hubs. Connections form easily in this manageable city. Croatians are warm and social.",
        "english": "English is widely spoken, especially among younger Croatians and in tourism. Daily life functions in English. Croatian is appreciated but not required. The Dalmatian coast's tourism orientation ensures English accessibility. Communication is straightforward.",
        "visa": "Croatia joined Schengen in 2023. EU citizens have freedom of movement. Non-EU visitors stay 90 days within Schengen. Croatia's Digital Nomad Visa allows one-year stays for remote workers earning €2,540+/month. The process is straightforward. Croatia actively welcomes digital nomads.",
        "culture": "Split's culture centers on Diocletian's Palace—a living Roman monument where people live, shop, and socialize within ancient walls. The Riva promenade is daily social life. The culture is Mediterranean—afternoon coffee, evening strolls, family dinners. History is lived daily, not museum-bound. The blend of ancient and modern defines Split's character.",
        "cleanliness": "Split maintains good standards. The old town and Riva are regularly cleaned. Beaches are maintained for tourism. Streets function well. Tap water is safe. The city makes visible efforts at maintenance, particularly in tourist areas. Standards are appropriate for a Mediterranean city.",
        "airquality": "Air quality in Split is excellent, with AQI typically 20-40. The Adriatic Sea and lack of heavy industry keep air clean. Sea breezes provide constant freshness. The coastal position ensures good ventilation. The air quality complements the outdoor lifestyle."
    },
    "sydney": {
        "climate": "Sydney has a humid subtropical climate with warm summers (22-28°C) and mild winters (10-17°C). The harbor moderates temperatures. Rain is possible year-round but not oppressive. Summer can see heat waves exceeding 40°C. The beach lifestyle is year-round, though water is cooler in winter. The climate is genuinely pleasant with abundant sunshine.",
        "cost": "Sydney is extremely expensive—among the world's costliest cities. A comfortable lifestyle costs AUD 4,500-7,000/month ($3,000-4,600). Apartments are brutal, ranging AUD 2,200-3,800/month. Dining out costs $18-35. The housing crisis is acute. The cost reflects limited supply and high demand in a desirable city.",
        "wifi": "Australian internet has improved with NBN. Sydney offers speeds of 50-100+ Mbps. Public WiFi is available but less comprehensive than Asia. Cafes offer connectivity. Coworking spaces provide reliable connections. Mobile coverage is excellent. The infrastructure supports remote work adequately.",
        "nightlife": "Sydney's nightlife has been affected by lockout laws but remains varied. The Rocks and Darling Harbour offer waterfront venues. Kings Cross has shed its edgy reputation. Newtown and Surry Hills have hip bars. The beach suburbs have their scenes. Rooftop bars with harbor views are highlights. The scene is sophisticated rather than wild.",
        "nature": "Sydney's nature is its defining feature. The harbor and beaches integrate into city life. Bondi to Coogee walk is iconic. The Blue Mountains are 90 minutes away. National parks surround the city. The Royal Botanic Garden provides urban green space. Nature is accessed daily, not just on weekends.",
        "safety": "Sydney is very safe by global standards. Violent crime is rare. Some areas have higher property crime. The beach culture creates a relaxed, trusting atmosphere. Walking at night is comfortable in most areas. Australian common sense applies. Emergency services are excellent.",
        "food": "Sydney's food scene is world-class and multicultural. Asian cuisines are exceptional, reflecting immigration patterns. Seafood at the fish market is outstanding. Modern Australian cuisine innovates with local ingredients. Coffee culture is serious. The diversity and quality rival any global city.",
        "community": "Sydney has a significant international community. The tech, creative, and finance sectors draw global talent. The nomad community exists within broader professional networks. Coworking spaces host events. Australians are friendly and welcoming. The community is established and diverse.",
        "english": "Sydney is native English-speaking. Australian English has distinctive slang and expressions. Communication is effortless. The multicultural population means many languages are heard, but English is universal.",
        "visa": "Australian visa rules apply. ETAs allow short visits. Working holiday visas enable those under 30-35 to work and travel. Skilled worker visas are competitive. Australia has categories for tech professionals. The immigration system is organized but selective.",
        "culture": "Sydney's culture blends beach lifestyle with global city sophistication. The Opera House is iconic. Aboriginal heritage predates colonization by 65,000 years. The multicultural population shapes contemporary identity. The outdoor lifestyle is central—weekends involve beaches, bush walks, and barbecues. The culture is casual, confident, and sun-loving.",
        "cleanliness": "Sydney is very clean. Beaches are maintained. Public spaces are tidy. Transport is reasonably clean. The harbor sparkles. Tap water is excellent. Standards are high, maintained by both infrastructure and social expectation.",
        "airquality": "Air quality in Sydney is generally good (AQI 20-50). Bushfire smoke can create severe conditions during summer fire seasons—this has become more frequent. Sea breezes help disperse pollution. Most of the year, air quality is excellent."
    },
    "taipei": {
        "climate": "Taipei has a humid subtropical climate with hot, humid summers (28-35°C) and mild, damp winters (14-20°C). Rain is frequent year-round, with typhoon season June-October. The humidity is challenging in summer. Spring and autumn offer more comfortable conditions. Air conditioning is universal. The climate requires adaptation but is manageable.",
        "cost": "Taipei offers excellent value for a developed Asian capital. A comfortable lifestyle costs $1,800-2,800/month. Apartments range $600-1,200/month. Local food is cheap and excellent ($3-8). MRT is affordable. The cost-quality ratio is favorable compared to Japan or Korea.",
        "wifi": "Taiwan's internet infrastructure is excellent. Taipei offers speeds of 100+ Mbps commonly. Free public WiFi is widespread. Cafes welcome laptop workers. Mobile data is cheap and reliable. The city is comprehensively connected and ideal for remote work.",
        "nightlife": "Taipei's nightlife is varied. Night markets are social hubs—eating and shopping until late. Xinyi district has upscale clubs. Da'an has trendy bars. The scene is sophisticated and safe. Karaoke (KTV) is cultural institution. The energy is positive and inclusive.",
        "nature": "Taipei is surrounded by mountains accessible by metro. Yangmingshan National Park offers hiking and hot springs. Elephant Mountain provides city views. Day trips reach spectacular natural scenery. Jiufen and the northeast coast are highlights. Nature is remarkably accessible for a major city.",
        "safety": "Taipei is extremely safe—among the world's safest cities. Violent crime is rare. Lost items are returned. Walking anywhere at any hour is comfortable. The society is trusting and orderly. Safety is a genuine strength that shapes daily life.",
        "food": "Taiwanese food is exceptional—night market culture is legendary. Beef noodle soup, xiao long bao (soup dumplings), bubble tea, and countless snacks offer daily discoveries. The food scene blends Chinese regional cuisines. Quality is consistent and prices are low. Food is a primary reason to be in Taipei.",
        "community": "Taipei's international community is growing, with a developing nomad scene. Coworking spaces host events. The tech and startup ecosystems provide networking. Taiwanese are friendly and helpful. The community is welcoming though language barriers exist. Connections form through work spaces and shared interests.",
        "english": "English is taught but spoken ability varies. Younger Taiwanese often have reasonable English. Tourism areas function in English. Outside these zones, Mandarin becomes essential. Translation technology helps. The language barrier is real but navigable.",
        "visa": "Taiwan offers visa-free entry (90 days) for most Western nationalities. Work permits require sponsorship. Taiwan has the Gold Card visa for qualified professionals—a relatively accessible path. The process is organized. Taiwan welcomes international talent.",
        "culture": "Taiwanese culture blends Chinese tradition with Japanese influence and modern democracy. Temples and tech coexist. The night market culture is unique. Hot springs reflect Japanese legacy. The society is progressive and democratic—distinct from mainland China. Hospitality is genuine and warm.",
        "cleanliness": "Taipei is very clean by Asian standards. Streets are maintained. The MRT is spotless. Public facilities are excellent. Tap water is technically safe but most drink filtered. The attention to cleanliness is impressive and consistent.",
        "airquality": "Air quality in Taipei is moderate to good, with AQI typically 30-70. Traffic and weather affect levels. Seasonal variation exists—summer can see higher levels. The situation is better than many Asian capitals. Monitor conditions if sensitive."
    },
    "tbilisi": {
        "climate": "Tbilisi has a humid subtropical climate with hot summers (25-35°C) and cool winters (0-8°C). The city sits in a valley that can trap heat in summer. Spring and autumn are ideal with pleasant temperatures. Winter is manageable but can be cold. The wine country climate supports viticulture. Four seasons are distinct.",
        "cost": "Tbilisi offers exceptional value—among Europe's most affordable capitals. A comfortable lifestyle costs $1,000-1,600/month. Apartments range $300-700/month. Restaurant meals cost $5-12. Wine is local and incredibly cheap. The value attracts digital nomads seeking European lifestyle at affordable prices.",
        "wifi": "Georgia has invested in internet infrastructure. Tbilisi offers speeds of 30-80 Mbps. WiFi is common in cafes. Coworking spaces like Impact Hub provide reliable connections. Mobile data is cheap and reliable. The infrastructure supports remote work well.",
        "nightlife": "Tbilisi's nightlife is famous, particularly the techno scene. Bassiani is world-renowned. The underground club culture is serious and inclusive. Wine bars in the old town offer mellower options. The scene is creative, welcoming, and runs very late. Few cities match Tbilisi's nightlife-to-cost ratio.",
        "nature": "Georgia's nature is spectacular and accessible from Tbilisi. The Caucasus mountains are day-trip distance. Kazbegi's dramatic landscapes are 3 hours away. Wine regions like Kakheti offer pastoral beauty. The diversity—mountains, deserts, forests—is remarkable for a small country.",
        "safety": "Tbilisi is very safe—one of Europe's safest capitals. Violent crime is rare. Petty theft is uncommon. Georgian hospitality is legendary—guests are sacred. Walking at night is comfortable anywhere. The atmosphere is welcoming and trusting.",
        "food": "Georgian cuisine is a revelation—khachapuri (cheese bread), khinkali (dumplings), and endless variety. Wine is integral—Georgia claims to be wine's birthplace. The supra (feast) tradition welcomes guests lavishly. The food is flavorful, generous, and incredibly affordable. Georgian hospitality extends to the table.",
        "community": "Tbilisi has a rapidly growing nomad community. The value and visa policies attract remote workers. Coworking spaces and cafes serve as hubs. The community is diverse and international. Georgians are warm once initial reserve fades. The scene feels dynamic and emerging.",
        "english": "English is growing, especially among younger Georgians. Tourist areas and businesses manage in English. Outside central areas, Georgian or Russian helps. Learning basic Georgian phrases earns significant warmth. The language barrier is manageable but present.",
        "visa": "Georgia offers incredibly generous visa policies—365 days visa-free for most nationalities. This alone makes it attractive for nomads. Work doesn't require separate permits for most stays. The accessibility is exceptional. Georgia actively welcomes long-term visitors.",
        "culture": "Georgian culture is ancient, proud, and hospitable. Orthodox Christianity shapes traditions. The polyphonic singing is UNESCO-recognized. Wine culture dates back 8,000 years. The Cyrillic-looking alphabet is unique. The culture values hospitality, wine, and celebration. Guests are treated as gifts from God.",
        "cleanliness": "Tbilisi's cleanliness varies. The old town and tourist areas are maintained. Some streets show wear. Development is ongoing. Tap water is safe. Standards are improving with tourism growth. The situation is reasonable for an emerging destination.",
        "airquality": "Air quality in Tbilisi is moderate, with AQI typically 40-70. The valley location can trap pollution. Traffic affects central areas. Winter heating increases levels. The situation is manageable but noticeable. Conditions vary by season and weather."
    },
    "tokyo": {
        "climate": "Tokyo has a humid subtropical climate with four distinct seasons. Summers are hot and humid (28-35°C) with heavy rain. Winters are cool and dry (2-10°C). Spring cherry blossoms (March-April) and autumn colors (November) are spectacular. The humidity and rainy season (June-July) are challenging. The climate is manageable with preparation.",
        "cost": "Tokyo is expensive but offers surprising value in areas. A comfortable lifestyle costs ¥350,000-500,000/month ($2,400-3,400). Apartments range ¥120,000-200,000/month—small but functional. Convenience store food is cheap and good. Ramen is $8-12. High-end costs scale up quickly. Budget carefully but value exists.",
        "wifi": "Japan's internet infrastructure is excellent. Tokyo offers speeds of 100+ Mbps commonly. Free public WiFi has improved but isn't comprehensive. Cafes vary—many aren't laptop-friendly. Coworking spaces provide reliable connections. Pocket WiFi rentals solve connectivity. Mobile data is available but can be pricey.",
        "nightlife": "Tokyo's nightlife is legendary and varied. Shibuya and Shinjuku offer massive entertainment districts. Golden Gai has tiny, intimate bars. Roppongi caters to international crowds. The scene spans every preference—from jazz clubs to techno warehouses. The energy and variety are unmatched. Last trains end around midnight, but many areas run all night.",
        "nature": "Tokyo offers surprising nature access. Parks like Yoyogi and Shinjuku Gyoen provide urban escapes. Day trips reach Mount Takao, beaches, and hot springs. Mount Fuji is visible on clear days. The Japanese Alps are accessible for weekends. Nature balances the urban intensity.",
        "safety": "Tokyo is extraordinarily safe—possibly the world's safest major city. Violent crime is essentially nonexistent. Lost items are returned. Walking anywhere at any hour is completely comfortable. The society's order and trust are remarkable. Safety is a defining characteristic.",
        "food": "Japanese cuisine in Tokyo is unmatched—the city has more Michelin stars than any other. Sushi, ramen, tempura, and kaiseki are at their finest. Convenience stores serve genuinely good food. The attention to quality is obsessive. From ¥500 bowls to omakase experiences, excellence is available at every price point.",
        "community": "Tokyo's international community is significant but can feel segregated. The nomad scene is smaller than Southeast Asian hubs—cost and language are barriers. Coworking spaces exist but Japanese work culture differs. Connections require effort. The community that exists is sophisticated and committed.",
        "english": "English is taught universally but spoken ability is limited. Signs are often bilingual. Tourist areas manage in English. Business English exists in international contexts. Outside these, Japanese is necessary. The language barrier is real but technology helps. Learning Japanese significantly enriches the experience.",
        "visa": "Japan offers visa-free entry (90 days) for most Western nationalities. Work visas require sponsorship and are specific to categories. Japan has introduced startup visas and is expanding options. The immigration system is organized but conservative. Working legally requires proper arrangements.",
        "culture": "Japanese culture is unique—ancient traditions coexist with cutting-edge modernity. Temples and shrines provide spiritual anchors. The attention to craft and detail pervades everything. Social harmony and respect structure interactions. Pop culture—anime, fashion, gaming—has global influence. The culture rewards patient observation.",
        "cleanliness": "Tokyo is immaculately clean—the standard others are measured against. Streets are spotless despite few trash cans. The subway is pristine. Public toilets are technological marvels. The cleanliness reflects cultural values of order and respect for shared spaces.",
        "airquality": "Air quality in Tokyo is generally good, with AQI typically 30-60. Traffic affects levels locally. Seasonal variation exists—spring pollen affects many. The situation has improved dramatically from past decades. Most days the air is acceptable by global standards."
    },
    "vienna": {
        "climate": "Vienna has a humid continental climate with warm summers (20-28°C) and cold winters (-2 to 5°C). The city experiences all four seasons distinctly. Summer can be hot but rarely extreme. Winter is genuinely cold with occasional snow. Spring and autumn are pleasant for exploration. The continental climate delivers clear seasonal changes.",
        "cost": "Vienna is expensive by global standards but moderate for Western Europe. A comfortable lifestyle costs €2,200-3,200/month. Apartments range €900-1,500/month. Restaurant meals cost €15-25. The famous coffee house culture is affordable. Quality justifies cost. The city provides excellent value for what it offers.",
        "wifi": "Austrian internet infrastructure is excellent. Vienna offers speeds of 50-100+ Mbps. Public WiFi is available. Cafes welcome lingering—Vienna invented coffee house culture. Coworking spaces provide reliable connections. Mobile data is reliable. The city supports remote work well.",
        "nightlife": "Vienna's nightlife is sophisticated rather than wild. The famous coffee houses create evening atmosphere. Wine taverns (Heurigen) in the hills offer unique experiences. The club scene exists but is secondary to cultural offerings—opera, concerts, theater. The scene is cultured and refined.",
        "nature": "Vienna is one of Europe's greenest capitals. The Vienna Woods surround the city with hiking and cycling. The Danube provides river recreation. City parks are numerous and well-maintained. Day trips reach the Alps, wine regions, and Wachau Valley. Nature is integrated into city life.",
        "safety": "Vienna is extremely safe—consistently ranked among the world's safest and most livable cities. Violent crime is virtually nonexistent. Petty theft is rare. Walking anywhere at any time is comfortable. Austrian orderliness creates a secure environment. Safety is a major strength.",
        "food": "Viennese cuisine reflects imperial history. Wiener schnitzel, tafelspitz, and sachertorte are iconic. The coffee house culture serves pastries with serious tradition. International options reflect the cosmopolitan population. Quality is consistently high. The food culture emphasizes tradition and quality.",
        "community": "Vienna has a significant international community, including UN employees and business professionals. The nomad community is growing but not dominant. Coworking spaces and professional networks provide connections. Austrians can seem reserved initially but warm over time. The community is cultured and established.",
        "english": "English is widely spoken in Vienna, especially in business and among younger Austrians. Daily life functions in English. German is beneficial for deeper integration and appreciated locally. The international community ensures English accessibility. Communication is straightforward.",
        "visa": "Austria is part of the EU and Schengen. EU citizens have freedom of movement. Non-EU visitors stay 90 days within Schengen. Austria offers various residence permits for workers and self-employed. The Red-White-Red Card serves skilled workers. Austrian bureaucracy is organized but thorough.",
        "culture": "Vienna's culture is defined by imperial heritage, music, and intellectual tradition. The Habsburg legacy is everywhere—palaces, museums, and architecture. The musical heritage—Mozart, Beethoven, Strauss—continues in opera houses and concert halls. Coffee house culture is UNESCO-recognized. The culture is sophisticated, traditional, and proud.",
        "cleanliness": "Vienna is immaculately clean—consistently ranked among the world's cleanest cities. Streets are spotless. Public transport is pristine. Parks are meticulously maintained. Tap water from the Alps is excellent. The cleanliness reflects Austrian values of order and quality.",
        "airquality": "Air quality in Vienna is excellent, with AQI typically 20-40. The surrounding forests and limited heavy industry help. Environmental regulations are strict. The city has invested in clean transport. The air is clean and pleasant year-round."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
