#!/usr/bin/env python3
"""Rewrite batch 4: Detailed descriptions for cities A-B (annecy-bangalore)."""

import json
import os

BATCH_CITIES = {
    "annecy": {
        "climate": "Annecy has an Alpine-influenced climate with warm summers (20-27°C) and cold, snowy winters (0-5°C). The lake moderates temperatures somewhat. Summer is ideal for water activities, while winter offers nearby skiing. Spring and autumn bring shoulder season charm with fewer tourists. Rain is possible year-round, with thunderstorms common in summer afternoons. The mountains create microclimates—pack for variability.",
        "cost": "Annecy is expensive for a French town of its size, driven by tourism and affluence. A comfortable lifestyle costs €2,000-3,000/month. Apartments range €800-1,400/month. Restaurant meals run €18-30, reflecting the quality ingredients. The market offers excellent but pricey produce. Winter ski-season accommodation commands premiums. The cost reflects the exceptional quality of life and Alpine setting.",
        "wifi": "French internet infrastructure serves Annecy well, with average speeds of 50-80 Mbps. Fiber is expanding. Cafes offer WiFi, though the French preference for conversation over laptops applies. Coworking options are limited but exist. Mobile data through French providers works well. The town's size means less sophisticated digital infrastructure than cities, but connectivity is adequate for remote work.",
        "nature": "Annecy's setting is spectacular—a crystal-clear lake surrounded by Alpine peaks. The lake is swimmable in summer, with temperatures reaching 24°C. Mountains offer hiking in summer and skiing in winter, with resorts like La Clusaz nearby. Cycling paths circle the lake. The Semnoz mountain rises directly behind the town. Paragliding over the lake is popular. Nature is Annecy's primary attraction and lifestyle.",
        "safety": "Annecy is extremely safe—one of France's most pleasant towns. Violent crime is virtually nonexistent. Petty theft is rare. The affluent, family-oriented population contributes to the secure atmosphere. Water safety is important—follow lake rules and mountain safety guidelines. The only real risk is overestimating your Alpine abilities. Emergency services are excellent.",
        "food": "Savoyard cuisine dominates Annecy—fondue, raclette, and tartiflette are everywhere. Quality cheese is a given. The lake provides fresh fish, particularly perch and fera. The old town hosts excellent restaurants ranging from traditional to modern French. The market on Place Sainte-Claire is exceptional. Wine from nearby Savoie is underrated. Food quality is high, reflecting the region's produce and culinary tradition.",
        "community": "Annecy attracts outdoor enthusiasts, retirees, and those seeking quality of life. The international community is small but present. Digital nomads are less common—this isn't a hub but a lifestyle choice. Connections form through outdoor activities, language exchanges, and cultural events. The town is friendly but not transient. Building community requires time and shared interests rather than networking events.",
        "english": "English is spoken in tourist contexts but French dominates daily life. Many locals have some English, especially younger people in tourism. However, Annecy is proudly French—effort with the language is expected and appreciated. Learning French significantly enriches life here. University and business contexts offer more English. Non-French speakers can manage but will feel somewhat limited.",
        "visa": "France's visa rules apply. EU citizens have freedom of movement. Non-EU visitors stay 90 days within Schengen. France offers various long-stay visas but no specific digital nomad visa. The 'passeport talent' serves entrepreneurs and skilled workers. Non-lucrative visas require proof of income. Annecy has no special provisions—standard French immigration applies. The bureaucracy requires patience.",
        "culture": "Annecy's charm lies in its preserved medieval old town with flower-laden canals earning it the 'Venice of the Alps' nickname. The Château d'Annecy overlooks the town. Cultural events include the International Animated Film Festival and Venetian Carnival. The pace is relaxed—people prioritize outdoor life and quality time. Savoyard culture is distinct from Parisian France, more Alpine and traditional.",
        "cleanliness": "Annecy is immaculately clean—one of France's tidiest towns. The lake is famously pure, among Europe's cleanest. Streets and canals are well-maintained. The prosperous, tourism-dependent economy ensures high standards. Tap water is excellent. The French Alpine pride in cleanliness is evident everywhere. Even outside tourist season, standards remain high.",
        "airquality": "Air quality in Annecy is generally excellent, with AQI typically 15-35. The Alpine setting and lack of industry keep air clean. Lake breezes provide freshness. Winter inversions can temporarily trap pollution in the basin. Summer ozone levels may rise during heat waves. Overall, the air is among France's cleanest—a major draw for quality-of-life seekers."
    },
    "antalya": {
        "climate": "Antalya has a hot Mediterranean climate with scorching summers (30-40°C) and mild, rainy winters (10-18°C). The sea moderates coastal temperatures. Summer is beach season, though intense heat can be draining. Winter offers pleasant exploration weather. Spring and autumn are ideal—warm but not extreme. Over 300 sunny days per year make it a reliable warm destination.",
        "cost": "Turkey's economic situation makes Antalya exceptionally affordable for Westerners. A comfortable lifestyle costs $800-1,400/month. Apartments range $300-600/month, including sea views at the higher end. Restaurant meals cost $5-12, with incredible value at local spots. The tourist industry provides English-friendly services at local prices. Currency fluctuations make dollar or euro budgets go far.",
        "wifi": "Turkey has developed good internet infrastructure. Antalya offers speeds of 30-60 Mbps typically. WiFi is common in cafes and hotels. Mobile data through Turkcell, Vodafone, or Türk Telekom provides reliable backup. Some social media platforms face restrictions—VPNs are commonly used. Coworking spaces offer stable connections. Connectivity supports remote work adequately.",
        "nightlife": "Antalya's nightlife centers on Kaleiçi (old town) and the beach resort areas. The harbor area has atmospheric bars with sea views. Konyaaltı beach has modern beach clubs. The scene is active in summer, with tourism driving the energy. Club Arma and nearby venues offer late-night dancing. Winter is quieter but not dead. Turkish hospitality extends to evening entertainment.",
        "nature": "Antalya combines coast and mountains dramatically. The turquoise Mediterranean is the primary draw, with beaches and coves along the coast. The Taurus Mountains rise directly behind the city, offering cooler escapes. Düden Waterfalls cascade into the sea. Ancient sites like Olympos and Phaselis combine ruins with beaches. The Köprülü Canyon provides rafting adventures. Nature is spectacular and varied.",
        "safety": "Antalya is generally safe, a major tourism center that protects its reputation. Petty theft is possible in crowded areas. Traffic can be aggressive. The political situation requires monitoring, but tourist areas remain stable. Solo female travelers receive attention but harassment is generally manageable. Turkish people are hospitable and helpful. Standard precautions ensure a safe experience.",
        "food": "Turkish cuisine is a highlight of Antalya. Fresh seafood from the Mediterranean is excellent. Kebabs, meze, and pide (Turkish pizza) are daily pleasures. Breakfast spreads are legendary—cheese, olives, tomatoes, eggs, honey. The bazaars offer spices and produce. Baklava and Turkish delight satisfy sweet cravings. Street food is cheap and delicious. The food alone justifies visiting Turkey.",
        "community": "Antalya has a significant expat community, including many retirees and digital nomads drawn by affordability and weather. Russians and Europeans are heavily represented. The nomad community has grown rapidly due to value. Coworking spaces and cafes serve as gathering points. Turkish people are warm and welcoming. The mix of long-term residents and transient tourists creates varied social options.",
        "english": "English is widely spoken in tourism-focused Antalya. Hotels, restaurants, and shops in tourist areas function in English. Outside these zones, Turkish becomes necessary. Many young Turks speak some English. Learning basic Turkish phrases earns appreciation and improves daily interactions. The tourism industry ensures you can manage in English, but depth requires language effort.",
        "visa": "Turkey offers e-visas online for most nationalities (typically $50), allowing 90 days within 180. The process is quick and easy. Tourism focus makes entry simple. Longer stays require residence permits—the process has become more streamlined. Turkey offers a short-term residence permit for those with income. Work permits require employer sponsorship. The country is generally accessible.",
        "culture": "Antalya blends ancient history with resort modernity. The old town (Kaleiçi) contains Roman, Byzantine, and Ottoman heritage. Hadrian's Gate marks the entrance. The city was part of ancient Pamphylia. Modern Antalya is tourism-focused but retains Turkish character. The call to prayer echoes through the old town. Mediterranean cafe culture mixes with Turkish traditions. The layers of history are everywhere visible.",
        "cleanliness": "Antalya maintains good standards, particularly in tourist areas. Beaches are cleaned regularly and often hold Blue Flag certification. The old town is well-maintained. Streets are swept, and infrastructure is functional. Outside premium areas, standards may vary. Tap water is generally safe but most drink bottled. The tourism industry drives maintenance standards.",
        "airquality": "Air quality in Antalya is generally good, with AQI typically 30-60. Sea breezes keep coastal air fresh. Traffic and urban areas see higher levels. The Taurus Mountains provide a backdrop of clean mountain air. Summer heat can raise ozone levels temporarily. Forest fires occasionally affect air quality. Overall, the coastal setting ensures reasonable air quality."
    },
    "antigua": {
        "climate": "Antigua Guatemala has a subtropical highland climate due to its 1,500m altitude. Temperatures are spring-like year-round (15-25°C), rarely hot or cold. The rainy season (May-October) brings afternoon showers; dry season offers clear skies. The consistent pleasant weather is a major draw. Pack layers for cool evenings. The climate is comfortable almost every day of the year.",
        "cost": "Antigua offers excellent value for a tourist-focused town. A comfortable lifestyle costs $1,000-1,600/month. Apartments range $400-800/month, with colonial charm at higher prices. Restaurant meals cost $5-15, with local comedores even cheaper. Spanish schools offer affordable immersion. The touristic economy means prices are higher than rural Guatemala but remain reasonable by Western standards.",
        "wifi": "Guatemala's infrastructure is developing, and Antigua offers reasonable connectivity for the region. Average speeds are 20-40 Mbps. WiFi quality varies significantly by establishment. Coworking spaces like Impact Hub provide reliable connections. Mobile data through Tigo or Claro offers backup. Power can be inconsistent—have battery backup for important work. Overall adequate for remote work.",
        "nature": "Antigua sits in a valley surrounded by three volcanoes—Agua, Fuego, and Acatenango. Fuego erupts regularly, providing dramatic displays (from safe distances). Volcano hikes are popular, especially the overnight Acatenango trek. Lake Atitlán, one of the world's most beautiful lakes, is a few hours away. The Pacific coast and highlands offer weekend escapes. Nature is dramatic and accessible.",
        "safety": "Antigua is relatively safe for Guatemala, a country with challenging security in some areas. The tourist center is well-policed. Petty theft occurs—don't flash valuables. Walking at night in central areas is generally fine. Surrounding areas require more caution. Tourist shuttles are preferred over public buses for longer distances. Common sense and local advice keep most visitors safe.",
        "food": "Guatemalan cuisine centers on corn, beans, and simple preparations. Local dishes include pepián (meat stew), tamales, and chiles rellenos. Antigua's tourist focus brings excellent international options—Italian, Asian, and fusion restaurants abound. Coffee is exceptional—Guatemala produces some of the world's best. Breakfast at Café Condesa is a ritual. Fresh fruits and vegetables from the market are affordable.",
        "community": "Antigua has a strong international community of Spanish students, retirees, nomads, and expatriates. The compact town makes connections easy. Spanish schools create social networks. Coworking spaces and cafes serve as gathering spots. The community is creative and alternative-minded. Guatemalans are warm once you engage. Regular events, volunteer opportunities, and shared interest groups provide community.",
        "english": "English is widely spoken in Antigua's tourist economy, particularly in hotels, restaurants, and services. Outside this bubble, Spanish is essential. The town is one of the world's most popular Spanish-learning destinations, with excellent schools at affordable prices. Many visitors come specifically to learn. Basic Spanish significantly enriches the experience and is almost expected.",
        "visa": "Guatemala offers visa-free entry for most Western nationalities, with 90-day stays in the CA-4 region (Guatemala, Honduras, El Salvador, Nicaragua). Extensions are possible with some bureaucracy. The country doesn't have a digital nomad visa. Longer stays involve visa runs or residency applications. The relaxed immigration approach makes Antigua accessible for extended stays.",
        "culture": "Antigua is a UNESCO World Heritage Site, a beautifully preserved Spanish colonial city. Cobblestone streets, baroque architecture, and ruined churches create a magical atmosphere. Semana Santa (Holy Week) features elaborate processions and carpets made of colored sawdust. Indigenous Mayan culture surrounds the town. The contrast between colonial splendor and modern Guatemala creates complex dynamics. History is visibly everywhere.",
        "cleanliness": "Antigua maintains good standards for Central America. The colonial center is regularly cleaned and well-maintained. Cobblestone streets are swept. Outside the center, standards vary. Tap water is not safe—bottled or filtered water is essential. The tourism economy drives maintenance efforts. Overall cleanliness is reasonable, with the historic town notably well-kept.",
        "airquality": "Air quality in Antigua is generally good, with AQI typically 30-60. The highland location and valley setting provide fresh air. Wood smoke and dust can affect quality temporarily. Volcanic ash from Fuego occasionally reaches the town. The altitude and surrounding vegetation help maintain freshness. Overall, the mountain air is clean and pleasant."
    },
    "antwerp": {
        "climate": "Antwerp has a temperate oceanic climate with mild summers (18-23°C) and cool winters (2-7°C). Rain is frequent year-round—the Belgian joke is that it rains 200 days a year. Gray skies are common, especially in winter. Spring brings flowers and longer days. The climate is essentially identical to Amsterdam and Brussels. Invest in good rain gear and embrace indoor café culture.",
        "cost": "Antwerp is expensive but cheaper than Amsterdam. A comfortable lifestyle costs €2,200-3,200/month. Apartments range €1,000-1,600/month in central areas. Restaurant meals cost €18-30, with the fashion-forward scene sometimes commanding premiums. Belgian beer is affordable and excellent. The diamond district drives some costs. Overall, expect Western European prices with Belgian quality.",
        "wifi": "Belgium has excellent internet infrastructure. Antwerp offers speeds of 80-150 Mbps commonly, with fiber widely available. Public WiFi is accessible. Cafes welcome workers, though the Belgian café culture prefers conversation. Coworking spaces like Fosbury & Sons provide premium connectivity. Mobile coverage is excellent. Connectivity is never a concern in Belgium.",
        "nightlife": "Antwerp's nightlife is diverse and sophisticated. The fashion and creative industries create a stylish scene. Clubs range from techno warehouses to intimate cocktail bars. The Belgian beer culture means excellent pubs and beer cafes. Het Eilandje (the harbor area) has trendy venues. The scene is less rowdy than Amsterdam, more design-conscious. Thursday through Saturday are active, with a late-starting rhythm.",
        "nature": "Antwerp is urban with limited nature within city limits. The Scheldt River defines the waterfront. City parks like Nachtegalen Park and Rivierenhof provide green escapes. The Belgian countryside—Flanders fields, the coast—is easily accessible by train. The Netherlands' beaches are an hour away. Nature requires leaving the city, but excursions are easy with Belgium's excellent rail network.",
        "safety": "Antwerp is generally safe, with low violent crime rates. The diamond district receives extra security attention. Petty theft can occur in tourist areas and on public transport. Bike theft is common—use good locks. Some neighborhoods in the northern suburbs have worse reputations. Standard urban awareness applies. Overall, you can walk most areas comfortably at any hour.",
        "food": "Belgian cuisine is underrated excellence. Antwerp offers exceptional restaurants, from traditional flemish stews to innovative fine dining. Fries (frieten) are taken seriously—standalone frietkoten are institutions. Mussels in season are essential. Chocolate and waffles live up to reputation. The multicultural population brings diverse options. Food markets and the trendy south (Het Zuid) showcase the scene. Quality is high across all levels.",
        "community": "Antwerp hosts a significant international community centered on fashion, diamonds, and creative industries. Digital nomads are less prominent than in Amsterdam but present. The creative scene provides networking opportunities. Belgians can seem reserved initially but are genuine once connected. Expat groups and coworking spaces facilitate community. The fashion-forward culture gives the community a distinct character.",
        "english": "English is widely spoken in Antwerp, particularly in business and tourism. Belgians are generally multilingual—Dutch (Flemish) is primary, with French and English common. Daily life in English is manageable. However, deeper integration requires Dutch. Signage and services are often multilingual. The language politics between Dutch and French speakers is a Belgian complexity.",
        "visa": "Belgium is part of the EU and Schengen. EU citizens have full freedom. Non-EU visitors stay 90 days within Schengen. Belgium offers various permits for workers and entrepreneurs. The bureaucracy is typically Belgian—organized but not fast. Brussels, as EU capital, handles many international work arrangements. No specific digital nomad visa exists, but standard categories apply.",
        "culture": "Antwerp punches above its weight culturally. The fashion capital of Belgium, it's home to designers like Dries Van Noten and the Antwerp Six. Rubens lived and worked here—his house is a museum. The diamond trade has centuries of history. Modern art institutions like M HKA are world-class. The culture is creative, slightly avant-garde, and proud of being 'not Brussels.' Flemish identity is strong.",
        "cleanliness": "Belgian cities are well-maintained, and Antwerp is no exception. Streets are regularly cleaned, public spaces are tidy, and infrastructure is kept in good condition. The Belgian attention to quality extends to civic maintenance. Tap water is excellent. Public transport is clean. The overall impression is of orderly, well-managed urban life.",
        "airquality": "Air quality in Antwerp is moderate, with AQI typically 30-60. Port activities and traffic affect quality. The flat, densely populated Low Countries face regional pollution challenges. Coastal influences bring some freshness. Efforts to reduce emissions are ongoing. The situation is typical for Western European cities—not pristine but manageable."
    },
    "bangalore": {
        "climate": "Bangalore (Bengaluru) enjoys a moderate climate thanks to its 900m elevation. Temperatures range 20-35°C year-round, rarely extreme by Indian standards. The monsoon (June-September) brings heavy rains, while October-May is drier. The 'Garden City' reputation comes from pleasant weather. Evenings can be cool—unusual for South India. The climate is one of India's most comfortable.",
        "cost": "Bangalore offers excellent value for a major tech city. A comfortable lifestyle costs $1,000-1,800/month. Apartments range $400-800/month in good areas like Koramangala or Indiranagar. Restaurant meals cost $3-10, with street food even cheaper. Western-style cafes charge more but remain reasonable. The tech industry has increased costs, but value remains strong compared to Western tech hubs.",
        "wifi": "India has made massive internet investments, and Bangalore as the tech capital benefits significantly. Fiber connections offer 50-100+ Mbps. Cafes commonly offer WiFi, and coworking spaces like WeWork and 91springboard provide excellent connectivity. Mobile data through Jio, Airtel, or Vodafone is cheap and reliable. Load shedding (power cuts) are rare in central areas now.",
        "nightlife": "Bangalore has India's most vibrant nightlife scene. Indiranagar and Koramangala host endless bars, clubs, and live music venues. The craft beer revolution started here. Church Street in the CBD has legacy establishments. Clubs stay open later than other Indian cities. The young tech workforce drives the scene. International DJs and concerts are common. The atmosphere is relaxed and progressive by Indian standards.",
        "nature": "Bangalore itself is increasingly urbanized, but nature escapes exist. Cubbon Park and Lalbagh Gardens provide green lungs. The surrounding countryside has lakes and hills. Nandi Hills is a popular day trip. Coorg (4 hours) and Wayanad offer hill station retreats. Karnataka has spectacular nature—Hampi, coastal beaches, Western Ghats—all accessible for weekends.",
        "safety": "Bangalore is generally safe for an Indian city. Petty theft can occur but violent crime targeting foreigners is rare. Traffic is the main danger—chaotic and relentless. Solo female travelers exercise caution, particularly at night, though Bangalore is considered relatively progressive. The tech professional population creates a somewhat cosmopolitan atmosphere. Standard urban awareness applies.",
        "food": "Bangalore offers incredible food diversity. South Indian breakfast—dosa, idli, vada—is legendary and cheap. The tech workforce has driven excellent international options. Craft beer pairs with global cuisines. Street food is abundant and flavorful (exercise caution initially). Bangalore has emerged as India's culinary innovation hub. From ₹50 meals to fine dining, options span all budgets and tastes.",
        "community": "Bangalore has a massive tech and startup community, arguably India's largest. Coworking spaces are everywhere. Meetups, conferences, and networking events are constant. The international community includes tech workers, entrepreneurs, and digital nomads. Connections happen easily in professional contexts. The community is young, ambitious, and globally connected. English-speaking environments are common.",
        "english": "English is widely spoken in Bangalore, particularly in tech and business. It's essentially a working language alongside Kannada and Hindi. Signs are often in English. You can live entirely in English, though Kannada knowledge enriches local interactions. The tech ecosystem functions primarily in English. India's English fluency makes Bangalore accessible to international professionals.",
        "visa": "India requires visas for most nationalities. E-visas (e-Tourist, e-Business) allow 30-90 days and are straightforward to obtain. Extensions require visiting FRRO offices. India doesn't have a specific digital nomad visa—most work on tourist visas in gray areas or with business visas. Long-term options include employment visas requiring sponsorship. The bureaucracy can be challenging.",
        "culture": "Bangalore blends traditional South Indian culture with tech modernity. Temples and churches coexist with brewpubs and startups. The city is more cosmopolitan and progressive than much of India. Kannada culture has distinct traditions in food, music, and festivals. The tech influx has created a hybrid identity—neither fully traditional nor Western. The pace is fast but retains Indian warmth.",
        "cleanliness": "Bangalore faces challenges common to rapidly growing Indian cities. Main roads and upscale areas are maintained. Traffic congestion and construction create dust and chaos. Waste management is improving but inconsistent. Tap water should be filtered. Air quality varies by area and season. The tech campuses maintain different standards than public streets. Expect variety rather than uniform cleanliness.",
        "airquality": "Air quality in Bangalore is moderate to poor, with AQI often 50-150. Traffic emissions are the primary source. The city's elevation and relatively good tree cover help somewhat. Winter months can be worse with atmospheric inversions. It's better than Delhi but not pristine. Sensitive individuals should monitor conditions. The situation is typical for major Indian cities."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

    # Load existing data
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Update cities with detailed descriptions
    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")

    # Save updated data
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
