#!/usr/bin/env python3
"""Rewrite batch 3: Detailed descriptions for cities A continued (aixenprovence-amsterdam)."""

import json
import os

BATCH_CITIES = {
    "aixenprovence": {
        "climate": "Aix-en-Provence enjoys a classic Mediterranean climate with hot, dry summers (25-32°C) and mild winters (5-12°C). The city averages 300 sunny days per year. The famous Mistral wind occasionally sweeps through, bringing clear skies and dropping temperatures dramatically. Spring and autumn are ideal, with comfortable temperatures and fewer tourists. Rain falls mainly in autumn, sometimes in dramatic storms. The reliable sunshine makes outdoor café culture a year-round pleasure.",
        "cost": "Aix is expensive by French standards, though cheaper than Paris. A comfortable nomad lifestyle costs €2,000-3,000/month. Apartments in the center range €800-1,400/month; outside is cheaper. Restaurant meals cost €15-25, and a coffee at a classic café is €3-4. The Saturday market offers excellent produce at reasonable prices. Wine from surrounding regions is affordable and exceptional. Student presence helps keep some costs down.",
        "wifi": "France has solid internet infrastructure, and Aix benefits from good connectivity. Average speeds are 50-100 Mbps, with fiber increasingly available. Cafes offer WiFi, though the French café culture prioritizes conversation over laptops. Coworking spaces like La Coque provide reliable connections. Mobile data through Orange, SFR, or Free offers good backup. Overall connectivity is reliable for remote work.",
        "nightlife": "Aix's nightlife centers on the Cours Mirabeau and surrounding old town streets. The scene is sophisticated rather than wild—wine bars, jazz clubs, and aperitif terraces predominate. The large student population ensures some late-night energy. Summer festivals extend evening activities with outdoor concerts and cinema. The atmosphere is quintessentially Provençal—relaxed, social, and centered on good food and wine.",
        "nature": "Provence's landscapes are legendary, and Aix is perfectly positioned to explore them. Mont Sainte-Victoire, Cézanne's favorite subject, offers hiking with stunning views. The Verdon Gorge, Europe's Grand Canyon, is a day trip away. Lavender fields bloom purple in summer. The Calanques near Marseille provide dramatic coastal hiking. The Luberon villages offer endless exploration. Nature here inspired generations of artists.",
        "safety": "Aix-en-Provence is very safe, one of France's most pleasant cities. Petty crime is minimal, and violent crime is rare. The city has a prosperous, bourgeois character that contributes to security. Standard precautions in crowded areas apply. Walking at night is comfortable throughout the center. Emergency services are reliable. The relaxed atmosphere extends to safety—locals leave café tables unattended.",
        "food": "Provençal cuisine is a highlight of life in Aix. Local specialties include bouillabaisse (fish stew), daube (beef stew), and the famous calissons (almond candies). The markets overflow with olives, cheese, charcuterie, and fresh produce. Rosé wine is practically a food group here. Restaurants range from traditional bistros to Michelin-starred establishments. The focus on quality ingredients and simple preparation defines the cuisine. Eating well is central to local life.",
        "community": "Aix hosts a diverse community including students, artists, expats, and retirees drawn by the quality of life. The American university presence brings English speakers. Digital nomads are discovering the city's appeal. The community is cultured and interested in arts and ideas. Networking happens through cultural events, language exchanges, and café conversations. The city's size makes genuine connections possible.",
        "english": "English is spoken in tourism and business contexts, but French dominates daily life. Many younger people and professionals speak English. However, Aix is proudly French—making an effort with the language is appreciated and often necessary. University courses exist in English. Services in English are available but limited. Learning French significantly enriches the experience and opens doors.",
        "visa": "France is part of the EU and Schengen Area. EU citizens can live and work freely. Non-EU visitors can stay 90 days within Schengen. France offers long-stay visas for various purposes, including the 'passeport talent' for qualified professionals and entrepreneurs. The French visa process can be bureaucratic but is manageable with patience. France doesn't have a specific digital nomad visa but accommodates remote workers through other categories.",
        "culture": "Aix-en-Provence is steeped in culture and history. Cézanne was born here and painted the surrounding landscapes. The city's elegant 17th and 18th-century architecture reflects its prosperous past. The Festival d'Aix, an opera festival, draws international audiences each summer. Museums, galleries, and cultural events abound. The intellectual café tradition continues. Provençal identity is distinct from Parisian France—more Mediterranean, more relaxed, fiercely local.",
        "cleanliness": "Aix is well-maintained with the orderly character typical of prosperous French cities. The pedestrianized old town is regularly cleaned, fountains flow, and public spaces are tended. The French appreciation for aesthetics extends to civic maintenance. Markets leave little trace after packing up. Tap water is safe and excellent. The overall impression is of a beautifully preserved historic city.",
        "airquality": "Air quality in Aix is generally good, with AQI typically 20-50. The Mistral wind regularly clears any accumulated pollution. Lack of heavy industry and the surrounding natural landscapes help. Summer can see elevated ozone levels during heat waves. The pedestrianized center keeps car emissions away from where people gather. Mediterranean air quality is generally favorable."
    },
    "alexandria": {
        "climate": "Alexandria has a Mediterranean climate, cooler than the rest of Egypt due to sea breezes. Summers are warm and humid (26-32°C), while winters are mild (10-18°C) with occasional rain—rare elsewhere in Egypt. Spring brings the khamaseen wind carrying Saharan dust. The climate is pleasant October through April, with summer humidity being the main discomfort. Sea breezes moderate coastal temperatures.",
        "cost": "Alexandria offers excellent value, cheaper than Cairo and far cheaper than Western cities. A comfortable lifestyle costs $600-1,000/month. Apartments range $200-500/month, with sea views available at the higher end. Local food is incredibly cheap—$2-4 for a full meal. Western-style restaurants charge $10-15. Transportation by tram or Uber is minimal. Egypt's economic situation means exchange rates favor foreign currency.",
        "wifi": "Egypt's internet infrastructure has improved, with Alexandria offering decent connectivity. Average speeds are 20-50 Mbps. WiFi is available in cafes and hotels but can be inconsistent. Power fluctuations occasionally affect connectivity. Mobile data through Vodafone or Orange provides reasonable backup. Coworking spaces are limited but emerging. VPN services are advisable for some content.",
        "nightlife": "Alexandria's nightlife is more subdued than Cairo's but has character. The historic cafes along the Corniche offer atmospheric evenings. Some upscale hotels have bars. The cultural center scene includes occasional concerts and events. The city has a literary tradition—Lawrence Durrell and Constantine Cavafy lived here. Alexandria is more about late dinners and corniche walks than clubs.",
        "nature": "Alexandria stretches along the Mediterranean coast, with beaches being the primary natural asset. While city beaches are crowded, better options exist to the west. The desert begins at the city's edge, with El Alamein and Siwa Oasis accessible for trips. Lake Mariout offers a different landscape. The Nile Delta's agricultural land lies south. Nature in Egypt tends toward dramatic emptiness—desert, sea, and sky.",
        "safety": "Alexandria is generally safe for visitors, with typical urban precautions applying. Petty theft is possible in crowded areas. Solo female travelers receive more attention than in Western countries. Political situations can change—monitor news. Egyptians are hospitable, and tourist-targeted crime is relatively rare. Traffic is the biggest daily danger—crossing streets requires courage. Tourist police provide a visible presence in key areas.",
        "food": "Alexandrian cuisine reflects its Mediterranean and Egyptian heritage. Fresh seafood is excellent and affordable—grilled fish, calamari, and shrimp are standards. Ful medames (fava beans) and koshari (lentils and pasta) are Egyptian staples. The city's Greek and Italian influences linger in some dishes. Street food is cheap and flavorful. Abu Ashraf and other seafood restaurants are legendary. Food is a highlight of daily life.",
        "community": "Alexandria's expat and nomad community is smaller than Cairo's but exists. The city attracts those interested in its literary and historical significance. Some international organizations and businesses have presence. Connections happen through cultural venues and the limited coworking scene. Egyptians are warm and curious about foreigners. The community is more intimate, requiring proactive networking.",
        "english": "English is spoken in tourism, business, and educated circles, but Arabic dominates daily life. Younger Egyptians often have reasonable English. In hotels and restaurants, English usually works. Markets and transportation may require Arabic or creative communication. French also has historical presence. Learning basic Arabic phrases significantly improves interactions. University areas have more English speakers.",
        "visa": "Egypt offers visa on arrival for most nationalities ($25 for single entry). E-visas are also available. Standard tourist visas allow 30 days, extendable with some bureaucracy. Egypt doesn't have a specific digital nomad visa. Longer stays require business or work visas, which involve sponsorship. The process can be unpredictable—working with local fixers helps. Egypt remains relatively accessible.",
        "culture": "Alexandria was once the intellectual center of the ancient world, home to the famous library. Greek, Roman, Egyptian, and Arab influences layer through its history. Cavafy's poetry and Durrell's Alexandria Quartet captured its romantic character. The city feels different from the rest of Egypt—more Mediterranean, with a faded cosmopolitan elegance. The Bibliotheca Alexandrina continues the scholarly tradition. History is everywhere, sometimes crumbling but evocative.",
        "cleanliness": "Alexandria's cleanliness varies significantly. The Corniche and tourist areas are maintained, but other parts of the city face challenges. Egypt's population density strains infrastructure. Tap water should be filtered or bottled. Air quality can be affected by traffic and dust. New developments maintain higher standards. The overall situation is typical of developing Mediterranean cities—character rather than pristine.",
        "airquality": "Air quality in Alexandria is moderate, typically AQI 50-100. Sea breezes help disperse pollution, making it better than Cairo. Traffic emissions and seasonal dust affect quality. The khamseen wind brings Saharan dust that can severely impact air quality for days. Coastal areas benefit from cleaner air. Sensitive individuals should monitor conditions, especially in spring."
    },
    "alicante": {
        "climate": "Alicante enjoys one of Spain's best climates with hot summers (28-33°C) and mild winters (10-18°C). The city averages over 300 sunny days per year. Rain is scarce, falling mainly in autumn—sometimes in dramatic storms. Sea breezes moderate summer heat. Winter is pleasant enough for outdoor activities most days. The reliable sunshine makes Alicante popular with northern European retirees and nomads seeking vitamin D.",
        "cost": "Alicante offers excellent value for a Spanish coastal city. A comfortable nomad lifestyle costs €1,400-2,200/month. Apartments range €500-900/month, with sea views commanding premiums. Restaurants serve lunch menus for €10-12, and tapas and beer come in under €10. The airport's budget airlines keep travel costs low. Overall, Alicante provides Mediterranean lifestyle at reasonable prices.",
        "wifi": "Spain has invested in internet infrastructure, and Alicante benefits from reliable connectivity. Average speeds are 50-100 Mbps with fiber widely available. Cafes offer WiFi, and beach bars increasingly cater to digital workers. Coworking spaces like Workaway provide stable connections. Mobile data through Vodafone, Orange, or Movistar offers good backup. Connectivity is rarely an issue.",
        "nightlife": "Alicante's nightlife centers on the El Barrio area and the port. The scene ranges from traditional tapas bars to beach clubs and late-night venues. Summer brings chiringuitos (beach bars) and outdoor events. The Spanish schedule means dinner at 10pm and clubs opening at midnight. The atmosphere is relaxed and local rather than tourist-focused. Year-round sunshine keeps terraces populated. Thursdays through Saturdays are busiest.",
        "nature": "Beyond the beaches, Alicante offers diverse nature. The Santa Bárbara castle provides hiking with panoramic views. The island of Tabarca is a marine reserve perfect for snorkeling. The Costa Blanca coastline extends with coves and beaches. Inland, the mountains and wine regions offer cooler escapes. El Palmeral park provides urban green space. Nature is accessible and varied within short distances.",
        "safety": "Alicante is very safe, with one of Spain's lowest crime rates. Petty theft can occur in tourist areas during peak season—standard precautions apply. Violent crime is rare. The city has a relaxed, family-friendly atmosphere. Walking at night is comfortable in most areas. Beach safety is good with lifeguards in summer. Spanish police are helpful though may not speak much English.",
        "food": "Valencian cuisine in Alicante centers on rice dishes and fresh seafood. Paella originated nearby, and local versions are exceptional. Arroz a banda (rice cooked in fish stock) is an Alicante specialty. Fresh fish, grilled or fried, is excellent and affordable. Tapas culture thrives in El Barrio. The Mercado Central offers fresh produce. Ice cream (helado) is a local obsession, with horchata (tiger nut drink) a traditional favorite.",
        "community": "Alicante has attracted a growing international community, including many British and Scandinavian expats. Digital nomads have discovered its appeal more recently. The nomad community is developing, with meetups and coworking spaces fostering connections. Spaniards are warm and social, though language can be a barrier initially. The mix of retirees, families, and remote workers creates diverse networking opportunities.",
        "english": "English is spoken in tourist areas but less common than in larger Spanish cities. Many younger Spaniards have some English. In restaurants and shops, English often works, but not always. Learning basic Spanish significantly improves daily life and earns local appreciation. The expat community provides English-speaking social outlets. Business conducted in Spanish is preferable when possible.",
        "visa": "Spain is part of the EU and Schengen Area. EU citizens can live and work freely. Non-EU visitors can stay 90 days within Schengen. Spain offers a digital nomad visa (Ley de Startups) requiring €2,200/month income and Spanish health insurance. Non-lucrative visas are available for those with passive income. The bureaucracy can be slow but processes are established.",
        "culture": "Alicante blends Valencian heritage with coastal character. The Hogueras de San Juan festival in June features giant sculptures burned in spectacular bonfires. The old town and castle reflect centuries of history. Local traditions include the Moors and Christians parades. Valencian is spoken alongside Spanish by older residents. The lifestyle emphasizes family, food, and enjoying the weather. It's authentically Spanish rather than tourist-constructed.",
        "cleanliness": "Alicante maintains good standards for a Spanish city. Beaches are cleaned daily in season and have Blue Flag certification. The old town and port area are well-maintained. Streets are swept regularly. Recycling is expected. Tap water is safe, though locals often drink bottled. The city takes pride in its appearance, particularly in tourist-facing areas.",
        "airquality": "Air quality in Alicante is generally good, with AQI typically 25-50. Sea breezes disperse pollution, and heavy industry is minimal. Summer can see slightly elevated ozone during heat waves. The coastal position ensures fresh air most days. Saharan dust occasionally reaches the region, temporarily reducing quality. Overall, the air supports the outdoor lifestyle that draws people here."
    },
    "amman": {
        "climate": "Amman has a semi-arid climate with hot, dry summers (26-34°C) and cool, wet winters (4-12°C). The city's elevation (700-1,000m) moderates temperatures. Summer nights are pleasant. Winter brings rain and occasionally snow. Spring (March-May) and autumn (September-November) are ideal, with comfortable temperatures for exploration. Dust storms occasionally affect the city. The dry heat is more bearable than humid climates.",
        "cost": "Amman is moderately priced for the Middle East. A comfortable nomad lifestyle costs $1,200-1,800/month. Apartments range $400-800/month, with Western standards at the higher end. Restaurant meals cost $8-15, with street food much cheaper. Transportation is affordable via ride-hailing apps. Jordan's economy and currency have been stable. Costs have risen but remain reasonable for the region.",
        "wifi": "Jordan has developed reasonable internet infrastructure. Average speeds in Amman are 30-60 Mbps. WiFi is available in cafes and hotels. Mobile data through Zain, Orange, or Umniah provides reliable connectivity with decent 4G coverage. Coworking spaces like ZINC offer stable connections. VoIP services work without restriction. Overall connectivity supports remote work adequately.",
        "nightlife": "Amman's nightlife is more developed than many Middle Eastern cities. Rainbow Street in Jabal Amman hosts bars and lounges. The Abdoun area has upscale clubs and restaurants. Alcohol is available in licensed venues. The scene is sophisticated and social rather than party-focused. Thursday and Friday nights are busiest (the weekend). Western-style entertainment exists alongside traditional shisha cafes.",
        "nature": "Jordan packs remarkable natural diversity into a small country. From Amman, Petra is 3 hours south—a world wonder. Wadi Rum's desert landscapes are otherworldly. The Dead Sea, the lowest point on earth, offers unique floating experiences. The Dana Biosphere Reserve provides hiking and wildlife. Aqaba offers Red Sea diving. Nature excursions are highlights of time in Jordan.",
        "safety": "Jordan is one of the safest countries in the Middle East. The government prioritizes stability, and tourist protection is taken seriously. Violent crime is very rare. Petty theft is uncommon. Women may receive attention but harassment is generally manageable. The political situation requires monitoring, but Amman remains stable. Jordanians are hospitable and helpful to visitors. Traffic is the main daily hazard.",
        "food": "Jordanian cuisine shares much with Levantine traditions. Mansaf (lamb with rice and yogurt) is the national dish. Falafel, hummus, and shawarma are daily staples. Mezza (small plates) make for excellent social dining. Arabic coffee and sweet tea punctuate the day. Fresh juices are ubiquitous. Restaurants range from street stalls to upscale dining. The food is flavorful, generous, and affordable.",
        "community": "Amman hosts a significant international community including NGO workers, diplomats, and refugees from neighboring conflicts. The nomad community is small but growing. Coworking spaces and cafes facilitate connections. Jordanians are warm and welcoming, with strong hospitality traditions. Expat events, language exchanges, and cultural activities provide networking opportunities. The community is diverse and internationally minded.",
        "english": "English is widely spoken in Amman, particularly in business, tourism, and among younger Jordanians. Most signage is bilingual. You can manage daily life in English. However, Arabic enriches the experience—learning basics is appreciated. French also has some presence. Outside Amman and tourist areas, Arabic becomes more necessary. Jordanian hospitality means people help bridge language gaps.",
        "visa": "Jordan offers visa on arrival for most nationalities (40 JOD). The Jordan Pass (includes Petra entry and visa) provides value for tourists. Standard visas allow 30 days, extendable at police stations. Jordan doesn't have a specific digital nomad visa. Business and work visas require sponsorship. The process is relatively straightforward. Jordan positions itself as accessible and welcoming to visitors.",
        "culture": "Amman blends ancient history with modern Arab society. Roman ruins (the Citadel, amphitheater) dot the landscape. Islamic and Christian communities coexist peacefully. Hospitality is central to Jordanian culture—offers of tea and coffee are genuine and frequent. The royal family is generally respected. Palestinian and Iraqi refugees have shaped the city's character. Modernity and tradition coexist, with visible changes across generations.",
        "cleanliness": "Amman's cleanliness is moderate, improving in recent years. Upscale neighborhoods like Abdoun and Jabal Amman maintain high standards. Other areas vary. Waste management has improved but challenges remain. Tap water is treated but most people drink bottled. New developments and hotels are well-maintained. The city makes visible efforts toward cleanliness in tourist and business areas.",
        "airquality": "Air quality in Amman is moderate to fair, with AQI typically 50-100. Traffic emissions and dust affect quality. Winter heating adds to pollution. The hilltop location provides some natural ventilation. Spring dust storms can temporarily worsen conditions significantly. Higher neighborhoods generally have better air. The situation is manageable but noticeable, particularly for sensitive individuals."
    },
    "amsterdam": {
        "climate": "Amsterdam has a temperate oceanic climate with mild summers (17-22°C) and cool winters (2-6°C). Rain is frequent year-round—approximately 200 days see some precipitation. Gray skies are common, especially in winter, when daylight is limited (8:30am-4:30pm). Summer brings long days with light until 10pm. Wind is constant. The climate rewards those who embrace outdoor café culture between showers and invest in good rain gear.",
        "cost": "Amsterdam has become one of Europe's most expensive cities. A comfortable nomad lifestyle costs €2,800-4,000/month. Apartments are extremely difficult to find, ranging €1,500-2,500/month when available. Housing crisis means competition is fierce. Restaurant meals cost €20-35, and beers are €5-7. Cycling saves transportation costs. The cost reflects limited supply, not excessive luxury—expect modest living for high prices.",
        "wifi": "Dutch internet infrastructure is excellent, among Europe's best. Average speeds exceed 100 Mbps with gigabit connections common. Public WiFi is widespread and reliable. Cafes welcome laptops, though some limit WiFi during peak hours. Coworking spaces abound. Mobile data is excellent with competitive providers. The Netherlands' tech-forward approach ensures connectivity is never a concern.",
        "nightlife": "Amsterdam's nightlife is legendary and diverse. The Red Light District is just one facet—world-class electronic music venues, cozy brown cafes, jazz clubs, and cocktail bars offer endless options. Coffee shops provide a unique legal cannabis experience. The club scene runs until 6am or later. Leidseplein and Rembrandtplein are nightlife hubs. The Dutch approach is liberal—most things are permitted and done openly.",
        "nature": "Amsterdam is flat, watery, and surprisingly green. Vondelpark is the urban oasis. Beyond the city, the countryside is immediately accessible—windmills at Zaanse Schans, beaches at Zandvoort, tulip fields at Keukenhof (in spring). The network of canals defines the city's character. Cycling along waterways is the quintessential Amsterdam experience. The Netherlands' compactness means diverse landscapes are always close.",
        "safety": "Amsterdam is generally safe, with low violent crime rates. However, petty theft and pickpocketing are common, particularly around Central Station and tourist areas. Bike theft is endemic—always use two locks. Scams targeting tourists exist in nightlife areas. Cannabis is legal but be aware of surroundings. Cycling requires attention to rules and traffic. Overall, standard urban awareness keeps you safe.",
        "food": "Dutch cuisine is hearty rather than refined—stamppot, herring, and bitterballen reflect the practical culture. However, Amsterdam's international population has created an excellent global food scene. Indonesian cuisine (rijsttafel) is a colonial legacy worth exploring. Surinamese food offers spicy alternatives. The Albert Cuyp market and Foodhallen showcase the variety. Cheese is obviously excellent. Coffee culture rivals any European city.",
        "community": "Amsterdam hosts one of Europe's largest digital nomad and expat communities. Coworking spaces, meetups, and networking events are abundant. The international community is established and welcoming. Dutch directness can surprise, but once connected, relationships are genuine. Tech startups, creative agencies, and freelancers create a dynamic professional ecosystem. English is so common that integration into Dutch society can actually be challenging.",
        "english": "English fluency in Amsterdam is exceptional—possibly the highest among non-native countries. Business, socializing, and daily life can function entirely in English. Menus, signage, and services are commonly bilingual. This can make learning Dutch difficult—people switch to English automatically. While convenient, some feel this creates a bubble separate from Dutch culture.",
        "visa": "Netherlands is part of the EU and Schengen. EU citizens have full freedom of movement. Non-EU visitors can stay 90 days within Schengen. The Netherlands offers a self-employed residence permit for freelancers and entrepreneurs (requiring a business plan and income proof). Registration with the municipality is required for stays over 4 months. The bureaucracy is organized but thorough.",
        "culture": "Dutch culture values directness, equality, and pragmatism. The concept of 'gezelligheid' (cozy conviviality) defines social life. Cycling isn't just transportation—it's identity. Tolerance has historical roots, though politics have grown more complex. Art heritage from Rembrandt to Van Gogh fills world-class museums. Architecture spans from canal houses to bold modern design. The culture balances tradition with progressive values.",
        "cleanliness": "Amsterdam is well-maintained by European standards. Canal districts are regularly cleaned, parks are tidy, and public transport is spotless. Tourist areas receive extra attention. Graffiti and street mess exist but are managed. Dog waste is a local complaint. Tap water is excellent—among Europe's best. The Dutch commitment to orderly public spaces is evident.",
        "airquality": "Air quality in Amsterdam is moderate, with AQI typically 30-50. Vehicle emissions (especially scooters) and proximity to industrial areas affect quality. Coastal winds help disperse pollution. The flat, open landscape allows air movement. Climate change efforts are reducing emissions over time. Most days the air is acceptable, though sensitive individuals may notice differences from cleaner cities."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

    # Load existing data
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Update cities with detailed descriptions
    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")

    # Save updated data
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
