#!/usr/bin/env python3
"""Rewrite batch 15: Playa del Carmen, Oaxaca, Lima, Bogota, Cusco."""

import json
import os

BATCH_CITIES = {
    "playadelcarmen": {
        "climate": "Playa del Carmen has a tropical wet and dry climate with warm weather year-round. Temperatures range from 24-32°C (75-90°F) with higher humidity from May to October during the rainy season. Dry season (November-April) brings comfortable conditions with less humidity. Hurricane season runs June-November, though direct hits are rare. Sea breezes moderate the heat along the coast. Swimming is pleasant year-round.",
        "cost": "Playa del Carmen offers moderate costs that have risen with its popularity. Monthly expenses range from $1,500-2,800 USD for a comfortable lifestyle. Rent for a central one-bedroom apartment averages $800-1,400, with cheaper options away from 5th Avenue. Street food costs $3-5, while restaurant meals run $10-25. Beach clubs charge admission. Coworking spaces cost $150-300 monthly. Tourist area prices exceed local area costs significantly.",
        "wifi": "Internet in Playa del Carmen has improved significantly, though it can be inconsistent. Most cafes and coworking spaces offer 20-50 Mbps connections. Dedicated nomad-focused coworking spaces like Nest and Bunker provide more reliable speeds. Many apartments now have fiber connections. Having a backup mobile hotspot with Telcel is recommended for important calls. Some beachfront areas have spotty coverage.",
        "nightlife": "Playa del Carmen's nightlife is vibrant and diverse, centered on 5th Avenue (Quinta Avenida). Beach clubs like Mamita's transition from day parties to evening events. The downtown area has bars ranging from casual to upscale. Coco Bongo offers famous theatrical nightclub experiences. The 12th Street area has more local and alternative venues. Nights can extend until dawn, especially on weekends. The scene attracts an international crowd.",
        "nature": "Playa del Carmen serves as a gateway to the Riviera Maya's natural wonders. Pristine cenotes dot the jungle, offering swimming in crystal-clear freshwater sinkholes. The world's second-largest barrier reef lies offshore with exceptional snorkeling and diving. Day trips to biosphere reserves like Sian Ka'an reveal protected wilderness. Akumal offers sea turtle encounters. Mayan ruins at Tulum and Coba combine history with natural beauty.",
        "safety": "Playa del Carmen is generally safe for tourists, though awareness is important. Petty theft and scams occur in tourist areas. Keep valuables secure on beaches and in crowds. Some reports of drink spiking exist—watch your beverages. Avoid deserted areas late at night. Stick to well-lit streets and reputable transportation. The tourist police are visible along 5th Avenue. Most visitors experience no problems with basic precautions.",
        "food": "Playa del Carmen's food scene blends Mexican traditions with international influences. Taquerias serve excellent tacos al pastor and cochinita pibil. Seafood restaurants feature fresh ceviche and grilled fish. The tourist areas have everything from Italian to Thai. Markets like Mercado 30 offer authentic local eating. Fine dining options have multiplied for special occasions. Street food remains the best value. Beware inflated tourist menu prices.",
        "community": "Playa del Carmen has a large digital nomad and expat community drawn by the beach lifestyle. Coworking spaces serve as community hubs with networking events. Facebook groups connect thousands of remote workers. The scene includes entrepreneurs, online teachers, and remote employees. Many nomads cycle between Playa and other Mexico destinations. The transient nature means constantly meeting new people. Some find it superficial, others thrive.",
        "english": "English is widely spoken in Playa del Carmen's tourist zones. Most restaurants, hotels, and shops along 5th Avenue operate in English. Moving into local neighborhoods requires more Spanish. Service workers typically have functional English. Learning Spanish significantly enriches your experience and opens doors to authentic local culture. Many nomads manage with minimal Spanish, though it's not ideal.",
        "visa": "Mexico offers generous visa-free entry to citizens of many countries, with tourism permits valid for up to 180 days. This is automatically granted upon arrival—ask for the full duration. Extensions are possible but involve bureaucratic processes. There's no specific digital nomad visa, so most remote workers enter as tourists. Technically, working requires a permit, but enforcement for remote workers is minimal.",
        "culture": "Playa del Carmen has transformed from a fishing village to an international resort town. Mayan heritage persists in nearby ruins and cultural centers. The contemporary culture is shaped by tourism and the expat community, creating a somewhat artificial international bubble. Mexican traditions remain in food, music, and festivals, particularly in local neighborhoods away from 5th Avenue. Day of the Dead celebrations are observed.",
        "cleanliness": "Playa del Carmen's tourist areas are generally well-maintained, with 5th Avenue cleaned regularly. Beaches are groomed, though sargassum seaweed can affect conditions seasonally (typically May-September). Local neighborhoods vary in cleanliness. Tap water is not drinkable. Waste management is a challenge with rapid development. Some newer areas have better infrastructure. Check beach conditions before heading to the water.",
        "airquality": "Playa del Carmen has generally good air quality, benefiting from coastal breezes and limited industry. The main pollutant is dust from construction and unpaved roads. Humidity can feel heavy but doesn't indicate poor air quality. Mosquitoes can be a significant nuisance, especially after rain. No major air quality concerns exist for most visitors. The sea air feels fresh along the beach."
    },
    "oaxaca": {
        "climate": "Oaxaca City has a semi-arid subtropical climate with warm days and cool nights due to its altitude (1,550m). Temperatures range from 18-28°C (64-82°F) year-round, with the warmest months from April to June before rainy season. The rainy season (June-September) brings afternoon showers that clear quickly. Dry season offers ideal conditions. The comfortable climate is a major draw for extended stays.",
        "cost": "Oaxaca offers exceptional value for digital nomads. Monthly costs range from $1,000-1,800 USD for a comfortable lifestyle. Rent for a central one-bedroom apartment averages $400-700, with beautiful colonial options available. Street food meals cost $2-4, while restaurant dining runs $8-15. Mezcal is remarkably affordable at local spots. Coworking spaces cost $80-180 monthly. The strong dollar makes costs even more favorable.",
        "wifi": "Internet infrastructure in Oaxaca has improved significantly, though it remains less reliable than larger Mexican cities. Most cafes offer 10-40 Mbps connections. Dedicated coworking spaces like Hive and Casa Oaxaca Coworking provide more consistent speeds. Many apartments now have fiber connections. Having a Telcel SIM card as backup is recommended. Some historic buildings have challenging connectivity due to thick walls.",
        "nightlife": "Oaxaca's nightlife centers around mezcal culture and live music. Mezcalerías serve artisanal spirits in atmospheric settings. The Zócalo and surrounding streets come alive with bars and restaurants. Live music venues feature traditional Oaxacan son and contemporary bands. The scene is more cultural than clubbing-oriented. Friday nights are particularly vibrant. Festivals and fiestas bring street parties throughout the year.",
        "nature": "Oaxaca state boasts extraordinary natural diversity. Hierve el Agua features petrified waterfalls and natural infinity pools with valley views. The Sierra Norte offers cloud forests with community-based ecotourism and hiking. The coast at Puerto Escondido is a few hours away for beach breaks. Monte Albán archaeological site sits amid dramatic mountain scenery. Valley villages dot the surrounding landscapes with crafts and local culture.",
        "safety": "Oaxaca City is one of Mexico's safest destinations, with low crime rates and a peaceful atmosphere. The historic center is walkable at all hours. Protests related to teachers' unions and social movements occasionally occur but are typically peaceful. The surrounding state has more complex security in certain areas—check conditions for specific destinations. Tourist police patrol the center. Most visitors feel very secure.",
        "food": "Oaxaca is Mexico's culinary capital, with a food scene that alone justifies visiting. The seven moles (complex sauces) are legendary—don't miss negro and coloradito. Tlayudas (large crispy tortillas with toppings) are the local street food staple. Mercado 20 de Noviembre features smoky grilled meats and fresh ingredients. Chapulines (grasshoppers) are a crunchy delicacy. Chocolate and coffee traditions run deep. The food scene attracts culinary pilgrims worldwide.",
        "community": "Oaxaca has a growing digital nomad community, smaller but passionate. The city attracts creative types, food enthusiasts, and those seeking cultural immersion over beach parties. Coworking spaces host small but engaged communities. Language exchange meetups connect locals and foreigners. The art and textile scene draws designers and craftspeople. Integration with local culture is more accessible here than in resort towns.",
        "english": "English proficiency in Oaxaca is moderate, with more Spanish needed than in tourist-heavy destinations. Tourist areas and upscale restaurants handle English. Local markets, neighborhoods, and everyday services typically require Spanish. Learning Spanish significantly enriches your Oaxaca experience and is practically necessary for daily life. Many nomads take Spanish classes while staying. Translation apps help bridge gaps.",
        "visa": "Mexico offers generous visa-free entry to citizens of many countries, with tourism permits valid for up to 180 days. This is automatically granted upon arrival. Extensions are possible but involve bureaucratic processes. There's no specific digital nomad visa, so most remote workers enter as tourists. Technically, working requires a permit, but enforcement for remote workers is minimal. Oaxaca is popular for extended Mexican stays.",
        "culture": "Oaxaca is one of Mexico's most culturally rich destinations, where indigenous traditions thrive alongside colonial heritage. Zapotec and Mixtec cultures remain vibrant in surrounding villages. The art scene is exceptional, with textiles, black pottery, alebrijes (carved figures), and contemporary galleries. Día de los Muertos celebrations are among Mexico's most elaborate. Mezcal production is treated as sacred tradition. Festivals fill the calendar year-round.",
        "cleanliness": "Oaxaca's historic center is well-maintained, with cobblestone streets cleaned regularly. The Zócalo and surrounding areas are kept tidy. Markets are busy but reasonably clean. Some peripheral neighborhoods have rougher conditions. Tap water is not drinkable. Air quality is generally good due to altitude and limited traffic. Public restrooms are available in markets and restaurants. The city takes pride in its colonial beauty.",
        "airquality": "Oaxaca has generally good air quality, benefiting from its valley location and altitude. Traffic is relatively light compared to major Mexican cities. The dry season can bring some dust. Occasional agricultural burning in surrounding areas may affect conditions. The air feels fresh and clean most days. No major pollution concerns exist. The high altitude means stronger sun—bring sun protection."
    },
    "lima": {
        "climate": "Lima has an unusual desert climate moderated by the cold Humboldt Current, creating persistent overcast conditions from May to November (garúa season). Temperatures range from 15-20°C (59-68°F) in winter and 22-28°C (72-82°F) in summer (December-April). Rain is extremely rare despite the gray skies. Humidity is high year-round. Summer brings sunshine and beach weather. The climate takes adjustment but is never extreme.",
        "cost": "Lima offers good value for South America, especially outside upscale districts. Monthly costs range from $1,200-2,200 USD for a comfortable lifestyle. Rent for a central one-bedroom apartment in Miraflores averages $600-1,000, cheaper in other districts. Menú del día lunches cost $3-5. Restaurant dining in trendy areas runs $15-30. Coworking spaces cost $100-250 monthly. Transportation is very affordable.",
        "wifi": "Peru's internet infrastructure has improved significantly, and Lima offers generally reliable connectivity. Most cafes and coworking spaces provide 20-50 Mbps connections. Miraflores and San Isidro have the best infrastructure. Coworking spaces like WeWork and Comunal cater to remote workers. Residential connections can be inconsistent in older buildings. Mobile data through Movistar or Claro provides good backup. Some areas have fiber optic.",
        "nightlife": "Lima's nightlife has something for everyone, centered around Miraflores and Barranco neighborhoods. Barranco is the bohemian heart, with bars, live music venues, and clubs spread along its charming streets. Miraflores offers upscale lounges and international bars. Larcomar mall has ocean-view venues. Peña clubs feature live música criolla (traditional Peruvian music). The party scene runs late, with clubs filling after midnight.",
        "nature": "Lima is a desert city, but nature is accessible. The coastline offers dramatic clifftop views and surfing beaches. Miraflores' Parque del Amor provides Pacific Ocean panoramas. Day trips to Pachacamac ruins combine archaeology with desert landscapes. The nearby Paracas National Reserve features dramatic coastal scenery and wildlife. Mountain escapes into the Andes are 3-4 hours away. Lima's parks provide green respite.",
        "safety": "Lima requires more awareness than some South American capitals but is manageable with precautions. Miraflores and San Isidro are safe neighborhoods where you can walk freely. Petty theft and pickpocketing occur in crowded areas and on public transit. Avoid displaying expensive items. Certain districts like Callao should be avoided unless with knowledgeable guides. Use registered taxis or ride apps. Most tourists experience no problems.",
        "food": "Lima is South America's culinary capital, with world-renowned ceviche and a sophisticated food scene. Celebrity chefs like Gastón Acurio have elevated Peruvian cuisine globally. Don't miss cevicherías for fresh fish in tiger's milk (citrus marinade). Anticuchos (grilled beef heart) are beloved street food. Chinese-Peruvian fusion (chifa) is ubiquitous. The upscale Central restaurant consistently ranks among the world's best. Markets offer authentic eating experiences.",
        "community": "Lima has a growing digital nomad community, though smaller than some other Latin American hubs. Coworking spaces in Miraflores host networking events. The expat scene includes business professionals, NGO workers, and remote employees. Facebook groups and Meetups connect remote workers. The Peruvian startup ecosystem attracts entrepreneurs. Integration with locals takes effort but is rewarding. Spanish proficiency helps significantly.",
        "english": "English proficiency in Lima varies significantly. Miraflores and tourist areas have better English speakers. Business settings and upscale venues handle English well. Local neighborhoods, markets, and everyday services typically require Spanish. Younger Peruvians may speak some English. Spanish is essential for navigating the city fully and connecting with local culture. Many nomads take classes while staying.",
        "visa": "Peru offers visa-free entry for citizens of many countries, allowing stays of up to 90 days (sometimes 183 days at immigration's discretion). Extensions are possible through immigration offices. There's no specific digital nomad visa. Remote workers typically enter as tourists. Work visas require employer sponsorship. The tourist status is generally adequate for nomad stays. Visa runs to nearby countries are possible for longer stays.",
        "culture": "Lima blends pre-Columbian heritage with Spanish colonial history and modern cosmopolitanism. Historic center showcases baroque architecture and churches. Museums display Incan and pre-Incan artifacts. The coastal districts feel distinctly modern and international. Peruvian pride in cuisine and culture runs deep. Catholicism remains influential with religious festivals throughout the year. The city's inequality is visible between wealthy and poorer districts.",
        "cleanliness": "Lima's cleanliness varies dramatically by district. Miraflores and San Isidro are well-maintained with clean streets and parks. The historic center has improved but remains grittier. Industrial areas and poorer neighborhoods have more challenges. The persistent garúa (mist) can leave surfaces damp. Tap water is not safe to drink. Air quality is a concern due to traffic. The city is working on environmental improvements.",
        "airquality": "Lima has poor air quality, ranking among the more polluted cities in the Americas. Vehicle emissions and industrial activity contribute to smog, particularly in dry months. The geographic bowl effect traps pollution. Coastal areas like Miraflores have better air due to sea breezes. Air quality alerts are common. Sensitive individuals should monitor conditions. The greyness of winter can compound the heaviness."
    },
    "bogota": {
        "climate": "Bogotá has a subtropical highland climate due to its elevation (2,640m), creating cool, spring-like conditions year-round. Temperatures range from 8-19°C (46-66°F) daily, with little seasonal variation. Rain falls primarily April-May and October-November, typically in afternoon showers. Mornings are often clear and sunny. The altitude can cause initial adjustment for some visitors. Pack layers for temperature swings.",
        "cost": "Bogotá offers excellent value for a major capital. Monthly costs range from $1,200-2,200 USD for a comfortable lifestyle. Rent for a central one-bedroom apartment in Chapinero or La Candelaria averages $500-900. Set lunch menus (almuerzo corriente) cost $3-5. Restaurant dining runs $10-25. Transportation is very affordable. Coworking spaces cost $100-250 monthly. The strong dollar makes Colombia particularly favorable.",
        "wifi": "Colombia has invested heavily in internet infrastructure, and Bogotá offers good connectivity. Most cafes and coworking spaces provide 30-100 Mbps connections. The city has numerous coworking options, from international chains to local spaces like Tinkko and Selina. Residential areas have generally reliable internet with fiber available in newer buildings. Mobile data through Claro or Movistar provides solid backup.",
        "nightlife": "Bogotá's nightlife is legendary, with different vibes across neighborhoods. Zona T in Chapinero attracts upscale crowds with clubs and lounges. Chapinero Alto has become the LGBT+ and hipster hub with alternative venues. La Candelaria offers bohemian bars and live music. Salsa clubs (salsotecas) teach moves to beginners. Rumba (partying) typically starts very late and extends until dawn. Fridays and Saturdays are busiest.",
        "nature": "Bogotá sits at the edge of the Andes, offering exceptional nature access. Monserrate mountain provides panoramic city views via cable car or hiking trail. Cerros Orientales (Eastern Hills) feature walking and cycling paths. Day trips to Villa de Leyva showcase colonial architecture and desert landscapes. Chingaza National Park offers páramo ecosystems and hiking. The coffee region is a few hours away for rural escapes.",
        "safety": "Bogotá has improved dramatically in safety but requires street awareness. Tourist areas like La Candelaria and Zona T are generally safe but petty theft occurs. Keep valuables secure and avoid displaying expensive items. Some neighborhoods should be avoided, particularly at night. Use registered taxis or ride apps like Uber and DiDi. The expat community can provide current safety advice. Most visitors have positive experiences with basic precautions.",
        "food": "Colombian cuisine shines in Bogotá's diverse food scene. Traditional dishes include ajiaco (chicken soup), bandeja paisa (massive mixed plate), and arepas. The contemporary dining scene has exploded with innovative restaurants. Zona G is the gourmet neighborhood. Usaquén's flea market has great food stalls. Fresh tropical fruits are exceptional and cheap. Coffee culture is strong with specialty cafes throughout. Markets offer authentic local eating.",
        "community": "Bogotá has a thriving digital nomad and expat community that has grown significantly. Coworking spaces host regular networking events and workshops. The tech and startup ecosystem attracts entrepreneurs from across Latin America. Language exchange meetups are popular. The international community is welcoming and active across social media groups. Chapinero and Usaquén have particularly established nomad scenes.",
        "english": "English proficiency in Bogotá is moderate, better among younger people and in business settings. Tourist areas and upscale venues have more English speakers. Local neighborhoods and everyday services typically require Spanish. The digital nomad scene operates with more English. Learning Spanish is highly recommended and opens doors to Colombian culture and friendships. Many nomads take intensive classes while staying.",
        "visa": "Colombia offers visa-free entry for citizens of many countries, allowing stays of up to 90 days. Extensions are available through Migración Colombia for another 90 days. The digital nomad visa allows stays up to 2 years for remote workers, requiring proof of income and health insurance. Work visas require employer sponsorship. Colombia has become increasingly welcoming to remote workers with streamlined processes.",
        "culture": "Bogotá is Colombia's cultural heart, where colonial history meets urban innovation. La Candelaria's colonial architecture houses museums and street art. The gold museum displays pre-Columbian treasures. Contemporary art galleries and theaters flourish. Music scene spans vallenato tradition to electronic and hip-hop innovation. Colombian warmth and hospitality are legendary. The graffiti scene is world-class. Cultural events fill the calendar.",
        "cleanliness": "Bogotá's cleanliness varies by neighborhood. Wealthy northern districts are well-maintained. The historic La Candelaria has improved but shows urban grit. Some areas have litter and graffiti. Public parks are generally tidy. The TransMilenio bus system is clean and efficient. Tap water is safe to drink in Bogotá (unusual for South America). The city has made environmental improvements in recent years.",
        "airquality": "Bogotá has moderate to poor air quality, primarily due to vehicle emissions and traffic congestion. The high altitude and valley location can trap pollution. Air quality alerts occur during dry seasons. The car-free ciclovía on Sundays helps reduce emissions. Northern neighborhoods tend to have better air than industrial south. Sensitive individuals should monitor conditions. The city is working on green transportation initiatives."
    },
    "cusco": {
        "climate": "Cusco has a subtropical highland climate with two distinct seasons: dry (May-October) and wet (November-April). Temperatures range from 0-20°C (32-68°F) daily year-round, with significant day-night variation. Dry season brings clear, sunny days and cold nights. Wet season features afternoon thunderstorms but morning sunshine. The 3,400m altitude requires acclimatization. Layering is essential regardless of season.",
        "cost": "Cusco offers excellent value, though tourist areas charge premium prices. Monthly costs range from $800-1,500 USD for a comfortable lifestyle. Rent for a central one-bedroom apartment averages $300-600. Set lunch menus cost $2-4. Tourist restaurant meals run $10-20. Entrance fees to archaeological sites add up—consider the Boleto Turístico. Coworking spaces cost $60-150 monthly. Local neighborhood prices are much lower than tourist areas.",
        "wifi": "Internet in Cusco has improved but remains slower than Lima. Most cafes and accommodations offer 10-30 Mbps connections. The Plaza de Armas area has the best connectivity. Dedicated coworking spaces like Selina and Outsite provide more reliable speeds. Power outages occasionally affect connectivity. Having a mobile data backup is advisable. Newer hotels and apartments tend to have better internet. The altitude and terrain affect infrastructure.",
        "nightlife": "Cusco's nightlife caters to tourists and backpackers with a lively scene around the Plaza de Armas. Bars range from traditional peña venues with live Andean music to international party spots. Upstairs bars overlooking the plaza are popular for drinks with a view. Clubs play everything from reggaeton to electronic music. The party scene is friendly and international. Altitude affects alcohol tolerance, so pace yourself.",
        "nature": "Cusco is the gateway to some of Earth's most spectacular landscapes. Machu Picchu is the headline, reached by train or multi-day trek. The Sacred Valley features Inca ruins, markets, and adventure sports. Rainbow Mountain (Vinicunca) displays surreal striped peaks. The Andes offer endless hiking opportunities. The Amazon basin is accessible for jungle expeditions. Archaeological sites dot the surrounding hills. Nature here is world-class.",
        "safety": "Cusco is generally safe, with tourist areas well-patrolled. Petty theft and pickpocketing occur in crowded markets and during festivals. Keep valuables secure. Scams targeting tourists exist—be wary of unofficial tour operators. Altitude sickness is the biggest health concern for new arrivals. Some streets are poorly lit at night. Avoid walking alone in deserted areas. Most visitors experience Cusco safely with normal precautions.",
        "food": "Cusco's food scene blends traditional Andean cuisine with international options. Don't miss cuy (guinea pig) for adventurous eating. Alpaca meat is more approachable and delicious. Lomo saltado and rocoto relleno showcase Peruvian favorites. Markets like San Pedro offer fresh juices and local dishes. Fine dining has arrived with chefs showcasing Andean ingredients innovatively. Coca tea helps with altitude. Tourist restaurants often disappoint—seek local spots.",
        "community": "Cusco has a small but dedicated digital nomad community alongside a larger backpacker and tourist scene. Some nomads base here for the culture and nature despite infrastructure challenges. Coworking spaces create small communities. Long-term expats often work in tourism or NGOs. The constant tourist flow creates a transient atmosphere. Spanish language students form their own community. Sacred Valley villages offer quieter alternatives.",
        "english": "English proficiency in Cusco's tourist areas is good—tour guides and restaurants cater to international visitors. Local neighborhoods and markets require Spanish. Many locals speak some English due to tourism dependence. The tourism industry operates heavily in English. Spanish significantly enriches your experience and is needed for authentic cultural engagement. Language schools offer intensive courses popular with visitors.",
        "visa": "Peru offers visa-free entry for citizens of many countries, allowing stays of up to 90 days (sometimes 183 days at immigration's discretion). Extensions are possible through immigration offices. There's no specific digital nomad visa. Remote workers typically enter as tourists. The tourist status is adequate for most nomad stays. Some divide time between Cusco and other Peruvian destinations.",
        "culture": "Cusco was the Inca Empire's capital, and this heritage pervades daily life. Quechua language and traditions persist among indigenous communities. Colonial architecture sits atop Inca foundations throughout the city. Religious festivals blend Catholic and Andean practices—Inti Raymi (June) is spectacular. Textile arts continue ancient patterns and techniques. The city balances preservation with tourism pressures. Spiritual tourism draws seekers for plant ceremonies.",
        "cleanliness": "Cusco's historic center is well-maintained, with cobblestone streets swept regularly. Markets are bustling but reasonably clean. Some side streets and outer areas show more wear. Tap water is not safe to drink—stick to bottled or filtered. Public restrooms are available in restaurants and tourist sites (sometimes with fees). The altitude keeps bacterial growth lower than tropical destinations. The city takes pride in its heritage preservation.",
        "airquality": "Cusco has moderate air quality, affected by vehicle emissions in narrow colonial streets. The altitude and valley location can trap pollution. Burning of waste in surrounding areas occasionally impacts air quality. Generally, the mountain air feels cleaner than lowland cities. Most visitors don't notice issues. The thin air at altitude may challenge those with respiratory conditions. Dry season tends to have dustier conditions."
    }
}

def main():
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'category-descriptions.json')

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    for city_id, descriptions in BATCH_CITIES.items():
        data[city_id] = descriptions
        print(f"Updated descriptions for {city_id}")

    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\nTotal cities with descriptions: {len(data)}")

if __name__ == "__main__":
    main()
